# Category 2 Part 3: Remaining 16 Antibacterials

MEDS = [
    {
        "slug": "kanamycin",
        "generic_name": "Kanamycin",
        "display_name": "Kanamycin",
        "active_ingredient": "Kanamycin sulfate",
        "salt": "Kanamycin sulfate",
        "category": "Antibiotics",
        "description": "An aminoglycoside antibiotic with bactericidal activity against aerobic Gram-negative bacilli and Mycobacterium tuberculosis, reserved for MDR-TB and serious hospital infections.",
        "strengths": ["500 mg vial", "1 g vial"],
        "dosage_forms": ["Powder for Injection", "Solution for Injection"],
        "routes": ["Intramuscular", "Intravenous"],
        "mechanism_of_action": "Binds irreversibly to the bacterial 30S ribosomal subunit, causing misreading of codons and inhibition of translocation, terminating bacterial protein synthesis.",
        "pharmacodynamics": "Concentration-dependent bactericidal action against Enterobacteriaceae and second-line activity against Mycobacterium tuberculosis.",
        "absorption": "Poorly absorbed orally (<1%); rapidly absorbed after IM injection with peak serum levels in 1 hour.",
        "distribution": "Distributes mainly into extracellular fluid; poor CSF and bronchial penetration; <10% protein bound.",
        "metabolism": "Not metabolized; excreted entirely as active parent drug.",
        "excretion": "Greater than 90% eliminated unchanged in urine via glomerular filtration within 24 hours.",
        "bioavailability": "100% (parenteral)",
        "half_life": "2 to 3 hours",
        "protein_binding": "<10%",
        "onset": "Rapid peak serum concentration within 1 hour after IM injection",
        "duration": "12 to 24 hours",
        "indications": ["Multidrug-resistant tuberculosis (MDR-TB second-line injectable)", "Severe Gram-negative sepsis (when less toxic alternatives are contraindicated)", "Hepatic encephalopathy adjunct (oral, historically)"],
        "contraindications": ["Hypersensitivity to kanamycin or other aminoglycosides", "Myasthenia gravis", "Preexisting high-frequency sensorineural hearing loss"],
        "warnings": ["Black box warnings: Ototoxicity (high-frequency hearing loss and vestibular toxicity) and Nephrotoxicity", "Neuromuscular blockade and respiratory paralysis", "Avoid concurrent or sequential use of other ototoxic/nephrotoxic drugs"],
        "common_adverse_effects": ["Elevated serum creatinine", "Ototoxicity / tinnitus", "Dizziness", "Pain at injection site"],
        "serious_adverse_effects": ["Irreversible bilateral sensorineural deafness", "Acute tubular necrosis / renal failure", "Neuromuscular paralysis"],
        "drug_interactions": ["Loop diuretics (furosemide - greatly increases ototoxicity risk)", "Vancomycin, amphotericin B (additive nephrotoxicity)", "Neuromuscular blocking agents"],
        "monitoring": ["Baseline and periodic audiometry", "Serum creatinine and BUN", "Therapeutic drug monitoring (trough < 2-4 mcg/mL)"],
        "pregnancy": "Category D; risk of congenital deafness in the fetus.",
        "lactation": "Excreted in low levels in breast milk; use with caution.",
        "pediatric": "Use restricted to multi-drug resistant tuberculosis in specialized centers.",
        "geriatric": "Marked reduction in renal clearance; strict dose adjustment and auditory monitoring.",
        "renal": "Strict dose reduction mandatory: extend interval to 24-48 hours and monitor peak and trough serum levels.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Core historical second-line injectable for drug-resistant tuberculosis regimens", "Rapid concentration-dependent bactericidal killing"],
        "disadvantages": ["High risk of irreversible hearing loss with prolonged courses", "Narrow therapeutic index requiring blood level monitoring"],
        "key_points": ["Audit hearing with periodic audiometry during prolonged TB regimens", "Strictly monitor renal function and trough levels"],
        "memory_trick": "KANA-mycin: Kill Acid-fast bacilli (MDR-TB), but Keep Audiometry Nearby.",
        "key_suffix": "-mycin",
        "pronunciation_en": "kan-a-MYE-sin",
        "pronunciation_hi": "काना-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "chloramphenicol",
        "generic_name": "Chloramphenicol",
        "display_name": "Chloramphenicol",
        "active_ingredient": "Chloramphenicol sodium succinate",
        "salt": "Chloramphenicol sodium succinate",
        "category": "Antibiotics",
        "description": "A broad-spectrum classical antibiotic with excellent CSF penetration, reserved for life-threatening infections such as bacterial meningitis and rickettsial diseases when other options fail.",
        "strengths": ["250 mg", "500 mg", "1 g vial", "0.5% eye drops", "1% eye ointment"],
        "dosage_forms": ["Capsule", "Powder for Injection", "Ophthalmic Solution", "Ophthalmic Ointment"],
        "routes": ["Oral", "Intravenous", "Ophthalmic"],
        "mechanism_of_action": "Binds reversibly to the 50S subunit of 70S bacterial ribosomes, inhibiting the peptidyl transferase reaction and preventing peptide bond formation.",
        "pharmacodynamics": "Bacteriostatic against most organisms; bactericidal against Haemophilus influenzae, Neisseria meningitidis, and Streptococcus pneumoniae.",
        "absorption": "Rapidly and completely absorbed from GI tract (75-90% bioavailability); peak levels in 1 to 2 hours.",
        "distribution": "Exceptional tissue and lipid solubility; crosses the blood-brain barrier effectively (CSF levels 50-65% of serum); 50-60% protein bound.",
        "metabolism": "Extensively metabolized by hepatic glucuronyl transferase (approx. 90%) to inactive glucuronide conjugates.",
        "excretion": "Excreted primarily in urine (approx. 90%), with about 10% as unchanged drug via glomerular filtration.",
        "bioavailability": "75% to 90%",
        "half_life": "1.5 to 3.5 hours in adults (significantly prolonged in neonates to 24+ hours)",
        "protein_binding": "50% to 60%",
        "onset": "1 to 2 hours",
        "duration": "6 to 8 hours",
        "indications": ["Acute bacterial meningitis due to H. influenzae, N. meningitidis, or S. pneumoniae when penicillins/cephalosporins are contraindicated", "Severe rickettsial infections (Rocky Mountain spotted fever, epidemic typhus)", "Severe Salmonella infections / typhoid fever (second-line reserve)", "Bacterial conjunctivitis (topical eye drops)"],
        "contraindications": ["Hypersensitivity to chloramphenicol", "Preexisting bone marrow depression or blood dyscrasias", "Routine treatment of minor infections or prophylaxis"],
        "warnings": ["Black box warning: Serious and fatal blood dyscrasias (aplastic anaemia, hypoplastic anaemia, thrombocytopenia, granulocytopenia)", "Grey baby syndrome in neonates due to immature glucuronyl transferase enzyme (vomiting, ashen cyanosis, hypothermia, cardiovascular collapse)", "Therapeutic drug monitoring recommended (target peak 10-20 mcg/mL)"],
        "common_adverse_effects": ["Nausea", "Vomiting", "Diarrhoea", "Glossitis / stomatitis", "Dose-dependent reversible bone marrow suppression"],
        "serious_adverse_effects": ["Idiosyncratic irreversible fatal aplastic anaemia (1 in 25,000-40,000 patients)", "Grey baby syndrome (neonatal fatal toxicity)", "Optic and peripheral neuritis (prolonged therapy)"],
        "drug_interactions": ["Phenytoin, warfarin, sulfonylureas (inhibits hepatic CYP metabolism, increasing their toxicity)", "Phenobarbital, rifampicin (induce chloramphenicol metabolism)", "Iron supplements"],
        "monitoring": ["Complete blood count with differential every 2 to 3 days", "Serum chloramphenicol levels", "Hepatic and renal function"],
        "pregnancy": "Category C; contraindicated near term and during labor due to grey baby syndrome risk.",
        "lactation": "Excreted in human milk; avoid during breastfeeding due to infant bone marrow suppression risk.",
        "pediatric": "Contraindicated in neonates and premature infants (grey baby syndrome); monitor levels strictly in older children.",
        "geriatric": "Assess hepatic and renal function; dose adjustment needed in liver disease.",
        "renal": "No major dose reduction required for parent drug, but inactive metabolites accumulate; monitor CBC closely.",
        "hepatic": "Dose reduction mandatory in hepatic impairment to prevent toxic accumulation.",
        "advantages": ["Superior CSF penetration (equal to or higher than beta-lactams)", "Potent bactericidal activity against major meningeal pathogens"],
        "disadvantages": ["Risk of fatal idiosyncratic aplastic anaemia (independent of dose)", "Lethal grey baby syndrome in neonates"],
        "key_points": ["Strictly contraindicated in neonates (causes fatal grey baby syndrome)", "Risk of unpredictable, fatal aplastic anaemia restricts use to critical reserve indications"],
        "memory_trick": "CHLORAM-PHENICOL: Causes Hematologic Aplastic-anaemia, Puts Neonates In Collapse (Grey baby syndrome).",
        "key_suffix": "-phenicol",
        "pronunciation_en": "klor-am-FEN-i-kol",
        "pronunciation_hi": "क्लोरम-फेनिकोल",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "pristinamycin",
        "generic_name": "Pristinamycin",
        "display_name": "Pristinamycin",
        "active_ingredient": "Pristinamycin (mixture of pristinamycin IA and IIA)",
        "salt": "Pristinamycin",
        "category": "Antibiotics",
        "description": "An oral streptogramin antibiotic consisting of a synergistic combination of two factors (IA and IIA), used for methicillin-resistant Staphylococcus aureus (MRSA) and refractory streptococcal infections.",
        "strengths": ["250 mg", "500 mg"],
        "dosage_forms": ["Film-coated Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Consists of pristinamycin IA (a macrolactone) and IIA (a polyunsaturated macrolactone) that bind sequentially to separate sites on the bacterial 50S ribosomal subunit; binding of IIA increases affinity for IA by 100-fold, transforming bacteriostatic action into bactericidal inhibition.",
        "pharmacodynamics": "Synergistic bactericidal activity against MRSA, Streptococcus pyogenes, Streptococcus pneumoniae, and Enterococcus faecalis.",
        "absorption": "Moderately absorbed from the gastrointestinal tract; food increases absorption; peak concentrations achieved in 2 to 3 hours.",
        "distribution": "Good penetration into skin, subcutaneous fat, tonsils, bone, and synovial fluid; 70-80% bound to plasma proteins.",
        "metabolism": "Metabolized in the liver by oxidation and ester hydrolysis to several active and inactive metabolites.",
        "excretion": "Excreted predominantly in faeces (approx. 70-80%) via the biliary system; less than 10% in urine.",
        "bioavailability": "Approximately 40% to 50%",
        "half_life": "2 to 4 hours",
        "protein_binding": "70% to 80%",
        "onset": "1 to 2 hours",
        "duration": "8 hours (administered three times daily)",
        "indications": ["Skin and soft tissue infections caused by MRSA and Streptococcus", "Streptococcal pharyngitis and tonsillitis when beta-lactams and macrolides are unsuitable", "Exacerbations of chronic bronchitis due to susceptible pathogens", "Bone and joint infections (osteomyelitis) as step-down oral therapy"],
        "contraindications": ["Hypersensitivity to pristinamycin or other streptogramins (e.g., quinupristin/dalfopristin)", "Severe hepatic impairment"],
        "warnings": ["Gastrointestinal intolerance is common; take with meals to reduce nausea", "Risk of Clostridioides difficile colitis", "Potential for CYP3A4 inhibition"],
        "common_adverse_effects": ["Nausea", "Vomiting", "Epigastric discomfort", "Diarrhoea", "Cutaneous rash"],
        "serious_adverse_effects": ["Severe cutaneous adverse reactions (AGEP - acute generalized exanthematous pustulosis)", "Pseudomembranous colitis", "Hepatotoxicity"],
        "drug_interactions": ["CYP3A4 substrates (cyclosporine, tacrolimus, carbamazepine - increases their serum levels)", "Oral contraceptives", "Warfarin"],
        "monitoring": ["Liver enzymes in prolonged courses", "Skin evaluation for pustular or blistering rash", "Stool frequency"],
        "pregnancy": "Use during pregnancy only if clearly necessary; limited human safety data.",
        "lactation": "Excretion in breast milk unknown; use with caution.",
        "pediatric": "Tablets may be crushed for children over 6 years of age (50 mg/kg/day in 2-3 divided doses).",
        "geriatric": "No primary dose adjustment needed; assess gastrointestinal tolerance.",
        "renal": "No dose adjustment required in renal impairment (eliminated primarily via the biliary route).",
        "hepatic": "Dose reduction recommended in hepatic insufficiency.",
        "advantages": ["Oral bactericidal option for MRSA skin and soft tissue infections", "Synergistic dual-component mechanism prevents rapid emergence of resistance", "Safe in renal impairment without dose adjustment"],
        "disadvantages": ["Frequent dosing required (three times daily with meals)", "Significant incidence of gastrointestinal side effects"],
        "key_points": ["Take with meals to improve absorption and reduce stomach upset", "Synergistic streptogramin with oral activity against MRSA"],
        "memory_trick": "PRISTINA-mycin: Pristine oral skin MRSA fighter; 2 parts work synergistically.",
        "key_suffix": "-mycin",
        "pronunciation_en": "pris-tin-a-MYE-sin",
        "pronunciation_hi": "प्रिस्टिना-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "tedizolid",
        "generic_name": "Tedizolid",
        "display_name": "Tedizolid Phosphate",
        "active_ingredient": "Tedizolid phosphate",
        "salt": "Tedizolid phosphate",
        "category": "Antibiotics",
        "description": "A second-generation oxazolidinone antibiotic 4 to 8 times more potent than linezolid, administered once daily for 6 days for acute bacterial skin and skin structure infections (ABSSSI).",
        "strengths": ["200 mg", "200 mg IV vial"],
        "dosage_forms": ["Film-coated Tablet", "Lyophilized Powder for Injection"],
        "routes": ["Oral", "Intravenous"],
        "mechanism_of_action": "Prodrug converted by plasma phosphatases to active tedizolid, which binds to the 23S rRNA of the 50S bacterial ribosomal subunit, inhibiting initiation complex formation and protein synthesis.",
        "pharmacodynamics": "Potent activity against MRSA, VRSA, VRE (Enterococcus faecalis and faecium), and linezolid-resistant strains carrying the cfr chloramphenicol-florfenicol resistance methyltransferase gene.",
        "absorption": "Rapidly and near-completely absorbed orally; 91% absolute oral bioavailability; food does not affect exposure.",
        "distribution": "Extensive tissue distribution into skin and adipose tissue; 70-90% bound to human plasma proteins.",
        "metabolism": "Prodrug rapidly dephosphorylated in blood to active tedizolid; hepatic metabolism to inactive sulfate conjugate; minimal CYP involvement.",
        "excretion": "Excreted primarily in faeces (approx. 82%) and urine (approx. 18%, mostly as inactive sulfate conjugate).",
        "bioavailability": "Approximately 91%",
        "half_life": "12 hours (enables once-daily dosing)",
        "protein_binding": "70% to 90%",
        "onset": "1 to 2 hours",
        "duration": "24 hours",
        "indications": ["Acute bacterial skin and skin structure infections (ABSSSI) caused by MRSA, Streptococcus pyogenes, and Enterococcus faecalis", "Diabetic foot infections involving resistant Gram-positive cocci"],
        "contraindications": ["Hypersensitivity to tedizolid or oxazolidinones"],
        "warnings": ["Myelosuppression and peripheral/optic neuropathy (lower risk than linezolid during the approved 6-day course, but monitor in prolonged use)", "Weak reversible MAO inhibitor (caution with serotonergic agents)", "Clostridioides difficile colitis"],
        "common_adverse_effects": ["Nausea", "Headache", "Diarrhoea", "Vomiting", "Dizziness"],
        "serious_adverse_effects": ["Thrombocytopenia / myelosuppression (rare in 6-day course)", "Peripheral and optic neuropathy (with extended off-label use)", "Serotonin syndrome (rare)", "Pseudomembranous colitis"],
        "drug_interactions": ["Serotonergic agents (SSRIs, SNRIs, triptans - lower MAO inhibition than linezolid, but monitor)", "Adrenergic agents (pseudoephedrine - potential blood pressure elevation)"],
        "monitoring": ["Complete blood counts (platelets, hemoglobin) if therapy exceeds 6 days", "Visual symptoms if used off-label for prolonged periods", "Clinical resolution of skin lesions"],
        "pregnancy": "Category C; use only if potential benefit justifies potential fetal risk.",
        "lactation": "Excreted in animal milk; use caution during breastfeeding.",
        "pediatric": "Approved for pediatric patients 12 years and older (200 mg once daily).",
        "geriatric": "No dosage adjustment needed based on age.",
        "renal": "No dosage adjustment required in renal impairment or hemodialysis.",
        "hepatic": "No dosage adjustment required in mild, moderate, or severe hepatic impairment.",
        "advantages": ["Once-daily dosing for just 6 days (compared to linezolid BID for 10-14 days)", "4-8 times more potent in vitro than linezolid", "Much lower rate of myelosuppression and monoamine oxidase inhibition during standard courses", "No dose adjustment in renal or hepatic failure"],
        "disadvantages": ["Approved only for skin infections (limited clinical trial data for pneumonia and bacteremia)", "Higher acquisition cost"],
        "key_points": ["Once-daily 200 mg dose for only 6 days for skin infections", "Overcomes some linezolid-resistant cfr strains"],
        "memory_trick": "TEDI-zolid: TIME-SAVING (once daily, 6 days), Tougher on MRSA than linezolid.",
        "key_suffix": "-zolid",
        "pronunciation_en": "te-DIZ-oh-lid",
        "pronunciation_hi": "टेडिज़ो-लिड",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "dalbavancin",
        "generic_name": "Dalbavancin",
        "display_name": "Dalbavancin",
        "active_ingredient": "Dalbavancin hydrochloride",
        "salt": "Dalbavancin hydrochloride",
        "category": "Antibiotics",
        "description": "A second-generation lipoglycopeptide antibiotic with an ultra-long terminal half-life of 14 days, permitting complete therapy of acute bacterial skin infections in one or two doses.",
        "strengths": ["500 mg vial"],
        "dosage_forms": ["Lyophilized Powder for Solution for Infusion"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Binds to the D-alanyl-D-alanine terminus of growing bacterial peptidoglycan chains, blocking transglycosylation and transpeptidation; lipophilic side chain anchors to membrane, increasing potency.",
        "pharmacodynamics": "Rapid bactericidal killing against MRSA, MSSA, Streptococcus pyogenes, and vancomycin-susceptible Enterococcus faecalis.",
        "absorption": "100% bioavailable intravenously; infused over 30 minutes.",
        "distribution": "Extensive tissue distribution into skin and blister fluid; 93% bound to human plasma proteins (predominantly albumin).",
        "metabolism": "Minimal hepatic metabolism; not a substrate, inhibitor, or inducer of CYP450 enzymes.",
        "excretion": "Excreted unchanged in urine (approx. 33%) and faeces (approx. 20%), with remainder eliminated through slow non-enzymatic pathways.",
        "bioavailability": "100% (IV)",
        "half_life": "14.4 days (approx. 346 hours - ultra-long terminal half-life)",
        "protein_binding": "93%",
        "onset": "Peak serum level immediately at end of 30-minute IV infusion",
        "duration": "14 days per single dose",
        "indications": ["Acute bacterial skin and skin structure infections (ABSSSI) caused by MRSA, Streptococcus species, and Enterococcus faecalis", "Off-label use in osteomyelitis, joint infections, and infective endocarditis requiring outpatient therapy"],
        "contraindications": ["Hypersensitivity to dalbavancin or glycopeptides"],
        "warnings": ["Infusion-related reactions (flushing, rash, pruritus - slow infusion to 30 minutes or longer to avoid 'red-man' like syndrome)", "Dose reduction required in severe renal impairment", "Clostridioides difficile colitis"],
        "common_adverse_effects": ["Nausea", "Headache", "Diarrhoea", "Rash", "Infusion site irritation"],
        "serious_adverse_effects": ["Hypersensitivity / anaphylactoid reactions", "Hepatotoxicity (ALT elevations >3x ULN)", "Pseudomembranous colitis"],
        "drug_interactions": ["No major CYP-mediated drug interactions", "Concomitant nephrotoxic drugs (monitor renal function)"],
        "monitoring": ["Renal function tests (eGFR)", "Liver function tests", "Clinical signs of infusion reactions"],
        "pregnancy": "Category C; use during pregnancy only if potential benefit justifies potential risk to fetus.",
        "lactation": "Excreted in animal milk; use caution during breastfeeding.",
        "pediatric": "Approved for pediatric patients from birth for ABSSSI (single-dose weight-adjusted regimen).",
        "geriatric": "No dose adjustment based on age alone; assess renal function.",
        "renal": "In chronic renal impairment with eGFR < 30 mL/min not on regular hemodialysis, reduce single dose to 1000 mg (or 750 mg followed by 375 mg on day 8); no adjustment needed on regular scheduled hemodialysis.",
        "hepatic": "No dose adjustment needed in mild to moderate hepatic impairment.",
        "advantages": ["Entire course delivered in a single 1500 mg infusion (or 1000 mg day 1 + 500 mg day 8), eliminating compliance failure and PICC lines", "14-day half-life revolutionizes outpatient parenteral antibiotic therapy (OPAT)"],
        "disadvantages": ["Extremely long half-life means adverse reactions cannot be quickly washed out", "High initial acquisition cost"],
        "key_points": ["A single 1500 mg IV infusion covers 14 full days of therapy for MRSA skin infections", "Infuse over at least 30 minutes to avoid flushing and itching"],
        "memory_trick": "DALBA-vancin: DAYS AND WEEKS in blood (14-day half-life), Done in A Single Dose.",
        "key_suffix": "-vancin",
        "pronunciation_en": "dal-ba-VAN-sin",
        "pronunciation_hi": "डाल्बा-वैन्सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "daptomycin",
        "generic_name": "Daptomycin",
        "display_name": "Daptomycin",
        "active_ingredient": "Daptomycin",
        "salt": "Daptomycin",
        "category": "Antibiotics",
        "description": "A cyclic lipopeptide bactericidal antibiotic that binds to and depolarizes bacterial cell membranes, used for MRSA bacteremia, right-sided infective endocarditis, and severe skin infections.",
        "strengths": ["350 mg vial", "500 mg vial"],
        "dosage_forms": ["Lyophilized Powder for Injection"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Binds in a calcium-dependent manner to bacterial cell membranes, oligomerizes, and inserts into the lipid bilayer, creating pores that cause rapid potassium ion efflux, membrane depolarization, and cessation of DNA, RNA, and protein synthesis without cell lysis.",
        "pharmacodynamics": "Rapid concentration-dependent bactericidal action against MRSA, MSSA, VRE (Enterococcus faecalis and faecium), and coagulase-negative staphylococci; inactivated by pulmonary surfactant, therefore INEFFECTIVE for pneumonia.",
        "absorption": "100% bioavailable intravenously; given as a 30-minute IV infusion or 2-minute IV injection.",
        "distribution": "Distributes mainly into extracellular space (Vd approx. 0.1 L/kg); 90-93% bound to human plasma proteins.",
        "metabolism": "Little to no hepatic metabolism; does not interact with cytochrome P450 enzymes.",
        "excretion": "Excreted primarily unchanged by the kidneys (approx. 78% in urine via glomerular filtration); approx. 6% in faeces.",
        "bioavailability": "100% (IV)",
        "half_life": "8 to 9 hours",
        "protein_binding": "90% to 93%",
        "onset": "Rapid peak serum concentration at end of 30-minute infusion",
        "duration": "24 hours (administered once daily)",
        "indications": ["Staphylococcus aureus bloodstream infections (bacteremia) and right-sided infective endocarditis", "Complicated skin and soft tissue infections caused by MRSA and Enterococcus faecalis", "Vancomycin-resistant enterococcal (VRE) bacteremia (off-label high-dose)"],
        "contraindications": ["Hypersensitivity to daptomycin", "Treatment of pneumonia (inactivated by alveolar surfactant)"],
        "warnings": ["STRICTLY CONTRAINDICATED in pneumonia: pulmonary surfactant binds and inactivates daptomycin", "Myopathy and rhabdomyolysis: monitor serum creatine phosphokinase (CPK) weekly", "Eosinophilic pneumonia: rare, can present 2-4 weeks into therapy with fever, hypoxemia, and pulmonary infiltrates"],
        "common_adverse_effects": ["Elevated CPK levels", "Nausea", "Headache", "Diarrhoea", "Constipation"],
        "serious_adverse_effects": ["Rhabdomyolysis with acute kidney injury", "Eosinophilic pneumonia (requires immediate cessation and corticosteroids)", "Peripheral neuropathy", "Clostridioides difficile colitis"],
        "drug_interactions": ["HMG-CoA reductase inhibitors (statins - temporarily suspend during daptomycin to prevent additive rhabdomyolysis)", "Tobramycin / aminoglycosides (additive nephrotoxicity)"],
        "monitoring": ["Serum creatine phosphokinase (CPK) at baseline and at least weekly", "Renal function (BUN and creatinine)", "Monitor for new fever, dyspnea, or cough (eosinophilic pneumonia)"],
        "pregnancy": "Category B; use during pregnancy only if clearly needed.",
        "lactation": "Excreted in low levels in breast milk; compatible with breastfeeding.",
        "pediatric": "Approved for pediatric patients 1 year and older for bacteremia and skin infections.",
        "geriatric": "Renal function declines with age; monitor CPK and creatinine clearance closely.",
        "renal": "Dose adjustment required if CrCl < 30 mL/min (including hemodialysis): administer dose every 48 hours instead of every 24 hours.",
        "hepatic": "No dose adjustment required in mild to moderate hepatic impairment.",
        "advantages": ["Rapid bactericidal killing against MRSA without bacterial lysis (reduced toxin release)", "Once-daily dosing with 2-minute bolus option", "Gold standard bactericidal alternative to vancomycin for MRSA endocarditis and bacteremia"],
        "disadvantages": ["Cannot be used for pneumonia (inactivated by surfactant)", "Risk of skeletal muscle toxicity requires weekly CPK monitoring; statins must be held"],
        "key_points": ["Never use for pneumonia because lung surfactant inactivates the drug", "Stop statins and check CPK weekly to prevent rhabdomyolysis"],
        "memory_trick": "DAPTO-mycin: DEPOLARIZES membranes, DO NOT use in Pneumonia, DANGER to muscles (CPK).",
        "key_suffix": "-mycin",
        "pronunciation_en": "DAP-toe-mye-sin",
        "pronunciation_hi": "डैप्टो-माइसिन",
        "status": "active",
        "verification_status": "verified"
    }
]

print(f"Loaded {len(MEDS)} antibacterials in cat2_part3")
