# Category 2: Antibacterials (30 medicines)

MEDICINES = [
    {
        "slug": "roxithromycin",
        "generic_name": "Roxithromycin",
        "display_name": "Roxithromycin",
        "active_ingredient": "Roxithromycin",
        "salt": "Roxithromycin",
        "category": "Antibiotics",
        "description": "A semi-synthetic 14-membered macrolide antibiotic with high oral bioavailability and long elimination half-life, used for respiratory tract, ear-nose-throat, and skin infections.",
        "strengths": ["50 mg DT", "150 mg", "300 mg"],
        "dosage_forms": ["Dispersible Tablet", "Film-coated Tablet", "Oral Suspension"],
        "routes": ["Oral"],
        "mechanism_of_action": "Binds reversibly to the 50S subunit of bacterial ribosomes, blocking peptide chain elongation and inhibiting protein synthesis.",
        "pharmacodynamics": "Bacteriostatic spectrum covering Gram-positive cocci (Streptococcus, Staphylococcus), atypical pathogens (Mycoplasma, Chlamydia, Legionella), and select Gram-negatives.",
        "absorption": "Rapidly absorbed; significantly more acid-stable than erythromycin; food decreases absorption slightly, so take before meals.",
        "distribution": "High tissue and intracellular penetration, especially into lung macrophages and tonsillar tissue; 96% bound to alpha-1 acid glycoprotein.",
        "metabolism": "Partially metabolised in the liver; largely eliminated unchanged.",
        "excretion": "Excreted predominantly in faeces (approx. 53%) via bile and in urine (approx. 10%).",
        "bioavailability": "Approximately 50%",
        "half_life": "10 to 12 hours",
        "protein_binding": "96%",
        "onset": "1 to 2 hours",
        "duration": "12 to 24 hours",
        "indications": ["Community-acquired pneumonia", "Acute pharyngitis and tonsillitis", "Acute exacerbation of chronic bronchitis", "Skin and soft tissue infections", "Non-gonococcal urethritis"],
        "contraindications": ["Hypersensitivity to macrolides", "Severe hepatic impairment with concurrent ergot alkaloid therapy", "Concurrent use of cisapride or pimozide"],
        "warnings": ["QTc interval prolongation and risk of ventricular arrhythmias", "Hepatotoxicity / cholestatic jaundice", "Pseudomembranous colitis"],
        "common_adverse_effects": ["Nausea", "Epigastric pain", "Diarrhoea", "Headache", "Dizziness"],
        "serious_adverse_effects": ["Torsades de pointes / QT prolongation", "Cholestatic hepatitis", "Clostridioides difficile colitis", "Severe cutaneous reactions"],
        "drug_interactions": ["Ergotamine (severe vasoconstriction/ergotism)", "Theophylline (slight increase in theophylline levels)", "Warfarin (potentiates anticoagulation)", "Digoxin"],
        "monitoring": ["Liver function in prolonged therapy", "ECG in patients with cardiac arrhythmia risk factors"],
        "pregnancy": "Category B; use during pregnancy only if clearly indicated.",
        "lactation": "Excreted in low levels in breast milk; use with caution.",
        "pediatric": "Dispersible tablets widely used in pediatric respiratory infections.",
        "geriatric": "No dose adjustment needed unless severe renal and hepatic dysfunction coexist.",
        "renal": "Dose reduction in severe renal failure (eGFR < 15 mL/min).",
        "hepatic": "Dose reduction (150 mg once daily) in severe hepatic impairment.",
        "advantages": ["Higher oral bioavailability and acid stability than erythromycin", "Convenient twice-daily or once-daily dosing", "Superior respiratory tissue penetration"],
        "disadvantages": ["Lower activity against Haemophilus influenzae than amoxicillin-clavulanate", "Potential for QT prolongation"],
        "key_points": ["Take at least 15 minutes before meals for optimal absorption", "Excellent penetration into lung and tonsillar tissue"],
        "memory_trick": "ROXI-thromycin: Rocks respiratory bugs with convenient twice-daily dosing.",
        "key_suffix": "-thromycin",
        "pronunciation_en": "rox-ith-roe-MYE-sin",
        "pronunciation_hi": "रॉक्सिथ्रो-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "moxifloxacin",
        "generic_name": "Moxifloxacin",
        "display_name": "Moxifloxacin",
        "active_ingredient": "Moxifloxacin hydrochloride",
        "salt": "Moxifloxacin hydrochloride",
        "category": "Antibiotics",
        "description": "A fourth-generation respiratory fluoroquinolone with broad Gram-positive, Gram-negative, atypical, and anaerobic coverage, used for pneumonia, complicated intra-abdominal sepsis, and MDR-TB.",
        "strengths": ["400 mg", "400 mg/250 mL IV infusion", "0.5% eye drops"],
        "dosage_forms": ["Film-coated Tablet", "IV Infusion", "Ophthalmic Solution"],
        "routes": ["Oral", "Intravenous", "Ophthalmic"],
        "mechanism_of_action": "Inhibits bacterial topoisomerase II (DNA gyrase) and topoisomerase IV, disrupting bacterial DNA replication, transcription, and repair.",
        "pharmacodynamics": "Concentration-dependent bactericidal action with enhanced activity against Streptococcus pneumoniae and atypical organisms (Mycoplasma, Chlamydophila, Legionella).",
        "absorption": "Well absorbed (approx. 90%) from GI tract; food does not affect total exposure.",
        "distribution": "Extensive penetration into alveolar macrophages, lung parenchyma, and sinus tissue; 30-50% bound to plasma albumin.",
        "metabolism": "Hepatic glucuronide and sulfate conjugation; not metabolized by cytochrome P450 enzymes.",
        "excretion": "Approximately 45% excreted unchanged in urine and faeces; remainder as inactive conjugates.",
        "bioavailability": "Approximately 90%",
        "half_life": "12 hours",
        "protein_binding": "30% to 50%",
        "onset": "1 to 3 hours",
        "duration": "24 hours",
        "indications": ["Community-acquired pneumonia (CAP)", "Acute bacterial sinusitis", "Complicated skin and soft tissue infections", "Complicated intra-abdominal infections", "Second-line therapy for multidrug-resistant tuberculosis (MDR-TB)"],
        "contraindications": ["History of fluoroquinolone-associated tendinopathy", "Documented QT prolongation or concurrent antiarrhythmics", "Severe hepatic impairment (Child-Pugh C)", "Myasthenia gravis"],
        "warnings": ["Black box warnings for tendon rupture, peripheral neuropathy, and CNS toxicities", "Exacerbation of myasthenia gravis", "Aortic aneurysm and dissection risk"],
        "common_adverse_effects": ["Nausea", "Diarrhoea", "Dizziness", "Headache", "Dyspepsia"],
        "serious_adverse_effects": ["Achilles tendon rupture", "QT interval prolongation / Torsades de pointes", "Severe peripheral neuropathy", "Clostridioides difficile colitis"],
        "drug_interactions": ["Antacids containing Al/Mg, iron, zinc (chelation impairs absorption; separate by 4 hours)", "Class IA and III antiarrhythmics (additive QT prolongation)", "Oral hypoglycaemics"],
        "monitoring": ["Signs of tendinopathy (discontinue at first sign of tendon pain)", "ECG in high-risk cardiac patients", "Blood glucose in diabetics"],
        "pregnancy": "Avoid during pregnancy due to potential for juvenile cartilage toxicity.",
        "lactation": "Excreted in human milk; avoid during breastfeeding.",
        "pediatric": "Generally avoided in children, except in multidrug-resistant tuberculosis regimens.",
        "geriatric": "Increased vulnerability to tendon rupture and QT prolongation.",
        "renal": "No dosage adjustment needed in renal impairment (undergoes hepatic conjugation).",
        "hepatic": "Contraindicated in severe hepatic impairment (Child-Pugh C).",
        "advantages": ["No dosage adjustment needed in renal disease (unlike levofloxacin/ciprofloxacin)", "Once-daily dosing with 90% bioavailability", "Broad coverage including pneumococci, anaerobes, and atypicals"],
        "disadvantages": ["Class warnings for tendinitis and neurotoxicity", "Potential for QT prolongation"],
        "key_points": ["Safe in renal impairment without dose adjustment", "Avoid taking simultaneously with antacids or iron supplements"],
        "memory_trick": "MOXI-floxacin: Mixed anaerobic/aerobic activity, Once-daily, eXcellent in kidney disease.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "mox-i-FLOX-a-sin",
        "pronunciation_hi": "मॉक्सी-फ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "ofloxacin",
        "generic_name": "Ofloxacin",
        "display_name": "Ofloxacin",
        "active_ingredient": "Ofloxacin",
        "salt": "Ofloxacin",
        "category": "Antibiotics",
        "description": "A broad-spectrum second-generation fluoroquinolone widely utilized in India for enteric fever, infectious diarrhoea, and genitourinary tract infections.",
        "strengths": ["100 mg DT", "200 mg", "400 mg", "200 mg/100 mL IV", "0.3% eye/ear drops"],
        "dosage_forms": ["Film-coated Tablet", "Dispersible Tablet", "IV Infusion", "Ophthalmic/Otic Drops"],
        "routes": ["Oral", "Intravenous", "Ophthalmic", "Otic"],
        "mechanism_of_action": "Inhibits bacterial DNA gyrase and topoisomerase IV, preventing negative supercoiling of bacterial DNA and leading to rapid cell death.",
        "pharmacodynamics": "Bactericidal against Enterobacteriaceae, Salmonella, Shigella, and Neisseria; moderately active against Gram-positive bacteria.",
        "absorption": "Rapidly and almost completely absorbed (approx. 98% bioavailability); peak levels in 1 to 2 hours.",
        "distribution": "Extensive penetration into kidneys, bladder, prostate, lungs, and bile; 20-30% protein bound.",
        "metabolism": "Minimal hepatic metabolism (<10%); excreted primarily as parent drug.",
        "excretion": "Predominantly eliminated unchanged by the kidneys via tubular secretion and glomerular filtration (>80%).",
        "bioavailability": "Near 100%",
        "half_life": "5 to 7 hours",
        "protein_binding": "20% to 30%",
        "onset": "1 to 2 hours",
        "duration": "12 hours",
        "indications": ["Enteric fever (typhoid fever)", "Acute bacterial gastroenteritis (often combined with ornidazole)", "Urinary tract infections and acute pyelonephritis", "Prostatitis and pelvic inflammatory disease", "Bacterial conjunctivitis and otitis externa (drops)"],
        "contraindications": ["Hypersensitivity to quinolones", "History of fluoroquinolone-induced tendinitis", "Epilepsy or lowered seizure threshold", "Myasthenia gravis"],
        "warnings": ["Tendon rupture and tendinopathy", "CNS toxicity / seizures in predisposed patients", "Separate from multivalent cations (iron, calcium, magnesium, aluminum) by at least 2 hours"],
        "common_adverse_effects": ["Nausea", "Insomnia", "Headache", "Dizziness", "Diarrhoea"],
        "serious_adverse_effects": ["Achilles tendon rupture", "Seizures", "Peripheral neuropathy", "QT prolongation", "Stevens-Johnson syndrome"],
        "drug_interactions": ["Multivalent cation antacids and iron (impair absorption)", "Theophylline (modest increase in levels)", "NSAIDs (increased seizure risk)", "Warfarin"],
        "monitoring": ["Renal function tests (BUN / creatinine)", "Signs of tendon pain", "Blood glucose in diabetics"],
        "pregnancy": "Avoid during pregnancy due to potential for cartilage toxicity in the fetus.",
        "lactation": "Excreted in breast milk; avoid use or stop breastfeeding.",
        "pediatric": "Contraindicated in children and adolescents, except under strict specialist indications.",
        "geriatric": "Renal clearance is reduced; dose adjustment based on creatinine clearance.",
        "renal": "Dose reduction mandatory: if CrCl 20-50 mL/min, give 200 mg q24h; if CrCl < 20 mL/min, give 100 mg q24h.",
        "hepatic": "Caution in severe liver cirrhosis (maximum 400 mg daily).",
        "advantages": ["Near 100% oral bioavailability allows seamless IV to oral step-down", "High concentrations in prostate and urinary tract", "Established utility in enteric infections"],
        "disadvantages": ["Widespread resistance among uropathogens and Salmonella", "Class warnings for tendon and CNS toxicities"],
        "key_points": ["Frequently paired with ornidazole in India for acute gastroenteritis", "Must adjust dose in renal disease because it is excreted by the kidneys"],
        "memory_trick": "O-FLOX-acin: Over 95% bioavailability; Outflows through kidney.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "oh-FLOX-a-sin",
        "pronunciation_hi": "ओफ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "norfloxacin",
        "generic_name": "Norfloxacin",
        "display_name": "Norfloxacin",
        "active_ingredient": "Norfloxacin",
        "salt": "Norfloxacin",
        "category": "Antibiotics",
        "description": "A synthetic fluoroquinolone that achieves very high concentrations in the urinary tract and gastrointestinal lumen with low systemic tissue levels, making it ideal for UTIs and bacterial diarrhoea.",
        "strengths": ["100 mg", "200 mg", "400 mg", "0.3% eye/ear drops"],
        "dosage_forms": ["Tablet", "Ophthalmic/Otic Drops"],
        "routes": ["Oral", "Ophthalmic", "Otic"],
        "mechanism_of_action": "Inhibits bacterial DNA gyrase and topoisomerase IV, preventing DNA supercoiling, synthesis, and cell division.",
        "pharmacodynamics": "Bactericidal activity against Gram-negative urinary and gastrointestinal pathogens (E. coli, Klebsiella, Proteus, Salmonella, Shigella, Campylobacter).",
        "absorption": "Rapidly but incompletely absorbed (30-40% bioavailability); food or milk impairs absorption.",
        "distribution": "Low serum concentrations; concentrates intensely in renal parenchyma, bladder urine, and intestinal lumen; 14% protein bound.",
        "metabolism": "Partially metabolised in the liver to six active metabolites possessing weaker antibacterial activity.",
        "excretion": "Approximately 30-40% excreted unchanged in urine within 24 hours; about 30% excreted in faeces.",
        "bioavailability": "30% to 40%",
        "half_life": "3 to 4 hours",
        "protein_binding": "14%",
        "onset": "1 to 2 hours",
        "duration": "12 hours",
        "indications": ["Acute and recurrent uncomplicated urinary tract infections (UTIs)", "Complicated UTIs (except with systemic sepsis)", "Bacterial infectious gastroenteritis / traveller's diarrhoea", "Spontaneous bacterial peritonitis (SBP) prophylaxis in cirrhotics"],
        "contraindications": ["Hypersensitivity to fluoroquinolones", "History of tendinitis or tendon rupture", "Myasthenia gravis", "Pregnancy and lactation"],
        "warnings": ["Do not use for systemic bloodstream infections (poor systemic tissue penetration)", "Tendon disorders and central neurotoxicity", "Take 1 hour before or 2 hours after meals with plenty of fluids"],
        "common_adverse_effects": ["Nausea", "Dyspepsia", "Abdominal cramps", "Headache", "Dizziness"],
        "serious_adverse_effects": ["Tendon rupture (Achilles)", "Clostridioides difficile colitis", "Crystalluria (especially in alkaline urine with low fluid intake)"],
        "drug_interactions": ["Antacids containing Al/Mg, calcium, iron supplements (drastically reduce absorption)", "Theophylline (increases theophylline levels)", "Warfarin (increased INR)"],
        "monitoring": ["Urinary symptoms and urine culture", "Adequate hydration to prevent crystalluria", "Renal function in elderly or impaired patients"],
        "pregnancy": "Avoid during pregnancy; potential arthropathy in growing joints.",
        "lactation": "Excreted in breast milk; avoid use.",
        "pediatric": "Not recommended in children and adolescents under 18 years.",
        "geriatric": "Dose adjustment for renal impairment; higher tendon rupture risk.",
        "renal": "If CrCl ≤ 30 mL/min, reduce dose to 400 mg once daily.",
        "hepatic": "No dose adjustment necessary.",
        "advantages": ["High urinary and fecal concentrations with low systemic toxicity", "Established agent for SBP prophylaxis in chronic liver disease"],
        "disadvantages": ["Poor systemic absorption makes it inappropriate for pneumonia or deep-seated systemic sepsis", "Rising fluoroquinolone resistance in uropathogens"],
        "key_points": ["Drink plenty of water to prevent crystals in the urine", "Take on an empty stomach with a full glass of water"],
        "memory_trick": "NOR-floxacin: Narrower systemic levels, NOT for pneumonia, Optimal for Renal/gut tract.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "nor-FLOX-a-sin",
        "pronunciation_hi": "नॉरफ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "faropenem",
        "generic_name": "Faropenem",
        "display_name": "Faropenem",
        "active_ingredient": "Faropenem sodium",
        "salt": "Faropenem sodium",
        "category": "Antibiotics",
        "description": "An orally bioavailable penem antibiotic with high stability against extended-spectrum beta-lactamases (ESBLs), used for resistant respiratory, ENT, and urinary tract infections.",
        "strengths": ["150 mg", "200 mg", "300 mg", "100 mg DT"],
        "dosage_forms": ["Film-coated Tablet", "Dispersible Tablet", "Dry Syrup"],
        "routes": ["Oral"],
        "mechanism_of_action": "Binds with high affinity to penicillin-binding proteins (PBPs), primarily PBP1A, 1B, 2, and 3, inhibiting peptidoglycan cell wall cross-linking and triggering autolysis.",
        "pharmacodynamics": "Broad-spectrum bactericidal activity against Gram-positive, Gram-negative, and anaerobic pathogens; highly resistant to hydrolysis by class A, C, and D beta-lactamases including ESBLs.",
        "absorption": "Rapidly absorbed after oral administration; peak plasma levels reached in 1 to 1.5 hours.",
        "distribution": "Distributes well into sputum, tonsils, sinus mucosa, and middle ear fluid; 96% bound to plasma proteins in humans.",
        "metabolism": "Hydrolyzed in renal brush border by renal dehydropeptidase-I (DHP-I) to inactive metabolites, but more stable to DHP-I than imipenem.",
        "excretion": "Approximately 15-20% excreted unchanged in urine, with remainder as ring-opened inactive metabolites.",
        "bioavailability": "Approximately 70-80%",
        "half_life": "1 hour",
        "protein_binding": "96%",
        "onset": "Peak serum level within 1 to 1.5 hours",
        "duration": "8 hours (administered three times daily)",
        "indications": ["Community-acquired pneumonia with suspected or proven ESBL organisms", "Acute bacterial sinusitis and otitis media refractory to first-line agents", "Complicated and recurrent urinary tract infections", "Skin and soft tissue infections"],
        "contraindications": ["Hypersensitivity to faropenem, penems, or other carbapenem beta-lactam antibiotics", "History of anaphylaxis to cephalosporins or penicillins"],
        "warnings": ["Reserve for confirmed or highly suspected resistant infections to prevent emergence of carbapenemase resistance", "Diarrhoea and risk of Clostridioides difficile colitis", "Cross-reactivity with beta-lactam allergy"],
        "common_adverse_effects": ["Diarrhoea", "Abdominal discomfort", "Nausea", "Loose stools", "Rash"],
        "serious_adverse_effects": ["Pseudomembranous colitis", "Anaphylaxis", "Liver transaminase elevations", "Seizures (extremely rare)"],
        "drug_interactions": ["Imipenem/cilastatin or other carbapenems (do not combine)", "Sodium valproate (penems/carbapenems may lower valproate levels)", "Probenecid (prolongs faropenem excretion)"],
        "monitoring": ["Clinical response", "Stool frequency (watch for severe watery diarrhoea)", "Renal function"],
        "pregnancy": "Use during pregnancy only if clearly needed and potential benefit justifies potential risk.",
        "lactation": "Excreted into breast milk in small amounts; use caution.",
        "pediatric": "Paediatric dry syrup and dispersible tablets used in selected refractory respiratory infections under specialist supervision.",
        "geriatric": "Assess renal function; reduce dose in impaired renal clearance.",
        "renal": "Dose adjustment required in renal impairment: if CrCl 30-50 mL/min, give 150-200 mg q12h; if CrCl < 30 mL/min, give 150 mg q24h.",
        "hepatic": "No dosage adjustment needed for hepatic impairment.",
        "advantages": ["Only orally active penem/carbapenem-like antibiotic available in outpatient practice", "Stable against extended-spectrum beta-lactamases (ESBLs)"],
        "disadvantages": ["Short half-life requiring three-times-daily dosing", "Should be used judiciously as a reserve antibiotic to prevent resistance"],
        "key_points": ["Oral reserve antibiotic for ESBL-producing bacteria", "Take three times daily at evenly spaced intervals"],
        "memory_trick": "FARO-penem: Oral FAR-reaching Penem against ESBLs.",
        "key_suffix": "-penem",
        "pronunciation_en": "fa-roe-PEN-em",
        "pronunciation_hi": "फ़ैरो-पेनेम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "telithromycin",
        "generic_name": "Telithromycin",
        "display_name": "Telithromycin",
        "active_ingredient": "Telithromycin",
        "salt": "Telithromycin",
        "category": "Antibiotics",
        "description": "A semi-synthetic ketolide antibiotic derived from erythromycin, engineered to overcome macrolide resistance in Streptococcus pneumoniae.",
        "strengths": ["400 mg", "800 mg"],
        "dosage_forms": ["Film-coated Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Binds to two distinct domains (II and V) on the 23S rRNA of the bacterial 50S ribosomal subunit, maintaining high affinity even against MLSB-resistant strains.",
        "pharmacodynamics": "Concentration-dependent bactericidal action against penicillin- and erythromycin-resistant Streptococcus pneumoniae and respiratory pathogens.",
        "absorption": "Rapidly absorbed; peak plasma concentration attained within 1 to 3 hours; unaffected by food.",
        "distribution": "High penetration into respiratory tissues, alveolar macrophages, and white blood cells; 60-70% bound to plasma proteins.",
        "metabolism": "Extensively metabolized by CYP3A4 (50%) and non-CYP pathways (50%).",
        "excretion": "Excreted in faeces (approx. 7%) and urine (approx. 13% unchanged).",
        "bioavailability": "Approximately 57%",
        "half_life": "10 hours",
        "protein_binding": "60% to 70%",
        "onset": "1 to 2 hours",
        "duration": "24 hours",
        "indications": ["Community-acquired pneumonia due to multi-drug resistant Streptococcus pneumoniae (MDRSP)"],
        "contraindications": ["Myasthenia gravis (black box warning: risk of fatal respiratory failure)", "History of telithromycin-associated hepatitis or jaundice", "Concurrent use with pimozide, cisapride, or ergot alkaloids"],
        "warnings": ["Severe hepatotoxicity including acute liver failure and death", "Visual disturbances (blurred vision, difficulty focusing) requiring caution when driving", "QTc interval prolongation"],
        "common_adverse_effects": ["Diarrhoea", "Nausea", "Dizziness", "Dysgeusia (altered taste)", "Blurred vision"],
        "serious_adverse_effects": ["Fulminant liver failure", "Exacerbation of myasthenia gravis (fatal)", "Ventricular arrhythmias / Torsades de pointes", "Loss of consciousness / syncope"],
        "drug_interactions": ["Simvastatin / atorvastatin (severe rhabdomyolysis due to CYP3A4 inhibition)", "Digoxin (increased levels)", "Ketoconazole / itraconazole", "Midazolam"],
        "monitoring": ["Liver enzymes at first sign of fatigue or jaundice", "Visual acuity", "ECG in patients with cardiac risk"],
        "pregnancy": "Avoid in pregnancy unless benefits clearly outweigh potential fetal risks.",
        "lactation": "Excreted in animal milk; avoid breastfeeding during therapy.",
        "pediatric": "Not recommended in children under 18 years of age.",
        "geriatric": "Assess hepatic and cardiac function; monitor visual symptoms closely.",
        "renal": "Dose reduction (400 mg daily) in severe renal impairment (CrCl < 30 mL/min).",
        "hepatic": "Contraindicated in patients with prior telithromycin hepatotoxicity; caution in hepatic impairment.",
        "advantages": ["Retains activity against macrolide-resistant pneumococci due to dual 23S rRNA binding", "Convenient once-daily 800 mg regimen"],
        "disadvantages": ["Severe hepatotoxicity and myasthenia gravis warnings limit use to strict reserve indication", "Visual disturbances can impair driving"],
        "key_points": ["Strictly contraindicated in myasthenia gravis", "Reserve solely for community-acquired pneumonia when other options fail"],
        "memory_trick": "TELI-thromycin: Tough on resistant bugs, but Terribly Toxic to the liver and myasthenia.",
        "key_suffix": "-thromycin",
        "pronunciation_en": "tel-ith-roe-MYE-sin",
        "pronunciation_hi": "टेलिथ्रो-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "gemifloxacin",
        "generic_name": "Gemifloxacin",
        "display_name": "Gemifloxacin",
        "active_ingredient": "Gemifloxacin mesylate",
        "salt": "Gemifloxacin mesylate",
        "category": "Antibiotics",
        "description": "An advanced fluoroquinolone with potent dual-targeting against bacterial DNA gyrase and topoisomerase IV, specifically indicated for acute bacterial exacerbation of chronic bronchitis and mild-to-moderate CAP.",
        "strengths": ["320 mg"],
        "dosage_forms": ["Film-coated Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Inhibits both topoisomerase II (DNA gyrase) and topoisomerase IV, resulting in rapid bacterial DNA fragmentation and cell death.",
        "pharmacodynamics": "High potency against Streptococcus pneumoniae (including penicillin-resistant strains), Haemophilus influenzae, and atypical pathogens.",
        "absorption": "Rapidly absorbed; peak plasma concentration within 0.5 to 2 hours.",
        "distribution": "Excellent penetration into lung parenchyma and bronchial mucosa; 55-73% bound to plasma proteins.",
        "metabolism": "Undergoes limited hepatic metabolism; not extensively metabolized by cytochrome P450 enzymes.",
        "excretion": "Approximately 36% eliminated in urine and 61% in faeces as unchanged drug and metabolites.",
        "bioavailability": "Approximately 71%",
        "half_life": "7 hours",
        "protein_binding": "55% to 73%",
        "onset": "1 hour",
        "duration": "24 hours",
        "indications": ["Acute bacterial exacerbation of chronic bronchitis (AECB)", "Mild to moderate community-acquired pneumonia (CAP)"],
        "contraindications": ["Hypersensitivity to fluoroquinolones", "History of quinolone-associated tendinopathy", "Myasthenia gravis"],
        "warnings": ["Maculopapular rash occurs more frequently, particularly in females under 40 and with therapy exceeding 7 days", "Tendinitis and tendon rupture", "QT prolongation"],
        "common_adverse_effects": ["Diarrhoea", "Rash (erythematous/maculopapular)", "Nausea", "Headache", "Abdominal pain"],
        "serious_adverse_effects": ["Achilles tendon rupture", "Severe cutaneous adverse reactions", "QTc prolongation", "Clostridioides difficile colitis"],
        "drug_interactions": ["Antacids containing magnesium/aluminum, iron, sucralfate (take gemifloxacin 2 hours before or 3 hours after)", "Class IA and III antiarrhythmics", "Probenecid (increases AUC)"],
        "monitoring": ["Skin inspection for rash (discontinue if rash develops)", "Tendon pain or swelling", "Renal function"],
        "pregnancy": "Avoid in pregnancy; potential arthropathy in weight-bearing joints.",
        "lactation": "Excreted in breast milk; avoid use during lactation.",
        "pediatric": "Contraindicated in children under 18 years of age.",
        "geriatric": "No dose adjustment based on age alone; monitor renal function.",
        "renal": "If CrCl ≤ 40 mL/min, reduce dose to 160 mg every 24 hours.",
        "hepatic": "No dose adjustment required in mild to moderate hepatic impairment.",
        "advantages": ["High potency against multi-drug resistant S. pneumoniae", "Short 5-day course effective for AECB"],
        "disadvantages": ["Higher rash incidence compared to other fluoroquinolones", "Standard fluoroquinolone class side effects"],
        "key_points": ["Limit treatment duration to 5-7 days to minimize rash incidence", "Once daily 320 mg tablet"],
        "memory_trick": "GEMI-floxacin: GEM for the lungs, but watch for rash in 5 days.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "jem-i-FLOX-a-sin",
        "pronunciation_hi": "जेमी-फ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "teicoplanin",
        "generic_name": "Teicoplanin",
        "display_name": "Teicoplanin",
        "active_ingredient": "Teicoplanin",
        "salt": "Teicoplanin",
        "category": "Antibiotics",
        "description": "A glycopeptide antibiotic related to vancomycin with lower nephrotoxicity and red-man syndrome rates, administered once daily or via intramuscular injection for serious Gram-positive infections.",
        "strengths": ["200 mg vial", "400 mg vial"],
        "dosage_forms": ["Powder for Solution for Injection/Infusion"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Inhibits cell wall peptidoglycan synthesis by binding tightly to the D-alanyl-D-alanine terminus of cell wall precursor pentapeptides, preventing polymerization.",
        "pharmacodynamics": "Bactericidal against methicillin-resistant Staphylococcus aureus (MRSA), enterococci, and Streptococcus species; lacks activity against Gram-negative organisms.",
        "absorption": "Not absorbed orally (oral use restricted to C. difficile enterocolitis); 100% bioavailable after IM or IV administration.",
        "distribution": "Distributes well into lung tissue, synovial fluid, and bone; 90-95% bound to plasma proteins; prolonged elimination half-life.",
        "metabolism": "Minimal hepatic metabolism (<3%); does not undergo significant biotransformation.",
        "excretion": "Approximately 80% eliminated unchanged in urine via glomerular filtration.",
        "bioavailability": "90% after intramuscular injection; 100% IV",
        "half_life": "100 to 170 hours (very long elimination half-life)",
        "protein_binding": "90% to 95%",
        "onset": "Loading doses required over first 48 hours to reach target therapeutic trough levels (>15-20 mcg/mL)",
        "duration": "24 hours (once-daily maintenance after loading)",
        "indications": ["Methicillin-resistant Staphylococcus aureus (MRSA) bacteremia and endocarditis", "Complicated bone and joint infections (osteomyelitis)", "Complicated skin and soft tissue infections", "Hospital-acquired pneumonia due to MRSA", "Oral therapy for Clostridioides difficile colitis (second-line)"],
        "contraindications": ["Hypersensitivity to teicoplanin or glycopeptides"],
        "warnings": ["Loading doses are essential to achieve therapeutic trough levels rapidly", "Ototoxicity and nephrotoxicity, particularly when combined with aminoglycosides", "Cross-reactivity in vancomycin-allergic patients is possible though low"],
        "common_adverse_effects": ["Rash", "Local pain at intramuscular injection site", "Fever", "Mild transient serum creatinine rise"],
        "serious_adverse_effects": ["Ototoxicity (tinnitus, high-frequency hearing loss)", "Nephrotoxicity / acute kidney injury", "Thrombocytopenia and leukopenia", "Red man-like syndrome (infrequent)"],
        "drug_interactions": ["Aminoglycosides, amphotericin B, colistin (additive nephrotoxicity and ototoxicity)", "Loop diuretics (additive ototoxicity)", "Ciclosporin"],
        "monitoring": ["Trough serum levels (target >15 mcg/mL for uncomplicated, >20-30 mcg/mL for endocarditis/osteomyelitis)", "Renal function (BUN/creatinine)", "Audiometry in prolonged courses"],
        "pregnancy": "Use in pregnancy only if the potential benefit outweighs the risk of fetal ototoxicity.",
        "lactation": "Excretion in human milk is unknown; use with caution.",
        "pediatric": "Approved for neonates and children; loading dose based on age and weight.",
        "geriatric": "Renal clearance decreases with age; adjust maintenance dose based on creatinine clearance.",
        "renal": "Dose adjustment required after day 4: if CrCl 30-80 mL/min, halve maintenance dose; if CrCl < 30 mL/min, give maintenance dose every third day.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Can be administered intramuscularly as well as IV bolus", "Significantly lower incidence of nephrotoxicity and red-man syndrome than vancomycin", "Once-daily maintenance dosing"],
        "disadvantages": ["Long half-life means slow correction if toxicity develops", "Requires multiple loading doses in first 48 hours to achieve therapeutic levels"],
        "key_points": ["Three loading doses (every 12 hours) are crucial before switching to once-daily maintenance", "Can be given by direct IV injection over 5 minutes or IM injection"],
        "memory_trick": "TEICO-planin: Takes Easier Injection (IM allowed, no slow infusion needed), Calmer than vancomycin.",
        "key_suffix": "-planin",
        "pronunciation_en": "tye-koe-PLAN-in",
        "pronunciation_hi": "टाइको-प्लानिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefotaxime",
        "generic_name": "Cefotaxime",
        "display_name": "Cefotaxime",
        "active_ingredient": "Cefotaxime sodium",
        "salt": "Cefotaxime sodium",
        "category": "Antibiotics",
        "description": "A parenteral third-generation cephalosporin with excellent cerebrospinal fluid penetration, widely used for neonatal sepsis, bacterial meningitis, and serious systemic infections.",
        "strengths": ["250 mg", "500 mg", "1 g", "2 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Binds to penicillin-binding proteins (PBPs), inhibiting bacterial peptidoglycan cell wall synthesis, resulting in cell wall lysis and bacterial death.",
        "pharmacodynamics": "Potent bactericidal activity against Streptococcus pneumoniae, Neisseria meningitidis, Haemophilus influenzae, and enteric Gram-negative bacilli; active metabolite desacetylcefotaxime acts synergistically.",
        "absorption": "Not absorbed orally; 100% bioavailable upon IV injection; peak levels within 30 minutes after IM.",
        "distribution": "Excellent penetration into CSF (inflamed meninges), pleural, peritoneal, and synovial fluid; 30-50% bound to plasma proteins.",
        "metabolism": "Partially metabolized in the liver to desacetylcefotaxime, which possesses significant intrinsic antibacterial activity and synergy.",
        "excretion": "Approximately 60% excreted in urine unchanged, and 20% as active desacetyl metabolite.",
        "bioavailability": "100% (parenteral)",
        "half_life": "1 to 1.5 hours for parent drug; 1.5 hours for desacetyl metabolite",
        "protein_binding": "30% to 50%",
        "onset": "Immediate (IV)",
        "duration": "6 to 8 hours",
        "indications": ["Acute bacterial meningitis (especially in neonates and young infants)", "Neonatal sepsis", "Community-acquired and hospital-acquired pneumonia", "Spontaneous bacterial peritonitis (SBP)", "Complicated urinary tract infections and intra-abdominal sepsis"],
        "contraindications": ["Hypersensitivity to cefotaxime or other cephalosporins", "History of severe immediate anaphylaxis to penicillins"],
        "warnings": ["Dose reduction in renal failure to prevent neurotoxicity and encephalopathy", "Pseudomembranous colitis risk", "Safe in neonates compared to ceftriaxone (does not cause biliary sludging or kernicterus)"],
        "common_adverse_effects": ["Phlebitis at IV site", "Diarrhoea", "Rash", "Nausea", "Eosinophilia"],
        "serious_adverse_effects": ["Clostridioides difficile colitis", "Anaphylaxis", "Neutropenia and agranulocytosis (prolonged therapy)", "Neurotoxicity / encephalopathy in renal failure"],
        "drug_interactions": ["Aminoglycosides (additive nephrotoxicity)", "Probenecid (decreases renal tubular secretion)", "Loop diuretics"],
        "monitoring": ["Renal function", "Complete blood count in courses exceeding 10 days", "Neurological status in renal insufficiency"],
        "pregnancy": "Category B; safe and widely used during pregnancy.",
        "lactation": "Excreted in low concentrations in breast milk; compatible with breastfeeding.",
        "pediatric": "Preferred third-generation cephalosporin in neonates under 28 days of life (avoids kernicterus associated with ceftriaxone).",
        "geriatric": "Assess renal clearance; adjust dosing interval in renal impairment.",
        "renal": "If CrCl < 20 mL/min, reduce maintenance dose by 50% or extend interval to every 12 hours.",
        "hepatic": "No major dosage adjustment required.",
        "advantages": ["Preferred cephalosporin in neonates because it does not displace bilirubin from albumin (no kernicterus risk)", "Excellent CSF penetration for meningitis", "Active metabolite acts synergistically"],
        "disadvantages": ["Requires dosing every 6-8 hours (shorter half-life than ceftriaxone)", "Parenteral only"],
        "key_points": ["First-choice 3rd-generation cephalosporin in neonates (safe from kernicterus)", "Administered every 6 to 8 hours for meningitis"],
        "memory_trick": "CEFO-TAX-ime: Safe TAX for neonates (avoids ceftriaxone bilirubin displacement).",
        "key_suffix": "-taxime",
        "pronunciation_en": "sef-oh-TAX-eem",
        "pronunciation_hi": "सेफ़ो-टैक्सिम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefepime",
        "generic_name": "Cefepime",
        "display_name": "Cefepime",
        "active_ingredient": "Cefepime hydrochloride",
        "salt": "Cefepime hydrochloride",
        "category": "Antibiotics",
        "description": "A fourth-generation parenteral cephalosporin with zwitterionic structure providing rapid penetration across outer bacterial membranes, highly active against Pseudomonas and Enterobacteriaceae.",
        "strengths": ["500 mg", "1 g", "2 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Binds to multiple penicillin-binding proteins (PBP2, PBP3, PBP1a/1b) inhibiting peptidoglycan synthesis; zwitterionic charge allows rapid diffusion through outer membrane porins.",
        "pharmacodynamics": "Bactericidal activity against Gram-positive cocci (MSSA, Streptococcus) and Gram-negative bacilli (Pseudomonas aeruginosa, Enterobacter cloacae, Citrobacter); resists AmpC chromosomal beta-lactamases.",
        "absorption": "100% bioavailable intravenously; rapid absorption following IM administration.",
        "distribution": "Widely distributed into lung, peritoneal fluid, bile, and inflamed meninges; approximately 20% bound to plasma proteins.",
        "metabolism": "Minimal hepatic metabolism (<10%); excreted primarily as parent drug.",
        "excretion": "Approximately 85% eliminated unchanged in urine via glomerular filtration.",
        "bioavailability": "100% (IV)",
        "half_life": "2 hours",
        "protein_binding": "20%",
        "onset": "Immediate upon IV infusion",
        "duration": "8 to 12 hours",
        "indications": ["Empiric therapy for febrile neutropenia in haematology-oncology patients", "Hospital-acquired and ventilator-associated pneumonia (HAP/VAP)", "Complicated intra-abdominal infections (with metronidazole)", "Complicated urinary tract infections and pyelonephritis", "Severe Pseudomonas aeruginosa infections"],
        "contraindications": ["Hypersensitivity to cefepime, cephalosporins, or severe beta-lactam allergy"],
        "warnings": ["Neurotoxicity (encephalopathy, myoclonus, seizures, non-convulsive status epilepticus) occurs if dose is not properly adjusted for renal dysfunction", "Clostridioides difficile colitis", "Positive direct Coombs test"],
        "common_adverse_effects": ["Phlebitis", "Diarrhoea", "Rash", "Nausea", "Headache"],
        "serious_adverse_effects": ["Cefepime-induced neurotoxicity / encephalopathy", "Non-convulsive status epilepticus", "Pseudomembranous colitis", "Anaphylaxis", "Agranulocytosis"],
        "drug_interactions": ["Aminoglycosides (additive nephrotoxicity)", "Probenecid (decreased renal clearance)", "Other nephrotoxic drugs"],
        "monitoring": ["Renal function (mandatory to adjust dosing and prevent neurotoxicity)", "Mental status and neurological checks", "Complete blood counts in extended courses"],
        "pregnancy": "Category B; use during pregnancy only if clearly needed.",
        "lactation": "Excreted in human milk in low concentrations; compatible with caution.",
        "pediatric": "Approved for pediatric febrile neutropenia and severe infections (50 mg/kg every 8-12h).",
        "geriatric": "Elderly patients frequently have unrecognized renal insufficiency; adjust dose to avoid encephalopathy.",
        "renal": "Strict dose reduction mandatory: if CrCl 30-50 mL/min, give 2g q12h; if CrCl 11-29 mL/min, give 2g q24h; if CrCl < 11 mL/min, give 1g q24h.",
        "hepatic": "No dosage adjustment necessary.",
        "advantages": ["Dual action against Pseudomonas aeruginosa and AmpC-producing Enterobacteriaceae", "Low affinity for chromosomal AmpC beta-lactamases", "Cornerstone empiric agent for febrile neutropenia"],
        "disadvantages": ["High risk of encephalopathy and myoclonus in unadjusted renal impairment", "Inactive against MRSA, ESBLs, and Enterococci"],
        "key_points": ["Always check renal function: failure to reduce dose causes confusion, myoclonus, and seizures", "Core agent for febrile neutropenia"],
        "memory_trick": "CEFE-pime: 4th-gen, Febrile neutropenia, Encephalopathy risk if renal dose forgotten.",
        "key_suffix": "-pime",
        "pronunciation_en": "SEF-e-peem",
        "pronunciation_hi": "सेफ़े-पीम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "ceftazidime",
        "generic_name": "Ceftazidime",
        "display_name": "Ceftazidime",
        "active_ingredient": "Ceftazidime pentahydrate",
        "salt": "Ceftazidime pentahydrate",
        "category": "Antibiotics",
        "description": "A third-generation parenteral cephalosporin with potent antipseudomonal activity, used for hospital-acquired infections, febrile neutropenia, and melioidosis.",
        "strengths": ["500 mg", "1 g", "2 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Binds to essential penicillin-binding proteins (PBP3), inhibiting peptidoglycan synthesis and producing filamentation and lysis of bacterial cells.",
        "pharmacodynamics": "High bactericidal activity against Pseudomonas aeruginosa and Gram-negative bacilli; weaker Gram-positive activity compared to cefotaxime/ceftriaxone; cornerstone agent for Burkholderia pseudomallei (melioidosis).",
        "absorption": "100% bioavailable parenterally; rapid peak within 1 hour following IM injection.",
        "distribution": "Good penetration into bronchial secretions, pleural fluid, bone, and cerebrospinal fluid (inflamed meninges); <10% protein bound.",
        "metabolism": "Not metabolized; excreted entirely as parent drug.",
        "excretion": "80% to 90% eliminated unchanged in urine by glomerular filtration within 24 hours.",
        "bioavailability": "100% (IV)",
        "half_life": "1.5 to 2 hours (prolonged in renal impairment)",
        "protein_binding": "<10%",
        "onset": "Immediate (IV)",
        "duration": "8 hours",
        "indications": ["Severe Pseudomonas aeruginosa infections", "Hospital-acquired pneumonia and ventilator-associated pneumonia", "Acute intensive phase of Melioidosis (Burkholderia pseudomallei)", "Complicated intra-abdominal and urinary tract infections", "Febrile neutropenia in immunocompromised patients"],
        "contraindications": ["Hypersensitivity to ceftazidime, cephalosporins, or severe immediate beta-lactam anaphylaxis"],
        "warnings": ["Renal dose adjustment necessary to avoid neurotoxicity", "Induction of AmpC beta-lactamases in Enterobacter species", "Clostridioides difficile colitis"],
        "common_adverse_effects": ["Phlebitis at injection site", "Diarrhoea", "Transient eosinophilia", "Maculopapular rash", "Nausea"],
        "serious_adverse_effects": ["Encephalopathy and seizures in renal failure", "Agranulocytosis", "Pseudomembranous colitis", "Anaphylaxis"],
        "drug_interactions": ["Aminoglycosides (additive nephrotoxicity)", "Chloramphenicol (antagonistic)", "Probenecid (minor effect compared to other beta-lactams)"],
        "monitoring": ["Renal function tests (BUN / creatinine)", "Complete blood counts in prolonged therapy", "Neurological checks in renal failure"],
        "pregnancy": "Category B; safe and widely used during pregnancy.",
        "lactation": "Excreted in low concentrations in breast milk; compatible with breastfeeding.",
        "pediatric": "Approved for neonates and children; crucial in cystic fibrosis exacerbations and melioidosis.",
        "geriatric": "Assess renal function; reduce dose based on glomerular filtration rate.",
        "renal": "Dose adjustment required: if CrCl 31-50 mL/min, give 1g q12h; if CrCl 16-30 mL/min, give 1g q24h; if CrCl ≤ 15 mL/min, give 500mg q24h.",
        "hepatic": "No dose adjustment necessary.",
        "advantages": ["Potent antipseudomonal third-generation cephalosporin", "Drug of choice for the intensive intravenous phase of melioidosis", "Low protein binding allows high free drug concentrations"],
        "disadvantages": ["Poor activity against Gram-positive cocci compared to cefotaxime/ceftriaxone", "Vulnerable to ESBLs and AmpC enzymes"],
        "key_points": ["Drug of choice for severe melioidosis (Burkholderia pseudomallei)", "High antipseudomonal activity with low protein binding"],
        "memory_trick": "CEFT-AZIDIME: Attacks Zillions of Invasive Deep Infectious Microbes (Pseudomonas & Melioidosis).",
        "key_suffix": "-tazidime",
        "pronunciation_en": "sef-TAZ-i-deem",
        "pronunciation_hi": "सेफ़्टाज़ि-डीम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefazolin",
        "generic_name": "Cefazolin",
        "display_name": "Cefazolin",
        "active_ingredient": "Cefazolin sodium",
        "salt": "Cefazolin sodium",
        "category": "Antibiotics",
        "description": "A first-generation parenteral cephalosporin with excellent activity against MSSA and Streptococcus, established worldwide as the gold standard for surgical antibiotic prophylaxis.",
        "strengths": ["500 mg", "1 g", "2 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Binds to bacterial penicillin-binding proteins (PBPs), inhibiting cross-linking of peptidoglycan in the cell wall, causing cell lysis.",
        "pharmacodynamics": "High bactericidal activity against methicillin-sensitive Staphylococcus aureus (MSSA), Streptococcus pyogenes, and select community Gram-negatives (E. coli, Proteus mirabilis).",
        "absorption": "100% bioavailable IV; rapid and complete absorption after IM injection.",
        "distribution": "Widely distributed into bone, synovial fluid, pleural fluid, and surgical wound tissue; 80-85% bound to plasma proteins.",
        "metabolism": "Not metabolized in the liver; excreted unchanged.",
        "excretion": "Approximately 80-100% eliminated unchanged in urine via glomerular filtration and tubular secretion.",
        "bioavailability": "100% (IV)",
        "half_life": "1.8 to 2 hours",
        "protein_binding": "80% to 85%",
        "onset": "Immediate (IV); peak tissue levels within 30 minutes",
        "duration": "6 to 8 hours",
        "indications": ["Surgical antibiotic prophylaxis (clean and clean-contaminated procedures)", "Methicillin-susceptible Staphylococcus aureus (MSSA) bacteremia and endocarditis", "Complicated skin and skin structure infections", "Bone and joint infections (osteomyelitis, septic arthritis)"],
        "contraindications": ["Hypersensitivity to cefazolin, cephalosporins, or severe immediate beta-lactam anaphylaxis"],
        "warnings": ["Infuse within 60 minutes prior to surgical incision for optimal tissue protection", "Dose adjustment in renal failure", "Clostridioides difficile colitis"],
        "common_adverse_effects": ["Phlebitis", "Diarrhoea", "Transient elevation of liver transaminases", "Rash", "Nausea"],
        "serious_adverse_effects": ["Pseudomembranous colitis", "Anaphylaxis", "Neutropenia (prolonged therapy)", "Seizures in high-dose renal impairment"],
        "drug_interactions": ["Probenecid (prolongs cefazolin half-life)", "Aminoglycosides (potential additive nephrotoxicity)", "Warfarin (monitor INR)"],
        "monitoring": ["Surgical wound healing", "Renal function in prolonged therapy", "Complete blood counts beyond 10 days of treatment"],
        "pregnancy": "Category B; safe and the agent of choice for Cesarean section prophylaxis.",
        "lactation": "Excreted in low levels in breast milk; compatible with breastfeeding.",
        "pediatric": "Standard surgical prophylaxis and MSSA treatment in pediatric patients (25-50 mg/kg/day).",
        "geriatric": "Check renal clearance; adjust dosing interval in renal impairment.",
        "renal": "Dose adjustment required: if CrCl 35-54 mL/min, give full dose q8h; if CrCl 11-34 mL/min, give 50% dose q12h; if CrCl ≤ 10 mL/min, give 50% dose q18-24h.",
        "hepatic": "No dose adjustment necessary.",
        "advantages": ["Global gold standard for surgical prophylaxis across orthopaedic, cardiac, and general surgery", "Better tolerated with lower phlebitis than antistaphylococcal penicillins (oxacillin/cloxacillin)"],
        "disadvantages": ["Inactive against MRSA, Enterococci, and Pseudomonas", "Parenteral only"],
        "key_points": ["Gold standard for surgical prophylaxis (administer 30-60 minutes before skin incision)", "Excellent activity against MSSA with minimal toxicity"],
        "memory_trick": "CEFA-zolin: Clean Incision, Surgical Anti-staphylococcal First-choice.",
        "key_suffix": "-zolin",
        "pronunciation_en": "sef-A-zoe-lin",
        "pronunciation_hi": "सेफ़ा-ज़ोलिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefadroxil",
        "generic_name": "Cefadroxil",
        "display_name": "Cefadroxil",
        "active_ingredient": "Cefadroxil monohydrate",
        "salt": "Cefadroxil monohydrate",
        "category": "Antibiotics",
        "description": "An oral first-generation cephalosporin with prolonged urinary and tissue persistence, used once or twice daily for skin, pharyngeal, and urinary tract infections.",
        "strengths": ["125 mg DT", "250 mg DT", "500 mg", "1 g"],
        "dosage_forms": ["Dispersible Tablet", "Film-coated Tablet", "Oral Suspension"],
        "routes": ["Oral"],
        "mechanism_of_action": "Bactericidal inhibition of cell wall synthesis by binding to penicillin-binding proteins (PBPs), halting peptidoglycan assembly.",
        "pharmacodynamics": "Active against Streptococcus pyogenes, methicillin-sensitive Staphylococcus aureus (MSSA), and uncomplicated urinary coliforms (E. coli, Proteus mirabilis).",
        "absorption": "Rapidly and near-completely absorbed from the gastrointestinal tract; food does not diminish absorption.",
        "distribution": "Widely distributed into skin, tonsillar tissue, sputum, and pleural fluid; 20% bound to plasma proteins.",
        "metabolism": "Not metabolized in the liver; eliminated unchanged.",
        "excretion": "Greater than 90% eliminated unchanged in urine via glomerular filtration and tubular secretion within 24 hours.",
        "bioavailability": "Greater than 90%",
        "half_life": "1.5 hours in plasma; sustained tissue and urinary levels allow 12-to-24 hour dosing",
        "protein_binding": "20%",
        "onset": "1 to 2 hours",
        "duration": "12 to 24 hours",
        "indications": ["Streptococcal pharyngitis and tonsillitis", "Skin and soft tissue infections (impetigo, cellulitis, folliculitis)", "Uncomplicated urinary tract infections (cystitis)"],
        "contraindications": ["Hypersensitivity to cephalosporins or severe immediate beta-lactam anaphylaxis"],
        "warnings": ["Dose reduction required in moderate to severe renal impairment", "Clostridioides difficile colitis risk", "Cross-reactivity in penicillin-allergic patients (approx. 5-10%)"],
        "common_adverse_effects": ["Dyspepsia", "Nausea", "Diarrhoea", "Rash", "Vaginal candidiasis"],
        "serious_adverse_effects": ["Pseudomembranous colitis", "Anaphylaxis", "Neutropenia (prolonged therapy)"],
        "drug_interactions": ["Probenecid (reduces renal clearance, elevating plasma levels)", "Oral contraceptives (minimal effect, but counsel on diarrhoea)"],
        "monitoring": ["Clinical resolution of pharyngitis or skin lesions", "Renal function in renal disease"],
        "pregnancy": "Category B; widely regarded as safe during pregnancy.",
        "lactation": "Excreted in low concentrations in breast milk; compatible with breastfeeding.",
        "pediatric": "Dispersible tablets widely used in pediatric streptococcal sore throat and impetigo.",
        "geriatric": "Check renal clearance; adjust dosing frequency in renal insufficiency.",
        "renal": "Dose adjustment based on CrCl: if CrCl 25-50 mL/min, dose q12h; if CrCl 10-25 mL/min, dose q24h; if CrCl < 10 mL/min, dose q36h.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Sustained urinary and tissue levels permit once or twice daily dosing, unlike cephalexin (which requires 4 times daily)", "Can be taken with food without affecting absorption"],
        "disadvantages": ["Inactive against MRSA and Pseudomonas", "Narrower Gram-negative spectrum compared to 3rd-generation cephalosporins"],
        "key_points": ["Convenient once-daily or twice-daily oral dosing for strep throat and skin infections", "Dispersible tablets convenient for children"],
        "memory_trick": "CEFA-DROX-il: Daily or twice-daily oral DROPS of penicillin-like coverage.",
        "key_suffix": "-droxil",
        "pronunciation_en": "sef-a-DROX-il",
        "pronunciation_hi": "सेफ़ा-ड्रॉक्सिल",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefaclor",
        "generic_name": "Cefaclor",
        "display_name": "Cefaclor",
        "active_ingredient": "Cefaclor monohydrate",
        "salt": "Cefaclor monohydrate",
        "category": "Antibiotics",
        "description": "A second-generation oral cephalosporin with enhanced activity against Haemophilus influenzae and Moraxella catarrhalis, used for upper and lower respiratory infections.",
        "strengths": ["125 mg DT", "250 mg", "375 mg ER", "500 mg"],
        "dosage_forms": ["Capsule", "Dispersible Tablet", "Extended-Release Tablet", "Oral Suspension"],
        "routes": ["Oral"],
        "mechanism_of_action": "Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs), leading to bacterial lysis.",
        "pharmacodynamics": "Active against Streptococcus pneumoniae, Streptococcus pyogenes, Moraxella catarrhalis, and beta-lactamase negative Haemophilus influenzae.",
        "absorption": "Well absorbed from the gastrointestinal tract; food delays peak absorption but total amount absorbed is preserved.",
        "distribution": "Good penetration into middle ear fluid, tonsils, bronchial mucosa, and lung parenchyma; 25% bound to plasma proteins.",
        "metabolism": "Not metabolized; excreted unchanged.",
        "excretion": "Approximately 60-85% excreted unchanged in urine within 8 hours.",
        "bioavailability": "High (over 90%)",
        "half_life": "0.6 to 1 hour",
        "protein_binding": "25%",
        "onset": "30 to 60 minutes",
        "duration": "8 hours (immediate release); 12 hours (ER)",
        "indications": ["Acute otitis media", "Acute bacterial sinusitis", "Pharyngitis and tonsillitis", "Acute bronchitis and pneumonia", "Uncomplicated urinary tract infections"],
        "contraindications": ["Hypersensitivity to cephalosporins or severe immediate beta-lactam allergy"],
        "warnings": ["Serum sickness-like reactions (erythema multiforme, joint swelling, fever) occur more frequently with cefaclor than other cephalosporins, especially in children", "Clostridioides difficile colitis"],
        "common_adverse_effects": ["Diarrhoea", "Nausea", "Vomiting", "Eosinophilia", "Headache"],
        "serious_adverse_effects": ["Serum sickness-like reaction", "Pseudomembranous colitis", "Anaphylaxis", "Erythema multiforme"],
        "drug_interactions": ["Probenecid (inhibits renal excretion)", "Antacids containing Mg/Al (decrease ER tablet absorption)", "Warfarin"],
        "monitoring": ["Signs of rash, arthralgia, or fever (serum sickness)", "Clinical resolution of infection"],
        "pregnancy": "Category B; safe during pregnancy.",
        "lactation": "Excreted in low levels in breast milk; compatible with breastfeeding.",
        "pediatric": "Widely used for pediatric otitis media; watch for serum sickness-like reactions.",
        "geriatric": "Assess renal function; adjust dosing if renal clearance is impaired.",
        "renal": "Dose adjustment usually required only in severe renal impairment (CrCl < 10 mL/min).",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Pleasant taste and dispersible formulation make it well accepted by pediatric patients", "Effective in otitis media and respiratory infections"],
        "disadvantages": ["Higher incidence of serum sickness-like reactions compared to other beta-lactams", "Short half-life requires 3 times daily dosing for standard formulations"],
        "key_points": ["Discontinue immediately if child develops hives, swollen joints, and fever (serum sickness-like reaction)", "ER tablets are taken twice daily with meals"],
        "memory_trick": "CEFA-clor: Otitis and respiratory CLEAR, but watch for serum-sickness CLOUDS.",
        "key_suffix": "-clor",
        "pronunciation_en": "SEF-a-klor",
        "pronunciation_hi": "सेफ़ा-क्लोर",
        "status": "active",
        "verification_status": "verified"
    }
]

print(f"Loaded {len(MEDICINES)} antibacterials in cat2")
