# Category 2 Continued: 20 more Antibacterials

MEDS = [
    {
        "slug": "cefditoren",
        "generic_name": "Cefditoren",
        "display_name": "Cefditoren Pivoxil",
        "active_ingredient": "Cefditoren pivoxil",
        "salt": "Cefditoren pivoxil",
        "category": "Antibiotics",
        "description": "An oral third-generation cephalosporin prodrug with enhanced affinity for penicillin-resistant Streptococcus pneumoniae and common respiratory pathogens.",
        "strengths": ["200 mg", "400 mg"],
        "dosage_forms": ["Film-coated Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Hydrolyzed by esterases during absorption to active cefditoren, which binds to PBPs and inhibits bacterial cell wall synthesis.",
        "pharmacodynamics": "High bactericidal activity against Streptococcus pneumoniae, Haemophilus influenzae, Moraxella catarrhalis, and MSSA.",
        "absorption": "Bioavailability approximately 14% on empty stomach, significantly increased when taken with a high-fat meal.",
        "distribution": "Good penetration into tonsillar tissue, bronchial mucosa, and middle ear fluid; 88% bound to plasma proteins.",
        "metabolism": "Prodrug pivoxil moiety cleaved by intestinal esterases to active cefditoren and pivalate; pivalate is conjugated with carnitine and excreted.",
        "excretion": "Eliminated primarily unchanged by the kidneys in urine via glomerular filtration and tubular secretion.",
        "bioavailability": "14% fasting, up to 20% with high-fat meals",
        "half_life": "1.6 hours",
        "protein_binding": "88%",
        "onset": "1.5 to 3 hours",
        "duration": "12 hours",
        "indications": ["Acute exacerbations of chronic bronchitis", "Community-acquired pneumonia", "Pharyngitis / tonsillitis", "Uncomplicated skin and skin structure infections"],
        "contraindications": ["Hypersensitivity to cephalosporins or beta-lactams", "Carnitine deficiency or inborn errors of metabolism causing carnitine loss", "Known milk protein hypersensitivity (contains sodium caseinate)"],
        "warnings": ["Carnitine depletion with prolonged therapy (pivalate conjugates carnitine)", "Must take with meals to maximize absorption", "Pseudomembranous colitis"],
        "common_adverse_effects": ["Diarrhoea", "Nausea", "Headache", "Abdominal pain", "Dyspepsia"],
        "serious_adverse_effects": ["Carnitine deficiency syndrome", "Clostridioides difficile colitis", "Anaphylaxis", "Severe cutaneous adverse reactions"],
        "drug_interactions": ["Antacids and H2-blockers (decrease oral absorption)", "Probenecid (increases plasma cefditoren levels)", "Carnitine-depleting medications"],
        "monitoring": ["Clinical response", "Stool frequency", "Renal function in patients with kidney impairment"],
        "pregnancy": "Category B; use during pregnancy only if clearly needed.",
        "lactation": "Excreted in animal milk; use caution during breastfeeding.",
        "pediatric": "Safety and effectiveness not established in pediatric patients under 12 years of age.",
        "geriatric": "No dose adjustment based on age alone; monitor renal function.",
        "renal": "If CrCl 30-49 mL/min, max dose 200 mg BID; if CrCl < 30 mL/min, max dose 200 mg once daily.",
        "hepatic": "No dose adjustment needed in mild to moderate hepatic impairment.",
        "advantages": ["Potent oral option for penicillin-resistant Streptococcus pneumoniae", "Effective alternative when macrolides and first-line cephalosporins fail"],
        "disadvantages": ["Must be taken with fatty meals for adequate absorption", "Carnitine-depleting pivalate ester restricts prolonged courses"],
        "key_points": ["Always take with a meal to ensure adequate absorption", "Avoid in patients with milk protein allergy or carnitine deficiency"],
        "memory_trick": "CEF-DI-TOREN: DI-et (food) needed to absorb, TORN between bugs and carnitine depletion.",
        "key_suffix": "-ditoren",
        "pronunciation_en": "sef-DYE-tohr-en",
        "pronunciation_hi": "सेफ़-डाइटोरन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "ampicillin-sulbactam",
        "generic_name": "Ampicillin / Sulbactam",
        "display_name": "Ampicillin + Sulbactam",
        "active_ingredient": "Ampicillin sodium and sulbactam sodium",
        "salt": "Ampicillin sodium and sulbactam sodium",
        "category": "Antibiotics",
        "description": "An injectable aminopenicillin combined with a beta-lactamase inhibitor, providing broad coverage against beta-lactamase producing organisms, anaerobes, and Acinetobacter baumannii.",
        "strengths": ["750 mg", "1.5 g", "3 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Ampicillin inhibits bacterial cell wall synthesis; sulbactam irreversibly binds and inactivates beta-lactamases and has intrinsic bactericidal activity against Acinetobacter baumannii PBPs.",
        "pharmacodynamics": "Bactericidal against MSSA, Streptococcus, Enterococcus faecalis, Listeria, anaerobes (Bacteroides fragilis), and Acinetobacter baumannii.",
        "absorption": "100% bioavailable upon intravenous administration; well absorbed intramuscularly.",
        "distribution": "Widely distributed in peritoneal fluid, skin blister fluid, lung, and bile; 28% (ampicillin) and 38% (sulbactam) protein bound.",
        "metabolism": "Minimal hepatic metabolism; both drugs eliminated largely unchanged.",
        "excretion": "Approximately 75-85% of both ampicillin and sulbactam eliminated unchanged in urine within 8 hours.",
        "bioavailability": "100% (IV)",
        "half_life": "1 hour (parent drug and inhibitor have parallel kinetics)",
        "protein_binding": "28% to 38%",
        "onset": "Immediate (IV)",
        "duration": "6 to 8 hours",
        "indications": ["Acinetobacter baumannii hospital-acquired infections and ventilator pneumonia (high-dose sulbactam regimens)", "Intra-abdominal infections (appendicitis, peritonitis)", "Gynecological infections / pelvic inflammatory disease", "Diabetic foot infections (polymicrobial coverage)", "Aspiration pneumonia and lung abscess"],
        "contraindications": ["Hypersensitivity to ampicillin, sulbactam, or penicillins", "History of cholestatic jaundice / hepatic dysfunction associated with ampicillin-sulbactam"],
        "warnings": ["Severe anaphylactic reactions in penicillin-allergic patients", "Clostridioides difficile colitis", "Renal dose adjustment essential"],
        "common_adverse_effects": ["Pain at injection site", "Diarrhoea", "Rash", "Nausea", "Elevated ALT/AST"],
        "serious_adverse_effects": ["Anaphylaxis", "Pseudomembranous colitis", "Cholestatic hepatitis / jaundice", "Neutropenia"],
        "drug_interactions": ["Allopurinol (high rate of maculopapular rash)", "Probenecid (reduces renal tubular secretion of both components)", "Methotrexate"],
        "monitoring": ["Renal function (BUN / creatinine)", "Liver enzymes", "Complete blood counts during extended therapy"],
        "pregnancy": "Category B; widely used and considered safe in pregnancy.",
        "lactation": "Excreted in low concentrations in breast milk; compatible with breastfeeding.",
        "pediatric": "Approved for pediatric intra-abdominal, skin, and ENT infections.",
        "geriatric": "Assess renal function; adjust dosing interval in renal impairment.",
        "renal": "Dose adjustment required: if CrCl 15-29 mL/min, dose q12h; if CrCl 5-14 mL/min, dose q24h.",
        "hepatic": "Use with caution; monitor liver enzymes.",
        "advantages": ["Intrinsic bactericidal affinity of sulbactam for Acinetobacter baumannii PBP2 makes it a mainstay for carbapenem-resistant Acinetobacter", "Excellent anaerobic and enterococcal coverage"],
        "disadvantages": ["High rates of resistance among hospital Enterobacteriaceae", "Requires frequent IV dosing (every 6 to 8 hours)"],
        "key_points": ["First-line component in high-dose combinations for MDR Acinetobacter baumannii", "Covers Enterococcus faecalis and oral/bowel anaerobes"],
        "memory_trick": "AMPI-SULBACTAM: Saves Unstable Lungs from Bad ACinetobacter and Bowel Anaerobes.",
        "key_suffix": "-cillin / -bactam",
        "pronunciation_en": "am-pi-SIL-in / sul-BAK-tam",
        "pronunciation_hi": "एम्पी-सिलिन / सुलबैक्टम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "ceftolozane-tazobactam",
        "generic_name": "Ceftolozane / Tazobactam",
        "display_name": "Ceftolozane + Tazobactam",
        "active_ingredient": "Ceftolozane sulfate and tazobactam sodium",
        "salt": "Ceftolozane sulfate and tazobactam sodium",
        "category": "Antibiotics",
        "description": "An advanced antipseudomonal cephalosporin combined with a beta-lactamase inhibitor, engineered specifically to overcome multidrug-resistant Pseudomonas aeruginosa.",
        "strengths": ["1.5 g vial (1 g ceftolozane / 0.5 g tazobactam)", "3 g vial (2 g ceftolozane / 1 g tazobactam)"],
        "dosage_forms": ["Powder for Concentrate for Solution for Infusion"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Ceftolozane inhibits PBPs (PBP1b, PBP1c, PBP3) with high affinity and resistance to ampC hydrolysis and efflux pumps; tazobactam protects against most class A and class C beta-lactamases.",
        "pharmacodynamics": "Unrivalled bactericidal activity against multidrug-resistant and extensively drug-resistant (MDR/XDR) Pseudomonas aeruginosa and ESBL-producing Enterobacteriaceae.",
        "absorption": "100% bioavailable by IV infusion over 1 hour.",
        "distribution": "Good penetration into pulmonary epithelial lining fluid and abdominal tissues; 16-21% (ceftolozane) and 30% (tazobactam) protein bound.",
        "metabolism": "Minimal hepatic metabolism; ceftolozane not metabolized by CYP enzymes.",
        "excretion": "Over 95% of ceftolozane and 80% of tazobactam eliminated unchanged in urine via glomerular filtration.",
        "bioavailability": "100% (IV)",
        "half_life": "2.7 to 3 hours",
        "protein_binding": "16% to 21%",
        "onset": "Immediate upon IV infusion",
        "duration": "8 hours",
        "indications": ["Hospital-acquired bacterial pneumonia and ventilator-associated pneumonia (HABP/VABP)", "Complicated intra-abdominal infections (combined with metronidazole)", "Complicated urinary tract infections including acute pyelonephritis", "Multidrug-resistant (MDR) Pseudomonas aeruginosa sepsis"],
        "contraindications": ["Severe hypersensitivity to ceftolozane, tazobactam, or other beta-lactams"],
        "warnings": ["Renal dose adjustment is critical (higher failure rates if underdosed in moderate renal impairment)", "Pseudomembranous colitis", "Direct Coombs test seroconversion"],
        "common_adverse_effects": ["Nausea", "Diarrhoea", "Headache", "Pyrexia", "Constipation"],
        "serious_adverse_effects": ["Clostridioides difficile colitis", "Anaphylaxis", "Renal impairment / AKI", "Agranulocytosis"],
        "drug_interactions": ["No significant CYP-mediated drug interactions", "Probenecid (increases tazobactam exposure)"],
        "monitoring": ["Renal function daily (mandatory for timely dose adjustments)", "Blood and respiratory cultures", "CBC in prolonged therapy"],
        "pregnancy": "Use during pregnancy only if clearly needed and benefits justify potential risks.",
        "lactation": "Excreted into human breast milk in low concentrations; use caution.",
        "pediatric": "Approved for pediatric complicated intra-abdominal and urinary infections aged birth and older.",
        "geriatric": "Renal impairment common; adjust dose based on CrCl.",
        "renal": "Dose adjustments: if CrCl 30-50 mL/min, give 750 mg q8h (or 1.5g q8h for pneumonia); if CrCl 15-29 mL/min, give 375 mg q8h (or 750mg q8h for pneumonia); on hemodialysis, single loading dose followed by maintenance.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Potent first-line reserve agent for difficult-to-treat and XDR Pseudomonas aeruginosa", "Penetrates lung epithelial lining fluid effectively at the 3 g HABP/VABP dose"],
        "disadvantages": ["Inactive against metallo-beta-lactamases (NDM, VIM) and carbapenemases (KPC)", "Costly reserve agent requiring antimicrobial stewardship"],
        "key_points": ["Best-in-class agent for MDR Pseudomonas aeruginosa", "Pneumonia dosing (3 g q8h) is double the intra-abdominal dose (1.5 g q8h)"],
        "memory_trick": "TOLO-ZANE: TOtal LOck on resistant Pseu-dO-moNAS.",
        "key_suffix": "-tolozane",
        "pronunciation_en": "sef-TOE-loe-zane / taz-oh-BAK-tam",
        "pronunciation_hi": "सेफ़्टोलो-ज़ेन / टैज़ो-बैक्टम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "ceftazidime-avibactam",
        "generic_name": "Ceftazidime / Avibactam",
        "display_name": "Ceftazidime + Avibactam",
        "active_ingredient": "Ceftazidime pentahydrate and avibactam sodium",
        "salt": "Ceftazidime pentahydrate and avibactam sodium",
        "category": "Antibiotics",
        "description": "A novel beta-lactam / non-beta-lactam diazabicyclooctane beta-lactamase inhibitor combination active against carbapenem-resistant Enterobacteriaceae (KPC, OXA-48).",
        "strengths": ["2.5 g vial (2 g ceftazidime / 0.5 g avibactam)"],
        "dosage_forms": ["Powder for Concentrate for Solution for Infusion"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Ceftazidime inhibits cell wall synthesis; avibactam is a non-beta-lactam beta-lactamase inhibitor that reversibly inhibits Class A (KPC), Class C (AmpC), and some Class D (OXA-48) beta-lactamases via covalent carbamylation.",
        "pharmacodynamics": "Restores ceftazidime activity against carbapenem-resistant Klebsiella pneumoniae (KPC), OXA-48 carbapenemases, and ESBLs; inactive against Class B metallo-beta-lactamases (NDM) unless paired with aztreonam.",
        "absorption": "100% bioavailable intravenously; administered as a 2-hour IV infusion.",
        "distribution": "Good penetration into lungs, abdominal cavity, and kidneys; <10% (ceftazidime) and 8% (avibactam) protein bound.",
        "metabolism": "Neither component undergoes significant hepatic metabolism.",
        "excretion": "Both excreted predominantly unchanged in urine by glomerular filtration (>80% within 24 hours).",
        "bioavailability": "100% (IV)",
        "half_life": "2 to 2.7 hours",
        "protein_binding": "<10%",
        "onset": "Immediate upon IV infusion",
        "duration": "8 hours",
        "indications": ["Carbapenem-resistant Enterobacteriaceae (CRE) infections producing KPC or OXA-48", "Hospital-acquired and ventilator-associated bacterial pneumonia", "Complicated intra-abdominal infections (with metronidazole)", "Complicated urinary tract infections / pyelonephritis", "Synergistic combination with aztreonam for NDM metallo-beta-lactamase producers"],
        "contraindications": ["Severe hypersensitivity to ceftazidime, avibactam, or cephalosporins"],
        "warnings": ["Renal dose adjustment is mandatory to prevent underdosing and treatment failure or neurotoxicity", "Not active against metallo-beta-lactamases (NDM) on its own", "Pseudomembranous colitis"],
        "common_adverse_effects": ["Positive direct Coombs test", "Nausea", "Diarrhoea", "Headache", "Constipation"],
        "serious_adverse_effects": ["Clostridioides difficile colitis", "Encephalopathy / neurotoxicity in renal impairment", "Anaphylaxis", "Thrombocytopenia"],
        "drug_interactions": ["OAT1/OAT3 inhibitors (may increase avibactam levels slightly)", "Probenecid", "Aminoglycosides (additive nephrotoxicity)"],
        "monitoring": ["Renal function tests (eGFR daily in ICU patients)", "Coombs test if hemolytic anaemia suspected", "Bacterial susceptibility profile"],
        "pregnancy": "Category B; use during pregnancy only if clearly needed.",
        "lactation": "Excreted in low levels in breast milk; use caution.",
        "pediatric": "Approved for infants 3 months and older for complicated UTI, intra-abdominal infections, and HAP/VAP.",
        "geriatric": "Renal clearance is frequently decreased; adjust dose based on CrCl.",
        "renal": "Dose adjustments required: if CrCl 31-50 mL/min, give 1.25 g q8h; if CrCl 16-30 mL/min, give 0.9375 g q12h; if CrCl 6-15 mL/min, give 0.9375 g q24h; on hemodialysis, give 0.9375 g after each dialysis session.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Life-saving reserve agent for KPC and OXA-48 carbapenem-resistant infections", "Non-beta-lactam inhibitor mechanism allows reversible binding without destruction"],
        "disadvantages": ["Inactive alone against NDM metallo-beta-lactamases (requires combining with Aztreonam)", "High cost and strict antimicrobial stewardship restrictions"],
        "key_points": ["First-line therapy for KPC and OXA-48 carbapenemase-producing Enterobacteriaceae", "Pair with Aztreonam to overcome NDM metallo-beta-lactamases"],
        "memory_trick": "AVI-bactam: AVIates over carbapenem resistance (KPC and OXA-48).",
        "key_suffix": "-tazidime / -avibactam",
        "pronunciation_en": "sef-TAZ-i-deem / AV-i-bak-tam",
        "pronunciation_hi": "सेफ़्टाज़ि-डीम / एवी-बैक्टम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "colistin",
        "generic_name": "Colistin",
        "display_name": "Colistin (Colistimethate Sodium)",
        "active_ingredient": "Colistimethate sodium (CMS)",
        "salt": "Colistimethate sodium",
        "category": "Antibiotics",
        "description": "A polymyxin antibiotic prodrug acting as a cationic detergent against Gram-negative outer membranes, reserved for extensively drug-resistant (XDR) pathogens.",
        "strengths": ["1 million IU (approx. 80 mg CMS)", "2 million IU", "3 million IU vial", "4.5 million IU vial"],
        "dosage_forms": ["Powder for Solution for Injection/Infusion or Inhalation"],
        "routes": ["Intravenous", "Inhalation"],
        "mechanism_of_action": "Binds to lipopolysaccharide (LPS) and phospholipids in the outer cell membrane of Gram-negative bacteria, displacing calcium and magnesium, causing membrane disruption and leakage of intracellular contents.",
        "pharmacodynamics": "Rapid concentration-dependent bactericidal action against carbapenem-resistant Pseudomonas aeruginosa, Acinetobacter baumannii, and Klebsiella pneumoniae; inherently inactive against Proteus, Serratia, and Burkholderia.",
        "absorption": "Not absorbed orally; administered IV as inactive prodrug CMS which slowly hydrolyzes to active colistin in plasma.",
        "distribution": "Poor penetration into pleural space, lung parenchyma, and CSF; nebulized route used as adjunct for ventilator pneumonia; 50% protein bound.",
        "metabolism": "CMS undergoes spontaneous non-enzymatic hydrolysis to active colistin in blood; colistin itself is cleared non-renally.",
        "excretion": "CMS is excreted largely unchanged by renal glomerular filtration; because clearance is renal, a greater percentage of CMS is converted to active colistin in renal impairment.",
        "bioavailability": "100% (IV)",
        "half_life": "2 to 3 hours for CMS; 14 to 18 hours for formed colistin",
        "protein_binding": "50%",
        "onset": "Loading dose required (9 million IU) to achieve therapeutic concentrations rapidly",
        "duration": "8 to 12 hours",
        "indications": ["Severe infections caused by multidrug-resistant and carbapenem-resistant Gram-negative bacteria (Acinetobacter, Klebsiella, Pseudomonas)", "Hospital-acquired and ventilator-associated pneumonia (IV plus adjunctive nebulized)", "Complicated urinary tract infections due to XDR organisms", "Cystic fibrosis pulmonary Pseudomonas colonisation (inhalation)"],
        "contraindications": ["Hypersensitivity to colistimethate sodium or polymyxins", "Myasthenia gravis (causes neuromuscular blockade)"],
        "warnings": ["High risk of dose-dependent nephrotoxicity (acute tubular necrosis)", "Neurotoxicity (paresthesias, ataxia, neuromuscular blockade, apnea)", "Loading dose mandatory due to slow conversion from CMS"],
        "common_adverse_effects": ["Elevated serum creatinine", "Oliguria", "Perioral and peripheral paresthesia", "Dizziness", "Bronchospasm (inhalation)"],
        "serious_adverse_effects": ["Acute kidney injury / tubular necrosis", "Respiratory muscle paralysis / apnea (neuromuscular blockade)", "Clostridioides difficile colitis"],
        "drug_interactions": ["Aminoglycosides, amphotericin B, vancomycin (drastically increases nephrotoxicity)", "Neuromuscular blocking agents (pancuronium, vecuronium - prolonged paralysis)", "Loop diuretics"],
        "monitoring": ["Serum creatinine and BUN daily", "Urine output every shift", "Signs of perioral numbness or muscle weakness"],
        "pregnancy": "Category C; crosses placenta, potential nephrotoxicity; use only when no alternatives exist.",
        "lactation": "Excreted in low amounts in breast milk; use with caution.",
        "pediatric": "Dosing based on mg of CBA (colistin base activity) or IU per kg; monitor renal status strictly.",
        "geriatric": "High incidence of nephrotoxicity; close monitoring of renal parameters.",
        "renal": "Dose adjustment mandatory: if CrCl 30-50 mL/min, give 5.5-7.5 million IU/day in 2 divided doses; if CrCl 10-29 mL/min, give 3-4.5 million IU/day in 2 divided doses; if CrCl < 10 mL/min, give 1.5-3 million IU/day. On hemodialysis, supplemental dose after dialysis.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Retains activity against heavily resistant Gram-negative bacilli when all newer agents fail", "Can be administered via nebulization directly into the lungs"],
        "disadvantages": ["High rate of acute nephrotoxicity (up to 30-50%)", "Complex dosing terminology (CMS vs CBA vs IU) creates medical calculation errors"],
        "key_points": ["Always administer an initial loading dose (9 million IU) in critically ill patients", "Watch serum creatinine daily and monitor for perioral tingling"],
        "memory_trick": "COLI-stin: Cold-hearted On Lipopolysaccharide; Kills Kidneys (nephrotoxic) and Nerves.",
        "key_suffix": "-colistin",
        "pronunciation_en": "koe-LIS-tin",
        "pronunciation_hi": "कोलिस-टिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "polymyxin-b",
        "generic_name": "Polymyxin B",
        "display_name": "Polymyxin B",
        "active_ingredient": "Polymyxin B sulfate",
        "salt": "Polymyxin B sulfate",
        "category": "Antibiotics",
        "description": "An active polymyxin antibiotic administered directly as active drug (not a prodrug), preferred over colistin for systemic bloodstream infections due to predictable pharmacokinetics and lower renal dependency.",
        "strengths": ["500,000 IU vial (approx. 50 mg)"],
        "dosage_forms": ["Powder for Solution for Injection/Infusion"],
        "routes": ["Intravenous", "Ophthalmic", "Topical"],
        "mechanism_of_action": "Binds to anionic lipid A portion of LPS in bacterial outer membrane, destabilizing membrane integrity and causing osmotic leakage of cellular contents.",
        "pharmacodynamics": "Rapid concentration-dependent bactericidal action against carbapenem-resistant Acinetobacter baumannii, Pseudomonas aeruginosa, and Klebsiella pneumoniae.",
        "absorption": "Administered directly as the active molecule; no conversion required (unlike colistimethate).",
        "distribution": "Moderate tissue distribution; does not penetrate intact blood-brain barrier; 78-92% bound to serum proteins.",
        "metabolism": "Cleared predominantly by non-renal metabolic and tissue binding pathways.",
        "excretion": "Less than 5% excreted unchanged in urine; predominantly eliminated via non-renal mechanisms.",
        "bioavailability": "100% (IV)",
        "half_life": "9 to 12 hours",
        "protein_binding": "78% to 92%",
        "onset": "Immediate upon infusion; loading dose (20,000-25,000 IU/kg) recommended",
        "duration": "12 hours",
        "indications": ["Severe bacteremia and septic shock due to carbapenem-resistant Gram-negative bacteria (CRAB, CRE, CRPA)", "Hospital-acquired pneumonia due to XDR pathogens (IV component)", "Complicated skin and wound infections (topical/IV)", "Superficial eye infections (ophthalmic drops)"],
        "contraindications": ["Hypersensitivity to polymyxins", "Concurrent administration with neurotoxic or nephrotoxic agents whenever possible"],
        "warnings": ["Nephrotoxicity and acute tubular necrosis", "Neuromuscular blockade causing respiratory paralysis", "Skin hyperpigmentation (especially on face and neck) reported in prolonged therapy"],
        "common_adverse_effects": ["Transient facial/cutaneous flushing and hyperpigmentation", "Perioral numbness", "Elevated serum creatinine", "Phlebitis"],
        "serious_adverse_effects": ["Acute renal failure / tubular necrosis", "Respiratory failure due to neuromuscular blockade", "Neurotoxicity (ataxia, convulsions)"],
        "drug_interactions": ["Aminoglycosides (additive nephrotoxicity and neuromuscular block)", "Amphotericin B", "Neuromuscular blockers (curare-like effects prolonged)"],
        "monitoring": ["Serum creatinine and BUN daily", "Urine output", "Neurological checks for paresthesia and muscle strength"],
        "pregnancy": "Avoid in pregnancy unless benefits outweigh significant potential nephrotoxic and neuromuscular risks.",
        "lactation": "Excretion in human milk unknown; use with extreme caution.",
        "pediatric": "Weight-based dosing (15,000-25,000 IU/kg/day in 2 divided doses); monitor renal parameters closely.",
        "geriatric": "High risk of acute kidney injury; close laboratory monitoring required.",
        "renal": "No routine dose reduction required for renal impairment (unlike colistin) because clearance is non-renal; some clinicians make modest reductions for severe toxicity.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Administered as active drug (predictable rapid serum levels without relying on prodrug conversion)", "Does not require renal dose adjustments, making it the preferred polymyxin for bloodstream infections"],
        "disadvantages": ["Not appropriate for urinary tract infections (low urinary excretion)", "High nephrotoxicity and risk of skin hyperpigmentation"],
        "key_points": ["Preferred over colistin for blood and lung infections because blood levels are predictable", "Do NOT use for urinary tract infections due to minimal urinary excretion"],
        "memory_trick": "POLYMYXIN-B: Best for Blood; Bad for Bladder (no urine clearance).",
        "key_suffix": "-myxin",
        "pronunciation_en": "pol-i-MIX-in BEE",
        "pronunciation_hi": "पॉलीमिक्सिन बी",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "tigecycline",
        "generic_name": "Tigecycline",
        "display_name": "Tigecycline",
        "active_ingredient": "Tigecycline",
        "salt": "Tigecycline",
        "category": "Antibiotics",
        "description": "A first-in-class glycylcycline antibiotic overcoming classical tetracycline efflux and ribosomal protection mechanisms, used for complicated skin, soft tissue, and intra-abdominal infections.",
        "strengths": ["50 mg vial"],
        "dosage_forms": ["Powder for Solution for Infusion"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Binds reversibly to the 30S ribosomal subunit with 5 times higher affinity than minocycline, halting peptide chain growth and overcoming classical tetracycline efflux pumps and ribosomal protection proteins.",
        "pharmacodynamics": "Broad bacteriostatic activity against MRSA, VRE, ESBL-producing Enterobacteriaceae, Acinetobacter baumannii, and anaerobes; inherently inactive against Pseudomonas, Proteus, and Providencia.",
        "absorption": "Administered exclusively by intravenous infusion over 30 to 60 minutes.",
        "distribution": "Extremely large volume of distribution (7 to 10 L/kg); concentrates heavily in tissues, bile, and bone; low serum concentrations; 71-89% protein bound.",
        "metabolism": "Minimal hepatic metabolism (<20%); primarily cleared unchanged.",
        "excretion": "Biliary excretion into faeces (approx. 59%) and renal excretion (approx. 33%).",
        "bioavailability": "100% (IV)",
        "half_life": "42 hours (prolonged terminal elimination half-life)",
        "protein_binding": "71% to 89%",
        "onset": "100 mg IV loading dose followed by 50 mg every 12 hours",
        "duration": "12 hours",
        "indications": ["Complicated intra-abdominal infections (peritonitis, abscesses)", "Complicated skin and soft tissue infections (including MRSA)", "Community-acquired pneumonia (when other alternatives fail)", "Part of combination therapy for multidrug-resistant Acinetobacter or CRE"],
        "contraindications": ["Hypersensitivity to tigecycline or tetracycline class antibiotics"],
        "warnings": ["FDA Black Box Warning: Increased risk of all-cause mortality compared to other treatments; reserve for when alternatives are unavailable", "Severe nausea and vomiting in up to 30% of patients", "Low serum levels: avoid in primary bacteremia"],
        "common_adverse_effects": ["Nausea (very common, up to 30%)", "Vomiting", "Diarrhoea", "Headache", "Abdominal pain"],
        "serious_adverse_effects": ["Acute pancreatitis (can be severe and fatal)", "All-cause mortality increase", "Severe hepatotoxicity / cholestasis", "Pseudomembranous colitis"],
        "drug_interactions": ["Warfarin (monitor INR carefully)", "Oral contraceptives (decreased efficacy)", "Calcineurin inhibitors"],
        "monitoring": ["Serum amylase and lipase (discontinue if pancreatitis develops)", "Liver function tests", "Clinical signs of treatment failure"],
        "pregnancy": "Avoid in pregnancy; causes fetal bone growth restriction and tooth discolouration.",
        "lactation": "Excreted in animal milk; avoid breastfeeding.",
        "pediatric": "Avoid in children under 8 years of age due to permanent tooth staining and enamel hypoplasia.",
        "geriatric": "No dose adjustment needed based on age.",
        "renal": "No dose adjustment required in renal impairment or hemodialysis.",
        "hepatic": "In severe hepatic impairment (Child-Pugh C), reduce maintenance dose to 25 mg every 12 hours following the 100 mg loading dose.",
        "advantages": ["Broad spectrum against MRSA, VRE, ESBLs, and Acinetobacter", "No dose adjustment needed in kidney failure", "High tissue penetration for intra-abdominal infections"],
        "disadvantages": ["Black box mortality warning; not suitable for bloodstream infections due to low serum levels", "High incidence of nausea/vomiting and risk of pancreatitis"],
        "key_points": ["Do NOT use for primary bloodstream infections due to low serum concentrations (high tissue distribution)", "Watch for severe nausea, vomiting, and acute pancreatitis"],
        "memory_trick": "TIGE-cycline: TISSUE tiger (great in tissue, terrible in blood), watch Pancreas and Nausea.",
        "key_suffix": "-cycline",
        "pronunciation_en": "tye-ge-SYE-kleen",
        "pronunciation_hi": "टाइगे-साइक्लिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "minocycline",
        "generic_name": "Minocycline",
        "display_name": "Minocycline",
        "active_ingredient": "Minocycline hydrochloride",
        "salt": "Minocycline hydrochloride",
        "category": "Antibiotics",
        "description": "A highly lipophilic second-generation tetracycline with excellent tissue and CNS penetration, widely used for moderate-to-severe acne vulgaris, MRSA skin infections, and multidrug-resistant Acinetobacter.",
        "strengths": ["50 mg", "100 mg", "100 mg IV vial"],
        "dosage_forms": ["Capsule", "Tablet", "Extended-Release Tablet", "Powder for Injection"],
        "routes": ["Oral", "Intravenous"],
        "mechanism_of_action": "Binds to the 30S ribosomal subunit, preventing entry of aminoacyl-tRNA into the ribosomal acceptor (A) site, inhibiting bacterial protein synthesis; also possesses anti-inflammatory and matrix metalloproteinase inhibitory properties.",
        "pharmacodynamics": "Broad bacteriostatic activity against Cutibacterium acnes, MRSA, atypical pathogens, Nocardia, and Acinetobacter baumannii; exhibits anti-inflammatory suppression of neutrophil chemotaxis.",
        "absorption": "Near-complete absorption (90-100%) from stomach and upper small intestine; minimally affected by food and dairy compared to older tetracyclines.",
        "distribution": "Highly lipophilic; achieves high concentrations in sebum, skin, CNS, tears, and saliva; 70-75% bound to plasma proteins.",
        "metabolism": "Metabolized in the liver (approx. 50%) to several inactive metabolites.",
        "excretion": "Excreted in faeces (approx. 20-30%) and urine (approx. 5-10% unchanged).",
        "bioavailability": "90% to 100%",
        "half_life": "15 to 22 hours (permits once or twice daily dosing)",
        "protein_binding": "70% to 75%",
        "onset": "1 to 2 hours",
        "duration": "12 to 24 hours",
        "indications": ["Moderate to severe inflammatory acne vulgaris", "Skin and soft tissue infections due to community-acquired MRSA", "Multidrug-resistant Acinetobacter baumannii infections (often IV component)", "Rheumatoid arthritis (disease-modifying adjunct due to MMP inhibition)", "Meningococcal carrier state eradication"],
        "contraindications": ["Hypersensitivity to tetracyclines", "Pregnancy and lactation", "Children under 8 years of age"],
        "warnings": ["Vestibular side effects (dizziness, vertigo, ataxia) occur more commonly in females", "Drug-induced lupus erythematosus and autoimmune hepatitis with prolonged acne therapy", "Blue-grey hyperpigmentation of skin, nails, sclera, and oral mucosa"],
        "common_adverse_effects": ["Dizziness / vertigo", "Nausea", "Dyspepsia", "Photosensitivity", "Diarrhoea"],
        "serious_adverse_effects": ["Drug-induced lupus syndrome", "Autoimmune hepatitis", "Pseudotumor cerebri (benign intracranial hypertension)", "Severe cutaneous drug reactions (DRESS syndrome)"],
        "drug_interactions": ["Multivalent cations: antacids, iron, calcium (chelate minocycline and reduce absorption; space by 2 hours)", "Isotretinoin (concurrent use contraindicated due to pseudotumor cerebri risk)", "Warfarin (potentiates anticoagulant effect)"],
        "monitoring": ["Signs of autoimmune symptoms (joint pain, rash, fever)", "Liver function in extended courses (>6 months)", "Inspection for skin/scleral hyperpigmentation"],
        "pregnancy": "Contraindicated; causes fetal bone growth retardation and permanent teeth staining.",
        "lactation": "Excreted into breast milk; contraindicated in nursing mothers.",
        "pediatric": "Contraindicated under 8 years due to permanent tooth discoloration and enamel defects.",
        "geriatric": "Higher incidence of dizziness and vestibular ataxia; cautious dosing.",
        "renal": "Does not accumulate significantly in renal failure; safe in moderate renal impairment without dose adjustment.",
        "hepatic": "Use with caution in preexisting liver disease.",
        "advantages": ["Superior lipophilicity and tissue penetration for skin and sebaceous glands", "No significant accumulation in renal impairment compared to older tetracyclines", "Proven activity against community-associated MRSA and Acinetobacter"],
        "disadvantages": ["Vestibular adverse effects (dizziness, lightheadedness)", "Risk of drug-induced lupus and slate-grey skin pigmentation on prolonged use"],
        "key_points": ["Never combine with oral isotretinoin (causes dangerous intracranial hypertension / pseudotumor cerebri)", "Take with a full glass of water while sitting upright to prevent pill-induced oesophagitis"],
        "memory_trick": "MINO-cycline: MINImizes acne and MRSA; watch for MINER's dizziness (vestibular) and slate-grey skin.",
        "key_suffix": "-cycline",
        "pronunciation_en": "min-oh-SYE-kleen",
        "pronunciation_hi": "मिनो-साइक्लिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "tobramycin",
        "generic_name": "Tobramycin",
        "display_name": "Tobramycin",
        "active_ingredient": "Tobramycin sulfate",
        "salt": "Tobramycin sulfate",
        "category": "Antibiotics",
        "description": "A potent aminoglycoside antibiotic with superior intrinsic activity against Pseudomonas aeruginosa compared to gentamicin, administered IV or via inhalation for cystic fibrosis.",
        "strengths": ["20 mg/2 mL", "80 mg/2 mL vial", "300 mg/5 mL inhalation solution", "0.3% eye drops"],
        "dosage_forms": ["Solution for Injection", "Inhalation Solution", "Ophthalmic Drops"],
        "routes": ["Intravenous", "Intramuscular", "Inhalation", "Ophthalmic"],
        "mechanism_of_action": "Binds irreversibly to the bacterial 30S ribosomal subunit, causing misreading of genetic code and premature termination of peptide chain synthesis, leading to cell membrane damage and bactericidal death.",
        "pharmacodynamics": "Rapid concentration-dependent bactericidal killing (Cmax/MIC driven) with significant post-antibiotic effect (PAE); potent against Pseudomonas aeruginosa and Gram-negative bacilli.",
        "absorption": "Poor oral absorption (<1%); 100% bioavailable parenterally; inhalation provides high local bronchial concentrations with low systemic absorption.",
        "distribution": "Confined largely to extracellular fluid; poor CSF and bronchial penetration after IV; <10% protein bound.",
        "metabolism": "Not metabolized; excreted entirely as active parent drug.",
        "excretion": "Greater than 90% eliminated unchanged in urine via glomerular filtration.",
        "bioavailability": "100% (IV/IM); systemic bioavailability approx. 12% following inhalation",
        "half_life": "2 to 3 hours in adults with normal renal function",
        "protein_binding": "<10%",
        "onset": "Rapid peak serum concentration within 30 to 60 minutes after infusion",
        "duration": "24 hours (extended-interval once-daily dosing) or 8 hours (multiple daily dosing)",
        "indications": ["Severe Pseudomonas aeruginosa infections and hospital-acquired sepsis", "Chronic pulmonary Pseudomonas aeruginosa infection in cystic fibrosis (inhalation)", "Complicated intra-abdominal and urinary tract infections (with beta-lactams)", "Bacterial conjunctivitis and keratitis (ophthalmic)"],
        "contraindications": ["Hypersensitivity to tobramycin or other aminoglycosides", "Myasthenia gravis (causes neuromuscular blockade)"],
        "warnings": ["Black box warnings: Nephrotoxicity (acute tubular necrosis) and Ototoxicity (vestibular and irreversible cochlear hearing loss)", "Therapeutic drug monitoring (trough and peak levels) mandatory", "Risk of fetal harm (congenital deafness)"],
        "common_adverse_effects": ["Elevated serum creatinine", "Cough and voice alteration (inhalation)", "Transient dizziness", "Ocular irritation (drops)"],
        "serious_adverse_effects": ["Permanent sensorineural hearing loss / cochlear damage", "Acute tubular necrosis / renal failure", "Neuromuscular blockade / respiratory arrest"],
        "drug_interactions": ["Loop diuretics (furosemide - greatly potentiates ototoxicity)", "Vancomycin, colistin, cisplatin, amphotericin B (additive nephrotoxicity)", "Neuromuscular blocking agents"],
        "monitoring": ["Therapeutic drug monitoring: trough level (<1 mcg/mL for once-daily) and peak levels", "Serum creatinine and BUN every 2 to 3 days", "Audiometry and vestibular function checks"],
        "pregnancy": "Category D; crosses placenta, risk of bilateral congenital irreversible deafness.",
        "lactation": "Excreted in low levels in breast milk; poorly absorbed by infant gut, but use caution.",
        "pediatric": "Commonly used in neonatal sepsis and pediatric cystic fibrosis; calculate dose carefully by weight.",
        "geriatric": "Renal clearance is reduced; once-daily dosing preferred with strict trough monitoring.",
        "renal": "Strict dose and interval adjustments mandatory: extend dosing interval (e.g. q36h or q48h) or reduce dose based on creatinine clearance and trough monitoring.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["2 to 4 times more active in vitro against Pseudomonas aeruginosa than gentamicin", "Once-daily extended interval dosing maximizes bactericidal peak while minimizing trough nephrotoxicity", "Inhalation formulation targets lungs without systemic toxicity"],
        "disadvantages": ["Narrow therapeutic index requiring blood level monitoring", "Irreversible ototoxicity and cumulative nephrotoxicity"],
        "key_points": ["More potent against Pseudomonas aeruginosa than gentamicin", "Keep trough levels below 1 mcg/mL to avoid renal damage and hearing loss"],
        "memory_trick": "TOBRA-mycin: Top Antipseudomonal aminoglycoside; Target low Trough to protect ears and kidneys.",
        "key_suffix": "-mycin",
        "pronunciation_en": "toe-bra-MYE-sin",
        "pronunciation_hi": "टोब्रा-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "netilmicin",
        "generic_name": "Netilmicin",
        "display_name": "Netilmicin",
        "active_ingredient": "Netilmicin sulfate",
        "salt": "Netilmicin sulfate",
        "category": "Antibiotics",
        "description": "A semi-synthetic aminoglycoside antibiotic derived from sisomicin with resistance to several bacterial modifying enzymes and demonstrably lower ototoxicity than gentamicin.",
        "strengths": ["25 mg/mL", "100 mg/mL", "300 mg/3 mL vial", "0.3% eye drops"],
        "dosage_forms": ["Solution for Injection", "Ophthalmic Solution"],
        "routes": ["Intravenous", "Intramuscular", "Ophthalmic"],
        "mechanism_of_action": "Binds irreversibly to the 30S bacterial ribosomal subunit, interfering with initiation complex formation and causing misreading of mRNA, leading to rapid bactericidal killing.",
        "pharmacodynamics": "Broad bactericidal spectrum against Enterobacteriaceae (E. coli, Klebsiella, Enterobacter, Serratia) and Pseudomonas aeruginosa; active against many gentamicin-resistant strains due to stability against modifying enzymes.",
        "absorption": "Rapidly and completely absorbed after intramuscular injection; 100% bioavailable IV.",
        "distribution": "Distributes primarily into extracellular fluids; achieves therapeutic levels in synovial, peritoneal, and pleural fluids; <10% protein bound.",
        "metabolism": "Not metabolized in humans; eliminated entirely as active parent drug.",
        "excretion": "Greater than 80% excreted unchanged in urine via glomerular filtration within 24 hours.",
        "bioavailability": "100% (IV/IM)",
        "half_life": "2 to 2.5 hours",
        "protein_binding": "<10%",
        "onset": "Peak serum level within 30 to 60 minutes after IM or end of IV infusion",
        "duration": "24 hours (once-daily regimen) or 8-12 hours",
        "indications": ["Severe systemic infections and bacteremia due to susceptible Gram-negative bacilli", "Complicated intra-abdominal sepsis (in combination with metronidazole)", "Complicated urinary tract infections and acute pyelonephritis", "Bacterial ocular infections (conjunctivitis, blepharitis)"],
        "contraindications": ["Hypersensitivity to netilmicin or aminoglycosides", "Myasthenia gravis"],
        "warnings": ["Nephrotoxicity and ototoxicity (although reported to be less than gentamicin, clinical caution remains mandatory)", "Therapeutic drug monitoring recommended in elderly or renal insufficiency", "Adequate patient hydration must be ensured"],
        "common_adverse_effects": ["Mild serum creatinine rise", "Dizziness", "Tinnitus", "Transient local injection site pain"],
        "serious_adverse_effects": ["Ototoxicity (cochlear and vestibular damage)", "Acute tubular necrosis / renal failure", "Neuromuscular blockade"],
        "drug_interactions": ["Loop diuretics (furosemide - potentiates ototoxicity)", "Other nephrotoxic drugs (amphotericin B, vancomycin, cisplatin)", "Muscle relaxants"],
        "monitoring": ["Renal function tests (BUN / creatinine)", "Serum peak and trough drug levels", "Audiometric checks if treatment exceeds 7-10 days"],
        "pregnancy": "Category D; potential risk of fetal eighth cranial nerve damage.",
        "lactation": "Excreted in small amounts in breast milk; use with caution.",
        "pediatric": "Approved for pediatric and neonatal sepsis; dosing adjusted based on age and weight.",
        "geriatric": "Renal clearance is reduced; once-daily dosing with trough monitoring is strongly advised.",
        "renal": "Dose adjustment required based on creatinine clearance: extend dosing interval or decrease dose; monitor trough levels (target <1-2 mcg/mL).",
        "hepatic": "No dose adjustment needed.",
        "advantages": ["Resistant to several bacterial aminoglycoside-modifying enzymes, overcoming gentamicin resistance", "Significantly lower cochlear and vestibular toxicity reported in clinical trials than gentamicin"],
        "disadvantages": ["Narrow therapeutic margin requiring monitoring", "Inactive against anaerobic pathogens"],
        "key_points": ["Lower ototoxicity profile than gentamicin", "Can be given as a convenient single daily dose"],
        "memory_trick": "NETIL-micin: NEWER aminoglycoside, NEATER on the ears than gentamicin.",
        "key_suffix": "-micin",
        "pronunciation_en": "ne-til-MYE-sin",
        "pronunciation_hi": "नेटिल-माइसिन",
        "status": "active",
        "verification_status": "verified"
    }
]

print(f"Loaded {len(MEDS)} additional antibacterials")
