# Category 3: Antifungals, Antivirals & Antiparasitics (25 medicines)

MEDS = [
    {
        "slug": "voriconazole",
        "generic_name": "Voriconazole",
        "display_name": "Voriconazole",
        "active_ingredient": "Voriconazole",
        "salt": "Voriconazole",
        "category": "Antifungals",
        "description": "A second-generation broad-spectrum triazole antifungal agent, established as the first-line treatment of choice for invasive aspergillosis.",
        "strengths": ["50 mg", "200 mg", "200 mg IV vial"],
        "dosage_forms": ["Film-coated Tablet", "Powder for Solution for Infusion", "Oral Suspension"],
        "routes": ["Oral", "Intravenous"],
        "mechanism_of_action": "Inhibits fungal cytochrome P450-dependent 14-alpha-sterol demethylase, blocking the conversion of lanosterol to ergosterol, leading to accumulation of toxic 14-methylated sterols and fungal cell membrane lysis.",
        "pharmacodynamics": "Fungicidal against Aspergillus species, Scedosporium, and Fusarium; fungistatic against Candida species (including fluconazole-resistant C. krusei and C. glabrata).",
        "absorption": "Rapidly and almost completely absorbed (approx. 96% oral bioavailability); food decreases absorption, so take 1 hour before or 1 hour after meals.",
        "distribution": "Widely distributed into tissues and CSF (CSF levels 50% of plasma levels); 58% bound to plasma proteins.",
        "metabolism": "Extensively metabolized by hepatic CYP2C19 (subject to genetic polymorphism), CYP2C9, and CYP3A4; exhibits non-linear saturation pharmacokinetics in adults.",
        "excretion": "Less than 2% excreted unchanged in urine; approximately 80% eliminated in urine as inactive metabolites and 20% in faeces.",
        "bioavailability": "Approximately 96%",
        "half_life": "6 hours (dose-dependent due to saturable metabolism)",
        "protein_binding": "58%",
        "onset": "IV loading dose (6 mg/kg q12h x 2 doses) achieves steady state within 24 hours",
        "duration": "12 hours",
        "indications": ["Invasive aspergillosis (first-line treatment of choice)", "Candidemia in non-neutropenic patients and disseminated Candida infections", "Invasive Scedosporium and Fusarium infections", "Esophageal candidiasis refractory to fluconazole", "Antifungal prophylaxis in high-risk allogeneic stem cell transplant recipients"],
        "contraindications": ["Hypersensitivity to voriconazole or other azoles", "Co-administration with potent CYP3A4 inducers (rifampicin, carbamazepine, St. John's wort)", "Concurrent use of terfenadine, astemizole, cisapride, pimozide, or quinidine"],
        "warnings": ["Visual disturbances (photopsia, altered color perception, blurred vision) occur in approx. 30% of patients within 30 minutes of dosing", "Hepatotoxicity: monitor LFTs at baseline and regularly during therapy", "Phototoxicity and risk of squamous cell carcinoma of the skin with prolonged therapy", "Therapeutic drug monitoring (TDM) strongly recommended (target trough 1.5 to 5.0 mcg/mL)"],
        "common_adverse_effects": ["Transient visual disturbances (photopsia / blurred vision)", "Fever", "Nausea", "Maculopapular rash", "Elevated ALT/AST"],
        "serious_adverse_effects": ["Severe hepatotoxicity / fulminant hepatic failure", "QTc interval prolongation / Torsades de pointes", "Squamous cell skin carcinoma", "Fluorosis and periostitis (in prolonged therapy)", "Hallucinations / neurotoxicity"],
        "drug_interactions": ["Potent CYP3A4/CYP2C19 substrate and inhibitor: greatly increases levels of tacrolimus, cyclosporine, sirolimus (sirolimus contraindicated)", "Warfarin (substantially increases INR)", "Statins (rhabdomyolysis risk)", "Omeprazole (doubles omeprazole levels)"],
        "monitoring": ["Therapeutic drug monitoring: trough concentration (trough target 1.5 - 5.0 mcg/mL)", "Liver function tests (baseline, weekly for 1 month, then monthly)", "Visual function checks", "Skin examination for sun sensitivity and premalignant lesions"],
        "pregnancy": "Category D; embryotoxic and teratogenic in animal models; avoid during pregnancy unless life-saving.",
        "lactation": "Excretion in human milk unknown; discontinue breastfeeding during therapy.",
        "pediatric": "Approved for children 2 years and older; clearance is faster in children, requiring higher mg/kg weight-based dosing.",
        "geriatric": "No dose adjustment based on age alone; assess hepatic and cardiac parameters.",
        "renal": "Oral tablet requires no renal adjustment; IV formulation contains sulfobutyl ether beta-cyclodextrin (SBECD) which accumulates in renal impairment (switch to oral if CrCl < 50 mL/min).",
        "hepatic": "Standard loading dose, but reduce maintenance dose by 50% in mild to moderate hepatic cirrhosis (Child-Pugh A and B).",
        "advantages": ["First-line drug of choice for invasive aspergillosis with superior survival over amphotericin B", "Near 100% oral bioavailability allows seamless IV to oral step-down", "Excellent penetration into brain tissue and CSF for fungal CNS infections"],
        "disadvantages": ["Non-linear saturable pharmacokinetics require frequent therapeutic drug monitoring", "Photosensitivity and skin cancer risk with long-term use"],
        "key_points": ["First-line drug of choice for invasive aspergillosis", "Counsel patients about temporary visual brightness or color changes that resolve within 30 minutes", "Monitor trough levels (target 1.5 - 5.0 mcg/mL)"],
        "memory_trick": "VORI-conazole: Visual disturbances, Overcomes aspergillus, Requires In-depth TDM.",
        "key_suffix": "-conazole",
        "pronunciation_en": "vor-i-KON-a-zole",
        "pronunciation_hi": "वोरिकॉना-ज़ोल",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "posaconazole",
        "generic_name": "Posaconazole",
        "display_name": "Posaconazole",
        "active_ingredient": "Posaconazole",
        "salt": "Posaconazole",
        "category": "Antifungals",
        "description": "An extended-spectrum triazole antifungal with potent activity against Aspergillus, Candida, and Mucorales (zygomycetes), widely used for prophylaxis in hematological malignancy and salvage therapy.",
        "strengths": ["100 mg delayed-release tablet", "300 mg/16.7 mL IV vial", "40 mg/mL oral suspension"],
        "dosage_forms": ["Delayed-Release Tablet", "Solution for Infusion", "Oral Suspension"],
        "routes": ["Oral", "Intravenous"],
        "mechanism_of_action": "Inhibits fungal lanosterol 14-alpha-demethylase, disrupting ergosterol synthesis and destabilizing the fungal cell membrane.",
        "pharmacodynamics": "Broad spectrum covering Aspergillus, Candida, Cryptococcus, Fusarium, and uniquely Mucorales (Rhizopus, Mucor, Lichtheimia).",
        "absorption": "Delayed-release tablets provide consistent, pH-independent absorption (much superior to oral suspension); bioavailability enhanced when taken with food.",
        "distribution": "Very large volume of distribution (approx. 5 to 25 L/kg); penetrates well into pulmonary alveolar cells and tissues; >98% bound to albumin.",
        "metabolism": "Predominantly undergoes phase II UDP-glucuronidation; minimal hepatic CYP-mediated oxidation.",
        "excretion": "Excreted mainly in faeces (approx. 77%, mostly unchanged) and urine (approx. 14% as glucuronides).",
        "bioavailability": "High with delayed-release tablets (>80% with food); erratic with oral suspension",
        "half_life": "26 to 35 hours (enables once-daily maintenance dosing with delayed-release tablets)",
        "protein_binding": ">98%",
        "onset": "Loading dose on day 1 (300 mg BID) achieves steady-state faster",
        "duration": "24 hours",
        "indications": ["Prophylaxis of invasive fungal infections in patients with AML/MDS receiving induction chemotherapy", "Prophylaxis of invasive fungal infections in allogeneic HSCT recipients with graft-versus-host disease (GVHD)", "Treatment of invasive aspergillosis refractory to or intolerant of first-line agents", "Treatment of mucormycosis (second-line or oral step-down after amphotericin B)", "Oropharyngeal candidiasis refractory to itraconazole or fluconazole"],
        "contraindications": ["Hypersensitivity to posaconazole or other azoles", "Concurrent administration of CYP3A4 substrates that prolong QTc (ergot alkaloids, terfenadine, pimozide)"],
        "warnings": ["QTc prolongation and cardiac arrhythmias", "Hepatotoxicity: monitor liver function tests", "Delayed-release tablets and oral suspension are NOT interchangeable due to differing dosing and bioavailability"],
        "common_adverse_effects": ["Nausea", "Diarrhoea", "Pyrexia", "Hypokalemia", "Headache"],
        "serious_adverse_effects": ["Severe hepatotoxicity / jaundice", "Torsades de pointes / QTc prolongation", "Pseudohyperaldosteronism (hypertension and hypokalemia) in high doses"],
        "drug_interactions": ["Potent CYP3A4 inhibitor: increases blood concentrations of cyclosporine, tacrolimus, and sirolimus (mandatory dose reductions and monitoring)", "Midazolam, statins, vincristine (neurotoxicity risk with vincristine)"],
        "monitoring": ["Therapeutic drug monitoring (target trough >0.7 mcg/mL for prophylaxis; >1.0-1.5 mcg/mL for treatment)", "Liver function tests", "Serum electrolytes (potassium and magnesium)", "ECG for QTc interval"],
        "pregnancy": "Category C; use only when benefit justifies potential risk to fetus.",
        "lactation": "Excreted in animal milk; avoid breastfeeding.",
        "pediatric": "Approved for pediatric patients 2 years and older for prophylaxis and treatment (delayed-release tablets).",
        "geriatric": "No dose adjustment based on age alone.",
        "renal": "No dose adjustment required for oral tablets in renal failure; IV formulation contains betadex sulfobutyl ether sodium which accumulates in moderate to severe renal impairment (eGFR < 50 mL/min).",
        "hepatic": "Use caution; monitor liver enzymes.",
        "advantages": ["Broader spectrum than voriconazole, covering Mucorales (zygomycosis)", "Delayed-release tablet formulation allows once-daily maintenance dosing", "Proven survival benefit in antifungal prophylaxis for AML/GVHD"],
        "disadvantages": ["Oral suspension and delayed-release tablets have different dosing and cannot be swapped milligram-for-milligram", "Potent CYP3A4 inhibition necessitates close immunosuppressant dose adjustment"],
        "key_points": ["Delayed-release tablets are preferred over suspension due to predictable absorption", "Active against Mucorales fungi unlike voriconazole"],
        "memory_trick": "POSA-conazole: Protective against Opportunistic Sickness and Aspergillosis, Plus Zygomycetes.",
        "key_suffix": "-conazole",
        "pronunciation_en": "poe-sa-KON-a-zole",
        "pronunciation_hi": "पोसाकॉना-ज़ोल",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "caspofungin",
        "generic_name": "Caspofungin",
        "display_name": "Caspofungin",
        "active_ingredient": "Caspofungin acetate",
        "salt": "Caspofungin acetate",
        "category": "Antifungals",
        "description": "A first-in-class parenteral echinocandin antifungal that inhibits fungal cell wall synthesis, used for invasive candidiasis, esophageal candidiasis, and salvage therapy for invasive aspergillosis.",
        "strengths": ["50 mg vial", "70 mg vial"],
        "dosage_forms": ["Lyophilized Powder for Solution for Infusion"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Non-competitively inhibits beta-(1,3)-D-glucan synthase, an enzyme absent in mammalian cells, preventing synthesis of beta-(1,3)-D-glucan in the fungal cell wall, causing osmotic fragility and lysis.",
        "pharmacodynamics": "Concentration-dependent fungicidal activity against Candida species (including azole-resistant C. glabrata and C. krusei); fungistatic against Aspergillus species; inactive against Cryptococcus and Mucorales.",
        "absorption": "Not absorbed from gastrointestinal tract; administered solely as a 1-hour intravenous infusion.",
        "distribution": "Extensive tissue distribution into liver, kidneys, and spleen; minimal CSF and ocular penetration; 97% bound to human albumin.",
        "metabolism": "Slowly metabolized by hydrolysis and N-acetylation in the liver to inactive peptide breakdown products; not cleared by CYP450 enzymes.",
        "excretion": "Excreted in faeces (approx. 35%) and urine (approx. 41%, with <2% unchanged).",
        "bioavailability": "100% (IV)",
        "half_life": "9 to 11 hours (beta phase); terminal half-life 40 to 50 hours",
        "protein_binding": "97%",
        "onset": "70 mg loading dose on day 1 achieves steady state rapidly, followed by 50 mg once daily",
        "duration": "24 hours",
        "indications": ["Invasive candidiasis and candidemia in neutropenic and non-neutropenic patients", "Empirical therapy for presumed fungal infections in febrile neutropenic patients", "Esophageal candidiasis", "Salvage therapy for invasive aspergillosis in patients refractory to or intolerant of voriconazole or amphotericin B"],
        "contraindications": ["Hypersensitivity to caspofungin or other echinocandins"],
        "warnings": ["Hepatic dysfunction: monitor liver enzymes during therapy", "Dose adjustment required in moderate hepatic impairment", "Histamine-mediated symptoms (rash, facial swelling, pruritus) with rapid infusion"],
        "common_adverse_effects": ["Fever", "Phlebitis at injection site", "Nausea", "Hypokalemia", "Elevated AST/ALT/alkaline phosphatase"],
        "serious_adverse_effects": ["Anaphylaxis / severe histamine release", "Hepatotoxicity / clinical hepatitis", "Hyperbilirubinemia"],
        "drug_interactions": ["Cyclosporine (increases caspofungin AUC by 35% and increases ALT elevations; avoid combination unless benefits outweigh risk)", "Tacrolimus (caspofungin reduces tacrolimus trough by approx. 20%; monitor levels)", "Efavirenz, nevirapine, rifampicin, dexamethasone, phenytoin (induce caspofungin clearance; increase daily dose to 70 mg)"],
        "monitoring": ["Liver function tests (transaminases and bilirubin)", "Serum potassium", "Signs of infusion reactions"],
        "pregnancy": "Category C; embryotoxic in animal models; use only if potential benefit justifies potential risk.",
        "lactation": "Excreted in animal milk; use caution during breastfeeding.",
        "pediatric": "Approved for pediatric patients 3 months and older (dosed by body surface area: 70 mg/m2 loading, then 50 mg/m2/day).",
        "geriatric": "No dosage adjustment needed based on age alone.",
        "renal": "No dosage adjustment required in renal impairment or hemodialysis.",
        "hepatic": "No adjustment in mild hepatic impairment (Child-Pugh 5-6); in moderate hepatic impairment (Child-Pugh 7-9), reduce maintenance dose to 35 mg daily after 70 mg loading dose.",
        "advantages": ["Targets fungal cell wall (beta-1,3-glucan) absent in human cells, providing exceptional safety and tolerability", "No nephrotoxicity (vastly superior safety profile compared to amphotericin B)", "No dose adjustment required in renal failure"],
        "disadvantages": ["Inactive against Cryptococcus neoformans and Mucorales", "Parenteral only; requires daily IV infusion"],
        "key_points": ["First-line choice for candidemia and invasive candidiasis", "Requires a 70 mg loading dose on Day 1 followed by 50 mg daily"],
        "memory_trick": "CASPO-fungin: Candida Smasher; Beta-Glucan Buster; Zero Nephrotoxicity.",
        "key_suffix": "-fungin",
        "pronunciation_en": "kas-poe-FUN-jin",
        "pronunciation_hi": "कैस्पो-फ़ंजिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "micafungin",
        "generic_name": "Micafungin",
        "display_name": "Micafungin",
        "active_ingredient": "Micafungin sodium",
        "salt": "Micafungin sodium",
        "category": "Antifungals",
        "description": "A second-generation echinocandin antifungal with no loading dose requirement, used for invasive candidiasis, candidemia, and antifungal prophylaxis in stem cell transplantation.",
        "strengths": ["50 mg vial", "100 mg vial"],
        "dosage_forms": ["Lyophilized Powder for Solution for Infusion"],
        "routes": ["Intravenous"],
        "mechanism_of_action": "Non-competitively inhibits 1,3-beta-D-glucan synthase, disrupting fungal cell wall integrity and leading to osmotic lysis.",
        "pharmacodynamics": "Potent concentration-dependent fungicidal activity against Candida species including azole-resistant strains; fungistatic against Aspergillus.",
        "absorption": "Administered exclusively by intravenous infusion over 1 hour; 100% bioavailable.",
        "distribution": "Extensively distributed into tissues; poor CSF and ocular penetration; >99% bound to plasma proteins (predominantly albumin).",
        "metabolism": "Metabolized hepatically by arylsulfatase and catechol-O-methyltransferase; minimal CYP3A hydroxylation.",
        "excretion": "Excreted predominantly in faeces via biliary elimination (>70%); less than 15% excreted in urine.",
        "bioavailability": "100% (IV)",
        "half_life": "14 to 17 hours (enables once-daily dosing without requiring an initial loading dose)",
        "protein_binding": ">99%",
        "onset": "Rapid steady state reached within 4 days without requiring a loading dose",
        "duration": "24 hours",
        "indications": ["Treatment of candidemia, acute disseminated candidiasis, and Candida peritonitis", "Esophageal candidiasis", "Prophylaxis of Candida infections in hematopoietic stem cell transplant (HSCT) recipients during neutropenia"],
        "contraindications": ["Hypersensitivity to micafungin or echinocandins"],
        "warnings": ["Hepatotoxicity and development of hepatic tumors seen in preclinical high-dose rodent models (monitor LFTs)", "Infusion-related histamine reactions", "Hemolysis and hemolytic anaemia reported rarely"],
        "common_adverse_effects": ["Nausea", "Pyrexia", "Hypokalemia", "Diarrhoea", "Headache", "Elevated liver transaminases"],
        "serious_adverse_effects": ["Acute liver injury / jaundice", "Severe hemolytic anaemia", "Anaphylaxis / shock", "Renal impairment"],
        "drug_interactions": ["Very low potential for CYP-mediated drug interactions", "Slight increase in AUC of sirolimus, nifedipine, and itraconazole (monitor for toxicity)"],
        "monitoring": ["Liver function tests (ALT, AST, alkaline phosphatase, bilirubin)", "Complete blood count for hemolysis", "Renal function tests"],
        "pregnancy": "Category C; use during pregnancy only if potential benefit justifies potential risk.",
        "lactation": "Excreted in animal milk; use caution during breastfeeding.",
        "pediatric": "Approved for pediatric patients from neonates to adolescents for invasive candidiasis and prophylaxis.",
        "geriatric": "No dose adjustment required based on age.",
        "renal": "No dosage adjustment needed in renal impairment or hemodialysis.",
        "hepatic": "No dosage adjustment needed in mild to moderate hepatic impairment (Child-Pugh A and B).",
        "advantages": ["Does NOT require an initial loading dose (unlike caspofungin)", "Minimal drug-drug interactions compared to azoles and other echinocandins", "Safe in renal impairment without dose adjustment"],
        "disadvantages": ["Inactive against Cryptococcus and Mucorales", "Preclinical rodent warning regarding hepatic tumors with prolonged high exposure"],
        "key_points": ["First-line choice for candidemia; no loading dose needed (100 mg once daily)", "Fewer drug interactions than caspofungin or azoles"],
        "memory_trick": "MICA-fungin: MINIMAL interactions, Candida killer, Always 100 mg daily (no loading).",
        "key_suffix": "-fungin",
        "pronunciation_en": "mye-ka-FUN-jin",
        "pronunciation_hi": "माइका-फ़ंजिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "luliconazole",
        "generic_name": "Luliconazole",
        "display_name": "Luliconazole",
        "active_ingredient": "Luliconazole",
        "salt": "Luliconazole",
        "category": "Antifungals",
        "description": "A potent topical imidazole antifungal with exceptionally low minimum inhibitory concentrations (MICs) against dermatophytes, permitting once-daily application for only 1 to 2 weeks.",
        "strengths": ["1% cream", "1% lotion"],
        "dosage_forms": ["Topical Cream", "Topical Lotion"],
        "routes": ["Topical"],
        "mechanism_of_action": "Inhibits fungal lanosterol 14-alpha-demethylase, disrupting ergosterol synthesis in fungal cell membranes; uniquely incorporates an optically active R-enantiomer dithioacetal structure providing extreme affinity for dermatophyte enzymes.",
        "pharmacodynamics": "Broad fungicidal activity against Trichophyton rubrum, Trichophyton mentagrophytes, Epidermophyton floccosum, and Malassezia; MIC values are significantly lower than terbinafine, clotrimazole, and ketoconazole.",
        "absorption": "Minimal systemic absorption after topical application; concentrates heavily in the stratum corneum with sustained reservoirs.",
        "distribution": "High retention in keratinized skin layers; systemic plasma concentrations remain negligible (<5 ng/mL).",
        "metabolism": "Any absorbed drug is metabolized in the liver via glucuronidation and CYP pathways.",
        "excretion": "Excreted in urine and faeces as trace inactive metabolites.",
        "bioavailability": "<1% systemic bioavailability",
        "half_life": "24 to 36 hours retention in stratum corneum",
        "protein_binding": ">99% systemically",
        "onset": "Rapid relief of pruritus and scaling within 3 to 5 days",
        "duration": "24 hours (once-daily application)",
        "indications": ["Tinea cruris (jock itch)", "Tinea corporis (ringworm)", "Tinea pedis (athlete's foot - interdigital and plantaris)"],
        "contraindications": ["Hypersensitivity to luliconazole or any component of the cream/lotion", "Ophthalmic, oral, or intravaginal use"],
        "warnings": ["For external topical dermatological use only; avoid contact with eyes and mucous membranes", "Contact dermatitis and local allergic sensitization"],
        "common_adverse_effects": ["Application site pruritus", "Mild local skin burning sensation", "Contact dermatitis", "Erythema"],
        "serious_adverse_effects": ["Severe allergic contact dermatitis / blistering (rare)", "Secondary bacterial infection from scratching"],
        "drug_interactions": ["Topical application produces negligible systemic levels; no clinically significant systemic drug interactions reported"],
        "monitoring": ["Clinical inspection of skin lesions and mycological cure assessment"],
        "pregnancy": "Category C; minimal systemic absorption, but use only if clearly indicated.",
        "lactation": "Minimal systemic absorption; safe on intact skin away from the breast.",
        "pediatric": "Approved for pediatric patients 12 years and older for tinea pedis and tinea cruris/corporis.",
        "geriatric": "No dose adjustment required.",
        "renal": "No dose adjustment required (topical).",
        "hepatic": "No dose adjustment required (topical).",
        "advantages": ["Shortest treatment duration among topical antifungals (once daily for 1 week in tinea cruris/corporis; 2 weeks in tinea pedis)", "Lowest MIC of all topical antifungals against dermatophytes", "Excellent skin reservoir effect ensures high local concentrations"],
        "disadvantages": ["Topical only; not effective for systemic mycoses or widespread onychomycosis", "Higher acquisition cost than generic clotrimazole"],
        "key_points": ["Apply once daily for just 1 week for ringworm and jock itch (2 weeks for athlete's foot)", "Remarkably low MIC against Trichophyton rubrum"],
        "memory_trick": "LULI-conazole: LOWEST MIC, ONE week treatment, LULLS fungal ringworm to sleep.",
        "key_suffix": "-conazole",
        "pronunciation_en": "loo-li-KON-a-zole",
        "pronunciation_hi": "लुलिकॉना-ज़ोल",
        "status": "active",
        "verification_status": "verified"
    }
]

print(f"Loaded {len(MEDS)} antifungals in cat3")
