# Group 2: Antibacterials (30 medicines)

MEDICINES = [
    {
        "slug": "roxithromycin",
        "generic_name": "Roxithromycin",
        "display_name": "Roxithromycin",
        "active_ingredient": "Roxithromycin",
        "salt": "Roxithromycin",
        "category": "Antibiotics",
        "description": "A semi-synthetic 14-membered ring macrolide antibiotic with high oral bioavailability and long half-life, used for respiratory, skin, and genital tract infections.",
        "strengths": ["50 mg DT", "150 mg", "300 mg"],
        "dosage_forms": ["Dispersible Tablet", "Film-coated Tablet", "Suspension"],
        "routes": ["Oral"],
        "mechanism_of_action": "Binds reversibly to the 50S subunit of bacterial 70S ribosomes, inhibiting translocation and peptide chain elongation, blocking bacterial protein synthesis.",
        "pharmacodynamics": "Bacteriostatic spectrum covering Gram-positive cocci (Streptococcus, Staphylococcus), atypical pathogens (Mycoplasma, Chlamydia, Legionella), and select Gram-negatives.",
        "absorption": "Rapidly absorbed; significantly more acid-stable and bioavailable than erythromycin; take 15 minutes before food.",
        "distribution": "High tissue and intracellular penetration, especially into alveolar macrophages, tonsils, and bronchial mucosa; 96% protein bound (to alpha-1 acid glycoprotein).",
        "metabolism": "Partially metabolised in the liver; predominantly eliminated unchanged.",
        "excretion": "Excreted mainly in faeces via biliary elimination (approx. 53%) and in urine (approx. 10%).",
        "bioavailability": "Approximately 50%",
        "half_life": "10 to 12 hours (allowing once or twice daily dosing)",
        "protein_binding": "96%",
        "onset": "1 to 2 hours",
        "duration": "12 to 24 hours",
        "indications": ["Community-acquired pneumonia", "Acute pharyngitis and tonsillitis", "Acute exacerbations of chronic bronchitis", "Skin and soft tissue infections", "Non-gonococcal urethritis"],
        "contraindications": ["Hypersensitivity to macrolides", "Severe hepatic impairment with concurrent ergot alkaloid therapy (ergotism risk)", "Concurrent use of terfenadine, astemizole, or cisapride"],
        "warnings": ["Prolongation of QT interval and risk of ventricular arrhythmias", "Hepatotoxicity and cholestatic jaundice", "Clostridioides difficile-associated diarrhoea"],
        "common_adverse_effects": ["Nausea", "Vomiting", "Epigastric pain", "Diarrhoea", "Headache"],
        "serious_adverse_effects": ["QT prolongation / Torsades de pointes", "Cholestatic hepatitis", "Pseudomembranous colitis", "Severe allergic reactions"],
        "drug_interactions": ["Ergotamine (severe peripheral vasospasm/ergotism)", "Theophylline (modest increase in theophylline levels)", "Warfarin (potentiates anticoagulant effect)", "Digoxin (increased bioavailability)"],
        "monitoring": ["Liver function in prolonged therapy", "ECG in patients with cardiac risk factors or concurrent QT-prolonging drugs"],
        "pregnancy": "Category B; use during pregnancy only if clearly needed.",
        "lactation": "Excreted in small amounts in breast milk; use with caution.",
        "pediatric": "Dispersible tablet formulations used widely in pediatric respiratory infections.",
        "geriatric": "No primary dose adjustment required unless severe renal and hepatic failure co-exist.",
        "renal": "No major dose reduction in mild to moderate renal disease; reduce dose in severe renal impairment (eGFR < 15 mL/min).",
        "hepatic": "Dose reduction (150 mg once daily) in severe hepatic impairment.",
        "advantages": ["Higher oral bioavailability and acid stability than erythromycin", "Once or twice daily dosing improves compliance", "Concentrates heavily in respiratory tissues and macrophages"],
        "disadvantages": ["Lower activity against Haemophilus influenzae than amoxicillin-clavulanate", "Potential for QT prolongation"],
        "key_points": ["Take at least 15 minutes before food or on an empty stomach for optimal absorption", "Excellent penetration into respiratory tissues"],
        "memory_trick": "ROXI-thromycin: Rocks the respiratory tract twice daily; take before meals.",
        "key_suffix": "-thromycin",
        "pronunciation_en": "rox-ith-roe-MYE-sin",
        "pronunciation_hi": "रॉक्सिथ्रो-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "moxifloxacin",
        "generic_name": "Moxifloxacin",
        "display_name": "Moxifloxacin",
        "active_ingredient": "Moxifloxacin hydrochloride",
        "salt": "Moxifloxacin hydrochloride",
        "category": "Antibiotics",
        "description": "A fourth-generation 'respiratory' fluoroquinolone with enhanced Gram-positive, anaerobic, and atypical coverage, widely used for pneumonia, tuberculosis, and intra-abdominal infections.",
        "strengths": ["400 mg", "400 mg/250 mL IV infusion", "0.5% eye drops"],
        "dosage_forms": ["Film-coated Tablet", "Solution for Infusion", "Ophthalmic Solution"],
        "routes": ["Oral", "Intravenous", "Ophthalmic"],
        "mechanism_of_action": "Bactericidal dual-target inhibition of bacterial DNA gyrase (topoisomerase II) and topoisomerase IV, preventing DNA replication, transcription, and repair.",
        "pharmacodynamics": "Concentration-dependent bactericidal killing (AUC/MIC driven); potent against Streptococcus pneumoniae, Mycoplasma, Legionella, anaerobes, and Mycobacterium tuberculosis.",
        "absorption": "Well absorbed (approx. 90%) from GI tract; food delays absorption slightly but does not reduce overall exposure.",
        "distribution": "Extensive penetration into lung tissue, alveolar macrophages, bronchial mucosa, and sinus tissues; 30-50% bound to plasma albumin.",
        "metabolism": "Metabolized by phase II glucuronide and sulfate conjugation in the liver; not significantly dependent on cytochrome P450 enzymes.",
        "excretion": "Approximately 45% eliminated unchanged in urine and faeces; remainder excreted as glucuronide and sulfate metabolites.",
        "bioavailability": "Approximately 90%",
        "half_life": "12 hours (allowing once-daily dosing)",
        "protein_binding": "30% to 50%",
        "onset": "Peak serum concentration in 1 to 3 hours",
        "duration": "24 hours",
        "indications": ["Community-acquired pneumonia (CAP)", "Acute bacterial sinusitis", "Complicated intra-abdominal infections (with anaerobic coverage)", "Complicated skin and soft tissue infections", "Multidrug-resistant tuberculosis (MDR-TB second-line)"],
        "contraindications": ["History of tendon disorders related to fluoroquinolone treatment", "Documented QT prolongation or concurrent use of Class IA/III antiarrhythmics", "Severe hepatic impairment", "Myasthenia gravis"],
        "warnings": ["Black box warnings: Tendinitis and tendon rupture (especially Achilles tendon)", "Peripheral neuropathy and central nervous system toxicities (confusion, hallucinations)", "Exacerbation of myasthenia gravis", "Aortic aneurysm rupture risk"],
        "common_adverse_effects": ["Nausea", "Diarrhoea", "Dizziness", "Headache", "Dyspepsia"],
        "serious_adverse_effects": ["Achilles tendon rupture", "QT prolongation / Torsades de pointes", "Severe peripheral neuropathy", "Clostridioides difficile colitis", "Hepatotoxicity"],
        "drug_interactions": ["Antacids containing aluminum/magnesium, iron supplements, sucralfate (chelation reduces absorption - separate by 4 hours)", "Class IA and III antiarrhythmics (additive QT prolongation)", "Oral hypoglycaemics (dysglycaemia risk)", "NSAIDs (increased seizure risk)"],
        "monitoring": ["ECG in patients at risk of arrhythmia", "Signs of tendinopathy (discontinue at first sign of tendon pain or swelling)", "Blood glucose in diabetics"],
        "pregnancy": "Avoid in pregnancy; fluoroquinolones induce cartilage damage in juvenile animal models.",
        "lactation": "Excreted in human milk; avoid during breastfeeding.",
        "pediatric": "Generally avoided in children due to arthropathy risk, except in multidrug-resistant tuberculosis.",
        "geriatric": "Higher risk of tendon rupture and severe QT prolongation; use with caution.",
        "renal": "No dosage adjustment needed in renal impairment (including dialysis) as it undergoes hepatic conjugation.",
        "hepatic": "Contraindicated in severe hepatic impairment (Child-Pugh C).",
        "advantages": ["Once-daily dosing with 90% oral bioavailability", "No renal dosage adjustment needed", "Excellent anaerobic and atypical coverage alongside pneumococcal potency"],
        "disadvantages": ["Class warnings for tendinitis, aortic aneurysm, and QT prolongation", "Should be reserved for severe or refractory respiratory infections"],
        "key_points": ["No dosage adjustment needed in renal disease (distinct from ciprofloxacin/levofloxacin)", "Do not take with antacids or iron pills at the same time"],
        "memory_trick": "MOXI-floxacin: Mixed anaerobic/aerobic activity, Once-daily, eXcellent lung penetration.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "mox-i-FLOX-a-sin",
        "pronunciation_hi": "मॉक्सी-फ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "ofloxacin",
        "generic_name": "Ofloxacin",
        "display_name": "Ofloxacin",
        "active_ingredient": "Ofloxacin",
        "salt": "Ofloxacin",
        "category": "Antibiotics",
        "description": "A second-generation broad-spectrum fluoroquinolone widely utilized in India for gastrointestinal infections, enteric fever, and genitourinary tract infections.",
        "strengths": ["100 mg DT", "200 mg", "400 mg", "200 mg/100 mL IV infusion", "0.3% eye/ear drops"],
        "dosage_forms": ["Film-coated Tablet", "Dispersible Tablet", "IV Infusion", "Ophthalmic/Otic Drops"],
        "routes": ["Oral", "Intravenous", "Ophthalmic", "Otic"],
        "mechanism_of_action": "Bactericidal inhibition of DNA gyrase (topoisomerase II) and topoisomerase IV, halting bacterial chromosome supercoiling, transcription, and division.",
        "pharmacodynamics": "Broad-spectrum activity against Gram-negative bacilli (Enterobacteriaceae, Salmonella, Shigella) and atypical bacteria; moderately active against Gram-positives.",
        "absorption": "Rapidly and almost completely absorbed from the GI tract (approx. 98% bioavailability); peak levels in 1 to 2 hours.",
        "distribution": "Extensive tissue distribution into prostate, lungs, kidneys, bile, and blister fluid; 20-30% bound to plasma proteins.",
        "metabolism": "Minimal hepatic metabolism (<10%); less than 5% metabolised to desmethylofloxacin.",
        "excretion": "Predominantly eliminated unchanged by the kidneys via tubular secretion and glomerular filtration (>80%).",
        "bioavailability": "Near 100%",
        "half_life": "5 to 7 hours (prolonged in renal failure)",
        "protein_binding": "20% to 30%",
        "onset": "1 to 2 hours",
        "duration": "12 hours",
        "indications": ["Enteric fever (typhoid fever) and infectious gastroenteritis (often with ornidazole)", "Urinary tract infections (pyelonephritis, complicated cystitis)", "Bacterial prostatitis", "Pelvic inflammatory disease and non-gonococcal urethritis", "Bacterial conjunctivitis and otitis externa (drops)"],
        "contraindications": ["Hypersensitivity to quinolones", "History of fluoroquinolone-induced tendinitis", "Epilepsy / pre-existing central nervous system seizure disorders", "Myasthenia gravis"],
        "warnings": ["Tendon rupture and tendinopathy", "CNS stimulation and seizure precipitation", "Separate administration from multivalent cations (iron, calcium, magnesium, aluminum) by at least 2 hours"],
        "common_adverse_effects": ["Nausea", "Insomnia / sleep disturbances", "Headache", "Dizziness", "Diarrhoea"],
        "serious_adverse_effects": ["Achilles tendinitis / rupture", "Convulsions", "Peripheral neuropathy", "QT interval prolongation", "Toxic epidermal necrolysis (rare)"],
        "drug_interactions": ["Multivalent cation antacids and iron (markedly impairs absorption)", "Theophylline (modest inhibition of metabolism)", "NSAIDs (increased seizure risk)", "Warfarin"],
        "monitoring": ["Renal function tests (BUN / creatinine)", "Signs of tendon pain or swelling", "Blood sugar in diabetic patients"],
        "pregnancy": "Avoid during pregnancy due to potential for juvenile cartilage damage.",
        "lactation": "Excreted in human breast milk; avoid use or discontinue breastfeeding.",
        "pediatric": "Contraindicated in children and growing adolescents, except under strict specialist indications (e.g. MDR infections).",
        "geriatric": "Renal clearance is reduced; dose adjustment based on creatinine clearance.",
        "renal": "Dose reduction mandatory: if CrCl 20-50 mL/min, give 200 mg every 24h; if CrCl < 20 mL/min, give 100 mg every 24h.",
        "hepatic": "Caution in severe liver cirrhosis (maximum 400 mg daily).",
        "advantages": ["Near 100% oral bioavailability: oral and IV doses are interchangeable", "Excellent penetration into prostatic tissue and urinary tract", "Established track record in enteric infections"],
        "disadvantages": ["Class warnings for tendon and neurological toxicities", "Substantial resistance emergence in Enterobacteriaceae and Salmonella"],
        "key_points": ["Widely combined with ornidazole for acute infectious diarrhoea in India", "Dose must be reduced in kidney disease because it is eliminated by the kidneys"],
        "memory_trick": "O-FLOX-acin: Over 95% bioavailability; Outflows through kidney.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "oh-FLOX-a-sin",
        "pronunciation_hi": "ओफ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "norfloxacin",
        "generic_name": "Norfloxacin",
        "display_name": "Norfloxacin",
        "active_ingredient": "Norfloxacin",
        "salt": "Norfloxacin",
        "category": "Antibiotics",
        "description": "A synthetic fluoroquinolone that achieves very high concentrations in the urinary tract and gastrointestinal lumen with low systemic tissue levels, making it ideal for UTIs and bacterial diarrhoea.",
        "strengths": ["100 mg", "200 mg", "400 mg", "0.3% eye/ear drops"],
        "dosage_forms": ["Tablet", "Ophthalmic/Otic Drops"],
        "routes": ["Oral", "Ophthalmic", "Otic"],
        "mechanism_of_action": "Inhibits bacterial DNA gyrase and topoisomerase IV, preventing DNA supercoiling, synthesis, and cell division.",
        "pharmacodynamics": "Bactericidal activity against Gram-negative urinary and gastrointestinal pathogens (E. coli, Klebsiella, Proteus, Salmonella, Shigella, Campylobacter).",
        "absorption": "Rapidly but incompletely absorbed (30-40% bioavailability); food or milk impairs absorption.",
        "distribution": "Low serum concentrations; concentrates intensely in renal parenchyma, bladder urine, and intestinal lumen; 14% protein bound.",
        "metabolism": "Partially metabolised in the liver to six active metabolites possessing weaker antibacterial activity.",
        "excretion": "Approximately 30-40% excreted unchanged in urine within 24 hours; about 30% excreted in faeces.",
        "bioavailability": "30% to 40%",
        "half_life": "3 to 4 hours (prolonged in renal failure)",
        "protein_binding": "14%",
        "onset": "1 to 2 hours",
        "duration": "12 hours",
        "indications": ["Acute and recurrent uncomplicated urinary tract infections (UTIs)", "Complicated UTIs (except with systemic sepsis)", "Bacterial infectious gastroenteritis / traveller's diarrhoea", "Spontaneous bacterial peritonitis (SBP) prophylaxis in cirrhotics"],
        "contraindications": ["Hypersensitivity to fluoroquinolones", "History of tendinitis or tendon rupture", "Myasthenia gravis", "Pregnancy and lactation"],
        "warnings": ["Do not use for systemic bloodstream infections (poor systemic tissue penetration)", "Tendon disorders and central neurotoxicity", "Take 1 hour before or 2 hours after meals with plenty of fluids"],
        "common_adverse_effects": ["Nausea", "Dyspepsia", "Abdominal cramps", "Headache", "Dizziness"],
        "serious_adverse_effects": ["Tendon rupture (Achilles)", "Clostridioides difficile colitis", "Crystalluria (especially in alkaline urine with low fluid intake)"],
        "drug_interactions": ["Antacids containing Al/Mg, calcium, iron supplements (drastically reduce absorption)", "Theophylline (increases theophylline levels)", "Warfarin (increased INR)"],
        "monitoring": ["Urinary symptoms and urine culture", "Adequate hydration to prevent crystalluria", "Renal function in elderly or impaired patients"],
        "pregnancy": "Avoid during pregnancy; potential arthropathy in growing joints.",
        "lactation": "Excreted in breast milk; avoid use.",
        "pediatric": "Not recommended in children and adolescents under 18 years.",
        "geriatric": "Dose adjustment for renal impairment; higher tendon rupture risk.",
        "renal": "If CrCl ≤ 30 mL/min, reduce dose to 400 mg once daily.",
        "hepatic": "No dose adjustment necessary.",
        "advantages": ["High urinary and fecal concentrations with low systemic toxicity", "Established agent for SBP prophylaxis in chronic liver disease"],
        "disadvantages": ["Poor systemic absorption makes it inappropriate for pneumonia or deep-seated systemic sepsis", "Rising fluoroquinolone resistance in uropathogens"],
        "key_points": ["Drink plenty of water to prevent crystals in the urine", "Take on an empty stomach with a full glass of water"],
        "memory_trick": "NOR-floxacin: Narrower systemic levels, NOT for pneumonia, Optimal for Renal/gut tract.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "nor-FLOX-a-sin",
        "pronunciation_hi": "नॉरफ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "faropenem",
        "generic_name": "Faropenem",
        "display_name": "Faropenem",
        "active_ingredient": "Faropenem sodium",
        "salt": "Faropenem sodium",
        "category": "Antibiotics",
        "description": "An orally bioavailable penem antibiotic with high stability against extended-spectrum beta-lactamases (ESBLs), used for resistant respiratory, ENT, and urinary tract infections.",
        "strengths": ["150 mg", "200 mg", "300 mg", "100 mg DT"],
        "dosage_forms": ["Film-coated Tablet", "Dispersible Tablet", "Dry Syrup"],
        "routes": ["Oral"],
        "mechanism_of_action": "Binds with high affinity to penicillin-binding proteins (PBPs), primarily PBP1A, 1B, 2, and 3, inhibiting peptidoglycan cell wall cross-linking and triggering autolysis.",
        "pharmacodynamics": "Broad-spectrum bactericidal activity against Gram-positive, Gram-negative, and anaerobic pathogens; highly resistant to hydrolysis by class A, C, and D beta-lactamases including ESBLs.",
        "absorption": "Rapidly absorbed after oral administration; peak plasma levels reached in 1 to 1.5 hours.",
        "distribution": "Distributes well into sputum, tonsils, sinus mucosa, and middle ear fluid; 96% bound to plasma proteins in humans.",
        "metabolism": "Hydrolyzed in renal brush border by renal dehydropeptidase-I (DHP-I) to inactive metabolites, but more stable to DHP-I than imipenem.",
        "excretion": "Approximately 15-20% excreted unchanged in urine, with remainder as ring-opened inactive metabolites.",
        "bioavailability": "Approximately 70-80%",
        "half_life": "1 hour",
        "protein_binding": "96%",
        "onset": "Peak serum level within 1 to 1.5 hours",
        "duration": "8 hours (administered three times daily)",
        "indications": ["Community-acquired pneumonia with suspected or proven ESBL organisms", "Acute bacterial sinusitis and otitis media refractory to first-line agents", "Complicated and recurrent urinary tract infections", "Skin and soft tissue infections"],
        "contraindications": ["Hypersensitivity to faropenem, penems, or other carbapenem beta-lactam antibiotics", "History of anaphylaxis to cephalosporins or penicillins"],
        "warnings": ["Reserve for confirmed or highly suspected resistant infections to prevent emergence of carbapenemase resistance", "Diarrhoea and risk of Clostridioides difficile colitis", "Cross-reactivity with beta-lactam allergy"],
        "common_adverse_effects": ["Diarrhoea", "Abdominal discomfort", "Nausea", "Loose stools", "Rash"],
        "serious_adverse_effects": ["Pseudomembranous colitis", "Anaphylaxis", "Liver transaminase elevations", "Seizures (extremely rare)"],
        "drug_interactions": ["Imipenem/cilastatin or other carbapenems (do not combine)", "Sodium valproate (penems/carbapenems may lower valproate levels)", "Probenecid (prolongs faropenem excretion)"],
        "monitoring": ["Clinical response", "Stool frequency (watch for severe watery diarrhoea)", "Renal function"],
        "pregnancy": "Use during pregnancy only if clearly needed and potential benefit justifies potential risk.",
        "lactation": "Excreted into breast milk in small amounts; use caution.",
        "pediatric": "Paediatric dry syrup and dispersible tablets used in selected refractory respiratory infections under specialist supervision.",
        "geriatric": "Assess renal function; reduce dose in impaired renal clearance.",
        "renal": "Dose adjustment required in renal impairment: if CrCl 30-50 mL/min, give 150-200 mg q12h; if CrCl < 30 mL/min, give 150 mg q24h.",
        "hepatic": "No dosage adjustment needed for hepatic impairment.",
        "advantages": ["Only orally active penem/carbapenem-like antibiotic available in outpatient practice", "Stable against extended-spectrum beta-lactamases (ESBLs)"],
        "disadvantages": ["Short half-life requiring three-times-daily dosing", "Should be used judiciously as a reserve antibiotic to prevent resistance"],
        "key_points": ["Oral reserve antibiotic for ESBL-producing bacteria", "Take three times daily at evenly spaced intervals"],
        "memory_trick": "FARO-penem: Oral FAR-reaching Penem against ESBLs.",
        "key_suffix": "-penem",
        "pronunciation_en": "fa-roe-PEN-em",
        "pronunciation_hi": "फ़ैरो-पेनेम",
        "status": "active",
        "verification_status": "verified"
    }
]
