"""
Batch 1: Analgesics, Musculoskeletal, Antibacterials (55 medicines)
"""

BATCH1_MEDICINES = [
    {
        "slug": "ketoprofen",
        "generic_name": "Ketoprofen",
        "display_name": "Ketoprofen",
        "active_ingredient": "Ketoprofen",
        "salt": "Ketoprofen",
        "category": "Pain & Inflammation",
        "description": "A propionic acid derivative NSAID with analgesic, anti-inflammatory and antipyretic actions, inhibiting both COX enzymes and leukocyte migration.",
        "strengths": ["50 mg", "100 mg", "200 mg SR", "2.5% gel"],
        "dosage_forms": ["Capsule", "SR Capsule", "Gel", "Injection"],
        "routes": ["Oral", "Topical", "Intramuscular"],
        "mechanism_of_action": "Reversible inhibition of cyclooxygenase enzymes (COX-1 and COX-2), thereby reducing prostaglandin synthesis; also exerts mild inhibition of lipoxygenase.",
        "pharmacodynamics": "Produces analgesia, decreases joint swelling and morning stiffness in inflammatory arthropathies.",
        "absorption": "Rapidly and near-completely absorbed from the GI tract; food delays peak concentration but not extent of absorption.",
        "distribution": "High volume into synovial fluid; 99% bound to plasma proteins (predominantly albumin).",
        "metabolism": "Extensive hepatic glucuronidation to inactive glucuronide conjugates.",
        "excretion": "Approximately 80% eliminated in urine, largely as glucuronide conjugates.",
        "bioavailability": "Approximately 90%",
        "half_life": "1.5 to 2 hours (immediate release); prolonged in sustained-release forms",
        "protein_binding": "Approximately 99%",
        "onset": "30 to 60 minutes orally",
        "duration": "4 to 6 hours (standard); up to 24 hours (SR)",
        "indications": ["Rheumatoid arthritis", "Osteoarthritis", "Acute musculoskeletal pain", "Dysmenorrhoea", "Ankylosing spondylitis"],
        "contraindications": ["Active peptic ulceration or GI bleeding", "Severe renal or hepatic failure", "Severe heart failure", "History of aspirin/NSAID-induced asthma or urticaria"],
        "warnings": ["Risk of GI ulceration and bleeding", "Fluid retention and cardiovascular thrombotic risk", "Renal papillary necrosis with prolonged use"],
        "common_adverse_effects": ["Dyspepsia", "Nausea", "Abdominal discomfort", "Headache", "Dizziness"],
        "serious_adverse_effects": ["Gastrointestinal haemorrhage", "Acute kidney injury", "Bronchospasm in aspirin-sensitive asthmatics", "Photosensitivity reactions"],
        "drug_interactions": ["Anticoagulants (increased bleeding risk)", "ACE inhibitors and diuretics (reduced antihypertensive effect, increased nephrotoxicity)", "Methotrexate", "Lithium"],
        "monitoring": ["Renal function", "Haemoglobin/haematocrit in prolonged therapy", "Blood pressure"],
        "pregnancy": "Avoid during third trimester due to risk of premature closure of ductus arteriosus; use during early pregnancy only if advised by clinician.",
        "lactation": "Small amounts excreted; use with caution and seek medical guidance.",
        "pediatric": "Safety and efficacy not established in younger children.",
        "geriatric": "Increased susceptibility to GI ulceration and renal toxicity; use lowest effective dose.",
        "renal": "Dose reduction required in moderate renal disease; contraindicated in severe renal impairment.",
        "hepatic": "Use caution and reduced dosage in chronic hepatic disease.",
        "advantages": ["Rapid onset of pain relief", "Dual COX and partial lipoxygenase pathway modulation", "Topical formulation reduces systemic exposure"],
        "disadvantages": ["Higher gastric irritation propensity compared to COX-2 selective agents", "Requires frequent dosing unless using SR forms"],
        "key_points": ["Take with food or milk to minimize gastric upset", "Avoid combining with other oral NSAIDs"],
        "memory_trick": "Keto-profen: Pro-inflammatory prostaglandins blocked by Keto.",
        "key_suffix": "-profen",
        "pronunciation_en": "kee-toe-PROH-fen",
        "pronunciation_hi": "कीटो-प्रो-फेन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "lornoxicam",
        "generic_name": "Lornoxicam",
        "display_name": "Lornoxicam",
        "active_ingredient": "Lornoxicam",
        "salt": "Lornoxicam",
        "category": "Pain & Inflammation",
        "description": "An oxicam-class NSAID with potent analgesic and anti-inflammatory properties, characterised by a relatively short elimination half-life.",
        "strengths": ["4 mg", "8 mg", "8 mg injection"],
        "dosage_forms": ["Tablet", "Rapid-release Tablet", "Powder for Injection"],
        "routes": ["Oral", "Intravenous", "Intramuscular"],
        "mechanism_of_action": "Potent balanced inhibitor of cyclooxygenase-1 and cyclooxygenase-2, suppressing prostaglandin biosynthesis and IL-6 release.",
        "pharmacodynamics": "High analgesic potency comparable to moderate opioids in post-operative and acute pain settings, alongside anti-inflammatory action.",
        "absorption": "Rapidly absorbed after oral administration; peak plasma levels reached in 1 to 2 hours.",
        "distribution": "Extensively bound to plasma proteins, predominantly albumin; good penetration into synovial fluid.",
        "metabolism": "Extensively metabolised in the liver, primarily via cytochrome P450 2C9 (CYP2C9) to inactive 5-hydroxy-lornoxicam.",
        "excretion": "Approximately two-thirds excreted via bile and faeces, and one-third via the kidneys.",
        "bioavailability": "Approximately 90-100%",
        "half_life": "3 to 5 hours",
        "protein_binding": "Approximately 99%",
        "onset": "30 to 45 minutes",
        "duration": "8 to 12 hours",
        "indications": ["Acute mild-to-moderate pain", "Post-operative surgical pain", "Osteoarthritis flare-ups", "Rheumatoid arthritis", "Lumbago and sciatica"],
        "contraindications": ["Active peptic ulcer or gastrointestinal bleeding", "Severe thrombocytopenia or bleeding diathesis", "Severe heart failure", "Severe renal or hepatic impairment"],
        "warnings": ["Gastrointestinal bleeding and perforation", "Cardiovascular thrombotic events", "Renal impairment particularly in hypovolemic patients"],
        "common_adverse_effects": ["Mild dizziness", "Dyspepsia", "Nausea", "Headache", "Abdominal pain"],
        "serious_adverse_effects": ["Severe GI bleeding", "Acute tubular necrosis", "Stevens-Johnson syndrome (rare)", "Thrombocytopenia"],
        "drug_interactions": ["Warfarin and other oral anticoagulants (bleeding risk)", "Methotrexate (increased toxicity)", "Sulfonylureas (enhanced hypoglycaemic effect)", "Diuretics"],
        "monitoring": ["Renal function", "Platelet count", "Liver function in extended therapy"],
        "pregnancy": "Contraindicated in the third trimester; not recommended during first and second trimesters unless essential.",
        "lactation": "Excretion in human milk not fully established; avoid during breastfeeding.",
        "pediatric": "Not recommended in children and adolescents under 18 years of age.",
        "geriatric": "Use with caution; start at lower dose range due to reduced renal and hepatic clearance.",
        "renal": "Avoid in severe renal impairment (GFR < 30 mL/min); monitor fluid status.",
        "hepatic": "Dose adjustment necessary in moderate hepatic impairment; contraindicated in severe liver disease.",
        "advantages": ["Short half-life reduces chronic accumulation risk", "Potent analgesia suitable for post-operative recovery", "Parenteral formulation available"],
        "disadvantages": ["Typical NSAID-associated GI and renal liabilities", "CYP2C9 poor metabolisers may exhibit elevated levels"],
        "key_points": ["Short half-life distinguishes it from other oxicams like piroxicam", "Take after meals to protect gastric mucosa"],
        "memory_trick": "Lorn-Oxi-cam: Fast-acting Oxicam with Lower persistence (short half-life).",
        "key_suffix": "-oxicam",
        "pronunciation_en": "lor-NOX-i-kam",
        "pronunciation_hi": "लॉर्नॉक्सी-कैम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "dexketoprofen",
        "generic_name": "Dexketoprofen",
        "display_name": "Dexketoprofen",
        "active_ingredient": "Dexketoprofen trometamol",
        "salt": "Dexketoprofen trometamol",
        "category": "Pain & Inflammation",
        "description": "The pharmacologically active (S)-(+)-enantiomer of ketoprofen formulated with trometamol for rapid absorption and analgesia at half the racemic dose.",
        "strengths": ["25 mg", "50 mg/2 mL injection", "1.25% gel"],
        "dosage_forms": ["Film-coated Tablet", "Solution for Injection", "Gel"],
        "routes": ["Oral", "Intramuscular", "Intravenous", "Topical"],
        "mechanism_of_action": "Selective activation of analgesia by inhibiting prostaglandin synthesis through COX-1 and COX-2 blockade, with higher chiral potency than the racemic mixture.",
        "pharmacodynamics": "Rapid-onset analgesia for acute nociceptive pain; anti-inflammatory and antipyretic efficacy with lower total chemical load.",
        "absorption": "Extremely fast dissolution and absorption due to the trometamol salt; Tmax reached within 15-30 minutes.",
        "distribution": "High binding to plasma albumin; volume of distribution is approximately 0.25 L/kg.",
        "metabolism": "Hepatic glucuronidation; undergoes no chiral inversion to the R-(-) enantiomer.",
        "excretion": "Almost entirely eliminated by renal excretion as glucuronide conjugates within 24 hours.",
        "bioavailability": "High (over 90%)",
        "half_life": "1.65 hours",
        "protein_binding": "99%",
        "onset": "15 to 30 minutes",
        "duration": "6 hours",
        "indications": ["Acute dental pain", "Musculoskeletal sprains and strains", "Post-operative pain", "Renal colic", "Dysmenorrhoea"],
        "contraindications": ["History of asthma triggered by NSAIDs", "Active peptic ulcer disease", "Severe hepatic or renal failure", "Third trimester of pregnancy"],
        "warnings": ["Gastrointestinal ulceration", "Dehydration increases risk of nephrotoxicity", "Cardiovascular precautions"],
        "common_adverse_effects": ["Nausea", "Vomiting", "Stomach pain", "Diarrhoea", "Dizziness"],
        "serious_adverse_effects": ["Peptic ulcer haemorrhage", "Bronchospasm", "Anaphylaxis", "Renal impairment"],
        "drug_interactions": ["Anticoagulants", "Lithium", "Methotrexate", "Other NSAIDs", "ACE inhibitors"],
        "monitoring": ["Pain response", "Signs of GI irritation", "Hydration status"],
        "pregnancy": "Contraindicated in third trimester; use only when strictly indicated in first two trimesters.",
        "lactation": "Excretion in breast milk unknown; use not recommended during lactation.",
        "pediatric": "Not recommended in pediatric patients under 18 years.",
        "geriatric": "Initiate at lower doses (e.g., 12.5 mg) and titrate carefully.",
        "renal": "Reduce dosage in mild renal impairment; avoid in moderate-to-severe renal failure.",
        "hepatic": "Reduce total daily dose in mild-to-moderate hepatic impairment.",
        "advantages": ["Rapid onset of analgesia within 15-30 minutes", "Lower dose needed than racemic ketoprofen", "Trometamol salt provides high aqueous solubility"],
        "disadvantages": ["Short duration requiring multiple daily doses for sustained pain", "Standard NSAID GI cautions"],
        "key_points": ["Trometamol formulation speeds up gastric emptying and absorption", "Ideal for acute dental and musculoskeletal pain spikes"],
        "memory_trick": "Dex = Dextro (active half), fast acting like an express train.",
        "key_suffix": "-profen",
        "pronunciation_en": "dex-kee-toe-PROH-fen",
        "pronunciation_hi": "डेक्स-कीटो-प्रो-फेन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "nabumetone",
        "generic_name": "Nabumetone",
        "display_name": "Nabumetone",
        "active_ingredient": "Nabumetone",
        "salt": "Nabumetone",
        "category": "Pain & Inflammation",
        "description": "A non-acidic prodrug NSAID that is metabolized in the liver to 6-methoxy-2-naphthylacetic acid (6-MNA), with reduced direct gastric mucosal toxicity.",
        "strengths": ["500 mg", "750 mg", "1000 mg"],
        "dosage_forms": ["Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Inactive prodrug converted in the liver to 6-MNA, which preferentially inhibits COX-2 over COX-1, reducing inflammatory prostaglandins.",
        "pharmacodynamics": "Long-acting anti-inflammatory and analgesic efficacy; lower direct topical acid-induced gastric injury because the parent compound lacks a free carboxylic acid.",
        "absorption": "Well absorbed from the gastrointestinal tract; food increases rate of absorption and conversion to active metabolite.",
        "distribution": "Active metabolite (6-MNA) is >99% bound to plasma proteins and penetrates into synovial fluid.",
        "metabolism": "Extensive first-pass hepatic transformation into active metabolite 6-MNA, followed by O-demethylation and glucuronide conjugation.",
        "excretion": "Approximately 80% recovered in urine (chiefly as conjugates of 6-MNA) and 10% in faeces.",
        "bioavailability": "Approximately 80% as active metabolite 6-MNA",
        "half_life": "22 to 30 hours for the active metabolite 6-MNA",
        "protein_binding": ">99%",
        "onset": "1 to 2 hours; steady-state therapeutic effect over several days",
        "duration": "24 hours",
        "indications": ["Osteoarthritis", "Rheumatoid arthritis", "Chronic inflammatory joint disease"],
        "contraindications": ["Aspirin triad (asthma, rhinitis, nasal polyps)", "Active GI bleeding", "Severe heart failure", "Severe renal disease"],
        "warnings": ["Systemic COX inhibition can still precipitate GI ulcers and renal dysfunction", "Thrombotic cardiovascular events", "Fluid retention"],
        "common_adverse_effects": ["Diarrhoea", "Dyspepsia", "Abdominal cramps", "Constipation", "Tinnitus"],
        "serious_adverse_effects": ["GI ulceration and bleeding", "Nephrotic syndrome", "Severe skin reactions", "Cardiovascular thrombosis"],
        "drug_interactions": ["Warfarin", "Aspirin and other NSAIDs", "ACE inhibitors", "Diuretics", "Lithium"],
        "monitoring": ["Complete blood count", "Renal function tests", "Stool occult blood in long-term therapy"],
        "pregnancy": "Avoid in the third trimester; fetal vascular complications reported with NSAIDs.",
        "lactation": "6-MNA is excreted in breast milk; avoid use while nursing.",
        "pediatric": "Safety and efficacy not established in pediatric patients.",
        "geriatric": "Steady-state plasma concentrations of 6-MNA may be higher; monitor closely.",
        "renal": "Caution in moderate renal impairment; avoid in severe renal insufficiency (GFR < 30 mL/min).",
        "hepatic": "Conversion to active metabolite occurs in liver; use caution in severe hepatic impairment.",
        "advantages": ["Once-daily dosing due to long half-life", "Prodrug nature avoids direct acidic contact irritation to gastric mucosa", "Preferential COX-2 activity"],
        "disadvantages": ["Delayed peak onset compared to fast-acting analgesics", "Systemic GI ulceration risk remains with chronic use"],
        "key_points": ["Non-acidic prodrug converted to 6-MNA", "Convenient once-daily dosing after dinner"],
        "memory_trick": "Nabumetone: Non-Acidic Body, Metabolised to active 6-MNA.",
        "key_suffix": "",
        "pronunciation_en": "na-BYOO-me-tone",
        "pronunciation_hi": "नाब्यू-मी-टोन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "sulindac",
        "generic_name": "Sulindac",
        "display_name": "Sulindac",
        "active_ingredient": "Sulindac",
        "salt": "Sulindac",
        "category": "Pain & Inflammation",
        "description": "An indene derivative prodrug NSAID whose sulfide metabolite reversibly inhibits COX enzymes; historically noted for relative renal-sparing characteristics.",
        "strengths": ["100 mg", "200 mg"],
        "dosage_forms": ["Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Prodrug reduced in vivo to active sulindac sulfide, which inhibits COX-1 and COX-2; active metabolite undergoes enterohepatic circulation and renal oxidation back to inactive sulfoxide.",
        "pharmacodynamics": "Exerts anti-inflammatory, analgesic, and antipyretic actions; active sulfide metabolite has less effect on renal prostaglandin synthesis compared to standard NSAIDs.",
        "absorption": "Approximately 90% of oral dose is absorbed; peak plasma levels of parent drug in 1-2 hours and active sulfide in 3-4 hours.",
        "distribution": "Extensively bound to plasma albumin (>93%); active sulfide metabolite reaches high concentrations in synovial fluid.",
        "metabolism": "Reversible reduction to active sulfide metabolite and irreversible oxidation to inactive sulfone metabolite in the liver.",
        "excretion": "About 50% excreted in urine (mainly as sulfone and glucuronide) and 25% in faeces.",
        "bioavailability": "Approximately 90%",
        "half_life": "7 to 8 hours for sulindac; 16 to 18 hours for active sulfide metabolite",
        "protein_binding": "93% to 98%",
        "onset": "1 to 2 hours",
        "duration": "12 to 24 hours",
        "indications": ["Osteoarthritis", "Rheumatoid arthritis", "Ankylosing spondylitis", "Acute gouty arthritis", "Acute painful shoulder (bursitis/tendinitis)"],
        "contraindications": ["Hypersensitivity to sulindac or aspirin", "Active gastrointestinal bleeding", "Severe hepatic dysfunction", "Third trimester of pregnancy"],
        "warnings": ["Pancreatitis has been reported more frequently with sulindac than some other NSAIDs", "Hepatotoxicity can occur", "Renal and cardiovascular alerts"],
        "common_adverse_effects": ["Gastrointestinal pain", "Nausea", "Dyspepsia", "Diarrhoea", "Rash"],
        "serious_adverse_effects": ["Acute pancreatitis", "Stevens-Johnson syndrome / toxic epidermal necrolysis", "Cholestatic jaundice", "Aplastic anaemia"],
        "drug_interactions": ["Anticoagulants (warfarin)", "Dimethyl sulfoxide (DMSO - may reduce active sulfide levels)", "Methotrexate", "Lithium", "Diuretics"],
        "monitoring": ["Liver function tests (ALT/AST)", "Renal function", "Amylase/lipase if severe abdominal pain develops"],
        "pregnancy": "Contraindicated in third trimester; risk of premature closure of ductus arteriosus and oligohydramnios.",
        "lactation": "Excretion in human milk unknown; use not recommended.",
        "pediatric": "Not established in pediatric populations.",
        "geriatric": "Higher risk of adverse renal and hepatic events; monitor closely.",
        "renal": "Relatively less inhibitory on renal prostacyclin, but caution still required in renal impairment.",
        "hepatic": "Dose reduction necessary in hepatic disease; liver injury reported.",
        "advantages": ["Enterohepatic recycling provides twice-daily dosing convenience", "Relative renal sparing compared to indomethacin"],
        "disadvantages": ["Pancreatitis and hepatic reactions observed", "Typical NSAID GI adverse effects"],
        "key_points": ["Prodrug reduced to active sulfide metabolite", "Watch for unexplained abdominal pain due to pancreatitis risk"],
        "memory_trick": "SUL-indac: Sparing of Urinary/renal prostacyclins, Liver produces active Sulfide.",
        "key_suffix": "",
        "pronunciation_en": "sul-IN-dak",
        "pronunciation_hi": "सुलिन-डैक",
        "status": "active",
        "verification_status": "verified"
    }
]
