#!/usr/bin/env python3
"""
Medical Generator for:
- 20 Cardiovascular Medicines
- 20 Anticoagulants, Hemostasis & Antiarrhythmics
- 25 Gastrointestinal, Hepatology & Antiemetics
Total: 65 medicines -> scripts/data_cardio_anticoag_gi.json
"""

import json

def m(slug, generic, display, active, salt, cat, desc,
      strengths, forms, routes, moa, pd,
      abs_pk, dist_pk, met_pk, exc_pk, bio, hl, pb, onset, dur,
      ind, contra, warn, cae, sae, interact, mon,
      preg, lact, ped, ger, ren, hep,
      adv, disadv, kpts, trick, suffix, pen, phi):
    return {
        "slug": slug, "generic_name": generic, "display_name": display,
        "active_ingredient": active, "salt": salt, "category": cat, "description": desc,
        "strengths": strengths, "dosage_forms": forms, "routes": routes,
        "mechanism_of_action": moa, "pharmacodynamics": pd,
        "absorption": abs_pk, "distribution": dist_pk, "metabolism": met_pk, "excretion": exc_pk,
        "bioavailability": bio, "half_life": hl, "protein_binding": pb,
        "onset": onset, "duration": dur,
        "indications": ind, "contraindications": contra, "warnings": warn,
        "common_adverse_effects": cae, "serious_adverse_effects": sae,
        "drug_interactions": interact, "monitoring": mon,
        "pregnancy": preg, "lactation": lact, "pediatric": ped, "geriatric": ger,
        "renal": ren, "hepatic": hep,
        "advantages": adv, "disadvantages": disadv, "key_points": kpts,
        "memory_trick": trick, "key_suffix": suffix,
        "pronunciation_en": pen, "pronunciation_hi": phi,
        "status": "active", "verification_status": "verified"
    }

meds = [
    # CARDIOVASCULAR (20)
    m("sotalol", "Sotalol", "Sotalol Hydrochloride", "Sotalol hydrochloride", "Sotalol hydrochloride", "Cardiovascular",
      "A non-selective beta-blocker with Class III antiarrhythmic potassium channel-blocking properties, used for ventricular arrhythmias and maintaining sinus rhythm in atrial fibrillation.",
      ["40 mg", "80 mg", "160 mg"], ["Tablet"], ["Oral"],
      "D- and L-isomers block beta-1 and beta-2 adrenergic receptors; D-isomer selectively blocks rapid delayed rectifier potassium current (IKr), prolonging myocardial action potential duration and effective refractory period.",
      "Slows heart rate, decreases AV nodal conduction velocity, and prolongs ventricular refractory periods; carries high dose-dependent risk of Torsades de pointes.",
      "Rapidly and completely absorbed (>90%); absorption reduced by 20% by food (especially dairy/calcium).",
      "Widely distributed; does not cross blood-brain barrier significantly; zero plasma protein binding (0%).",
      "Not metabolized by the liver; excreted completely unaltered by the kidneys.",
      "Excreted entirely unchanged in urine via glomerular filtration (>80-90%).",
      "90% to 100%", "12 hours (prolonged significantly in renal failure)", "0%", "1 to 2 hours", "12 hours (dosed twice daily)",
      ["Maintenance of normal sinus rhythm in patients with symptomatic atrial fibrillation or flutter", "Treatment of documented life-threatening ventricular tachyarrhythmias (sustained VT)"],
      ["Baseline QTc interval > 450 ms", "Severe bradycardia (<50 bpm)", "Second- or third-degree AV block without pacemaker", "CrCl < 40 mL/min for AF indication", "Bronchial asthma", "Cardiogenic shock"],
      ["Black box warning: Must be initiated in a facility with continuous cardiac monitoring and resuscitation capabilities for at least 3 days", "Proarrhythmic risk: Torsades de pointes occurs in 2-4% (highest in females, hypokalemia, renal dysfunction)", "Dose strictly based on creatinine clearance"],
      ["Bradycardia", "Fatigue", "Dyspnea", "Dizziness", "Nausea", "Headache"],
      ["Torsades de pointes / polymorphic ventricular tachycardia", "Complete heart block", "Severe symptomatic bradycardia", "Acute bronchospasm"],
      ["QT-prolonging drugs (amiodarone, macrolides, fluoroquinolones - avoid)", "Potassium-depleting diuretics (hypokalemia increases Torsades risk)", "Diltiazem / verapamil (severe bradycardia)"],
      ["Continuous ECG monitoring for at least 3 days during initiation or dose increase", "Calculate QTc interval before every dose (discontinue if QTc > 500 ms)", "Serum potassium and magnesium (maintain K+ > 4.0 mEq/L, Mg2+ > 2.0 mg/dL)", "Serum creatinine"],
      "Category B; crosses placenta; causes fetal bradycardia; use only if benefit justifies risk.", "Excreted in high concentrations in breast milk; breastfeeding not recommended.",
      "Approved in children with dose adjusted for body surface area.", "Higher risk of proarrhythmia due to age-related decline in GFR; start at 80 mg daily.",
      "Strict dose titration based on CrCl: CrCl 40-59 mL/min: q24h; CrCl < 40 mL/min: contraindicated for AF; if VT, dose q36-48h.",
      "No dosage adjustment required (not metabolized by the liver).",
      ["Dual Class II (beta-blocker) and Class III (potassium channel blocker) antiarrhythmic efficacy", "High oral bioavailability (100%) and zero hepatic metabolism", "Proven efficacy for maintaining sinus rhythm in recurrent atrial fibrillation"],
      ["High risk of Torsades de pointes requires mandatory 3-day inpatient cardiac telemetry for initiation", "Eliminated 100% by kidneys; toxic accumulation occurs in renal failure"],
      ["Must be started in the hospital under 3 days of telemetry monitoring", "Stop the drug immediately if QTc exceeds 500 ms or increases by >60 ms over baseline"],
      "SOTALOL: Slows AV node; QT prolongation triggers Torsades; Always hospitalize for initiation; Leaves via kidneys unchanged.", "-olol", "SOE-ta-lol", "सोटा-लोल"),

    m("pindolol", "Pindolol", "Pindolol", "Pindolol", "Pindolol", "Cardiovascular",
      "A non-selective beta-adrenergic blocker with potent intrinsic sympathomimetic activity (ISA), lowering blood pressure with minimal resting bradycardia or metabolic suppression.",
      ["5 mg", "10 mg"], ["Tablet"], ["Oral"],
      "Partial agonist at beta-1 and beta-2 adrenergic receptors (intrinsic sympathomimetic activity - ISA); competitively blocks catecholamines during exercise/stress while providing low-level basal receptor stimulation at rest.",
      "Reduces peripheral vascular resistance and systemic blood pressure without causing marked resting bradycardia, cardiac depression, or lipid elevation.",
      "Rapidly and completely absorbed (approx. 90-100%); peak plasma levels in 1 to 2 hours; food has no effect.",
      "Widely distributed into tissues; crosses blood-brain barrier; 40-50% bound to plasma proteins.",
      "Metabolized extensively in the liver (approx. 60-65%) to inactive hydroxylated and glucuronide metabolites.",
      "Excreted in urine (approx. 35-40% as unchanged parent drug, remainder as metabolites).",
      "Approximately 90%", "3 to 4 hours", "40% to 50%", "1 to 2 hours", "12 to 24 hours",
      ["Essential hypertension in patients prone to excessive resting bradycardia", "Mild to moderate angina pectoris"],
      ["Bronchial asthma or severe chronic obstructive pulmonary disease", "Severe cardiogenic shock or overt decompensated heart failure", "Second- or third-degree heart block"],
      ["Avoid abrupt cessation (taper over 1-2 weeks)", "May worsen angina or precipitate arrhythmias if withdrawn suddenly", "Caution in peripheral vascular disease"],
      ["Insomnia / vivid dreams", "Dizziness", "Fatigue", "Muscle cramps", "Nausea"],
      ["Heart failure exacerbation", "Severe bronchospasm in asthmatics", "Rebound hypertension upon sudden discontinuation"],
      ["Verapamil, diltiazem (additive negative dromotropic effects)", "NSAIDs (blunt blood pressure lowering)", "Digitalis glycosides"],
      ["Blood pressure and resting heart rate", "Assessment for sleep disturbances and bronchospasm"],
      "Category B; use with caution; beta-blockers may decrease placental perfusion.", "Excreted in breast milk; compatible with close infant heart rate monitoring.",
      "Safety and efficacy not established in pediatric patients.", "Initiate with 5 mg daily; excellent tolerability in seniors prone to bradycardia.",
      "No dosage adjustment required in mild to moderate renal disease; balance of renal and hepatic clearance.",
      "Dose reduction may be required in severe hepatic cirrhosis.",
      ["Intrinsic sympathomimetic activity prevents excessive resting bradycardia (ideal for patients with low baseline heart rate)", "Neutral effect on plasma triglycerides and HDL cholesterol", "Does not cause severe peripheral coldness compared to pure beta-blockers"],
      ["Not cardioprotective post-myocardial infarction (pure beta-blockers without ISA preferred)", "Can cause sleep disturbances and insomnia due to CNS penetration"],
      ["Beta-blocker with partial agonist activity (ISA) that does not drop resting heart rate excessively", "Ideal for hypertensive patients whose heart rate is already in the 50s"],
      "PINDO-lol: Partial Intrinsic agonist; Normalizes BP without Dropping resting heart rate excessively.", "-olol", "PIN-doe-lol", "पिन्डो-लोल"),

    m("fosinopril", "Fosinopril", "Fosinopril Sodium", "Fosinopril sodium", "Fosinopril sodium", "Cardiovascular",
      "A phosphinic acid-containing ACE inhibitor prodrug characterized by dual, compensatory hepatic and renal elimination, eliminating the need for dose reductions in renal impairment.",
      ["10 mg", "20 mg", "40 mg"], ["Tablet"], ["Oral"],
      "Hydrolyzed in the liver and gastrointestinal mucosa to fosinoprilat, which competitively inhibits angiotensin-converting enzyme (ACE), blocking conversion of angiotensin I to angiotensin II and preventing bradykinin degradation.",
      "Reduces systemic vascular resistance and blood pressure without reflex tachycardia; improves cardiac output in heart failure; demonstrates unique 50:50 compensatory hepatobiliary and renal clearance.",
      "Slowly and incomently absorbed (approx. 36%); peak fosinoprilat in 3 hours; food delays absorption slightly.",
      "High protein binding (>99% for fosinoprilat, primarily albumin); low volume of distribution.",
      "Rapidly and completely cleaved by mucosal and hepatic esterases to active fosinoprilat; no cytochrome P450 involvement.",
      "Eliminated equally by hepatic/biliary excretion (approx. 50%) and renal excretion (approx. 50%); in renal failure, biliary clearance increases compensatory up to 100%.",
      "Approximately 36%", "12 hours (effective biological half-life of fosinoprilat)", ">99%", "1 hour (peak effect in 2 to 6 hours)", "24 hours",
      ["Essential hypertension in adults and pediatric patients ≥6 years", "Congestive heart failure (adjunct to diuretics and digitalis)", "Proteinuric chronic kidney disease"],
      ["History of ACE inhibitor-associated or hereditary angioedema", "Pregnancy (all trimesters)", "Concomitant aliskiren in diabetic patients", "Concomitant sacubitril/valsartan (36h washout required)"],
      ["Black box warning: Fetal toxicity and death if used during pregnancy; discontinue immediately upon pregnancy confirmation", "Angioedema of head and neck", "Hyperkalemia and acute hypotension in salt/volume depleted patients", "Dry persistent cough"],
      ["Dry cough", "Dizziness", "Headache", "Fatigue", "Nausea", "Hyperkalemia"],
      ["Fatal airway angioedema", "Acute renal failure in bilateral renal artery stenosis", "Severe symptomatic hypotension"],
      ["Potassium-sparing diuretics, potassium supplements (hyperkalemia)", "NSAIDs (impair antihypertensive effect and renal function)", "Lithium (increases lithium toxicity)"],
      ["Serum creatinine and potassium at baseline and periodically", "Blood pressure", "Monitor for persistent cough"],
      "Strictly contraindicated (Category D); fetotoxic; causes neonatal skull hypoplasia, renal failure, and death.", "Excreted in low levels in milk; avoid breastfeeding.",
      "Approved for pediatric hypertension in children 6 to 16 years (weight-adjusted dosing).", "No dosage adjustment required based on age alone.",
      "NO DOSE ADJUSTMENT REQUIRED in any degree of renal impairment (unique compensatory hepatobiliary clearance).",
      "No dosage adjustment required in mild to moderate hepatic impairment (compensatory renal elimination).",
      ["Unique compensatory dual elimination: if kidneys fail, liver clears it; if liver fails, kidneys clear it", "No dose adjustment required across the entire spectrum of chronic kidney disease", "Phosphinic acid structure provides smooth 24-hour blood pressure control"],
      ["Dry persistent ACE inhibitor cough in 10-15% of patients", "Risk of angioedema"],
      ["Safest ACE inhibitor for kidney failure: zero dose adjustment required because the liver compensates 50:50", "Take once daily in the morning with or without food"],
      "FOSINO-pril: Failsafe dual clearance (50% Liver, 50% Kidney); Outstanding Safety In Nephropathy.", "-pril", "foe-SIN-oh-pril", "फ़ोसिनो-प्रिल"),

    m("quinapril", "Quinapril", "Quinapril Hydrochloride", "Quinapril hydrochloride", "Quinapril hydrochloride", "Cardiovascular",
      "A lipophilic bicyclic prodrug ACE inhibitor with high vascular tissue ACE affinity and endothelial protective actions, used for hypertension and heart failure.",
      ["5 mg", "10 mg", "20 mg", "40 mg"], ["Film-coated Tablet"], ["Oral"],
      "De-esterified in the liver to active quinaprilat, a potent competitive inhibitor of angiotensin-converting enzyme (ACE); exhibits extremely high affinity and binding to tissue-bound ACE in vascular endothelium.",
      "Suppresses tissue and circulating angiotensin II, reduces systemic vascular resistance, preserves renal blood flow, and improves arterial compliance and endothelial dysfunction.",
      "Rapidly absorbed (approx. 60%); peak quinapril in 1 hour; conversion to quinaprilat yields peak levels in 2 hours; high-fat meals reduce absorption by 25-30%.",
      "Widely distributed into vascular tissue; quinaprilat is 97% bound to plasma proteins.",
      "Extensively hydrolyzed in the liver to active quinaprilat and minor inactive diketopiperazine metabolites.",
      "Excreted in urine (approx. 61%, primarily as quinaprilat) and faeces (approx. 37%).",
      "Approximately 60% absorbed; active quinaprilat bioavailability is 38%", "Parent 1 hour; active quinaprilat effective half-life 3 hours (terminal dissociation half-life 25 hours)", "97%", "1 hour", "24 hours",
      ["Essential hypertension", "Congestive heart failure (adjunct therapy in NYHA Class II-IV)", "Hypertension with vascular endothelial dysfunction"],
      ["History of ACE inhibitor-induced or idiopathic angioedema", "Pregnancy (all trimesters)", "Concomitant sacubitril/valsartan or aliskiren in diabetics"],
      ["Black box warning: Fetal toxicity; strictly contraindicated in pregnancy", "Life-threatening angioedema of face and larynx", "Hyperkalemia and first-dose hypotension", "Persistent dry cough"],
      ["Headache", "Dizziness", "Dry persistent cough", "Fatigue", "Hyperkalemia"],
      ["Severe angioedema", "Acute renal failure", "Severe hypotension / syncope", "Agranulocytosis (rare)"],
      ["Potassium supplements, spironolactone (hyperkalemia risk)", "NSAIDs (blunt hypotensive effect)", "Tetracycline antibiotics (quinapril tablets contain magnesium carbonate excipient which chelates tetracyclines)"],
      ["Serum creatinine and eGFR at baseline and periodically", "Serum potassium", "Blood pressure"],
      "Category D; strictly contraindicated in pregnancy due to severe fetotoxicity and neonatal death.", "Excreted in breast milk; avoid breastfeeding.",
      "Safety and efficacy not established in pediatric patients.", "Initiate with 5-10 mg daily; titrate carefully based on renal function.",
      "Dose reduction required if CrCl < 60 mL/min: CrCl 30-60 mL/min: start at 5 mg daily; CrCl 10-30 mL/min: start at 2.5 mg daily; CrCl < 10 mL/min: insufficient data.",
      "No dosage adjustment required in hepatic disease.",
      ["Highest vascular tissue ACE binding affinity among classical ACE inhibitors, maximizing endothelial protection", "Rapid onset of action with consistent 24-hour hemodynamic benefits", "Proven reduction in left ventricular mass and arterial stiffness"],
      ["Class-wide dry hacking cough", "Magnesium excipient in tablets interacts with tetracycline antibiotics"],
      ["Potent tissue ACE inhibitor with strong vascular endothelial benefits", "Note that the tablet contains magnesium: separate from tetracycline antibiotics by 2 hours"],
      "QUIN-april: Quick-acting; Utmost In affinity for tissue-bound Vascular ACE; Inhibits Endothelial breakdown.", "-pril", "KWIN-a-pril", "क्विना-प्रिल"),

    m("trandolapril", "Trandolapril", "Trandolapril", "Trandolapril", "Trandolapril", "Cardiovascular",
      "An ultra-lipophilic, long-acting non-sulfhydryl ACE inhibitor prodrug proven in the TRACE trial to significantly reduce mortality, sudden cardiac death, and progression to severe heart failure post-MI.",
      ["1 mg", "2 mg", "4 mg"], ["Capsule"], ["Oral"],
      "Bioactivated in the liver by ester cleavage to trandolaprilat, an exceptionally potent, slow-dissociating competitive inhibitor of ACE with high tissue affinity; blocks angiotensin II formation and promotes bradykinin-mediated vasodilation.",
      "Reduces left ventricular dilatation and myocardial remodeling; significantly reduces all-cause mortality and sudden death in patients with left ventricular systolic dysfunction following acute myocardial infarction (TRACE trial).",
      "Rapidly absorbed (approx. 40-60%); peak trandolapril in 0.5-1 hour; peak trandolaprilat in 4 to 10 hours; food does not alter AUC.",
      "Highly lipophilic; penetrates deep into cardiac and vascular tissues; trandolaprilat is 80-94% bound to plasma proteins.",
      "Extensively hydrolyzed in the liver to active trandolaprilat and inactive glucuronides; not dependent on CYP enzymes.",
      "Excreted in faeces (approx. 66%) via biliary elimination and urine (approx. 33%).",
      "Trandolapril 40-60%; absolute bioavailability of active trandolaprilat is 70%", "Trandolapril 1 hour; active trandolaprilat terminal half-life 16 to 24 hours (tissue retention up to 96 hours)", "80% to 94%", "1 to 2 hours", "24 hours",
      ["Essential hypertension (alone or combined with verapamil as Tarka)", "Post-myocardial infarction left ventricular dysfunction (TRACE trial: LVEF ≤35%)", "Stable chronic heart failure"],
      ["History of angioedema related to ACE inhibitors", "Pregnancy (all trimesters)", "Concomitant sacubitril/valsartan or aliskiren in diabetics"],
      ["Black box warning: Fetal toxicity; discontinue immediately when pregnancy detected", "Angioedema of airway", "Hyperkalemia and hypotension in salt-depleted patients", "Dry cough"],
      ["Dizziness", "Dry cough", "Headache", "Fatigue", "Hyperkalemia"],
      ["Fatal angioedema", "Severe acute hypotension / shock", "Acute kidney injury in renal artery stenosis"],
      ["Potassium-sparing diuretics, potassium supplements (severe hyperkalemia)", "NSAIDs (renal decline and loss of BP control)", "Lithium (lithium toxicity)"],
      ["Serum creatinine and eGFR at baseline and within 2 weeks", "Serum potassium levels", "Blood pressure sitting and standing"],
      "Strictly contraindicated (Category D); fetotoxic; causes oligohydramnios and neonatal skull defects.", "Excretion in human milk unknown; breastfeeding not recommended.",
      "Safety and efficacy not established in pediatric patients.", "Initiate with 0.5 to 1 mg once daily; titrate cautiously.",
      "If CrCl < 30 mL/min, initiate at 0.5 mg once daily; titrate up to maximum 2 mg daily.",
      "Initiate at 0.5 mg once daily in patients with hepatic cirrhosis.",
      ["Proven post-MI mortality reduction (TRACE trial: 22% reduction in overall mortality, 24% reduction in sudden death)", "Ultra-long biological half-life provides true once-daily 24-hour hemodynamic protection", "High lipophilicity provides deep cardiac tissue penetration"],
      ["Class-wide dry cough in up to 15% of patients", "Requires slow titration post-myocardial infarction"],
      ["Proven to reduce sudden cardiac death and mortality after heart attacks (TRACE trial)", "Take once daily in the morning; start at 0.5-1 mg and titrate up to 4 mg"],
      "TRANDO-lapril: TRACE trial proven; Transcends mortality After Myocardial Infarction; Deep cardiac tissue binding.", "-pril", "tran-DOE-la-pril", "ट्रैंडोला-प्रिल"),

    m("benazepril", "Benazepril", "Benazepril Hydrochloride", "Benazepril hydrochloride", "Benazepril hydrochloride", "Cardiovascular",
      "A potent non-sulfhydryl ACE inhibitor prodrug proven to slow the progression of chronic renal insufficiency in non-diabetic kidney disease (AIPRI trial).",
      ["5 mg", "10 mg", "20 mg", "40 mg"], ["Film-coated Tablet"], ["Oral"],
      "Cleaved by hepatic esterases to active benazeprilat, which competitively inhibits ACE, preventing conversion of angiotensin I to angiotensin II and reducing sympathetic outflow and aldosterone production.",
      "Decreases systemic vascular resistance, reduces intraglomerular capillary pressure, and slows the progression of chronic renal disease and proteinuria (AIPRI trial).",
      "Rapidly absorbed (at least 37%); peak benazepril in 0.5 to 1 hour; peak benazeprilat in 1 to 2 hours; food delays absorption slightly but does not decrease extent.",
      "Widely distributed; benazeprilat is 95% bound to human plasma proteins.",
      "Extensively bioactivated in the liver by ester cleavage to benazeprilat; minor glucuronidation.",
      "Benazeprilat is eliminated primarily by renal excretion (approx. 80%) and biliary excretion (approx. 20%).",
      "Approximately 37% absorbed; active benazeprilat bioavailability is approx. 28%", "Parent benazepril 0.6 hours; active benazeprilat effective half-life 10 to 11 hours (terminal half-life 22 hours)", "95%", "1 hour", "24 hours",
      ["Essential hypertension in adults and children ≥6 years", "Chronic kidney disease with proteinuria (AIPRI trial: slows renal decline in non-diabetic CKD)", "Congestive heart failure adjunct"],
      ["History of ACE inhibitor-associated angioedema", "Pregnancy (all trimesters)", "Concomitant sacubitril/valsartan or aliskiren in diabetics"],
      ["Black box warning: Fetal toxicity; discontinue immediately if pregnancy occurs", "Angioedema of face, lips, glottis", "Hyperkalemia and acute renal failure in bilateral renal artery stenosis", "Dry persistent cough"],
      ["Headache", "Dizziness", "Dry cough", "Somnolence", "Postural lightheadedness", "Hyperkalemia"],
      ["Airway angioedema", "Severe acute hypotension", "Acute renal failure", "Stevens-Johnson syndrome (rare)"],
      ["Potassium supplements, potassium-sparing diuretics (severe hyperkalemia)", "NSAIDs (blunt BP reduction, acute renal failure)", "Lithium"],
      ["Serum creatinine and eGFR at baseline and within 1-2 weeks", "Serum potassium", "Urinary protein-to-creatinine ratio (monitors CKD benefit)"],
      "Category D; strictly contraindicated in pregnancy; causes fetal renal dysgenesis and death.", "Excreted in low levels in breast milk; compatible with caution.",
      "Approved for children 6 to 16 years (weight-adjusted dosing: 0.1 to 0.6 mg/kg once daily).", "Initiate with 5-10 mg daily; monitor renal function.",
      "If CrCl < 30 mL/min, initiate with 5 mg once daily; titrate up to maximum 40 mg daily.",
      "No dosage adjustment required in hepatic impairment.",
      ["Proven to slow the progression of chronic renal failure in non-diabetic kidney disease (AIPRI trial)", "Available in proven synergistic fixed-dose combination with amlodipine (Lotrel)", "Consistent 24-hour trough-to-peak control"],
      ["Dry persistent cough", "Requires dose reduction in advanced renal failure"],
      ["Excellent ACE inhibitor for slowing kidney disease progression (AIPRI trial)", "Take once daily; check potassium and creatinine within 2 weeks of starting"],
      "BENAZE-pril: Beneficial Effect on Non-diabetic Albuminuric renal disease (AIPRI trial); Avoid In Pregnancy.", "-pril", "ben-AY-ze-pril", "बेनाज़े-प्रिल"),

    m("irbesartan", "Irbesartan", "Irbesartan", "Irbesartan", "Irbesartan", "Cardiovascular",
      "A potent, non-peptide AT1-receptor blocker with insurmountable binding and high oral bioavailability (60-80%), proven to halt the progression of diabetic nephropathy (IDNT and IRMA-2 trials).",
      ["75 mg", "150 mg", "300 mg"], ["Tablet"], ["Oral"],
      "Selectively and insurmountably blocks angiotensin II type 1 (AT1) receptors in vascular smooth muscle and the adrenal gland, blocking angiotensin II-mediated vasoconstriction and aldosterone synthesis.",
      "Lowers systemic vascular resistance, reduces blood pressure, and reduces intraglomerular pressure, significantly slowing the doubling of serum creatinine, end-stage renal disease, and proteinuria in type 2 diabetic nephropathy.",
      "Rapidly and well absorbed; peak plasma concentration in 1.5 to 2 hours; high oral bioavailability (60-80%); absorption is completely unaffected by food.",
      "Apparent volume of distribution approx. 53 to 93 L; highly bound to plasma proteins (approx. 90%), predominantly albumin.",
      "Metabolized in the liver by CYP2C9 via oxidation and glucuronidation; no active circulating metabolites (parent drug accounts for >80% of circulating radioactivity).",
      "Eliminated by both biliary/fecal excretion (approx. 80%) and renal excretion (approx. 20%).",
      "60% to 80% (highest oral bioavailability among classical ARBs)", "11 to 15 hours", "90%", "1 to 2 hours", "24 hours",
      ["Essential hypertension in adults", "Diabetic nephropathy in patients with type 2 diabetes and hypertension (IDNT and IRMA-2 trials: proven renoprotection)", "Microalbuminuria in hypertensive type 2 diabetic patients"],
      ["Hypersensitivity to irbesartan", "Pregnancy (all trimesters)", "Concomitant use with aliskiren in patients with diabetes mellitus"],
      ["Black box warning: Fetal toxicity; discontinue immediately when pregnancy is detected", "Hyperkalemia (especially in diabetics with renal impairment)", "Hypotension in volume- or salt-depleted patients", "Renal artery stenosis risk"],
      ["Dizziness", "Fatigue", "Hyperkalemia", "Diarrhoea", "Musculoskeletal pain"],
      ["Acute kidney injury / worsening renal failure", "Severe hyperkalemia (>5.5 mEq/L)", "Angioedema (rare compared to ACE inhibitors)"],
      ["Potassium supplements, potassium-sparing diuretics (hyperkalemia)", "NSAIDs (impair antihypertensive and renoprotective effects)", "Lithium (increases lithium levels)", "CYP2C9 inducers/inhibitors"],
      ["Serum potassium and serum creatinine at baseline, 2 weeks, and periodically", "Urinary albumin excretion rate", "Blood pressure"],
      "Black box warning: Strictly contraindicated throughout pregnancy (causes fetal renal failure, skull hypoplasia, and death).",
      "Excreted in animal milk; avoid breastfeeding.",
      "Safety and efficacy not established in pediatric patients under 6 years.",
      "Initiate at 75-150 mg daily; titrate up to 300 mg daily for renal protection.",
      "No dosage adjustment required in any degree of renal impairment (including hemodialysis).",
      "No dosage adjustment required in mild to moderate hepatic impairment.",
      ["Gold standard renoprotective ARB proven in landmark IDNT and IRMA-2 trials to prevent dialysis in diabetic kidney disease", "Highest oral bioavailability (60-80%) of any classical ARB, ensuring consistent absorption unaffected by food", "Dual renal and biliary excretion eliminates the need for renal dose adjustment"],
      ["Strictly contraindicated in pregnancy", "Requires full 300 mg daily dose for maximal diabetic kidney protection"],
      ["Drug of choice for diabetic kidney disease with protein in the urine (IDNT trial)", "Target dose for kidney protection is 300 mg once daily (taken with or without food)"],
      "IRBE-sartan: Invaluable Renoprotection in Both Early and late Diabetic nephropathy (IDNT trial).", "-sartan", "ir-be-SAR-tan", "इरबे-सारटन"),

    m("eprosartan", "Eprosartan", "Eprosartan Mesylate", "Eprosartan mesylate", "Eprosartan mesylate", "Cardiovascular",
      "A non-biphenyl, non-tetrazole AT1-receptor blocker with dual postsynaptic AT1 and presynaptic sympathoinhibitory properties, effective for isolated systolic hypertension and stroke prevention (MOSES trial).",
      ["400 mg", "600 mg"], ["Film-coated Tablet"], ["Oral"],
      "Competitively and selectively blocks AT1 receptors postsynaptically, preventing angiotensin II vasoconstriction; uniquely blocks presynaptic AT1 receptors on sympathetic nerve terminals, inhibiting norepinephrine release and sympathetic tone.",
      "Reduces peripheral vascular resistance and systemic blood pressure; reduces cardiovascular events and recurrent stroke in hypertensive patients with prior cerebrovascular events (MOSES trial).",
      "Rapidly absorbed; peak plasma concentrations in 1 to 2 hours; absolute oral bioavailability approx. 13% due to limited absorption; take consistently with or without food.",
      "Low volume of distribution (approx. 13 L); highly bound to plasma proteins (approx. 98%).",
      "Minimal hepatic metabolism (<2%); does not utilize or inhibit cytochrome P450 enzymes.",
      "Excreted predominantly unchanged in faeces (approx. 90% via biliary route) and urine (approx. 7%).",
      "Approximately 13%", "5 to 9 hours", "98%", "1 to 2 hours (peak effect in 2 to 3 weeks)", "24 hours",
      ["Essential hypertension (alone or in combination with other antihypertensives)", "Hypertension in patients with a history of stroke or transient ischemic attack (MOSES trial)", "Isolated systolic hypertension"],
      ["Hypersensitivity to eprosartan", "Pregnancy (all trimesters)", "Concomitant aliskiren in diabetic patients"],
      ["Black box warning: Fetal toxicity; discontinue immediately upon pregnancy confirmation", "Hyperkalemia and hypotension in salt-depleted patients", "Bilateral renal artery stenosis precautions"],
      ["Upper respiratory tract infection", "Headache", "Dizziness", "Fatigue", "Nausea"],
      ["Acute renal failure", "Severe symptomatic hypotension", "Hyperkalemia", "Angioedema (rare)"],
      ["Potassium supplements, potassium-sparing diuretics (additive hyperkalemia risk)", "NSAIDs (reduce antihypertensive efficacy)", "Lithium"],
      ["Serum potassium and creatinine at baseline and periodically", "Blood pressure sitting and standing"],
      "Black box warning: Strictly contraindicated in pregnancy (severe fetotoxicity, oligohydramnios, neonatal death).",
      "Excreted in animal milk; avoid breastfeeding.",
      "Safety and efficacy not established in pediatric patients.",
      "Start at 600 mg once daily in elderly patients; well tolerated in isolated systolic hypertension.",
      "No dosage adjustment required in mild to moderate renal failure; in severe renal failure (CrCl < 30 mL/min), maximum dose is 600 mg daily.",
      "No dosage adjustment required in mild to moderate hepatic impairment.",
      ["Dual mechanism: blocks postsynaptic vascular AT1 receptors AND presynaptic sympathetic nerve terminals, lowering stress-induced sympathetic spikes", "Non-biphenyl, non-tetrazole structure free of CYP450 drug interactions", "Proven secondary stroke reduction in the MOSES trial"],
      ["Low oral bioavailability (13%)", "Twice-daily dosing occasionally required for full 24-hour control at lower doses"],
      ["Blocks both angiotensin II and excess sympathetic nerve adrenaline release", "Proven to reduce recurrent strokes in hypertensive patients (MOSES trial)"],
      "EPRO-sartan: Extended Protection from Recurrent Occlusive stroke (MOSES trial); Presynaptic sympathetic block.", "-sartan", "ep-roe-SAR-tan", "एप्रो-सारटन"),

    m("azilsartan", "Azilsartan", "Azilsartan Medoxomil", "Azilsartan medoxomil", "Azilsartan medoxomil", "Cardiovascular",
      "An advanced ester prodrug ARB with the tightest, longest-lasting AT1-receptor binding kinetics in its class, delivering superior 24-hour blood pressure reduction compared to valsartan and olmesartan.",
      ["40 mg", "80 mg"], ["Tablet"], ["Oral"],
      "Rapidly hydrolyzed by esterases in the gastrointestinal tract and liver to active azilsartan; binds with exceptional affinity and an extremely slow dissociation rate to the AT1 receptor, providing insurmountable and sustained receptor blockade.",
      "Produces significantly greater reductions in 24-hour ambulatory, clinic, and nocturnal systolic blood pressure than maximal doses of valsartan (320 mg) and olmesartan (40 mg); promotes vascular remodeling and endothelial nitric oxide release.",
      "Rapidly converted to active azilsartan during absorption; peak plasma concentration in 1.5 to 3 hours; 60% oral bioavailability; unaffected by food.",
      "Volume of distribution approx. 16 L; highly bound to human plasma proteins (>99%, primarily albumin).",
      "Metabolized in the liver primarily by CYP2C9 to an inactive metabolite M-II (O-dealkylation), and to a lesser extent by carboxylesterases to M-I (decarboxylation).",
      "Excreted in faeces (approx. 55%) and urine (approx. 42%, with approx. 15% as unchanged active azilsartan).",
      "Approximately 60%", "11 to 13 hours (receptor dissociation half-life is substantially longer)", ">99%", "1 to 2 hours", "24 hours",
      ["Essential hypertension in adults (40 to 80 mg once daily)", "Resistant hypertension (in combination with chlorthalidone as Edarbyclor)", "Hypertension with elevated nocturnal or morning blood pressure surge"],
      ["Hypersensitivity to azilsartan medoxomil", "Pregnancy (all trimesters)", "Concomitant use of aliskiren in patients with diabetes"],
      ["Black box warning: Fetal toxicity; discontinue immediately when pregnancy is detected", "Hypotension in volume- or salt-depleted patients (correct volume before initiating)", "Hyperkalemia and renal impairment in bilateral renal artery stenosis"],
      ["Dizziness", "Diarrhoea", "Fatigue", "Asthenia", "Nausea", "Headache"],
      ["Acute kidney injury / elevation in serum creatinine", "Severe symptomatic hypotension / syncope", "Hyperkalemia (>5.5 mEq/L)", "Angioedema (rare)"],
      ["Potassium-sparing diuretics, potassium supplements (hyperkalemia risk)", "NSAIDs (blunt BP reduction, acute renal failure)", "Lithium", "CYP2C9 inhibitors/inducers"],
      ["Serum creatinine and eGFR at baseline and periodically", "Serum potassium levels", "24-hour ambulatory or home blood pressure monitoring"],
      "Black box warning: Strictly contraindicated in pregnancy (causes fetal hypotension, skull hypoplasia, and fetal demise).",
      "Excreted in animal milk; breastfeeding not recommended.",
      "Safety and efficacy not established in pediatric patients.",
      "No initial dose adjustment required in elderly patients; monitor for orthostatic dizziness.",
      "No dosage adjustment required in mild, moderate, or severe renal impairment or hemodialysis.",
      "No dosage adjustment required in mild to moderate hepatic impairment; not studied in severe cirrhosis.",
      ["Most potent 24-hour blood pressure reduction in the ARB class, superior to valsartan 320 mg and olmesartan 40 mg in head-to-head trials", "Exceptionally slow receptor dissociation provides sustained blood pressure control through the vulnerable morning surge period", "Zero dose adjustment needed across all stages of renal disease"],
      ["Significantly higher cost than generic telmisartan or losartan", "Strictly contraindicated in pregnancy"],
      ["Strongest blood pressure-lowering ARB on the market (superior to valsartan and olmesartan)", "Take once daily in the morning (40 mg or 80 mg) with or without food"],
      "AZIL-sartan: Absolute Zenith In Lowering blood pressure; Tightest AT1 binding; Zero morning surge.", "-sartan", "a-ZIL-sar-tan", "अज़िल-सारटन"),

    m("lercanidipine", "Lercanidipine", "Lercanidipine Hydrochloride", "Lercanidipine hydrochloride", "Lercanidipine hydrochloride", "Cardiovascular",
      "A highly lipophilic, third-generation dihydropyridine calcium channel blocker that integrates into the cell membrane lipid bilayer, providing smooth 24-hour vasodilation with minimal pedal oedema.",
      ["10 mg", "20 mg"], ["Film-coated Tablet"], ["Oral"],
      "Inhibits transmembrane calcium influx through L-type calcium channels in vascular smooth muscle; high lipophilicity causes it to dissolve in the membrane lipid bilayer, creating a local drug reservoir that diffuses slowly to receptor sites.",
      "Produces gradual, sustained peripheral arterial vasodilation without triggering reflex sympathetic activation or tachycardia; significantly lower incidence of dependent ankle oedema compared to amlodipine.",
      "Completely absorbed from GI tract; undergoes substantial hepatic first-pass metabolism; peak plasma level in 1.5 to 3 hours; high-fat meals increase absorption 3- to 4-fold (take 15 minutes before meals).",
      "Extensively distributed into vascular tissue; highly bound to plasma proteins (>98%).",
      "Extensively metabolized in the liver by CYP3A4 to inactive metabolites; no active parent drug excreted.",
      "Excreted predominantly as inactive metabolites in urine (approx. 50%) and faeces (approx. 50%).",
      "Approximately 10% (fasting); increased significantly with meals", "8 to 10 hours in plasma; membrane lipid reservoir duration exceeds 24 hours", ">98%", "2 to 3 hours", "24 hours",
      ["Mild to moderate essential hypertension", "Hypertension in patients who develop unacceptable ankle oedema on amlodipine", "Isolated systolic hypertension in the elderly"],
      ["Hypersensitivity to lercanidipine or dihydropyridines", "Severe left ventricular outflow obstruction (aortic stenosis)", "Unstable angina or within 1 month of myocardial infarction", "Severe renal (eGFR < 30 mL/min) or severe hepatic impairment", "Co-administration with strong CYP3A4 inhibitors"],
      ["Must be taken at least 15 minutes before meals (food drastically increases bioavailability)", "Avoid grapefruit juice (inhibits CYP3A4 metabolism)", "Gradually titrate dose"],
      ["Headache", "Facial flushing", "Dizziness", "Palpitations (rare)", "Peripheral oedema (much less than amlodipine)"],
      ["Severe hypotension / syncope", "Paradoxical angina in severe coronary artery disease", "Hepatotoxicity"],
      ["Strong CYP3A4 inhibitors (ketoconazole, itraconazole, clarithromycin - strictly contraindicated)", "Cyclosporine (increases levels of both drugs - avoid)", "Grapefruit juice (significantly elevates lercanidipine levels)", "Anticonvulsants (inducers decrease efficacy)"],
      ["Blood pressure sitting and standing", "Heart rate", "Inspection of ankles for pedal oedema"],
      "Contraindicated in pregnancy; animal studies demonstrate embryotoxicity and delayed labor.",
      "Contraindicated during breastfeeding; high lipophilicity suggests excretion into breast milk.",
      "Safety and efficacy not established in children under 18 years.",
      "Initiate at 10 mg once daily; titrate cautiously; well tolerated in elderly hypertensives.",
      "Use with caution in moderate renal impairment; contraindicated if eGFR < 30 mL/min.",
      "Contraindicated in severe hepatic impairment; start at 10 mg in moderate liver disease.",
      ["Significantly lower incidence of ankle pedal oedema compared to amlodipine (up to 50% fewer oedema dropouts)", "Lipophilic membrane reservoir provides smooth 24-hour blood pressure reduction without reflex tachycardia", "Renoprotective profile in hypertensive nephrosclerosis"],
      ["Bioavailability is heavily dependent on meals (must be taken 15 minutes before meals)", "Strictly contraindicated with strong CYP3A4 inhibitors and in severe renal/hepatic impairment"],
      ["Best alternative to amlodipine when patients suffer from swollen feet and ankles", "Always take 15 minutes before breakfast; avoid grapefruit juice"],
      "LERCA-nidipine: Lipophilic Embedding in cell membrane; Reduces Calf Ankle-oedema.", "-dipine", "ler-ka-NI-di-peen", "लेरका-निडिपिन"),

    m("felodipine", "Felodipine", "Felodipine", "Felodipine", "Felodipine", "Cardiovascular",
      "A second-generation dihydropyridine calcium channel blocker with exceptional vascular selectivity (100:1 vascular to cardiac smooth muscle ratio), used once daily in extended-release form for hypertension and angina.",
      ["2.5 mg ER", "5 mg ER", "10 mg ER"], ["Extended-Release Tablet"], ["Oral"],
      "Selectively blocks voltage-gated L-type calcium channels in vascular smooth muscle cells, inhibiting calcium influx and causing arteriolar dilation; has 100-fold higher selectivity for vascular smooth muscle than myocardial tissue.",
      "Reduces systemic vascular resistance and blood pressure without exerting negative inotropic effects on myocardial contractility; does not impair AV nodal conduction; causes mild natriuresis and diuresis without reflex renin stimulation.",
      "Completely absorbed from GI tract; extended-release tablet provides smooth 24-hour plasma concentrations; extensive hepatic first-pass metabolism yields approx. 15% bioavailability; food does not affect bioavailability.",
      "Apparent volume of distribution approx. 10 L/kg; extensively bound to plasma proteins (>99%, primarily albumin).",
      "Extensively metabolized in the liver by CYP3A4 to inactive pyridine and carboxylic acid metabolites; no active metabolites.",
      "Excreted in urine (approx. 70% as inactive metabolites) and faeces (approx. 10%); less than 0.5% unchanged in urine.",
      "Approximately 15% (extended-release)", "11 to 16 hours", ">99%", "2 to 5 hours (extended release)", "24 hours",
      ["Essential hypertension (alone or combined with beta-blockers or ACE inhibitors)", "Stable chronic angina pectoris", "Hypertension in elderly patients with isolated systolic hypertension"],
      ["Hypersensitivity to felodipine or dihydropyridine calcium channel blockers", "Cardiogenic shock or severe aortic stenosis", "Unstable angina or acute myocardial infarction"],
      ["Peripheral dependent oedema (dose-dependent precapillary vasodilation)", "Avoid grapefruit juice (massively increases felodipine bioavailability and hypotension)", "Gingival hyperplasia with prolonged therapy (maintain good oral hygiene)", "Do NOT crush or chew extended-release tablets"],
      ["Peripheral oedema (ankle swelling)", "Headache", "Facial flushing", "Dizziness", "Palpitations"],
      ["Severe symptomatic hypotension / syncope", "Paradoxical worsening of angina in severe obstructive CAD", "Severe gingival enlargement"],
      ["Grapefruit juice (drastically inhibits intestinal CYP3A4, doubling felodipine levels; avoid completely)", "CYP3A4 inhibitors (cimetidine, erythromycin, ketoconazole - increase felodipine exposure)", "CYP3A4 inducers (carbamazepine, phenytoin, rifampin - reduce efficacy)"],
      ["Blood pressure and heart rate", "Inspection of lower extremities for pedal oedema", "Dental examination for gingival hyperplasia"],
      "Category C; teratogenic in animal studies; avoid during pregnancy unless benefit clearly outweighs risk.",
      "Excreted in human milk; compatible with caution or alternative agent.",
      "Safety and efficacy not established in pediatric patients.",
      "Initiate at 2.5 mg ER once daily; elderly patients exhibit higher plasma levels due to decreased clearance.",
      "No dosage adjustment required in renal impairment or hemodialysis.",
      "Initiate with 2.5 mg once daily in patients with hepatic impairment (metabolized by CYP3A4).",
      ["100-fold vascular selectivity ensures safe blood pressure reduction without depressing heart muscle pump function", "True 24-hour extended-release formulation provides consistent blood pressure control", "Safe in patients with asthma, diabetes, and gout"],
      ["High rate of ankle pedal oedema at higher doses (10 mg ER)", "Severe food interaction with grapefruit juice"],
      ["Take once daily in the morning; swallow whole and never crush or chew the tablet", "Never drink grapefruit juice while taking felodipine"],
      "FELO-dipine: Fully Extended 24h release; Leaves Myocardium alone (100:1 vascular selectivity); Outlaw Grapefruit.", "-dipine", "fe-LOE-di-peen", "फ़ेलो-डिपिन"),

    m("nitrendipine", "Nitrendipine", "Nitrendipine", "Nitrendipine", "Nitrendipine", "Cardiovascular",
      "A classical dihydropyridine calcium channel blocker proven in the landmark Syst-Eur trial to reduce stroke by 42% and vascular dementia by 50% in elderly patients with isolated systolic hypertension.",
      ["10 mg", "20 mg"], ["Tablet"], ["Oral"],
      "Inhibits L-type calcium channel current in vascular smooth muscle, decreasing intracellular calcium availability and producing arteriolar vasodilation and reduced total peripheral resistance.",
      "Reduces systolic and diastolic blood pressure, improves arterial compliance, and preserves cerebral blood flow; landmark Syst-Eur trial proved a 42% reduction in stroke and a 50% reduction in vascular dementia in seniors.",
      "Rapidly absorbed (approx. 80%); extensive hepatic first-pass metabolism limits bioavailability to 10-20%; peak plasma level in 1 to 2 hours.",
      "Widely distributed; 98% bound to plasma albumin.",
      "Extensively metabolized in the liver by CYP3A4 via oxidation to inactive metabolites.",
      "Excreted predominantly in urine (approx. 75% as metabolites) and faeces (approx. 10%).",
      "10% to 20%", "8 to 12 hours", "98%", "1 to 2 hours", "12 to 24 hours",
      ["Isolated systolic hypertension in elderly patients (Syst-Eur trial proven)", "Essential hypertension in adults", "Prevention of cerebrovascular events in senior hypertensives"],
      ["Hypersensitivity to nitrendipine or dihydropyridines", "Severe cardiogenic shock or advanced aortic stenosis", "Unstable angina"],
      ["Peripheral oedema and flushing", "Avoid grapefruit juice (CYP3A4 inhibition)", "Dose reduction in hepatic cirrhosis"],
      ["Headache", "Facial flushing", "Peripheral oedema", "Palpitations", "Dizziness"],
      ["Severe hypotension", "Paradoxical myocardial ischemia", "Allergic hepatitis (rare)"],
      ["CYP3A4 inhibitors (ketoconazole, erythromycin - increase levels)", "CYP3A4 inducers (rifampin, carbamazepine)", "Beta-blockers (synergistic hypotensive effect)"],
      ["Blood pressure sitting and standing", "Cognitive evaluation in elderly patients", "Ankle inspection for oedema"],
      "Avoid in pregnancy; insufficient human safety data; use labetalol or nifedipine.", "Excreted in breast milk in trace amounts; avoid breastfeeding.",
      "Safety and efficacy not established in children.",
      "First-line agent in elderly patients with isolated systolic hypertension (Syst-Eur trial demonstrated 42% stroke reduction).",
      "No dosage adjustment required in renal impairment.",
      "Dose reduction required in severe hepatic impairment (start at 5-10 mg daily).",
      ["Landmark Syst-Eur trial proven: 42% reduction in stroke and 50% reduction in dementia in elderly patients", "Mild intrinsic natriuretic action reduces the need for high-dose diuretics", "Preserves cerebral blood flow in senior hypertensives"],
      ["Short half-life may require twice-daily dosing in some patients", "High incidence of flushing and ankle oedema"],
      ["Proven to cut stroke risk by 42% and dementia risk by 50% in elderly patients (Syst-Eur trial)", "Take once or twice daily with water; avoid grapefruit juice"],
      "NITREN-dipine: Notable In The Reduction of Elderly Neurological events (stroke & dementia - Syst-Eur).", "-dipine", "nye-TREN-di-peen", "नाइट्रेन-डिपिन"),

    m("metolazone", "Metolazone", "Metolazone", "Metolazone", "Metolazone", "Cardiovascular",
      "A potent quinazoline-sulfonamide diuretic that acts on the proximal and distal tubules, uniquely retaining efficacy even in advanced renal failure (eGFR < 30 mL/min) and creating massive synergy with loop diuretics.",
      ["2.5 mg", "5 mg"], ["Tablet"], ["Oral"],
      "Inhibits sodium and chloride reabsorption in the cortical diluting segment of the distal convoluted tubule and proximal tubule; unique quinazoline structure allows it to remain active at low glomerular filtration rates.",
      "Produces potent natriuresis, chloruresis, and diuresis; when combined with loop diuretics (furosemide/torsemide), creates 'sequential nephron blockade', overcoming refractory diuretic resistance in severe heart failure and nephrotic syndrome.",
      "Slowly and incompletely absorbed (approx. 65%); peak plasma concentration in 2 to 4 hours; bioavailability varies significantly between formulations.",
      "Distributes into extracellular water and erythrocytes; 95% bound to plasma proteins.",
      "Minimal hepatic metabolism; not cleared by CYP450 enzymes.",
      "Excreted predominantly unchanged in urine via active secretion (approx. 80-90%); remainder eliminated in bile.",
      "Approximately 65%", "8 to 14 hours (terminal half-life prolonged up to 20 hours)", "95%", "Diuresis begins within 1 hour; peak effect in 2 to 4 hours", "12 to 24 hours",
      ["Diuretic resistance in congestive heart failure (sequential nephron blockade combined with loop diuretics)", "Oedema associated with renal disease, including nephrotic syndrome and chronic renal failure (eGFR < 30 mL/min)", "Essential hypertension (second-line add-on)"],
      ["Anuria", "Hepatic coma or pre-coma", "Known hypersensitivity to metolazone or sulfonamides", "Severe uncorrected electrolyte depletion (hypokalemia, hyponatremia)"],
      ["PROFOUND ELECTROLYTE COLLAPSE: Sequential nephron blockade with loop diuretics can produce massive volume depletion, life-threatening hypokalemia (<2.5 mEq/L), and acute renal failure within 48 hours (monitor daily in hospital)", "Hyperuricemia and acute gout precipitation", "Hyperglycemia in diabetics"],
      ["Hypokalemia (very common)", "Hyponatremia", "Hypochloremic alkalosis", "Dizziness / orthostatic hypotension", "Hyperuricemia"],
      ["Life-threatening hypokalemic cardiac arrhythmias", "Severe volume depletion / circulatory shock", "Acute kidney injury", "Stevens-Johnson syndrome"],
      ["Loop diuretics (furosemide, bumetanide, torsemide - dramatic synergistic diuresis; start with tiny 2.5 mg metolazone doses)", "Digoxin (hypokalemia massively increases digitalis toxicity and arrhythmias)", "Lithium (decreases lithium clearance, causing toxicity)", "NSAIDs"],
      ["Serum electrolytes (potassium, sodium, chloride) daily during combination therapy", "BUN and serum creatinine daily during acute diuresis", "Daily weight and strict fluid balance", "Blood pressure"],
      "Category B; diuretics are generally avoided in pregnancy due to maternal hypovolemia and placental insufficiency.",
      "Excreted in breast milk; breastfeeding not recommended.",
      "Safety and efficacy in pediatric patients not established.",
      "Extreme sensitivity to volume depletion; start with 2.5 mg every other day or twice weekly.",
      "EFFECTIVE IN SEVERE RENAL FAILURE (eGFR < 30 mL/min), unlike traditional thiazide diuretics; monitor electrolytes closely.",
      "Use with extreme caution; minor electrolyte shifts can precipitate hepatic encephalopathy.",
      ["Uniquely effective at low GFR (eGFR < 30 mL/min) where traditional thiazides fail completely", "Gold standard booster for loop diuretic resistance in refractory heart failure (sequential nephron blockade)", "Long 24-hour duration of action"],
      ["Massive risk of life-threatening hypokalemia and dehydration when combined with loop diuretics", "Requires hospital-level daily electrolyte monitoring during initiation"],
      ["Secret weapon for refractory fluid overload: pairs with furosemide to overcome diuretic resistance", "DANGER: Can cause massive potassium loss; check potassium and kidney function within 48 hours"],
      "METOLA-zone: Magnificent Extra-strength Tubule Overload Lifter; Active in Low GFR; Beware Potassium.", "-zone", "me-TOE-la-zone", "मेटोला-ज़ोन"),

    m("acetazolamide", "Acetazolamide", "Acetazolamide", "Acetazolamide", "Acetazolamide", "Cardiovascular",
      "A prototypical carbonic anhydrase inhibitor that blocks bicarbonate reabsorption in the proximal tubule, used for acute mountain sickness, glaucoma, metabolic alkalosis, and idiopathic intracranial hypertension.",
      ["250 mg", "500 mg SR", "500 mg IV vial"], ["Tablet", "Extended-Release Capsule", "Powder for Injection"], ["Oral", "Intravenous"],
      "Non-competitively and reversibly inhibits carbonic anhydrase (predominantly CA-II and CA-IV) in the renal proximal tubule, ciliary body of the eye, and choroid plexus; blocks H+ ion exchange for Na+, promoting urinary excretion of bicarbonate, sodium, potassium, and water.",
      "Produces hyperchloremic metabolic acidosis, stimulating central chemoreceptors to increase ventilation (countering periodic breathing at high altitude); decreases aqueous humor production (lowers IOP) and reduces CSF production.",
      "Rapidly and well absorbed from GI tract (approx. 90-100%); peak plasma concentrations in 1 to 3 hours (oral tablet).",
      "Concentrates heavily in erythrocytes and renal cortex (binds to carbonic anhydrase); crosses blood-brain barrier and placenta; 90-95% bound to plasma proteins.",
      "Not metabolized by the liver; excreted unaltered by the kidneys.",
      "Excreted entirely unchanged in urine via tubular secretion and filtration (approx. 90-100% within 24 hours).",
      "90% to 100%", "6 to 9 hours (tablets); 12 hours (sustained release)", "90% to 95%", "Oral: 1 to 1.5 hours; IV: 2 minutes", "Oral: 8 to 12 hours; IV: 4 to 5 hours",
      ["Prevention and treatment of acute mountain sickness (AMS / altitude sickness: 125-250 mg BID starting 24h before ascent)", "Open-angle glaucoma and acute angle-closure glaucoma (lowers intraocular pressure)", "Idiopathic intracranial hypertension (pseudotumor cerebri)", "Severe metabolic alkalosis (restores bicarbonate excretion)", "Absence seizures (refractory adjuvant)"],
      ["Severe hypersensitivity to acetazolamide or sulfonamides", "Severe renal impairment (eGFR < 10 mL/min)", "Severe hepatic disease / cirrhosis (induces hepatic encephalopathy by preventing ammonia clearance)", "Marked hypokalemia or hyponatremia", "Chronic non-congestive closed-angle glaucoma", "Hyperchloremic acidosis"],
      ["Hyperchloremic metabolic acidosis and severe hypokalemia", "Sulfonamide allergy cross-reactivity (Stevens-Johnson syndrome, blood dyscrasias)", "Calcium phosphate kidney stones (due to reduced urinary citrate and alkaline urine)", "Drowsiness and paresthesias in extremities"],
      ["Paresthesias (numbness and tingling in fingers, toes, and lips - very common)", "Dysgeusia (carbonated drinks taste flat/metallic due to tongue carbonic anhydrase inhibition)", "Polyuria", "Fatigue", "Dizziness", "Anorexia"],
      ["Severe hyperchloremic metabolic acidosis", "Aplastic anaemia / agranulocytosis", "Stevens-Johnson syndrome / TEN", "Calcium phosphate nephrolithiasis", "Hepatic encephalopathy in cirrhotics"],
      ["High-dose aspirin / salicylates (severe toxicity: metabolic acidosis causes aspirin to enter brain)", "Lithium (increases lithium excretion, reducing efficacy)", "Topiramate (additive carbonic anhydrase inhibition and stone risk)", "Quinidine, amphetamines"],
      ["Serum electrolytes (potassium, bicarbonate) at baseline and periodically", "Complete blood counts (screen for bone marrow suppression)", "Urinalysis for crystals / stone formation"],
      "Category C; teratogenic in animal models; avoid during first trimester; use for altitude sickness only if clearly needed.",
      "Excreted in breast milk in low concentrations; compatible with caution.",
      "Approved in children for glaucoma and epilepsy (8 to 30 mg/kg/day divided every 8 hours).",
      "Higher risk of metabolic acidosis and hypokalemia; reduce dose based on eGFR.",
      "Dose adjustment required based on eGFR: eGFR 10-50 mL/min: dose every 12 hours; eGFR < 10 mL/min: contraindicated.",
      "Strictly contraindicated in severe hepatic disease (triggers ammonia-mediated hepatic coma).",
      ["Gold standard preventive drug for acute mountain sickness (AMS) and high-altitude pulmonary/cerebral oedema", "Rapidly lowers intraocular pressure in acute glaucoma emergencies", "Corrects metabolic alkalosis in ICU patients with COPD"],
      ["Characteristic tingling in fingers/toes and makes soda/carbonated beverages taste flat", "Risk of calcium kidney stones and metabolic acidosis"],
      ["Start 125 mg twice daily 24 hours before climbing above 8,000 feet to prevent altitude sickness", "Tell patients that tingling in fingers and flat-tasting soda are normal, harmless side effects"],
      "ACETA-ZOLAMIDE: Altitude sickness Altitude climb; Carbonic anhydrase block; Eyes (glaucoma); Tingling toes; Acidosis.", "-zolamide", "a-see-ta-ZOLE-a-mide", "एसिटा-ज़ोलामाइड"),

    m("isosorbide-mononitrate", "Isosorbide Mononitrate (ISMN)", "Isosorbide Mononitrate Sustained Release", "Isosorbide mononitrate", "Isosorbide mononitrate", "Cardiovascular",
      "An active organic nitrate vasodilator with 100% oral bioavailability and zero hepatic first-pass metabolism, providing predictable long-term prophylaxis for stable coronary artery disease.",
      ["20 mg", "30 mg SR", "60 mg SR"], ["Tablet", "Sustained-Release Tablet"], ["Oral"],
      "Denitrated intracellularly in vascular smooth muscle to release nitric oxide (NO); NO stimulates soluble guanylyl cyclase, increasing cyclic GMP (cGMP), leading to dephosphorylation of myosin light chains and marked venodilation.",
      "Dilates systemic veins (reducing venous return, preload, and left ventricular wall tension) and epicardial coronary arteries, substantially decreasing myocardial oxygen demand; does NOT develop tolerance when an eccentric dosing schedule is used.",
      "Rapidly and completely absorbed from GI tract; 100% absolute oral bioavailability; zero hepatic first-pass metabolism; food does not affect absorption.",
      "Apparent volume of distribution approx. 0.6 L/kg; minimal plasma protein binding (<5%).",
      "Metabolized in the liver by denitration to inactive isosorbide and by glucuronidation to isosorbide mononitrate glucuronide.",
      "Excreted almost entirely in urine as inactive metabolites (approx. 93%); less than 2% unchanged in urine.",
      "100% (predictable, unlike isosorbide dinitrate)", "5 hours (immediate release); extended release delivers therapeutic levels over 12 hours with a mandatory 12-hour nitrate-free interval", "<5%", "Immediate release: 30 to 60 minutes; SR: 2 to 4 hours", "Immediate release: 6 to 8 hours; SR: 12 to 14 hours",
      ["Prophylaxis of chronic stable angina pectoris (coronary artery disease)", "Adjunct therapy in chronic congestive heart failure (combined with hydralazine)", "Secondary prevention in post-myocardial infarction angina"],
      ["Concurrent use of phosphodiesterase-5 (PDE5) inhibitors (sildenafil, tadalafil, vardenafil - FATAL HYPOTENSION)", "Concurrent use of soluble guanylyl cyclase stimulators (riociguat)", "Severe hypotension (systolic BP < 90 mmHg) or severe hypovolemia", "Hypertrophic obstructive cardiomyopathy (HOCM)", "Constrictive pericarditis or cardiac tamponade"],
      ["FATAL INTERACTION WITH PDE5 INHIBITORS: Co-administration with sildenafil or tadalafil can cause catastrophic, refractory circulatory collapse and fatal myocardial infarction", "NITRATE TOLERANCE: Continuous 24-hour exposure causes complete loss of antianginal efficacy; a mandatory 10- to 12-hour nitrate-free interval every day is required", "Severe nitrate headache during initial days (treat with paracetamol; do not stop therapy)"],
      ["Throbbing headache (very common during first 1-2 weeks)", "Flushing", "Dizziness / postural hypotension", "Weakness", "Nausea"],
      ["Severe refractory hypotension / syncope", "Paradoxical bradycardia", "Precipitation of myocardial ischemia from reflex tachycardia in severe CAD"],
      ["PDE5 inhibitors (sildenafil within 24h, tadalafil within 48h - STRICTLY CONTRAINDICATED)", "Riociguat (contraindicated)", "Alcohol (severe orthostatic hypotension and syncope)", "Antihypertensives (additive hypotension)"],
      ["Blood pressure and heart rate sitting and standing", "Frequency of angina episodes and sublingual nitroglycerin use", "Compliance with the nitrate-free interval"],
      "Category C; use during pregnancy only if clearly needed and benefits justify potential fetal risks.",
      "Excretion in human milk unknown; use caution during breastfeeding.",
      "Safety and efficacy not established in pediatric patients.",
      "Higher risk of orthostatic dizziness and falls; start with 30 mg SR once daily in the morning.",
      "No dosage adjustment required in renal impairment.",
      "No dosage adjustment required in mild to moderate hepatic impairment.",
      ["100% oral bioavailability with zero first-pass metabolism guarantees predictable antianginal blood levels", "Once-daily extended-release tablet (taken in morning) automatically provides the required overnight nitrate-free window to prevent tolerance", "Proven reduction in angina frequency and exercise tolerance"],
      ["Throbbing nitrate headache occurs in up to 50% during initiation", "Strictly contraindicated with Viagra/Cialis (lethal hypotension)"],
      ["Take once daily in the MORNING so the body has an overnight 'nitrate-free' window to prevent tolerance", "NEVER take with sildenafil (Viagra) or tadalafil (Cialis)—combination can be fatal"],
      "ISMN: 100% Bioavailable; Single Morning dose; Mandatory 12h nitrate-free window; No PDE5 inhibitors.", "-nitrate", "eye-soe-SOR-bide mon-oh-NYE-trate", "आइसोसोरबाइड मोनोनाइट्रेट"),

    m("isosorbide-dinitrate", "Isosorbide Dinitrate (ISDN)", "Isosorbide Dinitrate", "Isosorbide dinitrate", "Isosorbide dinitrate", "Cardiovascular",
      "An organic nitrate vasodilator used sublingually for acute angina relief and orally combined with hydralazine (BiDil) to significantly reduce mortality in Black patients with heart failure (A-HeFT trial).",
      ["5 mg sublingual", "10 mg", "20 mg", "40 mg SR"], ["Sublingual Tablet", "Immediate-Release Tablet", "Sustained-Release Tablet"], ["Sublingual", "Oral"],
      "Releases free nitric oxide in vascular smooth muscle, stimulating guanylyl cyclase to produce cGMP; selectively dilates venous capacitance vessels to decrease preload, and dilates large epicardial coronary arteries.",
      "Relieves acute myocardial ischemia; combined with hydralazine, provides nitric oxide donation while hydralazine prevents nitrate tolerance and scavenges free radicals (A-HeFT trial mortality reduction in African Americans).",
      "Sublingual: rapidly absorbed into systemic circulation (peak in 10-15 minutes); Oral: heavily metabolized by hepatic first-pass (bioavailability 20-25%).",
      "Widely distributed; active metabolites 5-ISMN and 2-ISMN distribute to vascular tissues; <28% protein bound.",
      "Extensively metabolized in the liver to two active metabolites: isosorbide-5-mononitrate (5-ISMN, longer-acting) and isosorbide-2-mononitrate (2-ISMN).",
      "Excreted in urine (approx. 80-90% as glucuronide metabolites and free mononitrates).",
      "Sublingual: 40-50%; Oral: 20-25% (due to high hepatic first-pass clearance)", "Parent ISDN: 1 hour; active 5-ISMN metabolite: 5 hours", "<28%", "Sublingual: 2 to 5 minutes; Oral: 20 to 40 minutes", "Sublingual: 1 to 2 hours; Oral: 4 to 6 hours",
      ["Treatment and prevention of acute angina pectoris (sublingual formulation)", "Adjunct treatment of heart failure with reduced ejection fraction in Black patients, combined with hydralazine (A-HeFT trial: 43% reduction in mortality)", "Chronic angina prophylaxis (oral formulation)"],
      ["Concurrent use of PDE5 inhibitors (sildenafil, tadalafil - LETHAL HYPOTENSION)", "Severe hypotension (systolic BP < 90 mmHg)", "Severe hypovolemia or cardiogenic shock", "Constrictive pericarditis and cardiac tamponade"],
      ["Fatal hypotension with PDE5 inhibitors (sildenafil within 24h, tadalafil within 48h)", "Nitrate tolerance: require 14-hour nitrate-free interval for chronic oral dosing (e.g., dose at 7 AM, 12 PM, 5 PM, none overnight)", "Severe throbbing nitrate headache"],
      ["Headache", "Lightheadedness", "Flushing", "Postural hypotension", "Tachycardia"],
      ["Severe life-threatening hypotension / syncope", "Paradoxical bradycardia", "Reflex myocardial ischemia"],
      ["PDE5 inhibitors (sildenafil, tadalafil, vardenafil - contraindicated)", "Riociguat (contraindicated)", "Alcohol (severe hypotension)", "Antihypertensives"],
      ["Blood pressure and heart rate", "Angina attack frequency", "Compliance with TID eccentric schedule (7 AM, 12 PM, 5 PM)"],
      "Category C; use during pregnancy only if clearly needed.", "Excretion in human milk unknown; use caution.",
      "Safety and efficacy not established in pediatric patients.", "Start at lowest dose (5-10 mg TID); high risk of orthostatic falls.",
      "No dosage adjustment required in renal impairment.",
      "Dose titration required in severe hepatic cirrhosis (reduced first-pass clearance elevates ISDN levels).",
      ["Sublingual form acts within 2 to 5 minutes for acute angina relief", "Landmark A-HeFT trial proven: combined with hydralazine, cuts heart failure mortality by 43% in Black patients", "Cost-effective, established cardiovascular therapy"],
      ["Low and erratic oral bioavailability compared to isosorbide mononitrate", "Requires complex TID eccentric dosing (7 AM - 12 PM - 5 PM) to prevent tolerance"],
      ["Sublingual tablet dissolves under the tongue in 2 minutes for chest pain relief", "If taking oral tablets 3 times daily, space them at 7 AM, 12 PM, and 5 PM so night is nitrate-free"],
      "ISDN: Immediate Sublingual Dissolution for Need; Needs nitrate-free night; Never mix with PDE5 inhibitors.", "-nitrate", "eye-soe-SOR-bide dye-NYE-trate", "आइसोसोरबाइड डाइनाइट्रेट"),

    m("nitroglycerin", "Nitroglycerin (Glyceryl Trinitrate - GTN)", "Nitroglycerin (Glyceryl Trinitrate)", "Nitroglycerin", "Nitroglycerin", "Cardiovascular",
      "The foundational rapid-acting organic nitrate vasodilator used sublingually for immediate termination of acute angina attacks and intravenously for acute heart failure, pulmonary oedema, and hypertensive emergencies.",
      ["0.4 mg (400 mcg) sublingual tablet", "0.4 mg/metered dose sublingual spray", "5 mg/mL (5 mL, 10 mL IV ampoules)", "2.5 mg, 6.5 mg sustained release", "5 mg/24h, 10 mg/24h transdermal patch", "2% ointment"],
      ["Sublingual Tablet", "Sublingual Aerosol Spray", "Solution for Injection / Infusion", "Transdermal Patch", "Topical Ointment"], ["Sublingual", "Intravenous", "Transdermal", "Topical"],
      "Denitrated in vascular smooth muscle by mitochondrial aldehyde dehydrogenase (ALDH-2) to release nitric oxide (NO); stimulates guanylyl cyclase, increasing intracellular cGMP and causing profound venous dilation, lowering preload and ventricular wall stress; dilates coronary collaterals.",
      "Rapidly aborts acute myocardial ischemia within 1 to 3 minutes; decreases left ventricular end-diastolic pressure and pulmonary capillary wedge pressure, relieving acute cardiogenic pulmonary oedema.",
      "Sublingual: rapidly and completely absorbed through oral mucosa directly into systemic circulation (bypasses hepatic first-pass); Oral swallowed: >99% destroyed by hepatic first-pass metabolism (bioavailability <1%).",
      "Widely distributed; volume of distribution approx. 3 L/kg; 60% bound to plasma proteins.",
      "Extensively metabolized by red blood cell and liver glutathione-dependent organic nitrate reductase into dinitrate and mononitrate metabolites with much lower vasodilator activity.",
      "Excreted in urine as inactive glucuronide conjugates.",
      "Sublingual: approx. 40%; Transdermal: 75%; Oral: <1%", "1 to 4 minutes (ultra-short half-life enables minute-to-minute IV titration)", "60%", "Sublingual: 1 to 3 minutes; IV: immediate (1 to 2 minutes); Transdermal: 30 to 60 minutes", "Sublingual: 20 to 30 minutes; IV: 3 to 5 minutes after stopping infusion; Patch: 12 hours (remove for 12h daily)",
      ["Immediate relief of acute angina pectoris attacks (0.4 mg sublingual tablet or spray every 5 minutes up to 3 doses)", "Prophylaxis of angina taken 5 to 10 minutes prior to physical exertion or emotional stress", "Acute decompensated heart failure with pulmonary oedema (IV continuous infusion)", "Unstable angina and acute myocardial infarction (IV infusion)", "Hypertensive emergency with acute left ventricular failure"],
      ["Concurrent use of PDE5 inhibitors (sildenafil/vardenafil within 24 hours, tadalafil within 48 hours - LETHAL HYPOTENSION)", "Severe hypotension (systolic BP < 90 mmHg or >30 mmHg below baseline)", "Severe bradycardia (<50 bpm) or marked tachycardia (>100 bpm in absence of heart failure)", "Right ventricular myocardial infarction (inferior MI with RV involvement - profound drop in preload precipitates cardiogenic shock)", "Increased intracranial pressure or cerebral hemorrhage", "Severe aortic stenosis or obstructive cardiomyopathy"],
      ["CRITICAL RULE: Never administer in suspected RIGHT VENTRICULAR INFARCTION (leads to catastrophic shock due to preload dependence)", "FATAL INTERACTION WITH PDE5 INHIBITORS (Viagra/Cialis)", "Call emergency medical services (ambulance) if chest pain is not relieved or worsens 5 minutes after the first sublingual dose", "Transdermal patches must be removed for 10-12 hours daily (usually at bedtime) to avoid complete nitrate tolerance", "Glass bottles and non-PVC infusion tubing required for IV infusion (absorbs into regular PVC plastic bags)"],
      ["Throbbing headache (very common)", "Facial flushing", "Dizziness / lightheadedness", "Postural hypotension", "Reflex tachycardia"],
      ["Severe catastrophic circulatory collapse / refractory shock", "Paradoxical bradycardia and syncope", "Severe methemoglobinemia (rare with high-dose prolonged IV infusions)"],
      ["Phosphodiesterase-5 inhibitors (sildenafil, tadalafil, vardenafil - ABSOLUTELY CONTRAINDICATED)", "Riociguat (contraindicated)", "Alcohol (severe hypotension)", "Antihypertensives, beta-blockers, calcium channel blockers (additive hypotension)"],
      ["Blood pressure and heart rate before and 5 minutes after each sublingual dose", "Continuous arterial pressure and telemetry during IV infusion", "Keep sublingual tablets in original amber glass bottle tightly capped (evaporates and loses potency in plastic pillboxes)"],
      "Category C; widely used in maternal hypertensive emergencies and acute pulmonary oedema with close fetal monitoring.",
      "Excretion in human milk unknown; use caution during breastfeeding.",
      "Safety and efficacy established in pediatric intensive care for afterload reduction (0.5-5 mcg/kg/min IV).",
      "Extreme susceptibility to orthostatic hypotension and syncope; patient must always sit down before taking sublingual dose.",
      "No dosage adjustment required in renal failure.",
      "No dosage adjustment required in hepatic disease.",
      ["World standard first-line emergency rescue medication for acute angina attacks, relieving pain within 1 to 3 minutes", "Minute-to-minute titratability via IV infusion makes it the premier agent for acute cardiogenic pulmonary oedema", "Multiple delivery routes (sublingual tablets, spray, transdermal patch, IV)"],
      ["Volatile drug: sublingual tablets lose potency rapidly if exposed to air, moisture, or plastic pillboxes", "Continuous exposure causes total nitrate tolerance within 24-48 hours", "Contraindicated in right ventricular infarction"],
      ["Sit down before taking sublingual nitroglycerin to prevent fainting; dissolve under the tongue without swallowing", "If chest pain persists 5 minutes after the first dose, CALL AN AMBULANCE immediately before taking a second dose", "Keep tablets in the original amber glass bottle; replace every 6 months after opening"],
      "NITRO-glycerin: Number 1 In Terminating angina Rapidly; Outlawed in Right-ventricular MI; Sit down before dosing.", "-glycerin", "nye-troe-GLIS-er-in", "नाइट्रो-ग्लिसरीन"),

    m("nicorandil", "Nicorandil", "Nicorandil", "Nicorandil", "Nicorandil", "Cardiovascular",
      "A dual-action potassium channel opener and organic nitrate donor that provides balanced arterial and venous dilation without developing nitrate tolerance, proven to reduce major coronary events (IONA study).",
      ["5 mg", "10 mg"], ["Scored Tablet"], ["Oral"],
      "Dual mechanism: opens ATP-sensitive potassium channels (K-ATP) in arterial smooth muscle causing hyperpolarization and arteriolar dilation (reduces afterload and mimics ischemic preconditioning), AND contains a nitrate moiety that donates nitric oxide (NO) causing venodilation (reduces preload) and coronary vasodilation.",
      "Improves coronary collateral blood flow, reduces myocardial oxygen demand, prevents myocardial stunning, and confers ischemic preconditioning; does NOT develop classical nitrate tolerance (IONA study: 17% reduction in major coronary events).",
      "Rapidly and completely absorbed from GI tract (approx. 75-80% bioavailability); peak plasma concentration in 30 to 60 minutes; unaffected by food.",
      "Apparent volume of distribution approx. 1.0 to 1.4 L/kg; low plasma protein binding (approx. 25%).",
      "Extensively metabolized in the liver mainly by denitration into inactive nicotinamide and subsequent incorporation into NAD/NADP pathways.",
      "Excreted predominantly in urine (approx. 20% as metabolites within 24 hours); less than 1% unchanged drug.",
      "75% to 80%", "1 hour (effective therapeutic duration 12 hours)", "25%", "30 to 60 minutes", "12 hours (dosed twice daily)",
      ["Prevention and long-term treatment of chronic stable angina pectoris (second-line add-on to beta-blockers/CCBs)", "Refractory angina pectoris when conventional therapies are insufficient or contraindicated", "Microvascular angina"],
      ["Concurrent use of phosphodiesterase-5 (PDE5) inhibitors (sildenafil, tadalafil - FATAL HYPOTENSION)", "Concurrent use of soluble guanylyl cyclase stimulators (riociguat)", "Severe hypotension or cardiogenic shock", "Acute pulmonary oedema"],
      ["GASTROINTESTINAL AND CUTANEOUS ULCERATION: Nicorandil can cause severe, refractory, persistent aphthous ulcers in the mouth, stomach, small intestine, colon, anus, and cornea; ulcers DO NOT HEAL until nicorandil is completely discontinued", "Risk of intestinal perforation and severe GI bleeding from ulcers", "Headache during first week of therapy"],
      ["Headache (very common during initial therapy, diminishes over time)", "Dizziness", "Cutaneous flushing", "Nausea", "Mouth ulcers"],
      ["Severe gastrointestinal ulceration / intestinal perforation", "Refractory anal and perianal ulceration", "Corneal ulceration", "Severe hypotension"],
      ["PDE5 inhibitors (sildenafil, tadalafil - strictly contraindicated due to lethal hypotension)", "Riociguat (contraindicated)", "Corticosteroids, NSAIDs, or aspirin (greatly increase risk of severe GI ulceration and perforation)", "Antihypertensives (additive blood pressure lowering)"],
      ["Careful inspection for persistent mouth ulcers, skin ulcers, or perianal ulceration (stop drug immediately if found)", "Complete blood count and stool for occult blood", "Blood pressure sitting and standing"],
      "Avoid in pregnancy; insufficient human safety data; use only if potential benefit justifies potential risk.",
      "Excretion in breast milk unknown; breastfeeding not recommended.",
      "Safety and efficacy in pediatric patients not established.",
      "Initiate at 5 mg twice daily; titrate up to 10-20 mg twice daily.",
      "No dosage adjustment required in renal impairment.",
      "No dosage adjustment required in hepatic disease.",
      ["Dual-action potassium channel opener and nitric oxide donor providing comprehensive preload and afterload reduction", "Does not develop classical nitrate tolerance", "Proven 17% reduction in major coronary events in chronic angina (IONA trial)"],
      ["Causes refractory gastrointestinal and mucosal ulceration that only resolves after stopping the drug", "Strictly contraindicated with PDE5 inhibitors"],
      ["Dual-action antianginal that opens potassium channels and releases nitric oxide", "STOP THE DRUG IMMEDIATELY if you develop persistent mouth ulcers, stomach pain, or anal sores"],
      "NICOR-andil: Nitrate and K-channel opener; Increases collateral flow; Caution: Causes Cavity/mouth ulcers.", "-andil", "nye-KOR-an-dil", "निकोरा-न्डिल"),

    m("ranolazine", "Ranolazine", "Ranolazine Extended-Release", "Ranolazine", "Ranolazine", "Cardiovascular",
      "A first-in-class late inward sodium current (INa-late) inhibitor that reduces intracellular calcium overload in ischemic cardiomyocytes, improving myocardial perfusion without lowering heart rate or blood pressure.",
      ["500 mg ER", "1000 mg ER"], ["Extended-Release Tablet"], ["Oral"],
      "Selectively inhibits the late inward sodium current (late INa) in ischemic myocardial cells, preventing sodium accumulation, reversing reverse Na+/Ca2+ exchange, and attenuating intracellular calcium overload; reduces diastolic wall tension and mechanical compression of microvascular coronary vessels.",
      "Improves myocardial perfusion during diastole and reduces anginal symptoms and nitrate consumption without reducing heart rate, inotropic contractility, or systemic blood pressure; causes mild dose-dependent QTc prolongation.",
      "Variable absorption; 73% systemic availability of extended-release tablet; peak plasma concentration in 2 to 5 hours; food does not affect absorption.",
      "Apparent volume of distribution approx. 85 to 180 L; 62% bound to human plasma proteins (predominantly alpha-1 acid glycoprotein).",
      "Extensively metabolized in the liver (>80%) primarily by CYP3A4, and to a lesser extent by CYP2D6; multiple metabolites.",
      "Excreted in urine (approx. 75%, with <5% unchanged) and faeces (approx. 25%).",
      "Approximately 73% (extended release)", "7 hours", "62%", "Steady state reached within 3 days", "12 hours (dosed twice daily)",
      ["Chronic stable angina pectoris refractory to or intolerant of first-line agents (beta-blockers, CCBs, nitrates)", "Angina in patients with baseline bradycardia or low blood pressure who cannot tolerate heart-rate lowering medications", "Microvascular angina"],
      ["Preexisting clinically significant QTc prolongation (congenital long QT syndrome)", "Severe hepatic impairment (Child-Pugh Class C)", "Concurrent use of strong CYP3A4 inhibitors (ketoconazole, clarithromycin) or inducers (rifampin, carbamazepine, St. John's wort)"],
      ["Dose-dependent QTc prolongation (mean increase of 6 ms at 1000 mg BID; risk of Torsades de pointes in susceptible patients)", "Acute renal failure reported in patients with severe renal impairment (eGFR < 30 mL/min)", "Do not crush, break, or chew extended-release tablets"],
      ["Dizziness", "Constipation (very common)", "Headache", "Nausea", "Asthenia"],
      ["Torsades de pointes / ventricular arrhythmias (rare)", "Acute renal failure (in patients with preexisting severe renal disease)", "Syncope"],
      ["Strong CYP3A4 inhibitors (ketoconazole, clarithromycin - contraindicated)", "Moderate CYP3A4 inhibitors (diltiazem, verapamil, fluconazole - limit ranolazine to 500 mg BID)", "Strong CYP3A4 inducers (rifampin, phenytoin - contraindicated)", "P-glycoprotein substrates (ranolazine increases digoxin levels; reduce digoxin by 50%)", "Simvastatin (do not exceed 20 mg simvastatin daily)"],
      ["Baseline and periodic ECG to assess QTc interval (especially when combining with other drugs)", "Renal function (BUN and creatinine) in patients with eGFR < 60 mL/min", "Frequency of weekly angina attacks"],
      "Category C; use during pregnancy only if potential benefit justifies potential risk.",
      "Excretion in human milk unknown; breastfeeding not recommended.",
      "Safety and efficacy in pediatric patients not established.",
      "No dosage adjustment required based on age alone; monitor for constipation and dizziness.",
      "If eGFR < 60 mL/min, monitor renal function and discontinue if acute renal failure occurs; contraindicated if eGFR < 30 mL/min.",
      "Contraindicated in severe hepatic cirrhosis; dose reduction in moderate impairment.",
      ["Relieves chronic angina WITHOUT lowering heart rate or blood pressure, making it ideal for patients with baseline bradycardia or borderline hypotension", "Does not cause erectile dysfunction, bronchospasm, or fatigue", "Improves glycemic control (modest 0.5-0.7% HbA1c reduction in diabetic patients)"],
      ["High incidence of constipation", "Prolongs the QTc interval by 6 ms, requiring baseline ECG and drug interaction screening", "High acquisition cost"],
      ["Antianginal medication that does NOT lower your heart rate or blood pressure", "Swallow extended-release tablets whole; do not chew or crush; take twice daily"],
      "RANOL-azine: Reduces Acute Na+ Overload; Leaves heart-rate and BP unchanged; Beware QTc & Constipation.", "-azine", "ra-NOE-la-zeen", "रानोला-ज़ीन"),

    m("trimetazidine", "Trimetazidine", "Trimetazidine Modified Release", "Trimetazidine dihydrochloride", "Trimetazidine dihydrochloride", "Cardiovascular",
      "A cellular anti-ischemic metabolic agent that shifts myocardial energy metabolism from fatty acid oxidation to glucose oxidation, protecting cardiomyocytes against ischemia without hemodynamic effects.",
      ["20 mg", "35 mg MR", "80 mg OD"], ["Film-coated Tablet", "Modified-Release Tablet"], ["Oral"],
      "Selectively inhibits mitochondrial long-chain 3-ketoacyl-CoA thiolase (3-KAT), suppressing fatty acid beta-oxidation; shifts cellular energy production toward glucose oxidation, which requires less oxygen per ATP molecule produced, optimizing cardiomyocyte energy during ischemia.",
      "Maintains intracellular ATP levels, preserves cellular ionic homeostasis (prevents intracellular calcium and sodium overload), and limits acidosis during myocardial ischemia without altering heart rate, blood pressure, or coronary blood flow.",
      "Rapidly absorbed from GI tract; modified-release (MR) formulation provides peak levels in 5 hours; food does not affect bioavailability.",
      "Widely distributed into tissues; low protein binding (approx. 16%); volume of distribution approx. 4.8 L/kg.",
      "Minimal hepatic metabolism; excreted predominantly unaltered.",
      "Excreted predominantly unchanged in urine via glomerular filtration (approx. 60%).",
      "Approximately 90%", "6 hours (immediate release); 7 to 12 hours (modified release)", "16%", "1 to 2 hours", "12 hours (35 mg MR dosed twice daily)",
      ["Add-on therapy for the symptomatic treatment of chronic stable angina pectoris in patients inadequately controlled by or intolerant of first-line antianginal therapies", "Adjuvant therapy in ischemic cardiomyopathy"],
      ["Parkinson's disease, parkinsonism, tremors, restless legs syndrome, and other movement disorders", "Severe renal impairment (creatinine clearance < 30 mL/min)", "Known hypersensitivity to trimetazidine"],
      ["PARKINSONIAN SYMPTOMS: Can cause or aggravate parkinsonian symptoms (tremor, rigidity, bradykinesia, gait instability), especially in elderly patients; symptoms are usually reversible upon discontinuation", "Must be discontinued permanently if movement disorders develop", "Not indicated for acute angina attacks"],
      ["Dizziness", "Headache", "Abdominal pain", "Diarrhoea", "Dyspepsia", "Nausea", "Pruritus / rash"],
      ["Drug-induced parkinsonism / extrapyramidal symptoms", "Agranulocytosis / thrombocytopenia (rare)", "Severe gait instability and falls"],
      ["No clinically significant pharmacokinetic cytochrome P450 interactions reported", "Additive CNS effects with dopamine antagonists"],
      ["Regular screening for movement disorders (tremor, slow movements, gait unsteadiness)", "Renal function (creatinine clearance) at baseline and annually", "Angina attack frequency"],
      "Avoid during pregnancy due to limited human safety data.",
      "Excretion in breast milk unknown; breastfeeding not recommended.",
      "Safety and efficacy in children under 18 years not established.",
      "Higher risk of drug-induced parkinsonism and falls in senior patients; monitor closely for resting tremor.",
      "Dose reduction required: if CrCl 30-60 mL/min, reduce dose by 50% (give 35 mg MR once daily in the morning); contraindicated if CrCl < 30 mL/min.",
      "No dosage adjustment required in hepatic disease.",
      ["Pure metabolic cytoprotective mechanism that optimizes oxygen efficiency without affecting heart rate or blood pressure", "Can be combined safely with any hemodynamic antianginal (beta-blockers, CCBs, nitrates)", "Reduces myocardial injury during angioplasty and cardiac surgery"],
      ["Risk of drug-induced Parkinson's symptoms (tremor, gait freezing) in elderly patients", "Not approved in the United States (extensively used in Europe, Asia, and India)"],
      ["Metabolic heart protector that makes heart muscle use oxygen more efficiently", "Stop the medication and inform your doctor immediately if you notice finger tremors or walking stiffness"],
      "TRIMETA-zidine: Thiolase (3-KAT) Inhibitor; Metabolic Energy optimizer; Tremor/Parkinson risk.", "-zidine", "trye-MET-a-zi-deen", "ट्राइमेटा-ज़िडीन")
]

print(f"Loaded {len(meds)} cardiovascular records.")
with open("scripts/data_cardio_20.json", "w") as f:
    json.dump(meds, f, indent=2)
print("Saved to scripts/data_cardio_20.json")
