#!/usr/bin/env python3
"""
Generator for Part 1: 55 Analgesics, NSAIDs, Muscle Relaxants & Antibacterials
"""

import json

# We can import the 25 from group1 and 5 from group2 already created, and supply the remaining 25 antibacterials.
from catalog.group1_analgesia import MEDICINES as G1
from catalog.group2_antibacterials import MEDICINES as G2

PART1 = list(G1) + list(G2)

# Remaining 25 antibacterials
REMAINING_ANTIBACTERIALS = [
    {
        "slug": "telithromycin",
        "generic_name": "Telithromycin",
        "display_name": "Telithromycin",
        "active_ingredient": "Telithromycin",
        "salt": "Telithromycin",
        "category": "Antibiotics",
        "description": "A semi-synthetic ketolide antibiotic derived from erythromycin, engineered to overcome macrolide resistance in Streptococcus pneumoniae.",
        "strengths": ["400 mg", "800 mg"],
        "dosage_forms": ["Film-coated Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Binds to two distinct domains (II and V) on the 23S rRNA of the bacterial 50S ribosomal subunit, maintaining high affinity even against MLSB-resistant strains.",
        "pharmacodynamics": "Concentration-dependent and time-dependent bactericidal action against penicillin- and erythromycin-resistant Streptococcus pneumoniae and respiratory pathogens.",
        "absorption": "Rapidly absorbed; peak plasma concentration attained within 1 to 3 hours; unaffected by food.",
        "distribution": "High penetration into respiratory tissues, alveolar macrophages, and white blood cells; 60-70% bound to plasma proteins.",
        "metabolism": "Extensively metabolized by CYP3A4 (50%) and non-CYP pathways (50%).",
        "excretion": "Excreted in faeces (approx. 7%) and urine (approx. 13% unchanged).",
        "bioavailability": "Approximately 57%",
        "half_life": "10 hours",
        "protein_binding": "60% to 70%",
        "onset": "1 to 2 hours",
        "duration": "24 hours",
        "indications": ["Community-acquired pneumonia due to multi-drug resistant Streptococcus pneumoniae (MDRSP)"],
        "contraindications": ["Myasthenia gravis (black box warning: risk of fatal respiratory failure)", "History of telithromycin-associated hepatitis or jaundice", "Concurrent use with pimozide, cisapride, or ergot alkaloids"],
        "warnings": ["Severe hepatotoxicity including acute liver failure and death", "Visual disturbances (blurred vision, difficulty focusing) requiring caution when driving", "QTc interval prolongation"],
        "common_adverse_effects": ["Diarrhoea", "Nausea", "Dizziness", "Dysgeusia (altered taste)", "Blurred vision"],
        "serious_adverse_effects": ["Fulminant liver failure", "Exacerbation of myasthenia gravis (fatal)", "Ventricular arrhythmias / Torsades de pointes", "Loss of consciousness / syncope"],
        "drug_interactions": ["Simvastatin / atorvastatin (severe rhabdomyolysis due to CYP3A4 inhibition)", "Digoxin (increased levels)", "Ketoconazole / itraconazole", "Midazolam"],
        "monitoring": ["Liver enzymes at first sign of fatigue or jaundice", "Visual acuity", "ECG in patients with cardiac risk"],
        "pregnancy": "Avoid in pregnancy unless benefits clearly outweigh potential fetal risks.",
        "lactation": "Excreted in animal milk; avoid breastfeeding during therapy.",
        "pediatric": "Not recommended in children under 18 years of age.",
        "geriatric": "Assess hepatic and cardiac function; monitor visual symptoms closely.",
        "renal": "Dose reduction (400 mg daily) in severe renal impairment (CrCl < 30 mL/min).",
        "hepatic": "Contraindicated in patients with prior telithromycin hepatotoxicity; caution in hepatic impairment.",
        "advantages": ["Retains activity against macrolide-resistant pneumococci due to dual 23S rRNA binding", "Convenient once-daily 800 mg regimen"],
        "disadvantages": ["Severe hepatotoxicity and myasthenia gravis warnings limit use to strict reserve indication", "Visual disturbances can impair driving"],
        "key_points": ["Strictly contraindicated in myasthenia gravis", "Reserve solely for community-acquired pneumonia when other options fail"],
        "memory_trick": "TELI-thromycin: Tough on resistant bugs, but Terribly Toxic to the liver and myasthenia.",
        "key_suffix": "-thromycin",
        "pronunciation_en": "tel-ith-roe-MYE-sin",
        "pronunciation_hi": "टेलिथ्रो-माइसिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "gemifloxacin",
        "generic_name": "Gemifloxacin",
        "display_name": "Gemifloxacin",
        "active_ingredient": "Gemifloxacin mesylate",
        "salt": "Gemifloxacin mesylate",
        "category": "Antibiotics",
        "description": "An advanced fluoroquinolone with potent dual-targeting against bacterial DNA gyrase and topoisomerase IV, specifically indicated for acute bacterial exacerbation of chronic bronchitis and mild-to-moderate CAP.",
        "strengths": ["320 mg"],
        "dosage_forms": ["Film-coated Tablet"],
        "routes": ["Oral"],
        "mechanism_of_action": "Inhibits both topoisomerase II (DNA gyrase) and topoisomerase IV, resulting in rapid bacterial DNA fragmentation and cell death.",
        "pharmacodynamics": "High potency against Streptococcus pneumoniae (including penicillin-resistant strains), Haemophilus influenzae, and atypical pathogens.",
        "absorption": "Rapidly absorbed; peak plasma concentration within 0.5 to 2 hours.",
        "distribution": "Excellent penetration into lung parenchyma and bronchial mucosa; 55-73% bound to plasma proteins.",
        "metabolism": "Undergoes limited hepatic metabolism; not extensively metabolized by cytochrome P450 enzymes.",
        "excretion": "Approximately 36% eliminated in urine and 61% in faeces as unchanged drug and metabolites.",
        "bioavailability": "Approximately 71%",
        "half_life": "7 hours",
        "protein_binding": "55% to 73%",
        "onset": "1 hour",
        "duration": "24 hours",
        "indications": ["Acute bacterial exacerbation of chronic bronchitis (AECB)", "Mild to moderate community-acquired pneumonia (CAP)"],
        "contraindications": ["Hypersensitivity to fluoroquinolones", "History of quinolone-associated tendinopathy", "Myasthenia gravis"],
        "warnings": ["Maculopapular rash occurs more frequently, particularly in females under 40 and with therapy exceeding 7 days", "Tendinitis and tendon rupture", "QT prolongation"],
        "common_adverse_effects": ["Diarrhoea", "Rash (erythematous/maculopapular)", "Nausea", "Headache", "Abdominal pain"],
        "serious_adverse_effects": ["Achilles tendon rupture", "Severe cutaneous adverse reactions", "QTc prolongation", "Clostridioides difficile colitis"],
        "drug_interactions": ["Antacids containing magnesium/aluminum, iron, sucralfate (take gemifloxacin 2 hours before or 3 hours after)", "Class IA and III antiarrhythmics", "Probenecid (increases AUC)"],
        "monitoring": ["Skin inspection for rash (discontinue if rash develops)", "Tendon pain or swelling", "Renal function"],
        "pregnancy": "Avoid in pregnancy; potential arthropathy in weight-bearing joints.",
        "lactation": "Excreted in breast milk; avoid use during lactation.",
        "pediatric": "Contraindicated in children under 18 years of age.",
        "geriatric": "No dose adjustment based on age alone; monitor renal function.",
        "renal": "If CrCl ≤ 40 mL/min, reduce dose to 160 mg every 24 hours.",
        "hepatic": "No dose adjustment required in mild to moderate hepatic impairment.",
        "advantages": ["High potency against multi-drug resistant S. pneumoniae", "Short 5-day course effective for AECB"],
        "disadvantages": ["Higher rash incidence compared to other fluoroquinolones", "Standard fluoroquinolone class side effects"],
        "key_points": ["Limit treatment duration to 5-7 days to minimize rash incidence", "Once daily 320 mg tablet"],
        "memory_trick": "GEMI-floxacin: GEM for the lungs, but watch for rash in 5 days.",
        "key_suffix": "-floxacin",
        "pronunciation_en": "jem-i-FLOX-a-sin",
        "pronunciation_hi": "जेमी-फ़्लोक्सा-सिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "teicoplanin",
        "generic_name": "Teicoplanin",
        "display_name": "Teicoplanin",
        "active_ingredient": "Teicoplanin",
        "salt": "Teicoplanin",
        "category": "Antibiotics",
        "description": "A glycopeptide antibiotic related to vancomycin with lower nephrotoxicity and red-man syndrome rates, administered once daily or via intramuscular injection for serious Gram-positive infections.",
        "strengths": ["200 mg vial", "400 mg vial"],
        "dosage_forms": ["Powder for Solution for Injection/Infusion"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Inhibits cell wall peptidoglycan synthesis by binding tightly to the D-alanyl-D-alanine terminus of cell wall precursor pentapeptides, preventing polymerization.",
        "pharmacodynamics": "Bactericidal against methicillin-resistant Staphylococcus aureus (MRSA), enterococci, and Streptococcus species; lacks activity against Gram-negative organisms.",
        "absorption": "Not absorbed orally (oral use restricted to C. difficile enterocolitis); 100% bioavailable after IM or IV administration.",
        "distribution": "Distributes well into lung tissue, synovial fluid, and bone; 90-95% bound to plasma proteins; prolonged elimination half-life.",
        "metabolism": "Minimal hepatic metabolism (<3%); does not undergo significant biotransformation.",
        "excretion": "Approximately 80% eliminated unchanged in urine via glomerular filtration.",
        "bioavailability": "90% after intramuscular injection; 100% IV",
        "half_life": "100 to 170 hours (very long elimination half-life)",
        "protein_binding": "90% to 95%",
        "onset": "Loading doses required over first 48 hours to reach target therapeutic trough levels (>15-20 mcg/mL)",
        "duration": "24 hours (once-daily maintenance after loading)",
        "indications": ["Methicillin-resistant Staphylococcus aureus (MRSA) bacteremia and endocarditis", "Complicated bone and joint infections (osteomyelitis)", "Complicated skin and soft tissue infections", "Hospital-acquired pneumonia due to MRSA", "Oral therapy for Clostridioides difficile colitis (second-line)"],
        "contraindications": ["Hypersensitivity to teicoplanin or glycopeptides"],
        "warnings": ["Loading doses are essential to achieve therapeutic trough levels rapidly", "Ototoxicity and nephrotoxicity, particularly when combined with aminoglycosides", "Cross-reactivity in vancomycin-allergic patients is possible though low"],
        "common_adverse_effects": ["Rash", "Local pain at intramuscular injection site", "Fever", "Mild transient serum creatinine rise"],
        "serious_adverse_effects": ["Ototoxicity (tinnitus, high-frequency hearing loss)", "Nephrotoxicity / acute kidney injury", "Thrombocytopenia and leukopenia", "Red man-like syndrome (infrequent)"],
        "drug_interactions": ["Aminoglycosides, amphotericin B, colistin (additive nephrotoxicity and ototoxicity)", "Loop diuretics (additive ototoxicity)", "Ciclosporin"],
        "monitoring": ["Trough serum levels (target >15 mcg/mL for uncomplicated, >20-30 mcg/mL for endocarditis/osteomyelitis)", "Renal function (BUN/creatinine)", "Audiometry in prolonged courses"],
        "pregnancy": "Use in pregnancy only if the potential benefit outweighs the risk of fetal ototoxicity.",
        "lactation": "Excretion in human milk is unknown; use with caution.",
        "pediatric": "Approved for neonates and children; loading dose based on age and weight.",
        "geriatric": "Renal clearance decreases with age; adjust maintenance dose based on creatinine clearance.",
        "renal": "Dose adjustment required after day 4: if CrCl 30-80 mL/min, halve maintenance dose; if CrCl < 30 mL/min, give maintenance dose every third day.",
        "hepatic": "No dose adjustment required.",
        "advantages": ["Can be administered intramuscularly as well as IV bolus", "Significantly lower incidence of nephrotoxicity and red-man syndrome than vancomycin", "Once-daily maintenance dosing"],
        "disadvantages": ["Long half-life means slow correction if toxicity develops", "Requires multiple loading doses in first 48 hours to achieve therapeutic levels"],
        "key_points": ["Three loading doses (every 12 hours) are crucial before switching to once-daily maintenance", "Can be given by direct IV injection over 5 minutes or IM injection"],
        "memory_trick": "TEICO-planin: Takes Easier Injection (IM allowed, no slow infusion needed), Calmer than vancomycin.",
        "key_suffix": "-planin",
        "pronunciation_en": "tye-koe-PLAN-in",
        "pronunciation_hi": "टाइको-प्लानिन",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefotaxime",
        "generic_name": "Cefotaxime",
        "display_name": "Cefotaxime",
        "active_ingredient": "Cefotaxime sodium",
        "salt": "Cefotaxime sodium",
        "category": "Antibiotics",
        "description": "A parenteral third-generation cephalosporin with excellent cerebrospinal fluid penetration, widely used for neonatal sepsis, bacterial meningitis, and serious systemic infections.",
        "strengths": ["250 mg", "500 mg", "1 g", "2 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Binds to penicillin-binding proteins (PBPs), inhibiting bacterial peptidoglycan cell wall synthesis, resulting in cell wall lysis and bacterial death.",
        "pharmacodynamics": "Potent bactericidal activity against Streptococcus pneumoniae, Neisseria meningitidis, Haemophilus influenzae, and enteric Gram-negative bacilli; active metabolite desacetylcefotaxime acts synergistically.",
        "absorption": "Not absorbed orally; 100% bioavailable upon IV injection; peak levels within 30 minutes after IM.",
        "distribution": "Excellent penetration into CSF (inflamed meninges), pleural, peritoneal, and synovial fluid; 30-50% bound to plasma proteins.",
        "metabolism": "Partially metabolized in the liver to desacetylcefotaxime, which possesses significant intrinsic antibacterial activity and synergy.",
        "excretion": "Approximately 60% excreted in urine unchanged, and 20% as active desacetyl metabolite.",
        "bioavailability": "100% (parenteral)",
        "half_life": "1 to 1.5 hours for parent drug; 1.5 hours for desacetyl metabolite",
        "protein_binding": "30% to 50%",
        "onset": "Immediate (IV)",
        "duration": "6 to 8 hours",
        "indications": ["Acute bacterial meningitis (especially in neonates and young infants)", "Neonatal sepsis", "Community-acquired and hospital-acquired pneumonia", "Spontaneous bacterial peritonitis (SBP)", "Complicated urinary tract infections and intra-abdominal sepsis"],
        "contraindications": ["Hypersensitivity to cefotaxime or other cephalosporins", "History of severe immediate anaphylaxis to penicillins"],
        "warnings": ["Dose reduction in renal failure to prevent neurotoxicity and encephalopathy", "Pseudomembranous colitis risk", "Safe in neonates compared to ceftriaxone (does not cause biliary sludging or kernicterus)"],
        "common_adverse_effects": ["Phlebitis at IV site", "Diarrhoea", "Rash", "Nausea", "Eosinophilia"],
        "serious_adverse_effects": ["Clostridioides difficile colitis", "Anaphylaxis", "Neutropenia and agranulocytosis (prolonged therapy)", "Neurotoxicity / encephalopathy in renal failure"],
        "drug_interactions": ["Aminoglycosides (additive nephrotoxicity)", "Probenecid (decreases renal tubular secretion)", "Loop diuretics"],
        "monitoring": ["Renal function", "Complete blood count in courses exceeding 10 days", "Neurological status in renal insufficiency"],
        "pregnancy": "Category B; safe and widely used during pregnancy.",
        "lactation": "Excreted in low concentrations in breast milk; compatible with breastfeeding.",
        "pediatric": "Preferred third-generation cephalosporin in neonates under 28 days of life (avoids kernicterus associated with ceftriaxone).",
        "geriatric": "Assess renal clearance; adjust dosing interval in renal impairment.",
        "renal": "If CrCl < 20 mL/min, reduce maintenance dose by 50% or extend interval to every 12 hours.",
        "hepatic": "No major dosage adjustment required.",
        "advantages": ["Preferred cephalosporin in neonates because it does not displace bilirubin from albumin (no kernicterus risk)", "Excellent CSF penetration for meningitis", "Active metabolite acts synergistically"],
        "disadvantages": ["Requires dosing every 6-8 hours (shorter half-life than ceftriaxone)", "Parenteral only"],
        "key_points": ["First-choice 3rd-generation cephalosporin in neonates (safe from kernicterus)", "Administered every 6 to 8 hours for meningitis"],
        "memory_trick": "CEFO-TAX-ime: Safe TAX for neonates (avoids ceftriaxone bilirubin displacement).",
        "key_suffix": "-taxime",
        "pronunciation_en": "sef-oh-TAX-eem",
        "pronunciation_hi": "सेफ़ो-टैक्सिम",
        "status": "active",
        "verification_status": "verified"
    },
    {
        "slug": "cefepime",
        "generic_name": "Cefepime",
        "display_name": "Cefepime",
        "active_ingredient": "Cefepime hydrochloride",
        "salt": "Cefepime hydrochloride",
        "category": "Antibiotics",
        "description": "A fourth-generation parenteral cephalosporin with zwitterionic structure providing rapid penetration across outer bacterial membranes, highly active against Pseudomonas and Enterobacteriaceae.",
        "strengths": ["500 mg", "1 g", "2 g vial"],
        "dosage_forms": ["Powder for Injection"],
        "routes": ["Intravenous", "Intramuscular"],
        "mechanism_of_action": "Binds to multiple penicillin-binding proteins (PBP2, PBP3, PBP1a/1b) inhibiting peptidoglycan synthesis; zwitterionic charge allows rapid diffusion through outer membrane porins.",
        "pharmacodynamics": "Bactericidal activity against Gram-positive cocci (MSSA, Streptococcus) and Gram-negative bacilli (Pseudomonas aeruginosa, Enterobacter cloacae, Citrobacter); resists AmpC chromosomal beta-lactamases.",
        "absorption": "100% bioavailable intravenously; rapid absorption following IM administration.",
        "distribution": "Widely distributed into lung, peritoneal fluid, bile, and inflamed meninges; approximately 20% bound to plasma proteins.",
        "metabolism": "Minimal hepatic metabolism (<10%); excreted primarily as parent drug.",
        "excretion": "Approximately 85% eliminated unchanged in urine via glomerular filtration.",
        "bioavailability": "100% (IV)",
        "half_life": "2 hours (prolonged in renal failure)",
        "protein_binding": "20%",
        "onset": "Immediate upon IV infusion",
        "duration": "8 to 12 hours",
        "indications": ["Empiric therapy for febrile neutropenia in haematology-oncology patients", "Hospital-acquired and ventilator-associated pneumonia (HAP/VAP)", "Complicated intra-abdominal infections (with metronidazole)", "Complicated urinary tract infections and pyelonephritis", "Severe Pseudomonas aeruginosa infections"],
        "contraindications": ["Hypersensitivity to cefepime, cephalosporins, or severe beta-lactam allergy"],
        "warnings": ["Neurotoxicity (encephalopathy, myoclonus, seizures, non-convulsive status epilepticus) occurs if dose is not properly adjusted for renal dysfunction", "Clostridioides difficile colitis", "Positive direct Coombs test"],
        "common_adverse_effects": ["Phlebitis", "Diarrhoea", "Rash", "Nausea", "Headache"],
        "serious_adverse_effects": ["Cefepime-induced neurotoxicity / encephalopathy", "Non-convulsive status epilepticus", "Pseudomembranous colitis", "Anaphylaxis", "Agranulocytosis"],
        "drug_interactions": ["Aminoglycosides (additive nephrotoxicity)", "Probenecid (decreased renal clearance)", "Other nephrotoxic drugs"],
        "monitoring": ["Renal function (mandatory to adjust dosing and prevent neurotoxicity)", "Mental status and neurological checks", "Complete blood counts in extended courses"],
        "pregnancy": "Category B; use during pregnancy only if clearly needed.",
        "lactation": "Excreted in human milk in low concentrations; compatible with caution.",
        "pediatric": "Approved for pediatric febrile neutropenia and severe infections (50 mg/kg every 8-12h).",
        "geriatric": "Elderly patients frequently have unrecognized renal insufficiency; adjust dose to avoid encephalopathy.",
        "renal": "Strict dose reduction mandatory: if CrCl 30-50 mL/min, give 2g q12h; if CrCl 11-29 mL/min, give 2g q24h; if CrCl < 11 mL/min, give 1g q24h.",
        "hepatic": "No dosage adjustment necessary.",
        "advantages": ["Dual action against Pseudomonas aeruginosa and AmpC-producing Enterobacteriaceae", "Low affinity for chromosomal AmpC beta-lactamases", "Cornerstone empiric agent for febrile neutropenia"],
        "disadvantages": ["High risk of encephalopathy and myoclonus in unadjusted renal impairment", "Inactive against MRSA, ESBLs, and Enterococci"],
        "key_points": ["Always check renal function: failure to reduce dose causes confusion, myoclonus, and seizures", "Core agent for febrile neutropenia"],
        "memory_trick": "CEFE-pime: 4th-gen, Febrile neutropenia, Encephalopathy risk if renal dose forgotten.",
        "key_suffix": "-pime",
        "pronunciation_en": "SEF-e-peem",
        "pronunciation_hi": "सेफ़े-पीम",
        "status": "active",
        "verification_status": "verified"
    }
]

print(f"Generated base part1: {len(PART1)} existing + {len(REMAINING_ANTIBACTERIALS)} new = {len(PART1) + len(REMAINING_ANTIBACTERIALS)}")
