#!/usr/bin/env python3
"""
MediDex Grow: Part A Data Generator
Covers:
- Remaining Antifungals, Antivirals, Antiparasitics (20 medicines)
- Cardiovascular & Antihypertensives (30 medicines)
"""

def m(slug, generic, display, active, salt, cat, desc,
      strengths, forms, routes, moa, pd,
      abs_pk, dist_pk, met_pk, exc_pk, bio, hl, pb, onset, dur,
      ind, contra, warn, cae, sae, interact, mon,
      preg, lact, ped, ger, ren, hep,
      adv, disadv, kpts, trick, suffix, pen, phi):
    return {
        "slug": slug, "generic_name": generic, "display_name": display,
        "active_ingredient": active, "salt": salt, "category": cat, "description": desc,
        "strengths": strengths, "dosage_forms": forms, "routes": routes,
        "mechanism_of_action": moa, "pharmacodynamics": pd,
        "absorption": abs_pk, "distribution": dist_pk, "metabolism": met_pk, "excretion": exc_pk,
        "bioavailability": bio, "half_life": hl, "protein_binding": pb,
        "onset": onset, "duration": dur,
        "indications": ind, "contraindications": contra, "warnings": warn,
        "common_adverse_effects": cae, "serious_adverse_effects": sae,
        "drug_interactions": interact, "monitoring": mon,
        "pregnancy": preg, "lactation": lact, "pediatric": ped, "geriatric": ger,
        "renal": ren, "hepatic": hep,
        "advantages": adv, "disadvantages": disadv, "key_points": kpts,
        "memory_trick": trick, "key_suffix": suffix,
        "pronunciation_en": pen, "pronunciation_hi": phi,
        "status": "active", "verification_status": "verified"
    }

MEDS_A = [
    # 1. isavuconazole
    m("isavuconazole", "Isavuconazole", "Isavuconazole (Isavuconazonium Sulfate)",
      "Isavuconazonium sulfate", "Isavuconazonium sulfate", "Antifungals",
      "A novel water-soluble triazole prodrug with broad-spectrum activity against invasive aspergillosis and mucormycosis, notable for causing QTc shortening rather than prolongation.",
      ["100 mg", "200 mg vial"], ["Capsule", "Powder for Solution for Infusion"], ["Oral", "Intravenous"],
      "Rapidly hydrolyzed by plasma esterases to active isavuconazole, which inhibits fungal 14-alpha-lanosterol demethylase, blocking ergosterol synthesis.",
      "Fungicidal against Aspergillus species and Mucorales; fungistatic against Candida and Cryptococcus.",
      "Near complete oral bioavailability (approx. 98%); unaffected by food or gastric pH.",
      "Very high volume of distribution (approx. 450 L); >99% bound to plasma albumin.",
      "Extensively metabolized by CYP3A4, CYP3A5, and subsequently glucuronidated.",
      "Excreted in faeces (approx. 46%) and urine (approx. 46%) predominantly as metabolites; <1% unchanged in urine.",
      "98%", "130 hours (long half-life allows once-daily maintenance)", ">99%", "Loading doses required over first 48 hours", "24 hours",
      ["Invasive aspergillosis", "Invasive mucormycosis (zygomycosis)", "Candidemia in refractory patients"],
      ["Hypersensitivity to isavuconazole", "Familial short QT syndrome", "Concurrent administration of strong CYP3A4 inducers/inhibitors"],
      ["Shortens the QTc interval (dose-dependent QTc shortening, unique among azoles)", "Hepatotoxicity: monitor LFTs", "Infusion-related hypersensitivity"],
      ["Nausea", "Vomiting", "Diarrhoea", "Headache", "Elevated liver enzymes", "Peripheral oedema"],
      ["Severe hepatotoxicity / hepatic failure", "Anaphylaxis", "Severe cutaneous adverse reactions (SCAR)"],
      ["CYP3A4 inducers (rifampin, carbamazepine - reduce levels drastically)", "Ketoconazole / high-dose CYP3A4 inhibitors", "Increases tacrolimus, cyclosporine, sirolimus exposure"],
      ["Liver function tests (baseline and weekly)", "ECG (assess QTc shortening)", "Therapeutic drug monitoring in complex cases"],
      "Avoid in pregnancy; embryotoxic in animal models.", "Excreted in milk; avoid breastfeeding.",
      "Approved for pediatric patients 1 year and older for aspergillosis and mucormycosis.",
      "No dosage adjustment required based on age.",
      "No dosage adjustment needed in renal impairment (does not contain cyclodextrin).",
      "No adjustment needed in mild to moderate hepatic impairment (Child-Pugh A and B); halve maintenance in severe.",
      ["Does not contain nephrotoxic cyclodextrin in IV formulation (safe in renal failure)", "Shortens rather than prolongs QTc interval", "Once-daily maintenance with 98% oral bioavailability"],
      ["Extremely high cost", "Long half-life means slow drug clearance if toxicity occurs"],
      ["First-line option for mucormycosis alongside amphotericin B", "Safe in renal impairment because IV formulation has no cyclodextrin"],
      "ISA-VU-conazole: Infuses Safely in Acute kidney failure (no cyclodextrin); Shortens QT.", "-conazole", "eye-sa-voo-KON-a-zole", "आइसवुकोना-ज़ोल"),

    # 2. anidulafungin
    m("anidulafungin", "Anidulafungin", "Anidulafungin",
      "Anidulafungin", "Anidulafungin", "Antifungals",
      "A semi-synthetic echinocandin antifungal that undergoes non-enzymatic chemical degradation, making it completely independent of renal and hepatic metabolism.",
      ["100 mg vial"], ["Powder for Solution for Infusion"], ["Intravenous"],
      "Non-competitively inhibits 1,3-beta-D-glucan synthase, halting fungal cell wall synthesis and causing osmotic lysis.",
      "Concentration-dependent fungicidal activity against Candida species (including C. glabrata and C. krusei); fungistatic against Aspergillus.",
      "Administered exclusively by intravenous infusion; 100% bioavailable.",
      "Extensively distributed into tissues; minimal CNS/ocular penetration; 84% bound to plasma proteins.",
      "Undergoes slow non-enzymatic chemical degradation at physiological temperature and pH into an open-ring peptide; not metabolized by hepatic enzymes.",
      "Less than 1% excreted in urine; degradation products excreted in faeces via biliary elimination.",
      "100% (IV)", "40 to 50 hours (terminal half-life)", "84%", "200 mg loading dose on day 1 achieves steady state rapidly", "24 hours",
      ["Invasive candidiasis and candidemia in adult patients", "Esophageal candidiasis", "Intra-abdominal and peritoneal Candida infections"],
      ["Hypersensitivity to anidulafungin or echinocandins"],
      ["Histamine-mediated infusion reactions (flush, pruritus, dyspnea - infuse at <1.1 mg/min)", "Hepatic effects (monitor liver transaminases)"],
      ["Phlebitis", "Hypokalemia", "Nausea", "Diarrhoea", "Headache", "Elevated transaminases"],
      ["Severe anaphylaxis / shock", "Acute hepatic dysfunction", "Coagulopathy"],
      ["Remarkably free of drug-drug interactions; no interaction with cyclosporine, tacrolimus, or CYP substrates"],
      ["Liver function tests", "Serum potassium", "Injection site checks"],
      "Category C; use during pregnancy only if clearly needed.", "Excreted in animal milk; use caution.",
      "Safety and efficacy in pediatric patients established for candidemia (dosed by weight).",
      "No dosage adjustment required based on age.",
      "Zero dose adjustment in any degree of renal impairment or dialysis (non-enzymatic degradation).",
      "Zero dose adjustment in any degree of hepatic impairment (non-hepatic chemical clearance).",
      ["Zero hepatic or renal clearance adjustments needed; uniquely cleared by chemical degradation", "No significant cytochrome P450 or drug interactions"],
      ["Parenteral only", "Inactive against Cryptococcus, Mucorales, and Fusarium"],
      ["Drug of choice for candidemia in severe liver or renal failure due to chemical clearance", "Requires 200 mg loading dose on Day 1, then 100 mg daily"],
      "ANIDULA-fungin: ANY-organ friendly; Non-enzymatic Degradation In Liver-less, Kidney-less clearance.", "-fungin", "a-nye-doo-la-FUN-jin", "अनिडुला-फ़ंजिन"),

    # 3. sertaconazole
    m("sertaconazole", "Sertaconazole", "Sertaconazole Nitrate",
      "Sertaconazole nitrate", "Sertaconazole nitrate", "Antifungals",
      "A topical broad-spectrum imidazole antifungal containing a unique benzothiophene ring, providing dual fungistatic and direct fungicidal action with potent anti-inflammatory and antipruritic properties.",
      ["2% cream", "2% lotion", "2% dust powder", "500 mg vaginal suppository"], ["Topical Cream", "Topical Lotion", "Topical Powder", "Vaginal Tablet"], ["Topical", "Vaginal"],
      "Dual mechanism: at low concentrations, inhibits 14-alpha-demethylase blocking ergosterol synthesis; at higher concentrations, benzothiophene ring directly inserts into fungal plasma membrane, forming pores and causing immediate cell death.",
      "Broad fungicidal activity against Trichophyton rubrum, T. mentagrophytes, Candida albicans, and Malassezia furfur; suppresses inflammatory cytokines (TNF-alpha).",
      "Negligible systemic absorption after topical or vaginal administration.",
      "Remains concentrated within the stratum corneum with cutaneous residence time exceeding 48 hours.",
      "Minimal systemically absorbed drug is metabolized by hepatic oxidation.",
      "Excreted in trace amounts in faeces and urine.",
      "<1% systemic bioavailability", "Cutaneous retention half-life >48 hours", ">99%", "Rapid reduction of pruritus within 48 to 72 hours", "24 hours (applied once or twice daily)",
      ["Tinea pedis (athlete's foot)", "Tinea cruris (jock itch)", "Tinea corporis (ringworm)", "Tinea versicolor", "Vulvovaginal candidiasis (500 mg single-dose ovule)"],
      ["Hypersensitivity to sertaconazole, imidazole antifungals, or formulation components"],
      ["For topical or vaginal use only; avoid contact with eyes", "Discontinue if contact dermatitis or sensitization develops"],
      ["Application site erythema", "Mild burning sensation", "Dry skin", "Pruritus"],
      ["Severe allergic contact dermatitis", "Cutaneous blistering / vesiculation"],
      ["No clinically significant systemic drug interactions due to negligible absorption"],
      ["Clinical evaluation of fungal lesions and relief of itching"],
      "Category C; negligible absorption, but use with caution in pregnancy.", "Safe on intact skin; avoid application to nipples before breastfeeding.",
      "Approved for pediatric patients 12 years and older.", "No dose adjustment required.",
      "No dosage adjustment required (topical).", "No dosage adjustment required (topical).",
      ["Dual fungicidal mechanism via benzothiophene ring overcomes resistance", "Potent intrinsic anti-inflammatory and antipruritic effect provides rapid symptom relief", "High lipophilicity provides 48-hour cutaneous reservoir"],
      ["Topical formulation only; ineffective for systemic or deep onychomycosis", "Higher cost than generic clotrimazole"],
      ["Dual-action imidazole with built-in anti-inflammatory property", "Single-dose 500 mg ovule highly effective for vaginal candidiasis"],
      "SERTA-conazole: SOOTHES (anti-inflammatory) and STRIKES (fungicidal benzothiophene).", "-conazole", "ser-ta-KON-a-zole", "सर्टाकॉना-ज़ोल"),

    # 4. amorolfine
    m("amorolfine", "Amorolfine", "Amorolfine Hydrochloride",
      "Amorolfine hydrochloride", "Amorolfine hydrochloride", "Antifungals",
      "A morpholine antifungal nail lacquer and cream with a unique dual-enzyme inhibition mechanism in the ergosterol pathway, applied once or twice weekly for onychomycosis.",
      ["5% nail lacquer", "0.25% cream"], ["Nail Lacquer", "Topical Cream"], ["Topical"],
      "Inhibits two separate fungal enzymes in the ergosterol biosynthesis pathway: delta-14-reductase and delta-7,delta-8-isomerase, depleting ergosterol and causing accumulation of toxic ignosterol.",
      "Broad-spectrum fungicidal and fungistatic action against dermatophytes (Trichophyton, Microsporum), yeasts (Candida), and nondermatophyte moulds causing nail infections.",
      "Nail lacquer forms a non-water-soluble film that penetrates nail plate deeply; systemic absorption is negligible (<1%).",
      "Concentrates in the nail plate and underlying nail bed; remains active in nail for up to 14 days after application.",
      "Trace amounts absorbed systemically are metabolized into polar metabolites.",
      "Eliminated in trace amounts via urine and faeces.",
      "<1%", "Retention in nail bed >14 days", "High locally", "Nail cure requires 6 months (fingernails) to 9-12 months (toenails)", "7 days (applied once weekly)",
      ["Distal and lateral subungual onychomycosis (without matrix involvement)", "Tinea pedis, tinea cruris, and tinea corporis (cream formulation)"],
      ["Hypersensitivity to amorolfine or lacquer ingredients", "Onychomycosis involving the nail matrix (lunula) requires oral therapy"],
      ["Nails should be filed down and cleansed with alcohol swabs before each application", "Avoid cosmetic nail varnish during treatment", "External nail use only"],
      ["Mild periungual burning", "Transient nail discoloration", "Dry brittle nails", "Erythema"],
      ["Severe contact dermatitis / paronychia (rare)"],
      ["No systemic drug interactions reported due to minimal absorption"],
      ["Monthly nail clipping and monitoring of clear nail growth from the proximal nail fold"],
      "Avoid during pregnancy due to lack of adequate human data.", "Avoid applying to breast area; use with caution.",
      "Not recommended for children under 18 years due to limited safety data.", "No dose adjustment required.",
      "No dosage adjustment required.", "No dosage adjustment required.",
      ["Once-weekly application improves patient compliance drastically over daily lacquers", "Dual-enzyme inhibition produces potent fungicidal action in the nail bed", "Zero systemic hepatotoxicity risk compared to oral terbinafine"],
      ["Treatment must be continued for 6 to 12 months until healthy nail regrows", "Ineffective if nail matrix/lunula is involved (>50% nail involvement)"],
      ["Apply once or twice weekly to affected fingernails (6 months) or toenails (9-12 months)", "Always file down the thickened nail surface before reapplying"],
      "AMOR-olfine: A Month of Regular filing Overcomes Rigid fungal nails.", "-olfine", "a-MORE-ol-feen", "अमोरोल-फ़ीन"),

    # 5. griseofulvin
    m("griseofulvin", "Griseofulvin", "Griseofulvin",
      "Griseofulvin microsize", "Griseofulvin", "Antifungals",
      "An oral fungistatic antifungal that binds to fungal tubulin and concentrates in newly formed keratin, established as the gold standard for tinea capitis (scalp ringworm) in children.",
      ["125 mg", "250 mg", "500 mg", "125 mg/5 mL suspension"], ["Tablet", "Oral Suspension"], ["Oral"],
      "Binds to fungal tubulin and disrupts the mitotic spindle apparatus, arresting fungal cells in metaphase; also binds to human keratin, rendering newly formed hair, skin, and nails resistant to fungal invasion.",
      "Fungistatic against dermatophytes (Trichophyton, Microsporum, Epidermophyton); completely inactive against Candida, bacteria, and deep mycoses.",
      "Variable and erratic absorption; microsize formulations improve absorption; absorption is doubled when taken with a high-fat meal (milk, cheese, butter).",
      "Deposits preferentially in keratin precursor cells of the skin, hair shafts, and nails; binds firmly to keratin; 84% bound to plasma proteins.",
      "Extensively metabolized in the liver by 6-demethylation and glucuronidation to inactive 6-demethylgriseofulvin.",
      "Excreted in urine (<1% unchanged), faeces (approx. 36%), and perspiration.",
      "Approximately 50% fasting; significantly higher with fatty meals", "9 to 24 hours", "84%", "Requires weeks to months of continuous therapy as infected keratin is shed", "24 hours",
      ["Tinea capitis (scalp ringworm - gold standard therapy in children)", "Tinea barbae (beard infection)", "Extensive tinea corporis and cruris unresponsive to topical agents", "Tinea unguium (onychomycosis - alternative)"],
      ["Severe liver disease / hepatic failure", "Porphyria (induces ALA synthetase and exacerbates acute porphyria)", "Pregnancy (teratogenic / embryotoxic)"],
      ["Must be taken with fatty food to ensure adequate absorption", "Photosensitivity: advise sun protection", "Potential for Disulfiram-like ethanol reaction"],
      ["Headache (very common at treatment initiation)", "Nausea", "Vomiting", "Diarrhoea", "Photosensitivity rash"],
      ["Hepatotoxicity / cholestasis", "Severe cutaneous adverse reactions (SJS/TEN)", "Granulocytopenia / leukopenia", "Lupus-like syndrome"],
      ["Warfarin (griseofulvin induces CYP, decreasing anticoagulant effect)", "Oral contraceptives (decreased contraceptive efficacy; barrier methods required)", "Alcohol (flushing, tachycardia - disulfiram-like effect)", "Barbiturates (decrease griseofulvin absorption)"],
      ["Complete blood counts every 2 to 4 weeks", "Liver and renal function tests during prolonged therapy (>1 month)"],
      "Strictly contraindicated (Category X); teratogenic and aneuploidic; men must wait 6 months before fathering a child.",
      "Contraindicated during breastfeeding; excretion in human milk unknown.",
      "First-line drug of choice for pediatric tinea capitis (10-20 mg/kg/day for 6-8 weeks with milk).",
      "No primary age-related adjustment; assess hepatic function.",
      "No dosage adjustment required in mild to moderate renal disease.",
      "Strictly contraindicated in severe liver impairment; monitor LFTs.",
      ["Gold standard agent for tinea capitis with decades of proven pediatric safety", "Concentrates selectively into keratinizing hair follicles and nails"],
      ["Requires prolonged courses (6-8 weeks for scalp, 6-12 months for nails)", "Multiple drug interactions and teratogenicity risk"],
      ["Always take with whole milk or fatty food for absorption", "First-choice oral treatment for scalp ringworm in school children"],
      "GRISEO-fulvin: Grows Into hair/nails; Requires Ingestion with Fat; Stops Spindle.", "-fulvin", "gris-ee-oh-FUL-vin", "ग्रिसियो-फ़ल्विन"),

    # 6. flucytosine
    m("flucytosine", "Flucytosine (5-FC)", "Flucytosine",
      "Flucytosine (5-fluorocytosine)", "Flucytosine", "Antifungals",
      "A fluorinated pyrimidine antifungal that converts intracellularly to 5-fluorouracil, combined synergistically with amphotericin B for cryptococcal meningitis.",
      ["250 mg", "500 mg", "2.5 g/250 mL IV infusion"], ["Capsule", "Solution for Infusion"], ["Oral", "Intravenous"],
      "Transported into fungal cells by cytosine permease and deaminated by fungal cytosine deaminase to 5-fluorouracil (5-FU); 5-FU inhibits thymidylate synthase and incorporates into fungal RNA, terminating protein and DNA synthesis.",
      "Concentration-dependent fungicidal synergy with amphotericin B against Cryptococcus neoformans and Candida species; never use as monotherapy due to rapid resistance emergence.",
      "Rapidly and well absorbed from GI tract (75-90% bioavailability); peak levels in 1 to 2 hours.",
      "Exceptional tissue penetration; penetrates readily into CSF (CSF levels 70-85% of serum levels), aqueous humor, and joints; <4% protein bound.",
      "Minimal hepatic metabolism (<5%); eliminated virtually entirely as active drug.",
      "Excreted predominantly unchanged in urine via glomerular filtration (>90% within 24 hours).",
      "75% to 90%", "3 to 5 hours (prolonged to 25-100 hours in severe renal failure)", "<4%", "1 to 2 hours", "6 hours (administered every 6 hours)",
      ["Cryptococcal meningitis in HIV/AIDS patients (induction phase combined with amphotericin B)", "Severe systemic candidiasis / endocarditis (in combination)", "Chromoblastomycosis"],
      ["Hypersensitivity to flucytosine", "Known complete dihydropyrimidine dehydrogenase (DPD) enzyme deficiency"],
      ["Black box warning: Bone marrow depression (leukopenia, thrombocytopenia, aplastic anaemia) occurs with peak levels >100 mcg/mL", "Strict therapeutic drug monitoring required (target peak 50 to 100 mcg/mL)", "Never administer as monotherapy (resistance develops within days)"],
      ["Nausea", "Vomiting", "Diarrhoea", "Abdominal pain", "Rash"],
      ["Dose-dependent bone marrow suppression (leukopenia, agranulocytosis, thrombocytopenia)", "Hepatotoxicity", "Enterocolitis / bowel perforation"],
      ["Amphotericin B (synergistic, but amphotericin nephrotoxicity causes flucytosine accumulation)", "Zidovudine / ganciclovir (additive bone marrow suppression)"],
      ["Therapeutic drug monitoring: peak level measured 2 hours post-dose (maintain between 50-100 mcg/mL)", "Complete blood counts (platelets, WBC) twice weekly", "Renal function (BUN/creatinine) twice weekly"],
      "Category C; teratogenic in animal studies; use in life-threatening cryptococcal meningitis when benefits outweigh fetal risks.",
      "Excretion in human milk unknown; discontinue breastfeeding.",
      "Weight-based dosing in pediatric cryptococcal infections (100 mg/kg/day in 4 divided doses); monitor levels closely.",
      "Renal clearance decreases with age; high risk of bone marrow suppression; adjust dose strictly.",
      "Strict dose reduction mandatory: if CrCl 20-40 mL/min, dose q12h; if CrCl 10-20 mL/min, dose q24h; if CrCl < 10 mL/min, dose q48h or guide by levels.",
      "Use with caution; monitor liver enzymes.",
      ["Synergistic standard of care with amphotericin B for cryptococcal meningitis, significantly reducing mortality", "Superb penetration into cerebrospinal fluid and brain tissue"],
      ["Severe myelosuppression if serum peak exceeds 100 mcg/mL", "Rapid emergence of resistance if used as single agent"],
      ["Always combine with amphotericin B; never use alone", "Check blood levels to prevent toxic bone marrow suppression"],
      "FLU-CYTOSINE: Fungal Cytosine Deaminase converts to 5-FU; Fatal to marrow if peak >100.", "-cytosine", "floo-SYE-toe-seen", "फ़्लू-साइटोसीन"),

    # 7. remdesivir
    m("remdesivir", "Remdesivir", "Remdesivir",
      "Remdesivir", "Remdesivir", "Antivirals",
      "A broad-spectrum monophosphoramidate adenosine nucleotide prodrug that halts viral RNA synthesis, used intravenously for COVID-19 in hospitalized and high-risk patients.",
      ["100 mg vial"], ["Lyophilized Powder for Injection", "Concentrate for Solution for Infusion"], ["Intravenous"],
      "Metabolized intracellularly into active remdesivir triphosphate (GS-443902), which competes with ATP for incorporation by viral RNA-dependent RNA polymerase (RdRp), causing delayed chain termination at position i+3.",
      "Potent antiviral activity against Coronaviridae (SARS-CoV-2, MERS-CoV), Filoviridae (Ebola), and Paramyxoviridae.",
      "Administered exclusively by intravenous infusion over 30 to 120 minutes.",
      "Widely distributed into tissues; 88-93% bound to human plasma proteins.",
      "Extensively metabolized by esterases and phosphoamidases intracellularly; minor CYP3A4 metabolism.",
      "Excreted in urine (approx. 74%, mostly as metabolite GS-441524) and faeces (approx. 18%).",
      "100% (IV)", "Parent drug 1 hour; active intracellular triphosphate metabolite half-life 20 to 25 hours", "88% to 93%", "Immediate upon IV infusion", "24 hours",
      ["Hospitalized patients with moderate to severe COVID-19 requiring supplemental oxygen", "High-risk outpatients with mild-to-moderate COVID-19 within 7 days of symptom onset (3-day course)"],
      ["Hypersensitivity to remdesivir or formulation excipients (SBECD)"],
      ["Hepatotoxicity: monitor ALT/AST (discontinue if ALT increases to >10x ULN)", "Infusion-related reactions and anaphylaxis", "Renal evaluation: formulation contains sulfobutyl ether beta-cyclodextrin (SBECD)"],
      ["Nausea", "Elevated AST and ALT", "Headache", "Rash", "Prolonged prothrombin time"],
      ["Severe liver injury / transaminitis", "Anaphylactic shock / severe infusion reaction", "Sinus bradycardia / cardiac arrhythmias"],
      ["Chloroquine / hydroxychloroquine (antagonizes antiviral activity; co-administration not recommended)", "CYP3A4 inducers (rifampin - reduce remdesivir concentrations)"],
      ["Hepatic transaminases (ALT, AST) before initiation and daily during treatment", "Renal function tests (BUN / creatinine)", "Prothrombin time / INR"],
      "Use during pregnancy only if potential benefit justifies potential risk; reassuring safety registries in severe COVID-19.",
      "Excreted in low levels in breast milk; compatible with breastfeeding.",
      "Approved for pediatric patients 28 days of age and older weighing at least 3 kg.",
      "No dosage adjustment required based on age alone.",
      "Recent trial data confirms safety in patients with eGFR < 30 mL/min and on dialysis; monitor renal function.",
      "Do not initiate if ALT ≥ 5x ULN; discontinue if ALT ≥ 10x ULN or accompanied by signs of liver inflammation.",
      ["Proven reduction in time to clinical recovery in hospitalized COVID-19 patients", "Early 3-day outpatient administration reduces hospitalization by 87% in high-risk patients"],
      ["Parenteral IV only; no oral formulation", "Transient elevations in liver transaminases are frequent"],
      ["Initiate as early as possible in course of COVID-19 infection", "Standard course is 200 mg loading on day 1, followed by 100 mg daily for 5 days total"],
      "REM-desivir: RdRp Enzyme Mistake terminates viral RNA replication.", "-desivir", "rem-DES-i-veer", "रेमडे-सिविर"),

    # 8. molnupiravir
    m("molnupiravir", "Molnupiravir", "Molnupiravir",
      "Molnupiravir", "Molnupiravir", "Antivirals",
      "An oral ribonucleoside prodrug that induces viral error catastrophe through lethal mutagenesis in viral RNA, used for mild-to-moderate COVID-19 in high-risk outpatients.",
      ["200 mg"], ["Capsule"], ["Oral"],
      "Hydrolyzed in blood to N4-hydroxycytidine (NHC), phosphorylated intracellularly to NHC triphosphate, which is utilized by viral RdRp; mispairs with adenine and guanine, inducing massive catastrophic mutations during replication ('error catastrophe').",
      "Broad antiviral activity against SARS-CoV-2 and RNA respiratory viruses; prevents production of infectious viral progeny.",
      "Rapidly absorbed; peak plasma concentration of active NHC within 1.5 hours; food has minimal effect.",
      "Vd of NHC is approximately 142 L; negligible plasma protein binding (0%).",
      "Prodrug cleaved by host esterases to NHC; NHC metabolized by endogenous pyrimidine salvage pathways.",
      "Cleared predominantly through metabolic elimination via pyrimidine pathways; minimal renal excretion.",
      "Rapid systemic conversion to active NHC", "Parent drug 1 hour; active metabolite NHC approx. 3.3 hours (intracellular half-life longer)", "0%", "1 to 2 hours", "12 hours (dosed twice daily for 5 days)",
      ["Mild to moderate COVID-19 in adults with positive viral testing who are at high risk for progression to severe disease, when alternative approved options are unavailable"],
      ["Hypersensitivity to molnupiravir", "Pregnancy and lactation (contraindicated due to embryo-fetal mutagenic toxicity)"],
      ["Strictly contraindicated during pregnancy and breastfeeding", "Individuals of childbearing potential must use reliable contraception during and for 4 days after therapy; males must use contraception for 3 months after last dose", "Not authorized for use under 18 years of age due to potential bone and cartilage toxicity"],
      ["Diarrhoea", "Nausea", "Dizziness", "Headache"],
      ["Severe hypersensitivity reactions / angioedema", "Embryo-fetal toxicity"],
      ["No significant CYP-mediated drug interactions or P-glycoprotein interactions reported (major advantage over nirmatrelvir/ritonavir)"],
      ["Confirmation of negative pregnancy test before initiation in females of childbearing potential", "Clinical symptom tracking"],
      "Strictly contraindicated in pregnancy; causes fetal harm, anatomical malformations, and embryo-fetal lethality.",
      "Contraindicated during treatment and for 4 days after the final dose; discard pumped milk.",
      "Strictly contraindicated under 18 years of age (affects bone growth and growth plates).",
      "No dosage adjustment required based on age.",
      "No dosage adjustment required in any degree of renal impairment.",
      "No dosage adjustment required in hepatic impairment.",
      ["Zero cytochrome P450 drug interactions, making it ideal for patients taking complex cardiac or transplant medications where Paxlovid is contraindicated", "No dosage adjustment needed for renal or hepatic impairment"],
      ["Lower efficacy in preventing hospitalization compared to Paxlovid or Remdesivir", "Contraindicated in pregnancy, lactation, and children"],
      ["Take 800 mg (four 200 mg capsules) every 12 hours for exactly 5 days", "Start within 5 days of symptom onset"],
      "MOLNU-piravir: Mutagenic Overload Leads to Non-viable Unfunctional viral RNA.", "-piravir", "mol-noo-PEER-a-veer", "मोलनु-पिराविर"),

    # 9. nirmatrelvir
    m("nirmatrelvir", "Nirmatrelvir / Ritonavir", "Paxlovid (Nirmatrelvir + Ritonavir)",
      "Nirmatrelvir and ritonavir", "Nirmatrelvir and ritonavir", "Antivirals",
      "A peptidomimetic inhibitor of the SARS-CoV-2 main protease (Mpro / 3CLpro) boosted with ritonavir, reducing COVID-19 hospitalization and death by up to 89% in high-risk patients.",
      ["300 mg nirmatrelvir (two 150 mg tablets) + 100 mg ritonavir (one 100 mg tablet) per dose"], ["Tablet (Dose Pack)"], ["Oral"],
      "Nirmatrelvir reversible inhibits the SARS-CoV-2 main protease (Mpro/3CLpro), preventing processing of viral polyprotein precursors; low-dose ritonavir acts as a pharmacokinetic booster by inhibiting CYP3A4, sustaining therapeutic nirmatrelvir blood levels.",
      "Potent antiviral inhibition of SARS-CoV-2 replication across all variants of concern (Omicron, Delta, etc.).",
      "Rapidly absorbed; peak nirmatrelvir concentrations reached in 3 hours when co-administered with ritonavir; food slightly improves absorption.",
      "Nirmatrelvir Vd approx. 104 L; 69% bound to human plasma proteins; ritonavir 98-99% bound.",
      "Nirmatrelvir undergoes minor CYP3A4 metabolism; protected from metabolism by ritonavir co-administration.",
      "Nirmatrelvir excreted in urine (approx. 50%) and faeces (approx. 35%); ritonavir eliminated predominantly in faeces.",
      "High when boosted with ritonavir", "Nirmatrelvir approx. 6 hours; ritonavir 3 to 5 hours", "69%", "1 to 3 hours", "12 hours (dosed twice daily for 5 days)",
      ["Treatment of mild-to-moderate COVID-19 in adults and pediatric patients (12 years and older weighing at least 40 kg) at high risk for progression to severe disease"],
      ["Hypersensitivity to nirmatrelvir or ritonavir", "Concurrent use of drugs highly dependent on CYP3A4 for clearance whose elevated levels cause life-threatening reactions (amiodarone, simvastatin, rivaroxaban, alfuzosin, sildenafil for PAH)"],
      ["Massive list of clinically significant drug-drug interactions due to ritonavir's potent CYP3A4 inhibition; review all patient medications", "Dose reduction required in moderate renal impairment (eGFR 30-59 mL/min)", "Rebound COVID-19 symptoms or antigen positivity reported in small subset 2-8 days after completing course"],
      ["Dysgeusia (metallic / bitter taste in mouth - very common)", "Diarrhoea", "Headache", "Hypertension", "Myalgia"],
      ["Severe hypersensitivity / anaphylaxis", "Toxic epidermal necrolysis", "Hepatotoxicity / clinical jaundice"],
      ["Contraindicated with: carbamazepine, phenobarbital, phenytoin, rifampin, St. John's wort (inducers reduce nirmatrelvir efficacy)", "Drastically increases levels of: calcineurin inhibitors, statins, antiarrhythmics, DOACs, benzodiazepines, PDE5 inhibitors"],
      ["Medication reconciliation before prescribing", "Renal function (eGFR) to calibrate dose", "Blood pressure in hypertensive patients"],
      "Use during pregnancy only if potential benefit justifies potential risk; limited data available.",
      "Compatible with caution; consider withholding breastfeeding during 5-day course.",
      "Authorized for adolescents 12 years and older weighing ≥40 kg.",
      "No dose adjustment based on age alone; monitor drug interactions closely.",
      "If eGFR 30-59 mL/min, reduce dose to 150 mg nirmatrelvir + 100 mg ritonavir twice daily; contraindicated if eGFR < 30 mL/min.",
      "No dosage adjustment in mild to moderate hepatic impairment; contraindicated in severe hepatic impairment (Child-Pugh C).",
      ["Reduces hospitalization and death by nearly 89% in unvaccinated high-risk patients", "Convenient 5-day oral outpatient regimen"],
      ["Extreme potential for drug-drug interactions due to ritonavir CYP3A4 inhibition", "Metallic dysgeusia taste experienced by many patients"],
      ["Must be started within 5 days of symptom onset", "Always screen patient's complete prescription and OTC drug list for interactions"],
      "NIRMATREL-vir: Cleaves Mpro protease; Requires Ritonavir booster; Review RX list.", "-matrelvir", "nir-ma-TREL-veer", "निरमाट्रेल्-विर"),

    # 10. sofosbuvir
    m("sofosbuvir", "Sofosbuvir", "Sofosbuvir",
      "Sofosbuvir", "Sofosbuvir", "Antivirals",
      "A breakthrough nucleotide analogue NS5B polymerase inhibitor with a high genetic barrier to resistance, serving as the backbone of direct-acting antiviral cures for chronic Hepatitis C.",
      ["400 mg"], ["Film-coated Tablet"], ["Oral"],
      "Uridine nucleotide prodrug metabolized in hepatocytes to active 2'-deoxy-2'-alpha-fluoro-beta-C-methyluridine triphosphate (GS-461203); acts as an obligate chain terminator for HCV NS5B RNA-dependent RNA polymerase.",
      "Pan-genotypic antiviral curative potency against all HCV genotypes (1 through 6); sustained virological response (SVR12 cure) rates exceed 95-98% when combined with NS5A inhibitors.",
      "Rapidly absorbed; peak plasma concentration of sofosbuvir within 0.5 to 2 hours; parent drug rapidly taken up by hepatocytes.",
      "61-65% bound to plasma proteins; major circulating inactive metabolite GS-331007 minimally bound.",
      "Extensively metabolized in the liver via cathepsin A and CES1 followed by phosphorylation to active triphosphate GS-461203; dephosphorylated to circulating inactive metabolite GS-331007.",
      "Excreted in urine (approx. 80%, primarily as inactive metabolite GS-331007) and faeces (approx. 14%).",
      "High (over 80%)", "Parent sofosbuvir 0.4 hours; inactive metabolite GS-331007 approx. 27 hours", "61% to 65%", "Rapid onset; 400 mg once daily with or without food", "24 hours",
      ["Chronic Hepatitis C virus (HCV) infection genotypes 1, 2, 3, 4, 5, and 6 in adults and pediatric patients 3 years and older (combined with velpatasvir, ledipasvir, or daclatasvir)", "HCV and HIV-1 coinfection"],
      ["Concurrent administration of amiodarone (life-threatening symptomatic bradycardia and fatal cardiac arrest reported)", "Strong P-glycoprotein inducers (rifampin, St. John's wort, carbamazepine - reduce sofosbuvir levels)"],
      ["Black box warning: Risk of Hepatitis B virus (HBV) reactivation in patients coinfected with HCV and HBV (screen for HBV before starting)", "Severe bradycardia when combined with amiodarone and another DAA", "Must be used in combination regimens (never as monotherapy)"],
      ["Fatigue", "Headache", "Nausea", "Insomnia", "Anemia (when paired with ribavirin)"],
      ["Severe symptomatic bradycardia (with amiodarone)", "HBV reactivation with fulminant hepatitis", "Severe depression (with ribavirin/interferon regimens)"],
      ["Amiodarone (strictly contraindicated due to fatal bradycardia)", "P-gp inducers (rifampin, phenobarbital, carbamazepine, oxcarbazepine, St. John's wort)", "Antacids (space by 4 hours)"],
      ["Screen for Hepatitis B surface antigen (HBsAg) and core antibody (anti-HBc) prior to therapy", "HCV RNA viral load at baseline, end of treatment, and 12 weeks post-treatment (SVR12)", "Heart rate if patient has cardiac disease"],
      "Category B; if used with ribavirin, ribavirin category X contraindication applies.",
      "Excreted in animal milk; compatible with caution.",
      "Approved for pediatric patients 3 years and older (pellets and tablets available).",
      "No dosage adjustment required based on age alone.",
      "Updated guidelines confirm safety without dose adjustment in severe renal impairment and ESRD on hemodialysis.",
      "No dosage adjustment required in mild, moderate, or severe hepatic impairment.",
      ["Pan-genotypic backbone of direct-acting antiviral cures with SVR12 cure rates >95%", "High genetic barrier to resistance", "Safe in decompensated cirrhosis and renal failure"],
      ["Fatal bradycardia interaction with amiodarone", "Risk of HBV reactivation during HCV clearance"],
      ["Cures Hepatitis C in 12 weeks with oral once-daily combination regimens", "Never combine with amiodarone"],
      "SOFOS-buvir: Single Oral Fix Overcomes Sickness in Hepatitis C; Stop Amiodarone.", "-buvir", "soe-FOS-byoo-veer", "सोफ़ोस-बुविर")
]

print(f"Loaded {len(MEDS_A)} from Part A generator")
