# Category 4: Cardiovascular & Antihypertensives (30 medicines)

def make_cardio(slug, generic, display, active, salt, desc, strengths, forms, routes,
                moa, pd, abs_pk, dist_pk, met_pk, exc_pk, bio, hl, pb, onset, dur,
                ind, contra, warn, cae, sae, interact, mon,
                preg, lact, ped, ger, ren, hep,
                adv, disadv, kpts, trick, suffix, pen, phi):
    return {
        "slug": slug, "generic_name": generic, "display_name": display,
        "active_ingredient": active, "salt": salt, "category": "Cardiovascular", "description": desc,
        "strengths": strengths, "dosage_forms": forms, "routes": routes,
        "mechanism_of_action": moa, "pharmacodynamics": pd,
        "absorption": abs_pk, "distribution": dist_pk, "metabolism": met_pk, "excretion": exc_pk,
        "bioavailability": bio, "half_life": hl, "protein_binding": pb,
        "onset": onset, "duration": dur,
        "indications": ind, "contraindications": contra, "warnings": warn,
        "common_adverse_effects": cae, "serious_adverse_effects": sae,
        "drug_interactions": interact, "monitoring": mon,
        "pregnancy": preg, "lactation": lact, "pediatric": ped, "geriatric": ger,
        "renal": ren, "hepatic": hep,
        "advantages": adv, "disadvantages": disadv, "key_points": kpts,
        "memory_trick": trick, "key_suffix": suffix,
        "pronunciation_en": pen, "pronunciation_hi": phi,
        "status": "active", "verification_status": "verified"
    }

MEDS_CAT4 = [
    # 1. nebivolol
    make_cardio("nebivolol", "Nebivolol", "Nebivolol Hydrochloride", "Nebivolol hydrochloride", "Nebivolol hydrochloride",
      "A third-generation highly cardioselective beta-1 adrenergic blocker with nitric oxide-mediated endothelial vasodilation and neutral metabolic profile.",
      ["2.5 mg", "5 mg", "10 mg"], ["Tablet"], ["Oral"],
      "Dual mechanism: highly selective competitive beta-1 adrenergic antagonist, and stimulates endothelial nitric oxide synthase (eNOS) via beta-3 adrenergic receptors, releasing nitric oxide and causing peripheral vasodilation.",
      "Reduces peripheral vascular resistance and blood pressure without reducing stroke volume; neutral effects on glucose and lipid metabolism; preserves erectile function.",
      "Rapidly absorbed; peak plasma concentration in 1.5 to 4 hours; food does not affect absorption.",
      "High volume of distribution (approx. 10 L/kg); 98% bound to plasma albumin.",
      "Extensively metabolized in liver by CYP2D6 via aromatic hydroxylation and glucuronidation; active hydroxylated metabolites contribute to beta-blocking effect.",
      "Excreted in urine (approx. 38%) and faeces (approx. 48%) predominantly as metabolites.",
      "12% in extensive CYP2D6 metabolizers; 96% in poor metabolizers", "10 hours (extensive metabolizers); 32 hours (poor metabolizers)", "98%", "1 to 2 hours", "24 hours",
      ["Essential hypertension", "Stable mild to moderate chronic heart failure (in addition to standard therapies in elderly patients ≥70 years)", "Hypertension with metabolic syndrome"],
      ["Severe bradycardia (<50 bpm)", "Second- or third-degree atrioventricular heart block", "Cardiogenic shock / decompensated heart failure", "Severe hepatic impairment"],
      ["Abrupt cessation may trigger rebound hypertension or myocardial infarction (taper over 1-2 weeks)", "May mask hypoglycemic tachycardia in diabetics", "Bronchospasm in severe reactive airway disease"],
      ["Headache", "Dizziness", "Fatigue", "Paresthesia", "Nausea", "Dyspnea"],
      ["Severe bradycardia / complete heart block", "Worsening heart failure", "Bronchospasm", "Raynaud's phenomenon"],
      ["CYP2D6 inhibitors (fluoxetine, paroxetine - increase nebivolol levels)", "Non-dihydropyridine calcium channel blockers (verapamil, diltiazem - severe bradycardia/AV block)", "Digoxin", "Clonidine"],
      ["Blood pressure and resting heart rate", "ECG for PR interval prolongation", "Blood glucose in diabetics"],
      "Avoid in pregnancy; beta-blockers reduce placental perfusion and cause fetal bradycardia and growth restriction.",
      "Excreted in breast milk; breastfeeding not recommended.",
      "Safety and efficacy not established in children.",
      "Initiate with 2.5 mg daily in elderly patients; excellent tolerability in senior heart failure trials (SENIORS trial).",
      "If severe renal impairment (eGFR < 30 mL/min), initiate with 2.5 mg once daily.",
      "Contraindicated in moderate to severe hepatic impairment.",
      ["Highest beta-1 cardioselectivity among beta-blockers", "Endothelial nitric oxide release promotes peripheral vasodilation", "Favorable metabolic profile (no worsening of insulin resistance or dyslipidemia)", "Significantly lower incidence of erectile dysfunction than other beta-blockers"],
      ["Variability in pharmacokinetics based on CYP2D6 genetic polymorphism", "Higher cost than atenolol or metoprolol"],
      ["Third-generation beta-blocker that dilates vessels by releasing nitric oxide", "Safest beta-blocker for male sexual function and metabolic syndrome"],
      "NEBI-volol: NO (Nitric Oxide) Endothelial Beta-blocker; Neutral on Insulin.", "-olol", "ne-BIV-oh-lol", "नेबिवो-लोल"),

    # 2. labetalol
    make_cardio("labetalol", "Labetalol", "Labetalol Hydrochloride", "Labetalol hydrochloride", "Labetalol hydrochloride",
      "A non-selective competitive beta-blocker with postsynaptic alpha-1 adrenergic blocking activity, established as the first-line drug of choice for hypertensive emergencies and hypertension in pregnancy.",
      ["100 mg", "200 mg", "5 mg/mL (20 mL IV ampoule)"], ["Film-coated Tablet", "Solution for Injection"], ["Oral", "Intravenous"],
      "Competitively blocks beta-1, beta-2, and alpha-1 adrenergic receptors; oral ratio of alpha:beta blockade is approx. 1:3; IV ratio is approx. 1:7; alpha-1 blockade reduces systemic vascular resistance while beta-1 blockade prevents reflex tachycardia.",
      "Produces prompt fall in blood pressure with maintained cardiac output, renal blood flow, and cerebral blood flow, without marked reflex tachycardia.",
      "Rapidly and completely absorbed from GI tract; undergoes substantial hepatic first-pass metabolism.",
      "Extensive tissue distribution; crosses placenta and blood-brain barrier; 50% bound to plasma proteins.",
      "Extensively metabolized in the liver via glucuronidation to inactive metabolites.",
      "Less than 5% excreted unchanged in urine; remainder eliminated as inactive glucuronides in urine (approx. 60%) and bile.",
      "Approximately 25% (oral)", "6 to 8 hours", "50%", "IV: 2 to 5 minutes; Oral: 20 minutes to 2 hours", "IV: 2 to 4 hours; Oral: 8 to 12 hours",
      ["Hypertensive emergencies and urgencies (IV bolus or continuous infusion)", "Hypertension in pregnancy (pre-eclampsia and chronic maternal hypertension - drug of choice)", "Acute aortic dissection (combined with vasodilator)", "Post-operative hypertension"],
      ["Severe sinus bradycardia", "Greater than first-degree heart block", "Cardiogenic shock / overt heart failure", "Bronchial asthma / severe COPD (beta-2 blockade)"],
      ["Postural / orthostatic hypotension (due to alpha-1 blockade - keep patients supine for 3 hours after IV injection)", "Hepatotoxicity: rare severe idiosyncratic liver injury reported", "May mask signs of hypoglycemia"],
      ["Dizziness / postural lightheadedness", "Scalp tingling / formication (characteristic alpha-blocker effect)", "Nausea", "Fatigue", "Nasal congestion"],
      ["Severe symptomatic postural hypotension", "Bradycardia / heart block", "Severe bronchospasm in asthmatics", "Drug-induced liver necrosis"],
      ["Verapamil / diltiazem (additive negative inotropic and dromotropic effects)", "Inhalation anaesthetics (myocardial depression)", "Cimetidine (increases labetalol bioavailability)"],
      ["Blood pressure and heart rate continuously during IV infusion", "Keep patient supine during and for 3 hours post-IV dose", "Liver function tests in prolonged oral therapy"],
      "Category C; drug of choice and first-line standard of care worldwide for gestational hypertension and pre-eclampsia.",
      "Excreted in low levels in breast milk; compatible with breastfeeding.",
      "Dosing established for pediatric hypertensive emergencies (0.2-1 mg/kg IV); use under specialist supervision.",
      "Higher risk of orthostatic hypotension; start with 100 mg BID orally.",
      "No dosage adjustment required in renal impairment.",
      "Use with caution; titrate carefully due to reduced first-pass hepatic metabolism.",
      ["Drug of choice for pregnancy-induced hypertension and pre-eclampsia", "Rapid, titratable IV blood pressure control in hypertensive emergencies without reflex tachycardia", "Preserves uteroplacental and cerebral blood flow"],
      ["Alpha-1 blockade causes orthostatic hypotension and characteristic scalp tingling", "Contraindicated in severe asthma and decompensated heart failure"],
      ["First-choice antihypertensive in pregnancy and pre-eclampsia", "IV drug of choice for hypertensive emergencies (give 20 mg slow IV bolus, double every 10 min)"],
      "LAB-ETA-LOL: Lowers Arterial Bloodpressure in Emergency & Tremendous in Pre-eclamps-IA.", "-lalol", "la-BAY-ta-lol", "लाबे-टालोल"),

    # 3. esmolol
    make_cardio("esmolol", "Esmolol", "Esmolol Hydrochloride", "Esmolol hydrochloride", "Esmolol hydrochloride",
      "An ultra-short-acting, cardioselective beta-1 adrenergic blocker metabolized rapidly by red blood cell esterases, used for rapid intraoperative and emergency control of supraventricular tachycardia and aortic dissection.",
      ["100 mg/10 mL vial", "2.5 g/10 mL ampoule for infusion"], ["Solution for Injection", "Concentrate for Solution for Infusion"], ["Intravenous"],
      "Selective competitive antagonist at myocardial beta-1 adrenergic receptors with negligible intrinsic sympathomimetic or membrane-stabilizing activity; rapidly hydrolyzed by cytoplasmic esterases in red blood cells.",
      "Rapidly slows sinus rate and AV nodal conduction velocity, decreasing myocardial contractility and oxygen consumption; effects dissipate within 15-20 minutes of stopping infusion.",
      "Administered exclusively by continuous intravenous infusion; 100% bioavailable.",
      "Rapidly distributes throughout the vascular compartment; Vd approx. 3.4 L/kg; 55% bound to plasma proteins.",
      "Rapidly metabolized via hydrolysis of its methyl ester linkage by red blood cell cytosol esterases into an acid metabolite (ASL-8123) with 1/1500th of esmolol's beta-blocking activity; completely independent of hepatic and renal enzymes.",
      "Acid metabolite excreted by the kidneys in urine (>73%); less than 2% unchanged esmolol.",
      "100% (IV)", "9 minutes (ultra-short elimination half-life)", "55%", "Immediate (peak effect within 2 to 6 minutes)", "10 to 20 minutes after stopping infusion",
      ["Rapid control of ventricular rate in supraventricular tachycardia (atrial fibrillation, atrial flutter, sinus tachycardia)", "Perioperative and post-operative hypertension and tachycardia", "Acute aortic dissection (immediate beta-blockade before vasodilator therapy)"],
      ["Severe sinus bradycardia (<50 bpm)", "Heart block greater than first degree", "Cardiogenic shock / overt acute heart failure", "Severe asthma or acute bronchospasm"],
      ["Dose-dependent hypotension occurs frequently (titrate carefully and monitor BP continuously)", "Tissue necrosis upon extravasation; avoid infusion concentrations >10 mg/mL", "Rapid reversal allows safety: turning off infusion terminates effect within 15 minutes"],
      ["Hypotension (approx. 25% of patients)", "Diaphoresis", "Dizziness", "Nausea", "Injection site phlebitis"],
      ["Severe symptomatic hypotension / syncope", "Severe bradycardia / asystole", "Bronchospasm in susceptible patients"],
      ["IV verapamil / diltiazem (severe cardiac arrest/asystole risk; do not combine)", "Digoxin (additive AV nodal conduction delay)", "Morphine (increases esmolol plasma levels)"],
      ["Continuous blood pressure and ECG telemetry throughout infusion", "Infusion site inspection for extravasation"],
      "Category C; use in pregnancy only if maternal cardiac emergency demands it; crosses placenta.",
      "Excretion in milk unknown; half-life is 9 minutes so maternal drug clears rapidly.",
      "Used off-label in pediatric intensive care for tachyarrhythmias (loading 500 mcg/kg then 50-300 mcg/kg/min).",
      "Elderly patients are more sensitive to hypotensive effects; titrate cautiously.",
      "No dosage adjustment required for parent esmolol; acid metabolite accumulates in renal failure but is largely inactive.",
      "No dosage adjustment required (metabolized exclusively by red blood cell esterases).",
      ["Ultra-short 9-minute half-life provides unparalleled safety: if hypotension develops, stopping the infusion reverses the effect within 15 minutes", "Metabolism by red blood cell esterases is independent of liver and kidney function", "Ideal for unstable perioperative and ICU patients"],
      ["Intravenous infusion only; cannot be used for chronic maintenance", "High rate of infusion-related hypotension requires continuous arterial line or automated BP checks"],
      ["Ultra-short-acting beta-blocker with a 9-minute half-life metabolized by red blood cells", "Turn off infusion to reverse adverse effects within 15 minutes"],
      "ESMOLOL: Extremely Short-acting; Metabolized by Oxygen-carrier (RBC) esterases; Lasts Only minutes.", "-olol", "EZ-moe-lol", "एस्मो-लोल"),

    # 4. perindopril
    make_cardio("perindopril", "Perindopril", "Perindopril Erbumine / Arginine", "Perindopril erbumine", "Perindopril erbumine",
      "A long-acting, lipophilic prodrug ACE inhibitor that provides sustained 24-hour tissue ACE inhibition, extensive endothelial protection, and proven reduction of cardiovascular events in stable coronary artery disease.",
      ["2 mg", "4 mg", "8 mg (erbumine)", "2.5 mg", "5 mg", "10 mg (arginine)"], ["Tablet"], ["Oral"],
      "Hydrolyzed in the liver to active metabolite perindoprilat, which competitively inhibits angiotensin-converting enzyme (ACE), blocking conversion of angiotensin I to angiotensin II, decreasing aldosterone, and inhibiting bradykinin degradation.",
      "Reduces peripheral vascular resistance without reflex tachycardia; promotes vascular remodeling and reduces left ventricular hypertrophy; enhances endothelial function via bradykinin-mediated nitric oxide release.",
      "Rapidly absorbed; peak perindopril concentration in 1 hour; 20% converted to active perindoprilat (peak perindoprilat in 3 to 4 hours); food decreases conversion to active metabolite, take before breakfast.",
      "Widely distributed into vascular tissues and endothelial cells; perindoprilat is 20% bound to plasma proteins.",
      "Extensively hydrolyzed in the liver by carboxylesterases into active perindoprilat and inactive glucuronide conjugates.",
      "Perindoprilat is eliminated unchanged in urine via glomerular filtration and tubular secretion.",
      "Approximately 65-70% (prodrug)", "Parent perindopril 1 hour; active perindoprilat effective half-life 17 hours (terminal dissociation half-life 30-120 hours)", "20%", "1 to 2 hours (peak effect in 4 to 6 hours)", "24 hours",
      ["Essential hypertension", "Stable coronary artery disease (EUROPA trial: reduces risk of cardiac events)", "Symptomatic congestive heart failure", "Post-myocardial infarction secondary prevention"],
      ["History of ACE inhibitor-induced or hereditary angioedema", "Pregnancy (all trimesters - teratogenic)", "Concomitant use with aliskiren in diabetic patients", "Concomitant sacubitril/valsartan (must observe 36-hour washout)"],
      ["Black box warning: Fetal toxicity and neonatal death if used during pregnancy; discontinue immediately upon pregnancy detection", "Angioedema (face, lips, larynx - can be fatal)", "Hyperkalemia and acute renal impairment in bilateral renal artery stenosis", "Dry persistent hacking cough (bradykinin accumulation)"],
      ["Dry persistent cough", "Dizziness / lightheadedness", "Headache", "Fatigue", "Hyperkalemia"],
      ["Life-threatening angioedema of airway", "Acute kidney injury", "Severe symptomatic hypotension / syncope", "Agranulocytosis / neutropenia (rare)"],
      ["Potassium supplements / potassium-sparing diuretics (severe hyperkalemia)", "NSAIDs (impair antihypertensive effect and precipitate acute renal failure)", "Lithium (elevates serum lithium toxicity)", "Sacubitril (angioedema - 36h washout required)"],
      ["Serum creatinine and eGFR at baseline and within 1-2 weeks of initiation", "Serum potassium levels", "Blood pressure sitting and standing"],
      "Black box warning: Strictly contraindicated in pregnancy (fetotoxic, causes renal dysgenesis and oligohydramnios).",
      "Excreted in animal milk; avoid breastfeeding.",
      "Safety and efficacy not established in pediatric patients.",
      "Start with 2 mg (erbumine) or 2.5 mg (arginine) in elderly patients; titrate based on renal function.",
      "Dose reduction based on CrCl: if CrCl 30-60 mL/min, give 2 mg daily; if CrCl 15-30 mL/min, give 2 mg every other day; if CrCl < 15 mL/min, give 2 mg on dialysis days.",
      "No dosage adjustment required in hepatic impairment.",
      ["EUROPA trial proven: significantly reduces cardiovascular death and myocardial infarction in stable coronary disease", "True 24-hour trough-to-peak ratio (>75%) ensuring consistent blood pressure control", "High tissue ACE lipophilicity improves vascular endothelial function"],
      ["Class-wide ACE inhibitor dry cough in 10-15% of patients", "Risk of angioedema and hyperkalemia"],
      ["Take once daily in the morning before breakfast", "Proven to reduce heart attacks in stable coronary artery disease (EUROPA trial)"],
      "PERINDO-pril: Proven Endothelial Remodeling In Narrowed Diseased vessels (EUROPA trial).", "-pril", "per-IN-doe-pril", "पेरिन्डो-प्रिल"),

    # 5. candesartan
    make_cardio("candesartan", "Candesartan", "Candesartan Cilexetil", "Candesartan cilexetil", "Candesartan cilexetil",
      "An ester prodrug angiotensin II receptor blocker (ARB) with insurmountable, tight AT1-receptor binding kinetics, proven to reduce cardiovascular mortality and hospitalizations in heart failure (CHARM trial).",
      ["4 mg", "8 mg", "16 mg", "32 mg"], ["Tablet"], ["Oral"],
      "Completely bioactivated during gastrointestinal absorption to active candesartan, which binds selectively and insurmountably to the AT1 receptor with high affinity and slow dissociation, blocking vasoconstriction and aldosterone secretion.",
      "Reduces peripheral vascular resistance and systemic blood pressure without causing dry cough; improves cardiac output and reduces left ventricular remodelling in heart failure with reduced ejection fraction (HFrEF).",
      "Completely hydrolyzed to active candesartan in the gastrointestinal wall; peak plasma concentration in 3 to 4 hours; food does not affect bioavailability.",
      "Highly bound to plasma albumin (>99%); small volume of distribution (approx. 0.13 L/kg).",
      "Undergoes minor hepatic metabolism by CYP2C9 to an inactive metabolite; clearance is predominantly through direct excretion.",
      "Eliminated by both renal excretion (approx. 33%) and biliary/fecal excretion (approx. 67%) predominantly as unchanged active candesartan.",
      "Approximately 15% (cilexetil ester)", "9 to 12 hours (effective biological half-life longer due to tight receptor binding)", ">99%", "2 to 4 hours (full effect in 2 to 4 weeks)", "24 hours",
      ["Essential hypertension in adults and children 1 to 17 years", "Heart failure with reduced ejection fraction (HFrEF - CHARM trial: reduces CV mortality and hospitalizations)", "Hypertensive diabetic nephropathy with microalbuminuria"],
      ["Hypersensitivity to candesartan", "Pregnancy (fetal toxicity)", "Concomitant use of aliskiren in patients with diabetes mellitus"],
      ["Black box warning: Fetal toxicity (contraindicated in pregnancy)", "Hyperkalemia, especially when combined with potassium-sparing diuretics or ACE inhibitors", "Hypotension in volume- or salt-depleted patients", "Renal impairment in bilateral renal artery stenosis"],
      ["Dizziness", "Headache", "Back pain", "Hyperkalemia", "Fatigue"],
      ["Acute renal failure", "Severe symptomatic hypotension", "Angioedema (rare compared to ACE inhibitors)", "Hyperkalemia (>5.5 mEq/L)"],
      ["Potassium supplements, spironolactone, eplerenone (additive hyperkalemia risk)", "NSAIDs (decrease antihypertensive effect and risk of acute kidney injury)", "Lithium (increases lithium levels)", "ACE inhibitors (dual RAS blockade increases toxicity)"],
      ["Serum creatinine and eGFR at baseline and within 1-2 weeks", "Serum potassium levels", "Blood pressure"],
      "Black box warning: Strictly contraindicated throughout pregnancy; causes fetal skull hypoplasia, oligohydramnios, and neonatal death.",
      "Excreted in animal milk; avoid breastfeeding.",
      "Approved for pediatric hypertension in children 1 year and older; dosed by body weight.",
      "Initiate at 4 mg once daily in frail elderly patients; titrate gradually.",
      "No initial dose adjustment required in mild to moderate renal impairment; initiate at 4 mg in severe renal impairment (CrCl < 30 mL/min).",
      "Initiate at 2-4 mg once daily in moderate hepatic impairment; use with caution in biliary obstruction.",
      ["Insurmountable AT1 receptor binding provides prolonged 24-hour blood pressure control even after missed doses", "Gold standard ARB for heart failure with proven mortality reduction (CHARM Alternative and Added trials)", "Virtually zero incidence of dry cough compared to ACE inhibitors"],
      ["Prodrug oral bioavailability is relatively modest (15%)", "Strictly contraindicated in pregnancy"],
      ["Proven heart failure mortality reduction (target dose 32 mg daily in heart failure)", "Does not cause the dry hacking cough seen with ACE inhibitors"],
      "CANDE-sartan: CAN Decrease Eventual mortality in heart failure (CHARM trial).", "-sartan", "kan-de-SAR-tan", "कैंडे-सारटन"),

    # 6. cilnidipine
    make_cardio("cilnidipine", "Cilnidipine", "Cilnidipine", "Cilnidipine", "Cilnidipine",
      "A unique fourth-generation dihydropyridine calcium channel blocker with dual L-type and N-type calcium channel blockade, suppressing sympathetic nerve activity and significantly reducing pedal oedema and proteinuria.",
      ["5 mg", "10 mg", "20 mg"], ["Tablet"], ["Oral"],
      "Dual blockade: blocks L-type voltage-gated calcium channels in vascular smooth muscle cells (causing arterial vasodilation) AND N-type calcium channels at sympathetic nerve endings (inhibiting norepinephrine release and sympathetic overactivity).",
      "Reduces peripheral vascular resistance and systemic blood pressure without causing reflex tachycardia; dilates both afferent and efferent renal arterioles, reducing glomerular capillary pressure and suppressing proteinuria; minimizes dependent pedal oedema by balancing capillary hydrostatic pressures.",
      "Rapidly absorbed; peak plasma concentration in 1.8 to 2.2 hours; food delays peak but does not reduce overall bioavailability.",
      "High volume of distribution; extensively bound to human plasma proteins (>98%).",
      "Extensively metabolized in the liver by CYP3A4 via dehydrogenation and ester cleavage to inactive metabolites.",
      "Excreted predominantly in faeces (approx. 80%) and urine (approx. 20%) as inactive metabolites.",
      "Approximately 13% to 20%", "2.5 hours (plasma elimination); biological tissue duration exceeds 24 hours", ">98%", "1 to 2 hours", "24 hours",
      ["Essential hypertension, particularly in patients with morning hypertension or sympathetic hyperactivity", "Hypertension with chronic kidney disease and proteinuria", "Hypertension complicated by amlodipine-induced pedal oedema (replacement therapy)", "White-coat hypertension and stress-induced blood pressure elevation"],
      ["Hypersensitivity to cilnidipine or other dihydropyridine calcium channel blockers", "Severe cardiogenic shock or unstable angina", "Severe aortic stenosis"],
      ["Hypotension and dizziness", "Hepatic impairment requires cautious dosing (cleared by CYP3A4)", "Gradually taper when discontinuing to prevent rebound hypertension"],
      ["Headache", "Flushing", "Dizziness", "Palpitations (much less than amlodipine)", "Nausea"],
      ["Severe symptomatic hypotension", "Excessive bradycardia (rare, due to N-type blockade in sinus node)", "Hepatotoxicity"],
      ["CYP3A4 inhibitors (ketoconazole, clarithromycin - increase cilnidipine levels)", "CYP3A4 inducers (rifampin, phenytoin - reduce efficacy)", "Digoxin (modest increase in digoxin levels)", "Other antihypertensives"],
      ["Blood pressure and heart rate sitting and standing", "Urine albumin-to-creatinine ratio (monitors antiproteinuric effect)", "Inspection of ankles for resolution of pedal oedema"],
      "Avoid in pregnancy; insufficient human safety data; use established pregnancy agents (labetalol, nifedipine).",
      "Excreted in breast milk in animal studies; avoid breastfeeding.",
      "Safety and efficacy not established in children.",
      "Start with a low dose (5 mg once daily); assess blood pressure response carefully.",
      "No dosage adjustment required in renal impairment; beneficial antiproteinuric action in chronic kidney disease.",
      "Dose reduction recommended in moderate to severe hepatic impairment (metabolized by CYP3A4).",
      ["Dual L- and N-type calcium channel blocker inhibits sympathetic hyperactivity, preventing reflex tachycardia", "Significantly lower incidence of ankle pedal oedema compared to amlodipine", "Dilates both afferent AND efferent renal arterioles, reducing intraglomerular pressure and proteinuria"],
      ["Not approved in the United States (extensively approved and prescribed in India and Japan)", "Metabolized by CYP3A4, leading to drug interactions with azoles and macrolides"],
      ["Drug of choice when patients develop swollen ankles (pedal oedema) on amlodipine", "Dual L-type and N-type channel blocker that protects kidneys and suppresses sympathetic spikes"],
      "CILNI-dipine: Calms Sympathetic Nerves (N-type), Cancels Leg Infiltration (no pedal oedema).", "-dipine", "sil-NI-di-peen", "सिलनी-डिपिन"),

    # 7. benidipine
    make_cardio("benidipine", "Benidipine", "Benidipine Hydrochloride", "Benidipine hydrochloride", "Benidipine hydrochloride",
      "A triple L-, T-, and N-type calcium channel blocker with high vascular membrane affinity, conferring long-lasting 24-hour antihypertensive, cardioprotective, and renoprotective effects with minimal pedal oedema.",
      ["4 mg", "8 mg"], ["Film-coated Tablet"], ["Oral"],
      "Triple calcium channel blocker: blocks L-type channels (arteriolar dilation), T-type channels (aldosterone suppression and cardiac protective effect), and N-type channels (sympathetic nerve inhibition and efferent arteriolar dilation).",
      "Slowly associates and dissociates from the dihydropyridine binding site within the cell membrane (membrane-bound reservoir), producing smooth, long-lasting blood pressure reduction without reflex tachycardia or renin-aldosterone activation.",
      "Well absorbed from the GI tract; peak plasma concentrations reached within 1 to 1.5 hours; takes longer to dissociate from vascular receptors than from plasma.",
      "Widely distributed into vascular tissue; highly bound to plasma proteins (>98%).",
      "Extensively metabolized in the liver by cytochrome P450 3A4 to inactive metabolites.",
      "Excreted in urine and faeces almost entirely as inactive metabolites; negligible renal excretion of unchanged drug.",
      "Approximately 15% to 25%", "1 to 2 hours in plasma; tissue receptor half-life >24 hours", ">98%", "1 hour", "24 hours",
      ["Essential hypertension", "Renovascular hypertension and hypertension associated with chronic kidney disease", "Angina pectoris (vasospastic and effort angina)"],
      ["Hypersensitivity to benidipine or dihydropyridines", "Severe cardiogenic shock", "Advanced aortic stenosis"],
      ["Severe hepatic impairment (hepatic clearance reduced)", "Hypotension during initiation in volume-depleted patients"],
      ["Headache", "Facial flushing", "Dizziness", "Palpitations", "Constipation"],
      ["Excessive hypotension", "Atrioventricular conduction block (rare)", "Drug-induced liver injury"],
      ["CYP3A4 inhibitors (itraconazole, erythromycin - elevate benidipine exposure)", "CYP3A4 inducers (rifampin - reduce efficacy)", "Other antihypertensives (additive hypotensive effect)"],
      ["Blood pressure and heart rate", "Liver function tests in hepatic impairment", "Renal parameters"],
      "Avoid during pregnancy; animal studies show teratogenicity and fetal distress.",
      "Avoid during breastfeeding; excreted in animal milk.",
      "Safety and efficacy not established in pediatric patients.",
      "Initiate at 2 to 4 mg once daily in elderly patients; titrate cautiously.",
      "No dosage adjustment required in renal impairment; renoprotective profile.",
      "Start with 2 mg once daily in patients with hepatic dysfunction.",
      ["Triple L-, T-, and N-type calcium channel blocker offering comprehensive vascular, renal, and cardiac protection", "Dilates efferent arterioles, reducing glomerular hypertension and proteinuria", "Membrane-reservoir kinetics guarantee smooth 24-hour blood pressure control"],
      ["Plasma half-life is short (requires high tissue affinity for extended action)", "Mainly available in Asian markets (India, Japan)"],
      ["Triple calcium channel blocker (L, T, and N types)", "Protects kidneys by dilating both afferent and efferent renal arterioles"],
      "BENI-dipine: Beneficial Triple blocker (L, T, N types) for Blood pressure, Efferent arterioles, and Nitrogenous kidney waste.", "-dipine", "ben-I-di-peen", "बेनी-डिपिन"),

    # 8. eplerenone
    make_cardio("eplerenone", "Eplerenone", "Eplerenone", "Eplerenone", "Eplerenone",
      "A selective mineralocorticoid receptor antagonist (MRA) with high specificity for aldosterone receptors, proven to reduce mortality in heart failure post-MI without the antiandrogenic side effects of spironolactone.",
      ["25 mg", "50 mg"], ["Film-coated Tablet"], ["Oral"],
      "Selectively binds to the mineralocorticoid receptor, competitively blocking aldosterone binding in the renal distal tubule and collecting duct; prevents sodium and water reabsorption while conserving potassium and magnesium; attenuates myocardial and vascular fibrosis.",
      "Reduces blood pressure, decreases left ventricular remodelling, reduces myocardial fibrosis, and prevents sudden cardiac death in heart failure; possesses 1000-fold lower affinity for androgen and progesterone receptors than spironolactone (no gynecomastia).",
      "Rapidly absorbed; peak plasma concentrations achieved in approximately 1.5 to 2 hours; absorption unaffected by food.",
      "Apparent volume of distribution approx. 43 to 90 L; approximately 50% bound to plasma proteins (predominantly alpha-1 acid glycoprotein).",
      "Extensively metabolized in the liver predominantly by CYP3A4 to inactive metabolites; no active circulating metabolites.",
      "Excreted in urine (approx. 67%) and faeces (approx. 32%) as inactive metabolites; less than 5% unchanged in urine.",
      "Approximately 69%", "4 to 6 hours", "50%", "Peak antihypertensive effect within 2 to 4 weeks", "24 hours",
      ["Heart failure with reduced ejection fraction (HFrEF) post-myocardial infarction (EPHESUS trial)", "Chronic heart failure with reduced ejection fraction NYHA class II (EMPHASIS-HF trial)", "Essential hypertension (resistant hypertension add-on)"],
      ["Serum potassium > 5.0 mEq/L at initiation", "Severe renal impairment (eGFR < 30 mL/min or serum creatinine >2.0 mg/dL in females, >2.5 mg/dL in males)", "Concurrent use with strong CYP3A4 inhibitors (ketoconazole, itraconazole, clarithromycin)", "Concurrent use with potassium-sparing diuretics or high-dose potassium supplements"],
      ["Hyperkalemia is the principal life-threatening risk; monitor serum potassium at baseline, 1 week, 1 month, and periodically", "Risk of hyperkalemia increased in patients with diabetes and moderate renal impairment", "Dose adjustment required with moderate CYP3A4 inhibitors"],
      ["Hyperkalemia", "Dizziness", "Diarrhoea", "Cough", "Headache"],
      ["Severe / fatal hyperkalemia (>6.0 mEq/L) causing cardiac arrest", "Acute kidney injury / elevation in serum creatinine", "Angioedema (rare)"],
      ["Strong CYP3A4 inhibitors (ketoconazole, clarithromycin - contraindicated due to 5-fold eplerenone increase)", "Moderate CYP3A4 inhibitors (diltiazem, verapamil, fluconazole - do not exceed 25 mg daily)", "ACE inhibitors and ARBs (monitor potassium strictly)", "NSAIDs (precipitate acute renal failure)"],
      ["Serum potassium and serum creatinine at baseline, day 7, day 30, and every 3-6 months thereafter", "Blood pressure sitting and standing"],
      "Category B; use during pregnancy only if clearly needed.",
      "Excretion in human milk unknown; use caution or alternative.",
      "Safety and efficacy not established in pediatric patients.",
      "Higher risk of hyperkalemia due to age-related decline in renal function; initiate with 25 mg daily and monitor electrolytes closely.",
      "Contraindicated if eGFR < 30 mL/min; if eGFR 30-49 mL/min, initiate with 25 mg every other day.",
      "No dosage adjustment needed in mild to moderate hepatic impairment; avoid in severe hepatic impairment.",
      ["Selective aldosterone antagonist that does NOT cause gynecomastia, breast pain, or menstrual irregularities (unlike spironolactone)", "Proven reduction in all-cause mortality and sudden cardiac death in post-MI heart failure (EPHESUS trial)", "Effective for resistant hypertension"],
      ["Significantly more expensive than generic spironolactone", "Requires strict monitoring of potassium and renal function to avoid fatal hyperkalemia"],
      ["No gynecomastia or breast pain (selective for aldosterone receptors, sparing androgen receptors)", "Check potassium at 1 week and 1 month after starting (stop if K+ > 5.5 mEq/L)"],
      "EPLEREN-one: Eliminates Progestational/androgenic Effects; Lowers End-organ Remodeling; check Potassium.", "-one", "eh-PLEER-en-own", "एप्लेरे-नोन"),

    # 9. indapamide
    make_cardio("indapamide", "Indapamide", "Indapamide", "Indapamide", "Indapamide",
      "A non-thiazide chlorosulfamoyl indole diuretic with dual diuretic and direct vascular smooth muscle vasodilating properties, established in major trials (HYVET, ADVANCE) for stroke and mortality reduction.",
      ["1.5 mg SR", "2.5 mg"], ["Sustained-Release Tablet", "Immediate-Release Tablet"], ["Oral"],
      "Dual action: inhibits sodium and chloride reabsorption in the early distal convoluted tubule (producing saluresis), AND directly reduces vascular reactivity to pressor amines by modulating transmembrane calcium influx in arterial smooth muscle cells.",
      "Lowers peripheral vascular resistance with minimal impact on plasma volume at low doses (1.5 mg SR); metabolically neutral: does not adversely affect lipid profiles or glucose tolerance; reduces left ventricular hypertrophy.",
      "Rapidly and completely absorbed; 1.5 mg sustained-release formulation provides stable plateau concentrations over 24 hours.",
      "Widely distributed into vascular tissue and erythrocytes; 76-79% bound to plasma proteins.",
      "Extensively metabolized in the liver (approx. 90%) to numerous inactive metabolites.",
      "Excreted in urine (approx. 60-70%, with only 5-7% unchanged) and faeces (approx. 20%).",
      "Near 100%", "14 to 24 hours (sustained release)", "76% to 79%", "1 to 2 hours (peak antihypertensive effect in 2 to 4 weeks)", "24 hours",
      ["Essential hypertension in adults", "Isolated systolic hypertension in the elderly (HYVET trial: reduced stroke and all-cause mortality)", "Hypertension in diabetic patients (ADVANCE trial: combined with perindopril)"],
      ["Severe renal failure (anuria)", "Hepatic encephalopathy / severe hepatic impairment", "Refractory hypokalemia", "Known hypersensitivity to indapamide or sulfonamides"],
      ["Hypokalemia and hyponatremia: check baseline and periodic serum electrolytes", "May precipitate or exacerbate hepatic encephalopathy in liver cirrhosis", "Hyperuricemia and gout precipitation"],
      ["Hypokalemia", "Fatigue", "Dizziness", "Headache", "Muscle cramps", "Nausea"],
      ["Severe life-threatening hypokalemia / cardiac arrhythmias", "Severe hyponatremia", "Hepatic encephalopathy in cirrhotics", "Stevens-Johnson syndrome"],
      ["Lithium (decreases lithium clearance, causing toxicity)", "QT-prolonging drugs (hypokalemia increases Torsades de pointes risk)", "NSAIDs (attenuate antihypertensive efficacy)", "Digoxin (hypokalemia potentiates digoxin toxicity)"],
      ["Serum electrolytes (potassium, sodium) at baseline and 4-6 weeks after initiation", "Serum uric acid and fasting glucose", "Blood pressure"],
      "Category B; diuretics are generally avoided in pregnancy due to risk of maternal hypovolemia and placental hypoperfusion.",
      "Excreted in breast milk; breastfeeding not recommended.",
      "Safety and efficacy not established in children.",
      "First-line agent in elderly patients with isolated systolic hypertension (HYVET trial demonstrated 30% stroke reduction in patients ≥80 years).",
      "Ineffective as a diuretic if eGFR < 30 mL/min, but vasodilating effect may persist; monitor electrolytes.",
      "Contraindicated in severe hepatic impairment / hepatic encephalopathy.",
      ["Proven to reduce stroke and all-cause mortality in the very elderly (HYVET trial)", "Metabolically neutral at 1.5 mg SR dose (no worsening of lipids or diabetes)", "Direct vasodilating action lowers blood pressure with minimal kaliuresis"],
      ["Sulfonamide cross-reactivity", "Risk of hypokalemia and hyponatremia if combined with other diuretics"],
      ["Proven stroke reduction in the very elderly (HYVET trial)", "Sustained-release 1.5 mg once daily taken in the morning"],
      "INDAP-amide: Invaluable in Nursing-home/Decade-8 patients (HYVET trial); Arterial Vasodilator.", "-amide", "in-DAP-a-mide", "इन्डापा-माइड"),

    # 10. ivabradine
    make_cardio("ivabradine", "Ivabradine", "Ivabradine Hydrochloride", "Ivabradine hydrochloride", "Ivabradine hydrochloride",
      "A selective and specific hyperpolarization-activated cyclic nucleotide-gated (HCN) pacemaker channel inhibitor that lowers heart rate without reducing myocardial contractility or blood pressure.",
      ["5 mg", "7.5 mg"], ["Film-coated Tablet"], ["Oral"],
      "Selectively blocks the hyperpolarization-activated cyclic nucleotide-gated (HCN) channel (If 'funny' pacemaker current) in the sinoatrial node, slowing the diastolic depolarization slope and reducing heart rate at rest and during exercise.",
      "Selectively reduces heart rate without affecting myocardial contractility (inotropy), intracardiac conduction (dromotropy), ventricular repolarization, or systemic blood pressure; decreases myocardial oxygen consumption and prolongs diastolic coronary perfusion time.",
      "Rapidly and completely absorbed; peak plasma concentration in approximately 1 hour on an empty stomach; food delays absorption by 1 hour and increases exposure by 20-30%, so take with meals.",
      "Apparent volume of distribution approx. 100 L; 70% bound to human plasma proteins.",
      "Extensively metabolized by CYP3A4 in the gut wall and liver by N-demethylation to an active N-desmethylated metabolite (S-18982) which has equal potency.",
      "Excreted equally in urine and faeces (approx. 4% unchanged in urine).",
      "Approximately 40% (due to first-pass metabolism)", "2 hours (effective half-life in plasma); terminal half-life 11 hours", "70%", "Heart rate reduction within 1 hour", "12 hours (dosed twice daily with meals)",
      ["Chronic heart failure with reduced ejection fraction (HFrEF NYHA II-IV, LVEF ≤35%) in sinus rhythm with resting heart rate ≥70 bpm (SHIFT trial)", "Stable chronic angina pectoris in patients with normal sinus rhythm who have contraindications to or intolerance of beta-blockers", "Inappropriate sinus tachycardia (off-label)"],
      ["Resting heart rate < 70 bpm prior to treatment", "Cardiogenic shock / acute decompensated heart failure", "Acute myocardial infarction", "Severe hypotension (<90/50 mmHg)", "Severe hepatic impairment", "Sick sinus syndrome or sino-atrial block", "Third-degree AV block", "Pacemaker-dependent rhythm (ineffective)", "Atrial fibrillation or flutter (ineffective, requires sinus rhythm)"],
      ["Atrial fibrillation risk: monitor regularly for irregular rhythm (discontinue if permanent AF develops)", "Visual phosphenes (enhanced brightness in parts of visual field) occur in approx. 15% due to retinal Ih channel inhibition", "Avoid strong CYP3A4 inhibitors and inducers", "Not indicated for acute angina attacks"],
      ["Phosphenes (transient visual luminous phenomena / brightness)", "Bradycardia (<50 bpm)", "Headache", "Dizziness", "Atrial fibrillation"],
      ["Severe symptomatic bradycardia", "Atrial fibrillation", "Ventricular arrhythmias / Torsades de pointes (secondary to profound bradycardia)", "Syncope"],
      ["Strong CYP3A4 inhibitors (ketoconazole, itraconazole, clarithromycin - contraindicated)", "Moderate CYP3A4 inhibitors (diltiazem, verapamil - increase ivabradine levels and cause excessive bradycardia; avoid combination)", "CYP3A4 inducers (rifampicin, St. John's wort, phenytoin - decrease efficacy)", "QT-prolonging drugs"],
      ["Resting heart rate (target 50 to 60 bpm in heart failure)", "Regular pulse check and ECG for atrial fibrillation", "Vision assessment for phosphenes"],
      "Strictly contraindicated during pregnancy; embryotoxic and teratogenic in animal studies; effective contraception required.",
      "Excreted in animal milk; contraindicated during breastfeeding.",
      "Approved for pediatric heart failure (dilated cardiomyopathy) 6 months and older in sinus rhythm.",
      "Initiate at 2.5 mg twice daily in patients aged 75 years or older.",
      "No dose adjustment required if CrCl > 15 mL/min; use caution if CrCl < 15 mL/min.",
      "Contraindicated in severe hepatic impairment (Child-Pugh C); no adjustment in mild.",
      ["Pure heart rate reduction without decreasing blood pressure or myocardial contractility (ideal in hypotensive heart failure)", "Reduces cardiovascular mortality and heart failure hospitalizations in patients with resting HR ≥70 bpm (SHIFT trial)", "Does not cause bronchospasm, depression, or erectile dysfunction (unlike beta-blockers)"],
      ["Only effective in patients with sinus rhythm (completely ineffective in atrial fibrillation)", "Visual phosphenes occur in 15% of patients due to retinal Ih channels"],
      ["Pure heart rate lowering drug that does NOT lower blood pressure", "Only works if patient is in sinus rhythm (ineffective in atrial fibrillation)", "Counsel patients about bright visual lights/flashes (phosphenes) in dim lighting"],
      "IVA-BRAD-ine: Inhibits 'funny' (If) current, Valued in heart failure, Acts strictly on Bradycardia.", "-bradine", "eye-VA-bra-deen", "इवाब्रा-डीन")
]

print(f"Loaded {len(MEDS_CAT4)} from Cat 4 cardiovascular")
