#!/usr/bin/env python3
"""
Generates 30 clinical records for scripts/data_cat3_cat4.json:
- 10 Antivirals / Antiparasitics (Category 3 completion)
- 20 Cardiovascular & Antihypertensives (Category 4 completion)
"""

import json

def m(slug, generic, display, active, salt, cat, desc,
      strengths, forms, routes, moa, pd,
      abs_pk, dist_pk, met_pk, exc_pk, bio, hl, pb, onset, dur,
      ind, contra, warn, cae, sae, interact, mon,
      preg, lact, ped, ger, ren, hep,
      adv, disadv, kpts, trick, suffix, pen, phi):
    return {
        "slug": slug, "generic_name": generic, "display_name": display,
        "active_ingredient": active, "salt": salt, "category": cat, "description": desc,
        "strengths": strengths, "dosage_forms": forms, "routes": routes,
        "mechanism_of_action": moa, "pharmacodynamics": pd,
        "absorption": abs_pk, "distribution": dist_pk, "metabolism": met_pk, "excretion": exc_pk,
        "bioavailability": bio, "half_life": hl, "protein_binding": pb,
        "onset": onset, "duration": dur,
        "indications": ind, "contraindications": contra, "warnings": warn,
        "common_adverse_effects": cae, "serious_adverse_effects": sae,
        "drug_interactions": interact, "monitoring": mon,
        "pregnancy": preg, "lactation": lact, "pediatric": ped, "geriatric": ger,
        "renal": ren, "hepatic": hep,
        "advantages": adv, "disadvantages": disadv, "key_points": kpts,
        "memory_trick": trick, "key_suffix": suffix,
        "pronunciation_en": pen, "pronunciation_hi": phi,
        "status": "active", "verification_status": "verified"
    }

meds = [
    # 1. daclatasvir
    m("daclatasvir", "Daclatasvir", "Daclatasvir Dihydrochloride", "Daclatasvir dihydrochloride", "Daclatasvir dihydrochloride", "Antivirals",
      "A potent direct-acting antiviral targeting HCV non-structural protein 5A (NS5A), combined with sofosbuvir for pan-genotypic Hepatitis C cures.",
      ["30 mg", "60 mg"], ["Film-coated Tablet"], ["Oral"],
      "Binds to the N-terminus of Domain I of the HCV NS5A replication complex, inhibiting both viral RNA replication and virion assembly.",
      "Rapid decline in HCV RNA viral load; pan-genotypic activity against genotypes 1 through 6.",
      "Rapidly absorbed; peak plasma concentration in 1 to 2 hours; high oral bioavailability (67%).",
      "Volume of distribution approx. 47 L; 99% bound to plasma proteins.",
      "Metabolized in the liver by CYP3A4 to inactive metabolites.",
      "Excreted predominantly in faeces (approx. 88%) via biliary elimination; less than 7% in urine.",
      "67%", "12 to 15 hours", "99%", "Rapid viral load suppression within days", "24 hours (once daily)",
      ["Chronic Hepatitis C virus infection genotypes 1, 2, 3, 4, and 6 (combined with sofosbuvir)", "HCV in patients with HIV-1 co-infection", "HCV in liver transplant recipients"],
      ["Concurrent use with strong CYP3A4 inducers (carbamazepine, rifampin, St. John's wort)"],
      ["Risk of Hepatitis B reactivation during HCV clearance (screen for HBV prior to therapy)", "Dose adjustment required with moderate CYP3A4 inhibitors (reduce to 30 mg) or inducers (increase to 90 mg)"],
      ["Headache", "Fatigue", "Nausea", "Diarrhoea"],
      ["Hepatitis B reactivation / acute liver failure", "Severe bradycardia (when combined with sofosbuvir and amiodarone)"],
      ["CYP3A4 inhibitors (reduce daclatasvir to 30 mg daily)", "CYP3A4 inducers (increase daclatasvir to 90 mg daily)", "Amiodarone (fatal bradycardia risk)"],
      ["HBsAg and anti-HBc before starting therapy", "HCV RNA at baseline, week 4, end of treatment, and week 12 (SVR12)", "Liver enzymes"],
      "Category B; if paired with ribavirin, ribavirin category X contraindication applies.", "Excreted in animal milk; use caution.",
      "Safety and efficacy in pediatric patients under 18 years not established.", "No dose adjustment based on age.",
      "No dosage adjustment required in any degree of renal impairment.", "No dosage adjustment required in mild, moderate, or severe hepatic impairment.",
      ["Pan-genotypic NS5A inhibitor paired successfully with sofosbuvir", "No dose adjustment in severe renal impairment", "High cure rates (>95% SVR12)"],
      ["CYP3A4 interactions require dose titration to 30 mg or 90 mg", "Requires combination therapy; cannot be used alone"],
      ["Standard dose is 60 mg once daily with sofosbuvir 400 mg for 12 weeks", "Adjust dose to 30 mg with CYP3A4 inhibitors, or 90 mg with CYP3A4 inducers"],
      "DACLA-tasvir: Direct-Acting Cure Linking with Sofosbuvir for All HCV genotypes.", "-asvir", "da-KLA-tas-veer", "डाक्ला-टासविर"),

    # 2. tenofovir-alafenamide
    m("tenofovir-alafenamide", "Tenofovir Alafenamide (TAF)", "Tenofovir Alafenamide Fumarate", "Tenofovir alafenamide fumarate", "Tenofovir alafenamide fumarate", "Antivirals",
      "A targeted nucleotide reverse transcriptase inhibitor (NRTI) prodrug delivering higher intracellular levels with 90% lower systemic tenofovir exposure, reducing renal and bone toxicities.",
      ["25 mg"], ["Film-coated Tablet"], ["Oral"],
      "Hydrolyzed intracellularly by carboxylesterase 1 (CES1) and cathepsin A in PBMCs and hepatocytes to tenofovir, which is diphosphorylated to tenofovir diphosphate; inhibits HBV reverse transcriptase and HIV-1 reverse transcriptase by chain termination.",
      "Potent suppression of Hepatitis B virus DNA replication with negligible renal tubular or bone mineral density toxicity compared to TDF.",
      "Rapidly absorbed; peak plasma concentration in 0.5 hours; take with food to optimize bioavailability.",
      "High intracellular uptake into hepatocytes and lymphocytes; 80% plasma protein binding.",
      "Intracellularly cleaved to tenofovir; minor CYP3A4 metabolism of parent drug.",
      "Excreted predominantly in faeces (>31%) and urine (<1% parent drug).",
      "High intracellular delivery", "Plasma half-life 0.5 hours; intracellular tenofovir diphosphate half-life 150-180 hours", "80%", "Rapid onset of viral suppression", "24 hours",
      ["Chronic Hepatitis B virus (HBV) infection in adults and pediatric patients ≥12 years with compensated liver disease", "HIV-1 infection (in combination antiretroviral regimens)"],
      ["Hypersensitivity to tenofovir alafenamide"],
      ["Black box warning: Severe acute exacerbations of hepatitis B after discontinuation (monitor liver function for several months post-cessation)", "Lactic acidosis and severe hepatomegaly with steatosis", "HIV resistance testing required before treatment"],
      ["Headache", "Abdominal pain", "Fatigue", "Cough", "Nausea"],
      ["Severe acute exacerbation of HBV after discontinuation", "Lactic acidosis / hepatic steatosis", "Proximal renal tubulopathy (rare compared to TDF)"],
      ["P-gp inducers (rifampin, carbamazepine - avoid combination)", "P-gp inhibitors (increase TAF absorption)"],
      ["Serum HBV DNA viral load", "ALT and AST regularly", "Renal function (eGFR, serum creatinine, urine protein) at baseline and periodically"],
      "Favorable safety profile; pregnancy registry data shows no increase in birth defects.", "Compatible with breastfeeding.",
      "Approved for pediatric patients 12 years and older weighing ≥35 kg.", "No dose adjustment based on age alone.",
      "No dosage adjustment required if CrCl ≥ 15 mL/min; safe on chronic hemodialysis (administer post-dialysis).",
      "No dosage adjustment in mild hepatic impairment; not recommended in decompensated cirrhosis.",
      ["90% lower systemic plasma tenofovir exposure than older tenofovir disoproxil (TDF)", "Significantly lower incidence of renal tubular dysfunction and bone mineral loss", "Safe in patients with mild-to-moderate renal impairment without dose modification"],
      ["Higher cost than generic TDF", "Slightly more weight gain and LDL cholesterol elevation than TDF"],
      ["First-line oral treatment for chronic Hepatitis B (25 mg once daily with food)", "Protects kidneys and bones much better than older tenofovir disoproxil"],
      "TAF: Targeted Alafenamide Formulation; Thwarts HBV; Tremendous Avoidance of Fractures/nephropathy.", "-fovir", "te-NOE-foe-veer a-la-FEN-a-mide", "टीनोफ़ोविर अलाफ़ेनामाइड"),

    # 3. adefovir
    m("adefovir", "Adefovir Dipivoxil", "Adefovir Dipivoxil", "Adefovir dipivoxil", "Adefovir dipivoxil", "Antivirals",
      "An oral acyclic nucleotide analogue used for chronic Hepatitis B, particularly effective against lamivudine-resistant YMDD mutant HBV strains.",
      ["10 mg"], ["Tablet"], ["Oral"],
      "Diester prodrug converted intracellularly by esterases to adefovir, which is phosphorylated to adefovir diphosphate; competitively inhibits HBV DNA polymerase and causes chain termination.",
      "Antiviral suppression of wild-type and lamivudine-resistant (YMDD motif mutant) HBV; low potency compared to entecavir and tenofovir.",
      "Rapidly absorbed; peak plasma concentration in 1.75 hours; 59% oral bioavailability.",
      "Low protein binding (<4%); distributes widely into total body water.",
      "Not metabolized by CYP450 enzymes; prodrug de-esterified to parent adefovir.",
      "Excreted predominantly unchanged in urine via active tubular secretion and glomerular filtration (approx. 45% in 24 hours).",
      "59%", "7.5 hours (elimination half-life)", "<4%", "1 to 2 hours", "24 hours",
      ["Chronic Hepatitis B in adults with evidence of active viral replication and persistent transaminitis", "Lamivudine-resistant HBV infection"],
      ["Hypersensitivity to adefovir dipivoxil"],
      ["Black box warning: Nephrotoxicity (proximal tubular dysfunction, Fanconi syndrome, hypophosphatemia) with prolonged use", "Severe acute exacerbations of hepatitis B after discontinuation", "Lactic acidosis and severe hepatomegaly with steatosis", "HIV resistance risk if undiagnosed HIV co-infection exists"],
      ["Asthenia", "Headache", "Abdominal pain", "Nausea", "Flatulence"],
      ["Renal tubular toxicity / Fanconi syndrome (hypophosphatemia, glycosuria, proteinuria)", "Acute kidney injury", "Lactic acidosis"],
      ["Nephrotoxic drugs (aminoglycosides, NSAIDs, cyclosporine - additive renal toxicity)", "Drugs eliminated by active tubular secretion"],
      ["Serum creatinine and eGFR at baseline and every 3 months", "Serum phosphorus every 3 months (screen for Fanconi syndrome)", "HBV DNA viral load and ALT"],
      "Category C; use during pregnancy only if potential benefit justifies potential risk.", "Excretion in human milk unknown; avoid breastfeeding.",
      "Safety and efficacy in pediatric patients under 12 years not established.", "Monitor renal clearance closely.",
      "Strict dose reduction mandatory: CrCl 30-49 mL/min: 10 mg q48h; CrCl 10-29 mL/min: 10 mg q72h; hemodialysis: 10 mg every 7 days post-dialysis.",
      "No dosage adjustment required in hepatic impairment.",
      ["Active against lamivudine-resistant YMDD mutant HBV strains", "Fewer gastrointestinal side effects than interferon"],
      ["Dose-dependent nephrotoxicity and Fanconi syndrome with prolonged therapy", "Much lower antiviral potency than tenofovir or entecavir"],
      ["Largely superseded by tenofovir, but useful historical salvage for lamivudine resistance", "Check serum creatinine and phosphorus every 3 months (Fanconi syndrome risk)"],
      "ADEFO-vir: Alternative Drug for Entecavir/lamivudine failure; Danger: Fanconi's Osmotic wasting.", "-fovir", "a-DEF-oh-veer", "अडेफ़ो-विर"),

    # 4. lamivudine
    m("lamivudine", "Lamivudine (3TC)", "Lamivudine", "Lamivudine", "Lamivudine", "Antivirals",
      "A classical cytidine nucleoside reverse transcriptase inhibitor (NRTI) used in combination regimens for HIV-1 infection and as a lower-dose agent for chronic Hepatitis B.",
      ["100 mg (HBV)", "150 mg", "300 mg (HIV)", "10 mg/mL oral solution"], ["Film-coated Tablet", "Oral Solution"], ["Oral"],
      "Phosphorylated intracellularly to lamivudine 5'-triphosphate, which competitively inhibits HIV-1 reverse transcriptase and HBV DNA polymerase, causing viral DNA chain termination.",
      "Potent suppression of HIV-1 and HBV viral replication; low genetic barrier to resistance (M184V mutation in HIV; M204I/V YMDD mutation in HBV).",
      "Rapidly absorbed; peak plasma concentration in 1 hour; 86% oral bioavailability; food does not affect absorption.",
      "Distributes into total body water; crosses into CSF (CSF/plasma ratio approx. 0.12); <36% bound to plasma albumin.",
      "Minor hepatic metabolism (<10%) to a trans-sulfoxide metabolite; cleared predominantly as unchanged drug.",
      "Excreted predominantly unchanged in urine via active organic cation transport and glomerular filtration (approx. 70%).",
      "86%", "5 to 7 hours in plasma; intracellular triphosphate half-life 16 to 19 hours", "<36%", "1 hour", "12 to 24 hours",
      ["HIV-1 infection (in combination with other antiretroviral agents: 300 mg once daily or 150 mg twice daily)", "Chronic Hepatitis B infection (100 mg once daily)", "Post-exposure prophylaxis (PEP) for occupational and non-occupational HIV exposure"],
      ["Hypersensitivity to lamivudine"],
      ["Black box warning: Do NOT use the 100 mg HBV dose in HIV-coinfected patients (causes rapid emergence of M184V HIV resistance)", "Severe acute exacerbation of hepatitis B after discontinuation", "Lactic acidosis and severe hepatomegaly with steatosis"],
      ["Headache", "Nausea", "Fatigue", "Diarrhoea", "Nasal symptoms / cough"],
      ["Lactic acidosis / hepatic steatosis", "Acute exacerbation of HBV on cessation", "Pancreatitis (especially in pediatric patients)", "Severe peripheral neuropathy"],
      ["Co-trimoxazole (trimethoprim increases lamivudine levels by 40%)", "Emtricitabine (same cytidine analogue mechanism; do not combine)", "Cladribine (antagonizes phosphorylation)"],
      ["HIV RNA viral load and CD4 count", "HBV DNA viral load and ALT in Hepatitis B", "Renal function (adjust dose for CrCl < 50 mL/min)"],
      "Category C; reassuring registry data; widely used in maternal prevention of mother-to-child HIV transmission.",
      "Excreted in breast milk; compatible with caution where breastfeeding with viral suppression is practiced.",
      "Approved for pediatric patients 3 months and older; dosed by body weight.",
      "Monitor renal function; adjust dosing interval in renal impairment.",
      "Dose reduction required: CrCl 30-49 mL/min: 150 mg once daily; CrCl 15-29 mL/min: 150 mg day 1 then 100 mg once daily; CrCl 5-14 mL/min: 150 mg day 1 then 50 mg once daily; CrCl < 5 mL/min: 50 mg day 1 then 25 mg once daily.",
      "No dosage adjustment required in hepatic impairment.",
      ["Cornerstone antiretroviral with unmatched safety and tolerability over 25 years", "Available in numerous low-cost fixed-dose combination generic tablets", "Safe in pregnancy and across pediatric age groups"],
      ["Low genetic barrier to resistance (single M184V point mutation confers total resistance)", "High rate of YMDD mutation in Hepatitis B (>70% resistance at 5 years)"],
      ["100 mg daily for Hepatitis B; 300 mg daily for HIV (never use 100 mg if patient has HIV)", "Adjust dose when kidney function (CrCl) drops below 50 mL/min"],
      "LAMI-vudine: Low-toxicity Anti-HIV/HBV Medicine; Mutation (M184V) is the main weakness.", "-vudine", "la-MI-vyoo-deen", "लैमी-व्युडीन"),

    # 5. praziquantel
    m("praziquantel", "Praziquantel", "Praziquantel", "Praziquantel", "Praziquantel", "Antiparasitics",
      "The global broad-spectrum anthelmintic of choice for schistosomiasis, liver and lung flukes, and cestode (tapeworm) infections including neurocysticercosis.",
      ["600 mg"], ["Film-coated Scored Tablet"], ["Oral"],
      "Increases cell membrane permeability to calcium ions in platyhelminths, producing rapid calcium influx, massive muscular contraction, paralysis, and tegumental vacuolization; dislodges parasites, exposing them to host immune attack.",
      "Lethal against all human Schistosoma species (S. haematobium, S. mansoni, S. japonicum), food-borne trematodes (Clonorchis, Opisthorchis, Paragonimus), and cestodes (Taenia solium, Taenia saginata, Hymenolepis nana).",
      "Rapidly absorbed (approx. 80%); undergoes substantial hepatic first-pass metabolism; food significantly increases bioavailability.",
      "Widely distributed into tissues and crosses the blood-brain barrier (effective for neurocysticercosis); 80% bound to plasma proteins.",
      "Extensively metabolized in the liver by CYP3A4 to inactive hydroxylated metabolites.",
      "Excreted predominantly in urine (approx. 70-80% as metabolites within 24 hours); approx. 15-35% in faeces.",
      "Approximately 80% absorbed; systemic bioavailability lower due to extensive first-pass metabolism", "0.8 to 1.5 hours (parent); active metabolites 4 to 5 hours", "80%", "Paralysis of parasites within minutes", "4 to 6 hours",
      ["Schistosomiasis (bilharzia) caused by all Schistosoma species (single dose 40-60 mg/kg)", "Neurocysticercosis caused by the larval form of Taenia solium (pork tapeworm)", "Intestinal tapeworm infections (Taenia saginata, Taenia solium, Hymenolepis nana)", "Clonorchiasis, opisthorchiasis, and paragonimiasis (liver and lung flukes)"],
      ["Ocular cysticercosis (destroying parasites in the eye triggers inflammatory blindness)", "Concomitant use of strong CYP inducers (rifampin drastically reduces efficacy)"],
      ["In neurocysticercosis, killing cysticerci causes local cerebral inflammation, seizures, and cerebral oedema (always co-administer corticosteroids)", "Avoid chewing tablets due to an extremely bitter taste that triggers vomiting", "Somnolence: avoid driving on treatment days"],
      ["Dizziness", "Headache", "Abdominal discomfort", "Nausea", "Drowsiness", "Urticaria / pruritus"],
      ["Seizures / intracranial hypertension (during neurocysticercosis treatment)", "Severe hypersensitivity / anaphylaxis", "Cardiac arrhythmias (rare)"],
      ["CYP3A4 inducers (rifampin, carbamazepine, phenytoin - reduce praziquantel levels up to 80-99%)", "CYP3A4 inhibitors (cimetidine, ketoconazole - increase praziquantel levels)", "Dexamethasone (reduces levels, but necessary in neurocysticercosis)"],
      ["Stool examination for ova and parasites at 4 to 6 weeks post-treatment", "Neurological examination and MRI/CT in neurocysticercosis", "Liver function tests in severe hepatic disease"],
      "Category B; widely used in pregnant women in endemic schistosomiasis regions with high safety profile.",
      "Excreted in low levels in breast milk; avoid breastfeeding on the day of treatment and for 72 hours thereafter.",
      "Approved for pediatric schistosomiasis and tapeworm infections; tablets can be crushed and mixed with sweet food.",
      "No specific dose adjustments; assess hepatic function.",
      "No dosage adjustment required in renal impairment.",
      "Dose reduction and caution required in severe liver disease (portal hypertension reduces first-pass clearance).",
      ["Single-dose curative efficacy for schistosomiasis (40 mg/kg single day treatment)", "Pan-fluke and pan-tapeworm coverage against virtually all flatworms", "World Health Organization essential medicine for global neglected disease control"],
      ["Extremely bitter taste causes gagging and vomiting if chewed", "Requires mandatory corticosteroid co-administration for neurocysticercosis"],
      ["Drug of choice for schistosomiasis and tapeworms", "Never chew the tablets (extremely bitter); swallow whole with a full glass of water with food"],
      "PRAZI-quantel: Paralyzes flatworms with Rapid Calcium Influx; Swallowed whole with food.", "-quantel", "pra-zi-KWAN-tel", "प्राज़ी-क्वांटेल"),

    # 6. ornidazole
    m("ornidazole", "Ornidazole", "Ornidazole", "Ornidazole", "Ornidazole", "Antiparasitics",
      "A 5-nitroimidazole derivative with a longer half-life (14 hours) and lower neurotoxicity than metronidazole, widely used in India for amoebiasis, giardiasis, and anaerobic infections.",
      ["500 mg", "500 mg/100 mL IV infusion"], ["Film-coated Tablet", "Solution for Infusion"], ["Oral", "Intravenous"],
      "Enters microbial cells by passive diffusion; nitro group is reduced by ferredoxin oxidoreductase into toxic free radicals that bind to bacterial and protozoan DNA, causing strand breakage and cell death.",
      "Potent antiprotozoal activity against Entamoeba histolytica, Giardia lamblia, and Trichomonas vaginalis; bactericidal against anaerobic bacteria (Bacteroides, Clostridium).",
      "Rapidly and almost completely absorbed from GI tract (>90% bioavailability); peak plasma concentration in 2 to 3 hours.",
      "Widely distributed into tissues, CSF, and body fluids; less than 15% bound to plasma proteins.",
      "Metabolized in the liver (approx. 85%) mainly by conjugation and hydroxylation to active and inactive metabolites.",
      "Excreted in urine (approx. 60-70%) and faeces (approx. 20-25%) as metabolites; less than 4% unchanged.",
      ">90%", "12 to 14 hours (longer half-life than metronidazole, allowing twice-daily or once-daily dosing)", "<15%", "1 to 2 hours", "12 to 24 hours",
      ["Amoebiasis (intestinal and hepatic amoebic liver abscess)", "Giardiasis", "Trichomoniasis of genitourinary tract", "Anaerobic bacterial infections and surgical prophylaxis"],
      ["Hypersensitivity to ornidazole or nitroimidazoles", "Preexisting active central nervous system diseases (epilepsy, multiple sclerosis)"],
      ["Central nervous system toxicity (dizziness, tremor, ataxia, convulsions, peripheral neuropathy with prolonged use)", "Disulfiram-like ethanol intolerance (milder than metronidazole, but avoid alcohol)", "Severe hepatic impairment requires 50% dose reduction"],
      ["Metallic taste in mouth", "Nausea", "Epigastric distress", "Dizziness", "Headache", "Somnolence"],
      ["Peripheral neuropathy (numbness, paresthesias in extremities)", "Epileptiform seizures", "Encephalopathy / cerebellar ataxia", "Leukopenia"],
      ["Alcohol / ethanol (mild disulfiram-like flushing, nausea, tachycardia)", "Coumarin anticoagulants / warfarin (potentiates anticoagulant effect)", "Phenobarbital (decreases ornidazole half-life)", "Lithium"],
      ["Complete blood counts in courses exceeding 10 days", "Neurological evaluation for paresthesias or ataxia", "Stool microscopy for cysts/trophozoites"],
      "Avoid in first trimester of pregnancy; use in 2nd and 3rd trimesters only if clearly indicated.",
      "Excreted in breast milk; withhold breastfeeding during therapy and for 48 hours after final dose.",
      "Approved for pediatric amoebiasis and giardiasis (dosed at 30-40 mg/kg/day once daily for 3 days).",
      "Assess renal and hepatic function; monitor for dizziness.",
      "No dosage adjustment required in mild to moderate renal failure; dose post-hemodialysis.",
      "Extend dosing interval to 24 hours in severe hepatic cirrhosis (half-life prolonged to 22 hours).",
      ["Longer half-life (14 hours) allows convenient once-daily or twice-daily dosing compared to metronidazole TID", "Significantly lower incidence of metallic taste, nausea, and vomiting than metronidazole", "Better patient compliance for amoebiasis and giardiasis"],
      ["Risk of peripheral neuropathy and ataxia with prolonged courses", "Cross-allergenicity with metronidazole"],
      ["Superior tolerability to metronidazole with twice-daily dosing (500 mg BID for 5 days in amoebiasis)", "Avoid alcohol during and for 48 hours after completing the course"],
      "ORNI-dazole: One-or-two doses daily (14h half-life); Outperforms metronidazole in gut tolerability.", "-dazole", "or-NI-da-zole", "ओर्निडा-ज़ोल"),

    # 7. pyrantel-pamoate
    m("pyrantel-pamoate", "Pyrantel Pamoate", "Pyrantel Pamoate", "Pyrantel pamoate", "Pyrantel pamoate", "Antiparasitics",
      "A depolarizing neuromuscular blocking anthelmintic that paralyzes pinworms, roundworms, and hookworms in the intestinal lumen, expelled safely by normal peristalsis.",
      ["250 mg", "50 mg/mL oral suspension"], ["Chewable Tablet", "Oral Suspension"], ["Oral"],
      "Acts as a depolarizing neuromuscular junction blocker and nicotinic acetylcholine receptor agonist in nematodes; causes persistent muscular depolarization, spastic paralysis, and detachment from the intestinal wall.",
      "Paralyzes Enterobius vermicularis (pinworm), Ascaris lumbricoides (roundworm), and Ancylostoma duodenale / Necator americanus (hookworms); completely inactive against whipworm (Trichuris) and flukes.",
      "Poorly absorbed from the gastrointestinal tract (<15%); acts locally within the intestinal lumen.",
      "Confined primarily to the gut lumen; absorbed trace amounts are bound to plasma proteins.",
      "Partially metabolized in the liver; bulk of drug passes through gut unaltered.",
      "Excreted predominantly unchanged in faeces (>50%); trace absorbed fraction eliminated in urine (<7%).",
      "<15% (desirable for luminal parasite clearance)", "1.75 hours (absorbed fraction)", "Low", "Paralysis of intestinal worms occurs within 2 to 4 hours", "24 hours",
      ["Enterobiasis (pinworm / threadworm infection - single dose of 11 mg/kg, repeat in 2 weeks)", "Ascariasis (common roundworm infection - single dose)", "Ancylostomiasis and necatoriasis (hookworm infection - daily for 3 days)"],
      ["Hypersensitivity to pyrantel pamoate", "Severe preexisting liver impairment"],
      ["Pinworm eggs survive in household dust: treat ALL household members simultaneously to prevent reinfection", "Repeat dose after 2 weeks in pinworm infections to eradicate newly hatched larvae", "Stains stools bright red/orange"],
      ["Abdominal cramps", "Nausea", "Vomiting", "Diarrhoea", "Transient headache"],
      ["Transient elevation in AST/ALT", "Severe hypersensitivity rash (rare)"],
      ["Piperazine (directly antagonizes pyrantel pamoate mechanism of action; do not co-administer)"],
      ["Visual inspection of stool or perianal cellophane tape test (Scotch tape test) for pinworm eggs"],
      "Category C; use in pregnancy only if clearly needed (prefer mebendazole/albendazole in 2nd/3rd trimester).",
      "Minimal systemic absorption; compatible with breastfeeding.",
      "Approved for children 2 years of age and older (11 mg/kg single dose, max 1 g); pleasant-tasting suspension.",
      "No dosage adjustment required.",
      "No dosage adjustment required (luminal agent).",
      "Use with caution in patients with preexisting severe hepatic disease.",
      ["Acts locally in the gut lumen with minimal (<15%) systemic absorption, providing exceptional safety", "Single-dose cure for pinworms and roundworms", "Available as pleasant chewable tablets and liquid suspensions ideal for children"],
      ["Completely ineffective against Trichuris trichiura (whipworm) and tapeworms", "Must repeat dose in 2 weeks for pinworms to break the autoinfection cycle"],
      ["First-line over-the-counter treatment for pinworms in children and families", "Treat the entire family simultaneously, wash bedsheets in hot water, and repeat in 2 weeks"],
      "PYRANTEL: Paralyzes Pinworms; Yields Rapid expulsion; Repeat After 2 weeks; Never mix with Piperazine.", "-antel", "pye-RAN-tel PAM-oh-ate", "पायरेन्टेल पैमोएट"),

    # 8. ciclopirox
    m("ciclopirox", "Ciclopirox", "Ciclopirox Olamine", "Ciclopirox olamine", "Ciclopirox olamine", "Antifungals",
      "A broad-spectrum hydroxypyridone antifungal with a unique metal ion-chelating mechanism, anti-inflammatory and antibacterial activity, used for onychomycosis, seborrheic dermatitis, and tinea.",
      ["8% nail lacquer", "1% cream", "1% shampoo", "0.77% gel"], ["Nail Lacquer", "Topical Cream", "Medicated Shampoo", "Topical Gel"], ["Topical"],
      "Chelates polyvalent cations (Fe3+ and Al3+), inhibiting metal-dependent enzymes (cytochromes, catalase, peroxidase) in fungal mitochondria; disrupts membrane transport and electron transport chains.",
      "Fungicidal against dermatophytes (Trichophyton, Microsporum), Candida, and Malassezia; intrinsic antibacterial activity against Gram-positive and Gram-negative bacteria; anti-inflammatory activity via 5-lipoxygenase inhibition.",
      "Nail lacquer penetrates deep through keratinized nail plate; minimal systemic absorption (<5%).",
      "Concentrates heavily in the stratum corneum, hair follicles, and nail plate; negligible systemic distribution.",
      "Minimal systemically absorbed drug is metabolized in the liver by glucuronidation.",
      "Excreted in urine (approx. 1-2% of applied topical dose) as glucuronide conjugate.",
      "<5% systemic absorption", "Systemic elimination half-life 1.7 hours", "94% to 97%", "Symptomatic improvement in skin within 1 week; nail cure requires 6 to 12 months", "24 hours (applied daily)",
      ["Mild to moderate onychomycosis of fingernails and toenails without lunula involvement (8% nail lacquer)", "Seborrheic dermatitis of the scalp (1% shampoo twice weekly)", "Tinea pedis, tinea cruris, and tinea corporis (cream or gel)", "Cutaneous candidiasis and tinea versicolor"],
      ["Hypersensitivity to ciclopirox or olamine components", "Ophthalmic or intravaginal application"],
      ["Nail lacquer: apply daily over previous coats, remove with alcohol every 7 days, and trim nails monthly", "Avoid open flames during lacquer application (flammable solvent)", "Local irritation and periungual erythema"],
      ["Application site burning or stinging", "Periungual erythema", "Local pruritus", "Nail shape changes / brittle nails"],
      ["Allergic contact dermatitis", "Severe periungual blistering (rare)"],
      ["No clinically significant drug interactions reported due to minimal systemic absorption"],
      ["Clinical examination of nail growth from nail fold", "Scalp inspection for reduction in scaling and erythema"],
      "Category B; minimal systemic absorption, safe for localized topical use in pregnancy.",
      "Excreted in human milk in trace amounts; compatible with breastfeeding (avoid applying to breast).",
      "Approved for pediatric patients 10 years and older for onychomycosis; 16 years and older for seborrheic dermatitis.",
      "No dosage adjustment required.",
      "No dosage adjustment required (topical).",
      "No dosage adjustment required (topical).",
      ["Unique metal chelation mechanism prevents development of fungal cross-resistance with azoles", "Triple antifungal, antibacterial, and anti-inflammatory action ideal for seborrheic dermatitis", "Non-toxic alternative to oral antifungals for superficial nail fungus"],
      ["Requires daily nail lacquer application for up to 48 weeks for complete cure", "Lower mycological cure rates than oral terbinafine for thick toenails"],
      ["Apply 8% nail lacquer daily to infected nails for 6-12 months; wipe off with alcohol every 7 days", "1% shampoo used twice weekly clears stubborn dandruff and seborrheic dermatitis"],
      "CICLO-pirox: Chelates Iron; Cleans Out nail fungus; Calms Itchy Seborrheic Scalp.", "-pirox", "sye-kloe-PEER-ox", "सिक्लो-पिरॉक्स"),

    # 9. nystatin
    m("nystatin", "Nystatin", "Nystatin", "Nystatin", "Nystatin", "Antifungals",
      "A classical polyene macrolide antifungal not absorbed from the gastrointestinal tract, serving as the gold standard topical and oral suspension treatment for oral candidiasis (thrush).",
      ["100,000 units/mL oral suspension", "100,000 units/g topical cream", "100,000 units vaginal tablet"], ["Oral Suspension", "Topical Cream", "Topical Ointment", "Vaginal Tablet"], ["Oral (Topical Swish and Swallow)", "Topical", "Vaginal"],
      "Binds irreversibly to ergosterol in the fungal cell membrane, forming transmembrane pores and barrel-like channels that leak potassium and essential cellular constituents, causing fungal cell death.",
      "Fungicidal and fungistatic against Candida albicans and other Candida species; completely inactive against bacteria, viruses, and dermatophytes.",
      "Not absorbed from intact skin, mucous membranes, or the gastrointestinal tract; acts purely locally.",
      "Confined entirely to the lumen of the gastrointestinal tract or the site of topical application; zero systemic distribution.",
      "Not metabolized; passes through the gastrointestinal tract unchanged.",
      "Excreted 100% unchanged in the faeces following oral administration.",
      "0% (negligible gastrointestinal absorption)", "Not applicable (not absorbed systemically)", "Not applicable", "Local antifungal relief within 24 to 48 hours", "6 hours (administered 4 times daily)",
      ["Oral candidiasis (oral thrush in infants, children, and adults - 'swish and swallow')", "Denture stomatitis and angular cheilitis", "Cutaneous candidiasis (diaper dermatitis, intertrigo)", "Vulvovaginal candidiasis (topical ovules)"],
      ["Hypersensitivity to nystatin or formulation excipients"],
      ["Oral suspension should be retained in the mouth as long as possible before swallowing ('swish and swallow')", "In infants, apply half dose to each side of the mouth after feeding", "Not for the treatment of systemic fungal infections"],
      ["Nausea", "Diarrhoea (with large oral doses)", "Vomiting", "Oral irritation", "Mild skin burning"],
      ["Severe hypersensitivity / contact dermatitis (rare)", "Stevens-Johnson syndrome (extremely rare)"],
      ["No systemic drug-drug interactions because the drug is not absorbed into the bloodstream"],
      ["Visual inspection of oral cavity for resolution of white plaques (curds)"],
      "Category C; virtually zero systemic absorption, widely considered safe in pregnancy for oral and vaginal thrush.",
      "Compatible with breastfeeding; not absorbed into maternal circulation.",
      "First-line treatment of choice for neonatal and pediatric oral thrush (100,000 units four times daily).",
      "No dosage adjustment required; excellent safety in elderly denture wearers.",
      "No dosage adjustment required in renal failure (not absorbed).",
      "No dosage adjustment required in hepatic disease (not absorbed).",
      ["Zero systemic absorption guarantees an exceptional safety profile with zero organ toxicity", "First-line gold standard for infant oral thrush and denture stomatitis", "Virtually zero emergence of fungal resistance despite decades of use"],
      ["Completely ineffective for systemic fungal infections", "Requires frequent dosing (four times daily) and must be swished in the mouth"],
      ["First-line treatment for oral thrush: 'Swish and swallow' 4 times daily for 7 to 14 days", "Safe in newborns and elderly patients because it is not absorbed into the blood"],
      "NYSTATIN: New York State lab discovery; No Systemic absorption; Treats All Thrush In Neonates.", "-statin", "nye-STAT-in", "नाइस्टैटिन"),

    # 10. favipiravir
    m("favipiravir", "Favipiravir", "Favipiravir", "Favipiravir", "Favipiravir", "Antivirals",
      "An oral pyrazinecarboxamide antiviral prodrug that selectively inhibits viral RNA-dependent RNA polymerase (RdRp), approved for novel or re-emerging pandemic influenza strains.",
      ["200 mg", "400 mg", "800 mg"], ["Film-coated Tablet"], ["Oral"],
      "Phosphoribosylated intracellularly to active favipiravir ribofuranosyltriphosphate (favipiravir-RTP), which selectively inhibits viral RNA-dependent RNA polymerase (RdRp) or incorporates into viral RNA, causing chain termination and lethal mutagenesis.",
      "Broad antiviral activity against RNA viruses including Influenza A, B, and C viruses, Arenaviruses, Bunyaviruses, Filoviruses (Ebola), and Coronaviruses.",
      "Rapidly absorbed; peak plasma concentration in 1 hour; 97% oral bioavailability; food slightly delays absorption.",
      "Apparent volume of distribution approx. 15 to 20 L; 54% bound to plasma proteins.",
      "Metabolized in the liver primarily by aldehyde oxidase (AO) and to a lesser extent by xanthine oxidase to inactive T-705M1; not cleared by CYP enzymes.",
      "Excreted almost entirely in urine (approx. 90%) as the inactive hydroxylated metabolite T-705M1.",
      "97%", "2 to 5.5 hours (dose-dependent saturable kinetics)", "54%", "1 hour", "12 hours (dosed twice daily after loading dose)",
      ["Treatment of novel or re-emerging pandemic influenza virus infections refractory to standard neuraminidase inhibitors", "Investigational use in severe emerging RNA virus outbreaks (Ebola, Lassa fever)"],
      ["Hypersensitivity to favipiravir", "Pregnancy and lactation (STRICTLY CONTRAINDICATED due to high teratogenic and embryotoxic risk)", "Severe hepatic failure"],
      ["Black box warning: Teratogenicity and early embryonic lethality; verified negative pregnancy test mandatory; reliable contraception required for women and men during and for 7 days post-treatment", "Hyperuricemia: elevates blood uric acid levels substantially (use caution in gout)", "Elevated liver transaminases (ALT/AST)"],
      ["Hyperuricemia (increased serum uric acid in up to 15-20% of patients)", "Diarrhoea", "Elevated ALT and AST", "Nausea", "Decreased neutrophil count"],
      ["Severe teratogenic fetal malformations", "Acute gouty arthritis attack", "Drug-induced hepatitis / jaundice"],
      ["Theophylline (favipiravir increases theophylline blood levels)", "Pyrazinamide (additive hyperuricemic effect)", "Repaglinide (CYP2C8 inhibition increases repaglinide levels)"],
      ["Serum pregnancy test prior to initiation in all females of reproductive potential", "Serum uric acid at baseline and during therapy", "Liver function tests (ALT/AST)"],
      "Strictly contraindicated (Category X); produces severe fetal anatomical malformations, limb defects, and embryo-fetal death.",
      "Contraindicated; excreted into breast milk.",
      "Safety and efficacy in pediatric patients not established.",
      "Dose reduction and close monitoring required due to age-related renal and hepatic clearance changes.",
      "Uric acid accumulates in renal impairment; monitor serum uric acid and eGFR.",
      "Dose reduction required in moderate hepatic impairment; contraindicated in severe cirrhosis.",
      ["Broad antiviral activity against diverse RNA virus families that carry resistant RdRp mutations", "Near 100% oral bioavailability with rapid cellular uptake", "Effective against oseltamivir-resistant influenza strains"],
      ["Severe teratogenicity restricts use to emergency pandemic situations", "Substantial elevations in blood uric acid trigger acute gout"],
      ["Oral antiviral for pandemic influenza resistant to Tamiflu", "STRICTLY CONTRAINDICATED IN PREGNANCY (causes severe birth defects); raises uric acid"],
      "FAVI-piravir: Fast Acting Viral RdRp Inhibitor; Fatal to Fetus (teratogenic); Avoid In gout.", "-piravir", "fa-vi-PEER-a-veer", "फ़ावि-पिराविर")
]

with open("scripts/data_cat3_cat4.json", "w") as f:
    json.dump(meds, f, indent=2)

print(f"[Cat 3 Generator] Successfully wrote {len(meds)} medicines to scripts/data_cat3_cat4.json")
