// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function sanitizeSupabaseUrl(rawUrl?: unknown): string | null {
  if (typeof rawUrl !== "string" || !rawUrl.trim()) return null;
  let val = rawUrl.trim();
  // If user or environment variable got pasted with "NAME=https://..."
  const urlMatch = val.match(/https?:\/\/[^\s"',;]+/);
  if (urlMatch) {
    val = urlMatch[0];
  }
  try {
    const parsed = new URL(val);
    if (parsed.protocol === "http:" || parsed.protocol === "https:") {
      return parsed.origin;
    }
  } catch {
    // invalid URL format
  }
  return null;
}

function sanitizeSupabaseKey(rawKey?: unknown): string | null {
  if (typeof rawKey !== "string" || !rawKey.trim()) return null;
  let val = rawKey.trim();
  // Strip variable name prefix like "KEY="
  if (val.includes("=")) {
    val = val.split("=").pop()?.trim() || val;
  }
  // If someone passed the URL as the key, ignore it
  if (val.startsWith("http://") || val.startsWith("https://")) {
    return null;
  }
  // Remove quotes or stray semicolons
  val = val.replace(/^['"]+|['";]+$/g, "").trim();
  return val.length > 5 ? val : null;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Candidate URLs from client-side or server-side envs
  const rawUrlCandidate =
    (typeof process !== "undefined" && process.env?.["NEXT_PUBLIC_SUPABASE_URL"]) ||
    import.meta.env["NEXT_PUBLIC_SUPABASE_URL"] ||
    import.meta.env["VITE_SUPABASE_URL"] ||
    (typeof process !== "undefined" && process.env?.["SUPABASE_URL"]) ||
    (typeof process !== "undefined" && process.env?.["VITE_SUPABASE_URL"]);

  // Candidate Keys from client-side or server-side envs
  const rawKeyCandidate =
    (typeof process !== "undefined" && process.env?.["NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"]) ||
    import.meta.env["NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"] ||
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    (typeof process !== "undefined" && process.env?.["SUPABASE_PUBLISHABLE_KEY"]) ||
    (typeof process !== "undefined" && process.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"]);

  let validUrl = sanitizeSupabaseUrl(rawUrlCandidate);
  let validKey = sanitizeSupabaseKey(rawKeyCandidate);

  // If variables were swapped, recover gracefully
  if (!validUrl && sanitizeSupabaseUrl(rawKeyCandidate)) {
    validUrl = sanitizeSupabaseUrl(rawKeyCandidate);
    validKey = sanitizeSupabaseKey(rawUrlCandidate);
  }

  if (!validUrl || !validKey) {
    console.warn(
      `[Supabase] Missing or invalid Supabase URL/Key. Using safe fallback client.`,
    );
    return createClient<Database>("https://placeholder.supabase.co", "placeholder-key", {
      global: {
        fetch: async () =>
          new Response(JSON.stringify([]), {
            status: 200,
            headers: { "content-type": "application/json" },
          }),
      },
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  return createClient<Database>(validUrl, validKey, {
    global: {
      fetch: createSupabaseFetch(validKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
