// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function sanitizeSupabaseUrl(rawUrl?: unknown): string | null {
  if (typeof rawUrl !== "string" || !rawUrl.trim()) return null;
  let val = rawUrl.trim();
  const urlMatch = val.match(/https?:\/\/[^\s"',;]+/);
  if (urlMatch) {
    val = urlMatch[0];
  }
  try {
    const parsed = new URL(val);
    if (parsed.protocol === "http:" || parsed.protocol === "https:") {
      return parsed.origin;
    }
  } catch {
    // invalid URL format
  }
  return null;
}

function sanitizeSupabaseKey(rawKey?: unknown): string | null {
  if (typeof rawKey !== "string" || !rawKey.trim()) return null;
  let val = rawKey.trim();
  if (val.includes("=")) {
    val = val.split("=").pop()?.trim() || val;
  }
  if (val.startsWith("http://") || val.startsWith("https://")) {
    return null;
  }
  val = val.replace(/^['"]+|['";]+$/g, "").trim();
  return val.length > 5 ? val : null;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const rawUrl =
    process.env["NEXT_PUBLIC_SUPABASE_URL"] ||
    process.env["SUPABASE_URL"] ||
    process.env["VITE_SUPABASE_URL"];
  const rawSecret =
    process.env["SUPABASE_SECRET_KEY"] || process.env["SUPABASE_SERVICE_ROLE_KEY"];

  const validUrl = sanitizeSupabaseUrl(rawUrl);
  const validSecret = sanitizeSupabaseKey(rawSecret);

  if (!validUrl || !validSecret) {
    console.warn(
      `[Supabase] Missing or invalid Supabase admin URL/Key. Using safe fallback admin client.`,
    );
    return createClient<Database>("https://placeholder.supabase.co", "placeholder-service-key", {
      global: {
        fetch: async () =>
          new Response(JSON.stringify([]), {
            status: 200,
            headers: { "content-type": "application/json" },
          }),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  return createClient<Database>(validUrl, validSecret, {
    global: {
      fetch: createSupabaseFetch(validSecret),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
